var arr_search = [
									'"关键字"', 
									'intitle:"关键字"', 
									'intitle:关键字1 关键字2', 
									'allintitle:', 
									'intext:', 
									'inurl:bd', 
									'资料 site:bd.com', 
									'资料 imagesize:13x32', 
									'资料 filetype:png', 
									'**************************', 
									'Google', 
									'搜狗搜索', 
									'微信搜一搜', 
									'垂类社群', 
									'聚合网址', 
									'**************************', 
									'inurl:baogao', 
									'SimilarSites:baogao.com', 
									'YouTube下载直接www.9xYouTube.com', 
									'ppt 插件iSlide', 
									'    在线设计网站canva.com', 
									'related:google.com #相关网址', 
									'"关键词1 关键词2" #精准位置1', 
									'关键词1 -关键词2 #精准位置2', 
									'关键词1 nearby #附近搜索', 
									'translate:关键词1 #翻译', 
									];