document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln(".cypt td {");
document.writeln("	text-align: center;");
document.writeln("	border: 1px solid #C0C0C0;");
document.writeln("	width: 25%;");
document.writeln("	height: 45px;");
document.writeln("	font-weight: 600;");
document.writeln("	font-size: 18px;");
document.writeln("	font-family:微软雅黑;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("<style>");
document.writeln(".danshuan { font-weight: bold; font-size: 18px; text-align: center;}");
document.writeln(".danshuan table {}");
document.writeln(".danshuan td { padding: 5px;}");
document.writeln(".danshuan span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".danshuan { font-size: 15px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'ipi\'>白哥哥<font color=\'#FFFF00\'>【金牌单双】</font></div>");
document.writeln("<table width=\'100%\' class=\'cypt\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>035期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【单单单】</font><font color=\'#0000FF\'>开：？00</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>034期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【单单单】</font><font color=\'#0000FF\'>开：蛇11</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>032期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【双双双】</font><font color=\'#0000FF\'>开：鼠40</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>029期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【双双双】</font><font color=\'#0000FF\'>开：鼠16</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>027期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【双双双】</font><font color=\'#0000FF\'>开：鼠28</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>026期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【双双双】</font><font color=\'#0000FF\'>开：狗30</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>025期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【双双双】</font><font color=\'#0000FF\'>开：猴32</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>022期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【单单单】</font><font color=\'#0000FF\'>开：猪41</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>021期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【单单单】</font><font color=\'#0000FF\'>开：蛇35</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>020期</font><img src=\'/yjjy/tz/images/am.png\'><font color=\'#FF0000\'>【单单单】</font><font color=\'#0000FF\'>开：猪29</font>准</td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'/#tz#876161\'><img src=/yjjy/tz/images/am.png width=35 height=23><span style=font-family:楷体;color:#00f><font size=\'4\'>好料记得截图分享</font></span><span style=font-family:楷体;><font size=\'5\' color=\'#FF0000\'>014993</font></span><font color=\'#FF0000\' size=\'5\'><span style=font-family:楷体;>.com</a></strong></table>");
document.writeln("</font>");
document.writeln("</tr></td>     ");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>	");