document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong333 { color: #171817; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #000;}");
document.writeln(".bizhong333-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #0a2cab;}");
document.writeln(".bizhong333-box { display: flex;}");
document.writeln(".bizhong333-box ul {}");
document.writeln(".bizhong333-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong333-box .bizhong333-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong333-box .bizhong333-r { width: 100%;}");
document.writeln(".bizhong333-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong333 { font-size: 16px;}");
document.writeln(".bizhong333-tit { font-size: 18px;}");
document.writeln(".bizhong333-box { display: block;}");
document.writeln(".bizhong333-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong333-box .bizhong333-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong333-box .bizhong333-r { width: 100%;}");
document.writeln(".bizhong333-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");


document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">077期必中18码：</font><font color=\'#FF0000\' size=\'2\'>12.36.48.09.21.33.03.15.27.11.23.35.10.34.46.04.16.40</font></li>");
document.writeln("            	<li>077期必中⑨码：<font color=\'#FF0000\' style=\"font-size: 14pt\">12.36.48.09.21.33.03.15.27</font></li>");
document.writeln("            	<li>077期必中①肖：<font color=\'#FF0000\' size=\'5\'>（马-12.36.48）</font></li>");
document.writeln("            	<li>077期必中③肖：<font color=\'#FF0000\' size=\'4\'>马鸡兔</font></li>");
document.writeln("            	<li>077期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>马鸡兔羊猴虎</font></li>");
document.writeln("            	<li>077期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>马鸡兔羊猴虎龙鼠</font></li>");
document.writeln("             	<li>077期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>马鸡兔羊猴虎龙鼠蛇狗</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>076期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>鸡虎狗鼠<span style=\'background-color: #FFFF00\'>兔</span>马</font></li>");
document.writeln("            	<li>076期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>鸡虎狗鼠<span style=\'background-color: #FFFF00\'>兔</span>马猴羊</font></li>");
document.writeln("             	<li>076期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>鸡虎狗鼠<span style=\'background-color: #FFFF00\'>兔</span>马猴羊蛇龙</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">075期必中18码：</font><font color=\'#FF0000\' size=\'2\'>08.32.44.<span style=\'background-color: #FFFF00\'>09</span>.21.33.03.15.27.06.18.30.12.24.36.07.19.43</font></li>");
document.writeln("            	<li>075期必中⑨码：<font color=\'#FF0000\' style=\"font-size: 14pt\">08.32.44.<span style=\'background-color: #FFFF00\'>09</span>.21.33.03.15.27</font></li>");
document.writeln("            	<li>075期必中①肖：<font color=\'#FF0000\' size=\'5\'>（狗-08.32.44）</font></li>");
document.writeln("            	<li>075期必中③肖：<font color=\'#FF0000\' size=\'4\'>狗<span style=\'background-color: #FFFF00\'>鸡</span>兔</font></li>");
document.writeln("            	<li>075期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>狗<span style=\'background-color: #FFFF00\'>鸡</span>兔鼠马猪</font></li>");
document.writeln("            	<li>075期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>狗<span style=\'background-color: #FFFF00\'>鸡</span>兔鼠马猪牛蛇</font></li>");
document.writeln("             	<li>075期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>狗<span style=\'background-color: #FFFF00\'>鸡</span>兔鼠马猪牛蛇龙羊</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>074期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>牛虎猪马兔蛇龙狗</font></li>");
document.writeln("             	<li>074期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>牛虎猪马兔蛇龙狗<span style=\'background-color: #FFFF00\'>羊</span>猴</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>073期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>猴鸡狗龙羊虎</font></li>");
document.writeln("            	<li>073期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>猴鸡狗龙羊虎<span style=\'background-color: #FFFF00\'>兔</span>蛇</font></li>");
document.writeln("             	<li>073期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>猴鸡狗龙羊虎<span style=\'background-color: #FFFF00\'>兔</span>蛇牛马</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");





document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中end-->");
document.writeln("");
document.writeln("");