document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong333 { color: #171817; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #000;}");
document.writeln(".bizhong333-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #0a2cab;}");
document.writeln(".bizhong333-box { display: flex;}");
document.writeln(".bizhong333-box ul {}");
document.writeln(".bizhong333-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong333-box .bizhong333-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong333-box .bizhong333-r { width: 100%;}");
document.writeln(".bizhong333-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong333 { font-size: 16px;}");
document.writeln(".bizhong333-tit { font-size: 18px;}");
document.writeln(".bizhong333-box { display: block;}");
document.writeln(".bizhong333-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong333-box .bizhong333-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong333-box .bizhong333-r { width: 100%;}");
document.writeln(".bizhong333-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">069期必中18码：</font><font color=\'#FF0000\' size=\'2\'>06.18.30.04.16.28.02.14.26.07.31.43.17.29.41.09.21.33</font></li>");
document.writeln("            	<li>069期必中⑨码：<font color=\'#FF0000\' style=\"font-size: 14pt\">06.18.30.04.16.28.02.14.26</font></li>");
document.writeln("            	<li>069期必中①肖：<font color=\'#FF0000\' size=\'5\'>（鼠-06.18.30）</font></li>");
document.writeln("            	<li>069期必中③肖：<font color=\'#FF0000\' size=\'4\'>鼠虎龙</font></li>");
document.writeln("            	<li>069期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>鼠虎龙猪牛鸡</font></li>");
document.writeln("            	<li>069期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>鼠虎龙猪牛鸡蛇羊</font></li>");
document.writeln("             	<li>069期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>鼠虎龙猪牛鸡蛇羊马狗</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>068期必中③肖：<font color=\'#FF0000\' size=\'4\'>羊<span style=\'background-color: #FFFF00\'>狗</span>兔</font></li>");
document.writeln("            	<li>068期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>羊<span style=\'background-color: #FFFF00\'>狗</span>兔猴蛇虎</font></li>");
document.writeln("            	<li>068期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>羊<span style=\'background-color: #FFFF00\'>狗</span>兔猴蛇虎猪鸡</font></li>");
document.writeln("             	<li>068期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>羊<span style=\'background-color: #FFFF00\'>狗</span>兔猴蛇虎猪鸡龙鼠</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">067期必中18码：</font><font color=\'#FF0000\' size=\'2\'>06.18.42.03.15.39.09.21.33.11.23.35.08.20<span style=\'background-color: #FFFF00\'>44</span>.13.25.49</font></li>");

document.writeln("            	<li>067期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>鼠兔鸡羊<span style=\'background-color: #FFFF00\'>狗</span>蛇</font></li>");
document.writeln("            	<li>067期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>鼠兔鸡羊<span style=\'background-color: #FFFF00\'>狗</span>蛇牛马</font></li>");
document.writeln("             	<li>067期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>鼠兔鸡羊<span style=\'background-color: #FFFF00\'>狗</span>蛇牛马龙猴</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">066期必中18码：</font><font color=\'#FF0000\' size=\'2\'>05.17.41.07.19.31.13.25.49.<span style=\'background-color: #FFFF00\'>12</span>.24.36.04.16.28.09.21.33</font></li>");

document.writeln("            	<li>066期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>牛猪蛇<span style=\'background-color: #FFFF00\'>马</span>虎鸡</font></li>");
document.writeln("            	<li>066期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>牛猪蛇<span style=\'background-color: #FFFF00\'>马</span>虎鸡龙猴</font></li>");
document.writeln("             	<li>066期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>牛猪蛇<span style=\'background-color: #FFFF00\'>马</span>虎鸡龙猴鼠狗</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>065期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>猴羊鼠狗龙蛇鸡牛</font></li>");
document.writeln("             	<li>065期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>猴羊鼠狗龙蛇鸡牛虎<span style=\'background-color: #FFFF00\'>马</span></font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");


document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>064期必中①肖：<font color=\'#FF0000\' size=\'5\'>（<span style=\'background-color: #FFFF00\'>猪</span>-07.19.43）</font></li>");
document.writeln("            	<li>064期必中③肖：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>猪</span>羊鼠</font></li>");
document.writeln("            	<li>064期必中⑥肖：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>猪</span>羊鼠兔马狗</font></li>");
document.writeln("            	<li>064期必中⑧肖：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>猪</span>羊鼠兔马狗牛猴</font></li>");
document.writeln("             	<li>064期必中⑩肖：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>猪</span>羊鼠兔马狗牛猴鸡龙</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>063期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>兔牛猴龙猪虎</font></li>");
document.writeln("            	<li>063期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>兔牛猴龙猪虎狗<span style=\'background-color: #FFFF00\'>羊</span></font></li>");
document.writeln("             	<li>063期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>兔牛猴龙猪虎狗<span style=\'background-color: #FFFF00\'>羊</span>蛇马</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">062期必中18码：</font><font color=\'#FF0000\' size=\'2\'>13.25.49.03.15.27.06.18.30.11.23.<span style=\'background-color: #FFFF00\'>35</span>.10.22.46.02.14.38</font></li>");

document.writeln("            	<li>062期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>蛇兔鼠<span style=\'background-color: #FFFF00\'>羊</span>猴龙</font></li>");
document.writeln("            	<li>062期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>蛇兔鼠<span style=\'background-color: #FFFF00\'>羊</span>猴龙鸡狗</font></li>");
document.writeln("             	<li>062期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>蛇兔鼠<span style=\'background-color: #FFFF00\'>羊</span>猴龙鸡狗虎牛</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>061期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>马狗蛇龙猪兔<span style=\'background-color: #FFFF00\'>猴</span>羊</font></li>");
document.writeln("             	<li>061期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>马狗蛇龙猪兔<span style=\'background-color: #FFFF00\'>猴</span>羊虎牛</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>060期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>马龙猴虎鼠猪鸡蛇</font></li>");
document.writeln("             	<li>060期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>马龙猴虎鼠猪鸡蛇牛<span style=\'background-color: #FFFF00\'>羊</span></font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>059期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>兔鼠猪狗羊虎<span style=\'background-color: #FFFF00\'>马</span>龙</font></li>");
document.writeln("             	<li>059期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>兔鼠猪狗羊虎<span style=\'background-color: #FFFF00\'>马</span>龙牛鸡</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>058期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>鼠兔猴<span style=\'background-color: #FFFF00\'>猪</span>虎龙</font></li>");
document.writeln("            	<li>058期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>鼠兔猴<span style=\'background-color: #FFFF00\'>猪</span>虎龙牛鸡</font></li>");
document.writeln("             	<li>058期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>鼠兔猴<span style=\'background-color: #FFFF00\'>猪</span>虎龙牛鸡马羊</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">057期必中18码：</font><font color=\'#FF0000\' size=\'2\'>06.18.30.08.<span style=\'background-color: #FFFF00\'>20</span>.32.10.22.34.05.17.41.14.26.38.07.19.43</font></li>");
document.writeln("            	<li>057期必中⑨码：<font color=\'#FF0000\' style=\"font-size: 14pt\">06.18.30.08.<span style=\'background-color: #FFFF00\'>20</span>.32.10.22.34</font></li>");
document.writeln("            	<li>057期必中①肖：<font color=\'#FF0000\' size=\'5\'>（鼠-06.18.30）</font></li>");
document.writeln("            	<li>057期必中③肖：<font color=\'#FF0000\' size=\'4\'>鼠<span style=\'background-color: #FFFF00\'>狗</span>猴</font></li>");
document.writeln("            	<li>057期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>鼠<span style=\'background-color: #FFFF00\'>狗</span>猴牛龙猪</font></li>");
document.writeln("            	<li>057期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>鼠<span style=\'background-color: #FFFF00\'>狗</span>猴牛龙猪马羊</font></li>");
document.writeln("             	<li>057期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>鼠<span style=\'background-color: #FFFF00\'>狗</span>猴牛龙猪马羊蛇兔</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>056期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>猪鸡猴蛇兔狗</font></li>");
document.writeln("            	<li>056期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>猪鸡猴蛇兔狗<span style=\'background-color: #FFFF00\'>鼠</span>虎</font></li>");
document.writeln("             	<li>056期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>猪鸡猴蛇兔狗<span style=\'background-color: #FFFF00\'>鼠</span>虎羊马</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>055期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>羊马龙猴牛虎鼠猪</font></li>");
document.writeln("             	<li>055期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>羊马龙猴牛虎鼠猪<span style=\'background-color: #FFFF00\'>狗</span>蛇</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>054期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>虎猪狗牛兔马鸡<span style=\'background-color: #FFFF00\'>蛇</span></font></li>");
document.writeln("             	<li>054期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>虎猪狗牛兔马鸡<span style=\'background-color: #FFFF00\'>蛇</span>鼠猴</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("             	<li>053期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>虎蛇兔猪狗鼠猴马<span style=\'background-color: #FFFF00\'>【羊】</span>龙</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");

document.writeln("            	<li>052期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>牛虎鼠龙猪狗</font></li>");
document.writeln("            	<li>052期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>牛虎鼠龙猪狗鸡<span style=\'background-color: #FFFF00\'>【猴】</span></font></li>");
document.writeln("             	<li>052期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>牛虎鼠龙猪狗鸡<span style=\'background-color: #FFFF00\'>【猴】</span>蛇兔</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">051期必中18码：</font><font color=\'#FF0000\' size=\'2\'>04.28.40.07.19.43.13.37.<span style=\'background-color: #FFFF00\'>49</span>.08.20.32.10.22.46.06.30.42</font></li>");
document.writeln("            	<li>051期必中⑨码：<font color=\'#FF0000\' style=\"font-size: 14pt\">04.28.40.07.19.43.13.37.<span style=\'background-color: #FFFF00\'>49</span></font></li>");
document.writeln("            	<li>051期必中①肖：<font color=\'#FF0000\' size=\'5\'>（虎-04.28.40）</font></li>");
document.writeln("            	<li>051期必中③肖：<font color=\'#FF0000\' size=\'4\'>虎猪<span style=\'background-color: #FFFF00\'>蛇</span></font></li>");
document.writeln("            	<li>051期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>虎猪<span style=\'background-color: #FFFF00\'>蛇</span>狗猴鼠</font></li>");
document.writeln("            	<li>051期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>虎猪<span style=\'background-color: #FFFF00\'>蛇</span>狗猴鼠牛马</font></li>");
document.writeln("             	<li>051期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>虎猪<span style=\'background-color: #FFFF00\'>蛇</span>狗猴鼠牛马羊龙</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">050期必中18码：</font><font color=\'#FF0000\' size=\'2\'>10.22.34.08.20.32.13.25.49.<span style=\'background-color: #FFFF00\'>05</span>.17.41.21.33.45.03.15.27</font></li>");

document.writeln("            	<li>050期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>猴狗蛇<span style=\'background-color: #FFFF00\'>牛</span>鸡兔</font></li>");
document.writeln("            	<li>050期必中⑧肖：<font color=\'#FF0000\' size=\'4\'>猴狗蛇<span style=\'background-color: #FFFF00\'>牛</span>鸡兔虎猪</font></li>");
document.writeln("             	<li>050期必中⑩肖：<font color=\'#FF0000\' size=\'4\'>猴狗蛇<span style=\'background-color: #FFFF00\'>牛</span>鸡兔虎猪龙马</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");






document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中end-->");
document.writeln("");
document.writeln("");