document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!-----开始----->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("");
document.writeln("<font color=\'#008000\' size=\'5\' style=\'font-weight: 700\' face=\'微软雅黑\'>【华哥聊码】 → （12组3中2）</font><font style=\'font-weight:700\' size=\'4\' face=\'微软雅黑\'><br>");
document.writeln("<!--说明-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 14pt\" color=\"#000080\">294期【华哥聊码】 → （12组3中2）</font><font size=\"5\"><br>");
document.writeln("		<font color=\"#FF0000\">（23倍）</font></font></b><font size=\"5\"></span></font></b><br>");
document.writeln("		<b>");
document.writeln("");
document.writeln("		【48.05.22】【16.42.25】【26.45.13】<br>");
document.writeln("		【20.09.12】【30.39.15】【27.42.18】<br>		");
document.writeln("		【28.16.39】【01.04.42】【19.18.06】<br>				");
document.writeln("		【31.11.19】【46.28.44】【11.10.46】</b><br>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 14pt\" color=\"#000080\">293期【华哥聊码】 → （12组3中2）</font><font size=\"5\"><br>");
document.writeln("		<font color=\"#FF0000\">（23倍）</font></font></b><font size=\"5\"></span></font></b><br>");
document.writeln("		<b>");
document.writeln("");
document.writeln("		【47.28.25】【04.21.29】【35.31.05】<br>");
document.writeln("		【02.34.46】【39.36.35】【48.28.12】<br>		");
document.writeln("		【12.36.09】【16.07.11】【05.33.42】<br>				");
document.writeln("		【46.48.45】【29.13.24】【<span style=\'background-color: #FFFF00\'>26.32</span>.15】</b><br>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 14pt\" color=\"#000080\">292期【华哥聊码】 → （12组3中2）</font><font size=\"5\"><br>");
document.writeln("		<font color=\"#FF0000\">（23倍）</font></font></b><font size=\"5\"></span></font></b><br>");
document.writeln("		<b>");
document.writeln("");
document.writeln("		【21.39.18】【32.31.05】【11.29.22】<br>");
document.writeln("		【17.01.39】【35.36.03】【43.<span style=\"background-color: #FFFF00\">10.37</span>】<br>		");
document.writeln("		【47.31.35】【28.46.27】【19.36.43】<br>				");
document.writeln("		【04.49.08】【24.38.32】【04.17.18】</b><br>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("　</font>");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388tz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("</font>");
document.writeln("");
document.writeln("  ");