document.writeln("");
document.writeln("");
document.writeln("<body style=\'margin: 0; overflow-x&#65306;auto; overflow-y&#65306;hidden;\'>");
document.writeln("");
document.writeln(" <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'&#26999;&#20307;\' style=\'font-size: 20pt\'>62631a</font><font color=\'#FFFFFF\' face=\'&#26999;&#20307;\' style=\'font-size: 20pt\'>&#12302;&#32477;&#26432;&#9312;&#23614;&#9312;&#32918;&#12303;</font></b></table>");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("<!--&#25512;&#24191;&#24320;&#22987;-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.manolotron.com:49/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:&#26999;&#20307;color:#00f><font style=\'font-size: 16pt\'>49&#22270;&#24211;<font color=\'#FF0000\'>49.com</font>&#22270;&#32440;&#26368;&#20840;-&#26368;&#24555;</a></strong></tr></table>");
document.writeln("<!--&#25512;&#24191;&#32467;&#26463;-->");
document.writeln("");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:left;background:#FFF;\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>071期杀【2尾】开00准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>070期杀【1尾】开06准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>069期杀【5尾】开08准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>068期杀【3尾】开20准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>067期杀【8尾】开34准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>066期杀【7尾】开42准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>065期杀【1尾】开04准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>064期杀【6尾】开46错 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>063期杀【5尾】开31准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>062期杀【5尾】开49准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>061期杀【6尾】开33准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>060期杀【7尾】开44准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>059期杀【9尾】开30准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>058期杀【7尾】开11准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>057期杀【3尾】开46准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>056期杀【8尾】开23准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>055期杀【2尾】开31准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>054期杀【5尾】开09准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>053期杀【4尾】开25准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>052期杀【6尾】开09准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>051期杀【1尾】开12准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>050期杀【0尾】开39准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>049期杀【7尾】开35准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>048期杀【8尾】开30准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>047期杀【1尾】开09准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>046期杀【5尾】开02准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>045期杀【7尾】开28准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>044期杀【6尾】开02准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>043期杀【9尾】开42准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>042期杀【4尾】开15准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>041期杀【5尾】开41准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>040期杀【9尾】开40准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>039期杀【2尾】开19准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>038期杀【6尾】开06错 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>037期杀【6尾】开10准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>036期杀【2尾】开29准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>035期杀【7尾】开44准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>034期杀【4尾】开11准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>033期杀【7尾】开30准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>032期杀【3尾】开40准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>031期杀【6尾】开07准 </span> </font></li>");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>030期杀【2尾】开03准 </span> </font></li>");
document.writeln("");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </ul></td> </tr>");
document.writeln("        </div>");
document.writeln("  ");
document.writeln("		        <td style=\'text-align:left;background:#FFF;\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("   ");

document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>071期杀【鼠】开00准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>070期杀【虎】开猪准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>069期杀【狗】开鸡准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>068期杀【猴】开鸡准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>067期杀【龙】开羊准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>066期杀【马】开猪准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>065期杀【兔】开牛准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>064期杀【虎】开羊准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>063期杀【猴】开狗准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>062期杀【马】开龙准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>061期杀【鼠】开猴准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>060期杀【龙】开鸡准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>059期杀【马】开猪准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>058期杀【兔】开马准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>057期杀【虎】开羊准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>056期杀【羊】开马准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>055期杀【猪】开狗准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>054期杀【兔】开猴准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>053期杀【羊】开龙准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>052期杀【马】开猴准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>051期杀【牛】开蛇准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>050期杀【羊】开虎准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>049期杀【马】开马错</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>048期杀【虎】开猪准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>047期杀【狗】开猴准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>046期杀【鼠】开兔准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>045期杀【蛇】开牛准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>044期杀【虎】开兔准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>043期杀【猴】开猪准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>042期杀【猪】开虎准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>041期杀【马】开鼠准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>040期杀【龙】开鼠准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>039期杀【羊】开鸡准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>038期杀【鼠】开狗准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>037期杀【狗】开马准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>036期杀【猪】开猪错</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>035期杀【猴】开猴错</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>034期杀【猪】开蛇准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>033期杀【牛】开狗准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>032期杀【兔】开鼠准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>031期杀【鸡】开鸡错</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>030期杀【虎】开牛准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");


document.writeln("");
document.writeln("   ");
document.writeln("");
document.writeln("			");
document.writeln("			");
document.writeln("			</ul></td>		");
document.writeln("			");
document.writeln("			");
document.writeln("    </tr> </div>");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");