document.writeln("");
document.writeln("");
document.writeln("<body style=\'margin: 0; overflow-x&#65306;auto; overflow-y&#65306;hidden;\'>");
document.writeln("");
document.writeln(" <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'&#26999;&#20307;\' style=\'font-size: 20pt\'>62827a</font><font color=\'#FFFFFF\' face=\'&#26999;&#20307;\' style=\'font-size: 20pt\'>&#12302;&#32477;&#26432;&#9312;&#23614;&#9312;&#32918;&#12303;</font></b></table>");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");

document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:left;background:#FFF;\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>");
document.writeln("");
document.writeln("");

document.writeln("");





document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>186期杀【1尾】开00准 </span> </font></li>");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>185期杀【3尾】开42准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>184期杀【2尾】开42错 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>183期杀【4尾】开25准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>182期杀【5尾】开27准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>181期杀【2尾】开27准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>180期杀【0尾】开02准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>179期杀【8尾】开01准 </span> </font></li>");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>178期杀【5尾】开20准 </span> </font></li>");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>177期杀【1尾】开11错 </span> </font></li>");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>176期杀【6尾】开03准 </span> </font></li>");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>175期杀【2尾】开40准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>174期杀【0尾】开48准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>173期杀【2尾】开49准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>172期杀【7尾】开32准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>171期杀【5尾】开16准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>170期杀【0尾】开10错</span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>169期杀【1尾】开45准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>168期杀【0尾】开14准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>167期杀【3尾】开14准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>166期杀【3尾】开32准 </span> </font></li>");
document.writeln("");
document.writeln("");
document.writeln("  <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>165期杀【1尾】开03准 </span> </font></li>");
document.writeln("");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </ul></td> </tr>");
document.writeln("        </div>");
document.writeln("  ");
document.writeln("		        <td style=\'text-align:left;background:#FFF;\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>186期杀【兔】开00准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>185期杀【马】开猪准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>184期杀【鸡】开猪准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>183期杀【猪】开龙准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>182期杀【鼠】开虎准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>181期杀【虎】开虎错</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>180期杀【鼠】开兔准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>179期杀【兔】开龙准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>178期杀【猪】开鸡准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>177期杀【鸡】开马准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>176期杀【猴】开虎准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>175期杀【兔】开牛准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>174期杀【狗】开蛇准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>173期杀【蛇】开龙准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>172期杀【猴】开鸡准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>171期杀【虎】开牛准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>170期杀【猴】开羊准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>169期杀【马】开猴准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>168期杀【猪】开兔准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>167期杀【鼠】开兔准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>166期杀【兔】开鸡准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");
document.writeln(" <li style=\'list-style-type: none;\' class=\'mli\'>  ");
document.writeln("			<font style=\'color:#000\' class=\'font1\'> ");
document.writeln("						<span style=\'font-size: 11pt\'>165期杀【羊】开虎准</span> </font></li>");
document.writeln("			<span style=\'font-size: 11pt\'></a> </span> </li>");
document.writeln("			");
document.writeln("   ");




document.writeln("");
document.writeln("   ");
document.writeln("");
document.writeln("			");
document.writeln("			");
document.writeln("			</ul></td>		");
document.writeln("			");
document.writeln("			");
document.writeln("    </tr> </div>");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");