document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong555 { color: #00ff00; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #000;}");
document.writeln(".bizhong555-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #f00;}");
document.writeln(".bizhong555-box { display: flex;}");
document.writeln(".bizhong555-box ul {}");
document.writeln(".bizhong555-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong555-box .bizhong555-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong555-box .bizhong555-r { width: 100%;}");
document.writeln(".bizhong555-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong555 { font-size: 16px;}");
document.writeln(".bizhong555-tit { font-size: 18px;}");
document.writeln(".bizhong555-box { display: block;}");
document.writeln(".bizhong555-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong555-box .bizhong555-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong555-box .bizhong555-r { width: 100%;}");
document.writeln(".bizhong555-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong555\'>");
document.writeln("	<div class=\'bizhong555-tit\'>澳门资料网（62635b.com）一尾一码</div>");
document.writeln("	<div class=\'bizhong555-box\'>");
document.writeln("    	<div class=\'bizhong555-l\'>");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">153期必中18码：</font><font color=\'#FF0000\' size=\'2\'>05.15.35.21.31.41.07.17.37.28.38.48.26.36.46.03.23.33</font></li>");
document.writeln("            	<li>153期必中12码：<font color=\'#FF0000\' style=\"font-size: 11pt\">05.15.35.21.31.41.07.17.37.28.38.48</font></li>");
document.writeln("            	<li>153期必中六码：<font color=\'#FF0000\' size=\'4\'>05.15.35.21.31.41</font></li>");
document.writeln("            	<li>153期必中①码：<font color=\'#FF0000\' size=\'5\'>（5尾-05.15.35）</font></li>");
document.writeln("            	<li>153期必中二尾：<font color=\'#FF0000\' size=\'4\'>5-1</font></li>");
document.writeln("            	<li>153期必中四尾：<font color=\'#FF0000\' size=\'4\'>5-1-7-8</font></li>");
document.writeln("            	<li>153期必中六尾：<font color=\'#FF0000\' size=\'4\'>5-1-7-8-6-3</font></li>");
document.writeln("             	<li>153期必中八尾：<font color=\'#FF0000\' size=\'4\'>5-1-7-8-6-3-0-9</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong555\'>");
document.writeln("	<div class=\'bizhong555-tit\'>澳门资料网（62635b.com）一尾一码</div>");
document.writeln("	<div class=\'bizhong555-box\'>");
document.writeln("    	<div class=\'bizhong555-l\'>");
document.writeln("        	<ul>");
document.writeln("");
document.writeln("            	<li>151期必中二尾：<font color=\'#FF0000\' size=\'4\'>2-<span style=\'background-color: #FFFF00\'>【8】</span></font></li>");
document.writeln("            	<li>151期必中三尾：<font color=\'#FF0000\' size=\'4\'>2-<span style=\'background-color: #FFFF00\'>【8】</span>-1</font></li>");
document.writeln("            	<li>151期必中四尾：<font color=\'#FF0000\' size=\'4\'>2-<span style=\'background-color: #FFFF00\'>【8】</span>-1-5</font></li>");
document.writeln("            	<li>151期必中五尾：<font color=\'#FF0000\' size=\'4\'>2-<span style=\'background-color: #FFFF00\'>【8】</span>-1-5-0</font></li>");
document.writeln("            	<li>151期必中六尾：<font color=\'#FF0000\' size=\'4\'>2-<span style=\'background-color: #FFFF00\'>【8】</span>-1-5-0-3</font></li>");
document.writeln("             	<li>151期必中七尾：<font color=\'#FF0000\' size=\'4\'>2-<span style=\'background-color: #FFFF00\'>【8】</span>-1-5-0-3-4</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("    	<div class=\'bizhong555-r\'>");
document.writeln("        	<ul>");
document.writeln("");
document.writeln("            	<li>必中六码：<font color=\'#FF0000\' size=\'4\'>08.28.<span style=\'background-color: #FFFF00\'>【48】</span></font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>11.21.41</font></li>");
document.writeln("            	<li>必中12码：<font color=\'#FF0000\' size=\'4\'>15.35.45</font></li>");
document.writeln("            	<li>必中15码：<font color=\'#FF0000\' size=\'4\'>10.20.40</font></li>");
document.writeln("            	<li>必中18码：<font color=\'#FF0000\' size=\'4\'>13.23.43</font></li>");
document.writeln("            	<li>必中21码：<font color=\'#FF0000\' size=\'4\'>14.24.44</font></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong555-foot\'><font color=\'#00FFFF\'>151期一尾中特：</font><font color=\'#FFFF00\' size=\'6\'>（<font color=\'#FFFF00\'>2尾</font>）</font><font color=\'#00FF00\'>单车变宝马~</font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中end-->");
document.writeln("");
document.writeln("");
document.writeln("");