document.writeln("");





document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>296期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font color=\"#FF0000\" style=\"font-size: 11pt\">");
document.writeln("		20.32.44.06.18.30.21.33.45.04.16.28.13.25.49</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">一肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><font size=\"5\">狗【中】</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗鼠鸡</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗鼠鸡虎蛇</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗鼠鸡虎蛇羊兔</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗鼠鸡虎蛇羊兔猴龙</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">296期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>295期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔鼠虎蛇羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">牛</span></font>龙</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔鼠虎蛇羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">牛</span></font>龙狗马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">295期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");


document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>294期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猴鸡马蛇虎牛羊兔<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">294期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>292期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">蛇狗猴猪牛马<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">蛇狗猴猪牛马<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font>虎鼠</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">292期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>291期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猪蛇鼠鸡牛羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猪蛇鼠鸡牛羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font>猴虎</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">291期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>290期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">龙猴鸡兔牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>狗</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">龙猴鸡兔牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>狗蛇马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">290期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");


document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>289期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猴兔<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猴兔<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font>狗虎</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猴兔<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font>狗虎马鸡</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猴兔<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font>狗虎马鸡羊猪</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">289期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>288期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font color=\"#FF0000\" style=\"font-size: 11pt\">");
document.writeln("		02.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">14</span></font>.38.06.30.42.04.16.28.12.24.36.08.20.44</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">一肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><font size=\"5\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font>【中】</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font>鼠虎</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font>鼠虎马狗</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font>鼠虎马狗兔羊</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font>鼠虎马狗兔羊猴猪</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">288期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>287期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");


document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鸡羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猴</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鸡羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猴</span></font>龙牛</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鸡羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猴</span></font>龙牛蛇鼠</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鸡羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猴</span></font>龙牛蛇鼠狗马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">287期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>286期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">龙猪牛狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">兔</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">龙猪牛狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">兔</span></font>蛇鸡</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">龙猪牛狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">兔</span></font>蛇鸡虎鼠</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">286期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>285期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font color=\"#FF0000\" style=\"font-size: 11pt\">");
document.writeln("	12.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">24</span></font>.36.13.25.49.07.19.31.11.23.35.02.14.26</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">一肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><font size=\"5\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">马</span></font>【中】</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">马</span></font>蛇猪</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">马</span></font>蛇猪羊龙</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">马</span></font>蛇猪羊龙牛猴</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">马</span></font>蛇猪羊龙牛猴鼠狗</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">285期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>284期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鸡狗虎龙猴蛇羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">牛</span></font>鼠</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">284期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>283期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font color=\"#FF0000\" style=\"font-size: 11pt\">");
document.writeln("		08.20.44.06.18.30.03.15.27.05.17.41.21.33.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">45</span></font></font></b></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗鼠兔牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗鼠兔牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font>猪龙</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗鼠兔牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font>猪龙虎马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">283期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>282期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猪龙猴羊狗虎兔<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">牛</span></font>马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">282期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>281期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">羊</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">羊</span></font>兔鼠</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">羊</span></font>兔鼠蛇虎</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">狗龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">羊</span></font>兔鼠蛇虎鸡猴</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">281期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>280期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">马蛇猴牛狗鸡虎猪<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">280期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>279期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">虎狗马羊猪蛇龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">兔</span></font>猴</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">279期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>278期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">龙鼠猪马羊狗蛇鸡<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">278期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");


document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>277期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");


document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">牛龙鸡狗兔猪<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">牛龙鸡狗兔猪<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>蛇羊</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">277期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>276期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");

document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">猴龙马虎猪牛鼠狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font></span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">276期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");

