document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>325期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">四头</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">2413头</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">四行</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">水金土火</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">双波</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">红波蓝波</span></b></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font size=\'2\' color=\"#FF0000\">10.12.15.18.20.23.24.26.30.34.40.42.45.46.47.48</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">一肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><font size=\"5\">鼠【暴富】</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鼠龙猴</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鼠龙猴狗马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鼠龙猴狗马羊虎</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鼠龙猴狗马羊虎蛇牛</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">325期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">开奖【鼠16】中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>324期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">四头</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><span style=\'background-color: #FFFF00\'>2</span>140头</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">四行</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\"><span style=\'background-color: #FFFF00\'>土</span>水金木</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">双波</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">红波<span style=\'background-color: #FFFF00\'>蓝波</span></span></b></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font size=\'2\' color=\"#FF0000\">01.02.09.10.12.13.14.18.20.23.24.25.</font><font size=\'5\' color=\"#FF0000\"><span style=\'background-color: #FFFF00\'>26</span></font><font size=\'2\' color=\"#FF0000\">.41.42.47.48</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔狗猴<span style=\'background-color: #FFFF00\'>虎</span>龙</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔狗猴<span style=\'background-color: #FFFF00\'>虎</span>龙蛇猪</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔狗猴<span style=\'background-color: #FFFF00\'>虎</span>龙蛇猪羊马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">324期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">开奖【鼠16】中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>323期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">四头</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">324<span style=\'background-color: #FFFF00\'>0</span>头</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">四行</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">土<span style=\'background-color: #FFFF00\'>金</span>木水</span></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">马猴猪<span style=\'background-color: #FFFF00\'>虎</span>羊</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">马猴猪<span style=\'background-color: #FFFF00\'>虎</span>羊牛龙</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">马猴猪<span style=\'background-color: #FFFF00\'>虎</span>羊牛龙兔蛇</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">323期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">开奖【鼠16】中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");