document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>073期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font color=\"#FF0000\" style=\"font-size: 12pt\">");
document.writeln("		02.03.08.09.20.21.26.28.30.31<br>32.33.35.38.39.40.42.43.48</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">一肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><font size=\"5\">兔【中】</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">三肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔猴蛇</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔猴蛇猪虎</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔猴蛇猪虎鸡马</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">兔猴蛇猪虎鸡马牛狗</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">073期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">开奖【62109.com】中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>072期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\'color:#00f; font-weight:700\'>特码</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b>");
document.writeln("		<font color=\"#FF0000\" style=\"font-size: 12pt\">");
document.writeln("		01.07.08.09.12.13.14.18.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">19.</span></font><font color=\"#FF0000\" style=\"font-size: 12pt\">30<br>31.34.37.42.43.47.48.49</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">羊马兔猪蛇龙猴</span><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><span style=\"font-size: 12pt\">鸡</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">072期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">开奖【62109.com】中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    </tbody>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#0000ff\' width=\'98%\' height=\'35\'>");
document.writeln("		<span style=\'color: #FFFFFF; font-weight:700\'><font size=\'4\'>071期澳门码神一肖一码大公开</font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">五肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鼠猪羊龙</span><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">虎</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">七肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鼠猪羊龙</span><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">虎</span></font><span style=\"font-size: 12pt\">猴蛇</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\'>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f; font-weight: 700\">九肖</span></td><td style=\'text-align:left\' align=\'center\' width=\'65%\' height=\'35\'>");
document.writeln("		<b><span style=\"font-size: 12pt\">鼠猪羊龙</span><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">虎</span></font><span style=\"font-size: 12pt\">猴蛇狗牛</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' width=\'82%\' height=\'35\'><b>");
document.writeln("		<span style=\"font-size: 12pt; color: #00f\">071期</span><span style=\'color:red; font-size:12pt\'>一肖一码</span><span style=\"font-size: 12pt; color: #000\">开奖【62109.com】中奖</span></b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");