document.writeln("<table style=\'border-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'font-weight:700;border:1px solid #000; height: 60px;\' align=center bgcolor=#000000 width=100%>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>62103b.com</font><font color=\'#FFFFFF\'>『24码中特』</font></font></b></table></td></tr>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!-----开始----->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-weight:700\' size=\'3\' face=\'微软雅黑\'>");
document.writeln("216期：<font color=\'#FF0000\'>【精准24码爆特】</font>开<font color=\'#FFFF00\'><span style=\'background-color: #000000\'>？00</span></font></font></td></tr>");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<p style=line-height:200%>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("<span style=font-size:13pt;font-family:微软雅黑>");
document.writeln("");
document.writeln("（02.15.31.11.06.30.19.03.24.12.42.28）<br>");
document.writeln("（36.08.43.37.21.44.32.23.40.17.01.45）</span></font></p>");
document.writeln("</td></tr>");
document.writeln("<!-----结束----->");
document.writeln("");
document.writeln("");
document.writeln("<!-----开始----->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-weight:700\' size=\'3\' face=\'微软雅黑\'>");
document.writeln("215期：<font color=\'#FF0000\'>【精准24码爆特】</font>开<font color=\'#FFFF00\'><span style=\'background-color: #000000\'>兔49</span></font></font></td></tr>");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<p style=line-height:200%>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("<span style=font-size:13pt;font-family:微软雅黑>");
document.writeln("");
document.writeln("（01.<span style=\'background-color: #FFFF00\'>49</span>.17.31.28.44.18.33.20.04.25.41）<br>");
document.writeln("（34.27.47.15.36.12.39.10.06.35.02.16）</span></font></p>");
document.writeln("</td></tr>");
document.writeln("<!-----结束----->");
document.writeln("");
document.writeln("<!-----开始----->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-weight:700\' size=\'3\' face=\'微软雅黑\'>");
document.writeln("214期：<font color=\'#FF0000\'>【精准24码爆特】</font>开<font color=\'#FFFF00\'><span style=\'background-color: #000000\'>虎14</span></font></font></td></tr>");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<p style=line-height:200%>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("<span style=font-size:13pt;font-family:微软雅黑>");
document.writeln("");
document.writeln("（20.34.09.01.12.17.21.04.45.31.42.43）<br>");
document.writeln("（48.06.36.47.44.16.19.15.33.<span style=\'background-color: #FFFF00\'>14</span>.40.02）</span></font></p>");
document.writeln("</td></tr>");
document.writeln("<!-----结束----->");


document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://aaallleee.www29769a.com:888/#62102c12\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;font-size:17pt;color:#00f>进入雷锋论坛</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>29769b.com</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("  ");