document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62815a.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【稳赚六肖】</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://gfftggh.www57235c.com:8443/#62102\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57235</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("011-012期<font color=\'#FF0000\' style=\'font-size: 14pt\'>【狗兔牛猪龙猴】</font>(<span style=\'background-color: #000000\'><font color=\'#FFFFFF\'>？00</font></span>期√)  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");
document.writeln("  <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("010-011期<font color=\'#FF0000\' style=\'font-size: 14pt\'>【羊马<span style=\'background-color: #FFFF00\'>龙</span>鸡兔蛇】</font>(<span style=\'background-color: #000000\'><font color=\'#FFFFFF\'>010</font></span>期√)  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");
document.writeln("  <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("009-010期<font color=\'#FF0000\' style=\'font-size: 14pt\'>【牛虎兔<span style=\'background-color: #FFFF00\'>狗</span>龙猴】</font>(<span style=\'background-color: #000000\'><font color=\'#FFFFFF\'>009</font></span>期√)  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");
document.writeln("  <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("007-008期<font color=\'#FF0000\' style=\'font-size: 14pt\'>【<span style=\'background-color: #FFFF00\'>猴</span>龙鼠马虎兔】</font>(<span style=\'background-color: #000000\'><font color=\'#FFFFFF\'>008</font></span>期√)  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");






document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.manolotron.com:49/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>49图库<font color=\'#FF0000\'>49.com</font>图纸最全-最快</a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body> ");