document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>62103c.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『解苹果报』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 ><p align=\'center\'>");
document.writeln("		<b>");
document.writeln("		<font face=\'隶书\' size=\'5\'>");
document.writeln("		<a style=\'text-decoration: none\' target=\'_blank\' href=\'https://49157b.com/#/picture/416995\'>");
document.writeln("		<font color=\'#FF0000\'>点击查看苹果报</font></a></font><font size=\'4\' face=\'微软雅黑\' color=\'#FF0000\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start--");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			135期<font color=\'#FF0000\'>【关注62103a.com】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：18点来料，关注62103c.com</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：来料<br>");
document.writeln("			大小：来料<br>");
document.writeln("			特码：来料");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			251期<font color=\'#FF0000\'>【关注62103a.com】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：18点来料，关注62103c.com</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：来料<br>");
document.writeln("			大小：来料<br>");
document.writeln("			特码：来料");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");

document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			250期<font color=\'#FF0000\'>【今期特门一二七，湖中荷花出污泥】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：一二七解一鼠兔，二虎牛，七马鸡，湖中解水肖鼠猪</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：猪马<span style=\'background-color: #FFFF00\'>虎</span>牛鸡鼠兔<br>");
document.writeln("			大小：大数<br>");
document.writeln("			特码：08.44.12.36.05.41.15.27.18.30.25.37.22.46");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");

document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			249期<font color=\'#FF0000\'>【今期生肖六畜来，阳春三月好景色】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：六畜来解马狗牛鸡羊猪，阳春解春肖兔虎龙</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：龙虎马狗<span style=\'background-color: #FFFF00\'>猪</span>鸡牛<br>");
document.writeln("			大小：小数<br>");
document.writeln("			特码：12.24.02.14.10.22.06.18.05.17.07.19.03.15");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");

document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			247期<font color=\'#FF0000\'>【风调雨顺报吉昌，横行霸道不好人】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：风调雨顺解风肖龙虎兔，雨肖鼠猪牛，吉昌解吉肖兔龙蛇马羊鸡</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：蛇鼠猪<span style=\'background-color: #FFFF00\'>牛</span>龙虎鸡羊<br>");
document.writeln("			大小：大数<br>");
document.writeln("			特码：35.47.28.40.29.41.27.39.36.48.26.38.31.43.33.45");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");

document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			245期<font color=\'#FF0000\'>【特码猜出是美人，蓝红开出生肖东】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：是美人解女肖蛇羊鸡猪兔，生肖东解东方生肖兔虎龙</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：<span style=\'background-color: #FFFF00\'>兔</span>虎龙蛇鸡猪羊<br>");
document.writeln("			大小：小数<br>");
document.writeln("			特码：01.13.02.14.12.24.11.23.07.19.05.17.09.21");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			244期<font color=\'#FF0000\'>【二与三八取合数，春花秋月何时了】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：春花秋月解春少兔虎龙，秋肖狗鸡猴</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：狗鸡猴<span style=\'background-color: #FFFF00\'>兔</span>龙虎牛<br>");
document.writeln("			大小：<span style=\'background-color: #FFFF00\'>大数</span><br>");
document.writeln("			特码：30.42.31.43.32.44.<span style=\'background-color: #FFFF00\'>25</span>.37.36.48.26.38.27.39");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table></div> ");
document.writeln("");