
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>62102c.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『解苹果报』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 ><p align=\'center\'>");
document.writeln("		<b>");
document.writeln("		<font face=\'隶书\' size=\'5\'>");
document.writeln("		<a style=\'text-decoration: none\' target=\'_blank\' href=\'https://49157b.com/#/picture/416995\'>");
document.writeln("		<font color=\'#FF0000\'>点击查看苹果报</font></a></font><font size=\'4\' face=\'微软雅黑\' color=\'#FF0000\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start--");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			135期<font color=\'#FF0000\'>【关注62102a.com】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：18点来料，关注62102c.com</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：来料<br>");
document.writeln("			大小：来料<br>");
document.writeln("			特码：来料");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			185期<font color=\'#FF0000\'>【关注62102a.com】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：18点来料，关注62102c.com</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：来料<br>");
document.writeln("			大小：来料<br>");
document.writeln("			特码：来料");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");

document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			183期<font color=\'#FF0000\'>【四六合一先后出，三七相逢做大戏】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：先后出解后肖马羊猴鸡狗猪，做大戏解大肖牛马虎狗羊猪</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：马羊狗猪牛虎<span style=\'background-color: #FFFF00\'>鸡</span><br>");
document.writeln("			大小：<span style=\'background-color: #FFFF00\'>大数</span><br>");
document.writeln("			特码：34.46.33.45.30.42.29.41.27.39.26.38.31.<span style=\'background-color: #FFFF00\'>43</span>");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			182期<font color=\'#FF0000\'>【二四当前五六到，选出二三是吉数】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：二四当前解二四龙，五六到解五龙猪，六蛇狗，二三解23蛇</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：蛇狗龙猪兔牛<span style=\'background-color: #FFFF00\'>猴</span><br>");
document.writeln("			大小：大数<br>");
document.writeln("			特码：35.47.30.42.36.48.29.41.37.49.27.39.32.44");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");


document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			180期<font color=\'#FF0000\'>【本期五八有玄机，双数出来不稀奇】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：本期五八有玄机，五解猪龙，八解羊猴，双数出来解双龙虎马狗猴鼠</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：猪羊龙<span style=\'background-color: #FFFF00\'>马</span>狗猴鼠<br>");

document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");





document.writeln("</table></div> ");
