document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>62815a.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『解苹果报』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388ttz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 ><p align=\'center\'>");
document.writeln("		<b>");
document.writeln("		<font face=\'隶书\' size=\'5\'>");
document.writeln("		<a style=\'text-decoration: none\' target=\'_blank\' href=\'https://49157b.com/#/picture/416995\'>");
document.writeln("		<font color=\'#FF0000\'>点击查看苹果报</font></a></font><font size=\'4\' face=\'微软雅黑\' color=\'#FF0000\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start--");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			000期<font color=\'#FF0000\'>【更新中】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：更新中</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：更新中<br>");
document.writeln("			特码：更新中");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");

document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			362期<font color=\'#FF0000\'>【今期生肖定管家，不是牛来就是马】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：管家解家肖牛马鸡羊狗猪</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：牛马鸡羊狗猪兔<br>");
document.writeln("			特码：03.15.10.22.07.19.09.21.06.18.05.17.01.13");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<font style=\'font-size: 13pt\'><b>");
document.writeln("			361期<font color=\'#FF0000\'>【今期权威放帖士，红波定会中特码】</font>");
document.writeln("			<br><font color=\'#0000FF\'>解析：红波解红肖鸡兔马鼠</font><br>");
document.writeln("			");
document.writeln("			<br>七肖：<span style=\'background-color: #FFFF00\'>鸡</span>兔马鼠龙羊牛<br>");
document.writeln("			特码：31.43.25.37.34.46.28.40.36.48.33.45.27.39");
document.writeln("			</b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");




document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table></div> ");
document.writeln("");