
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>62102c.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『西游谜语』</font></b></table>");
document.writeln("   ");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start--");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>206期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("关注62102c.com<BR>");
document.writeln("关注62102c.com</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：正在来料，关注论坛</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：www.62102c.com<br>");
document.writeln("			四肖：www.62102c.com<br>");
document.writeln("			特码：www.62102c.com			</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>212期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("关注62102c.com<BR>");
document.writeln("关注62102c.com</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：正在来料，关注论坛</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：www.62102c.com<br>");
document.writeln("			四肖：www.62102c.com<br>");
document.writeln("			特码：www.62102c.com			</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");


document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>210期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("将士凯旋烹牛羊<BR>");
document.writeln("豪情万丈寄酒肠</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：将士凯旋解吉肖鸡羊兔蛇龙马，明肖牛羊</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：牛羊马龙兔蛇<span style=\'background-color: #FFFF00\'>鸡</span><br>");
document.writeln("			四肖：牛羊马龙<br>");
document.writeln("			特码：15.39.09.21.22.34.12.36.25.37.23.47.31.43</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>208期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("咄咄怪事羊骑马<BR>");
document.writeln("一帆风顺好前程</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：明肖羊马，好前程解前肖鼠牛虎兔龙蛇</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：羊马<span style=\'background-color: #FFFF00\'>鼠</span>牛兔龙蛇<br>");
document.writeln("			四肖：羊马<span style=\'background-color: #FFFF00\'>鼠</span>牛<br>");
document.writeln("			特码：09.21.10.34.16.40.15.39.25.37.12.48.23.47</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>207期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("四海为家走天涯<BR>");
document.writeln("孤单一人孤到老</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：四海为家解家肖马牛羊鸡猪狗，走天涯解天肖兔马猴猪牛龙</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：龙猴牛<span style=\'background-color: #FFFF00\'>兔</span>猪鸡狗<br>");
document.writeln("			四肖：龙猴牛<span style=\'background-color: #FFFF00\'>兔</span><br>");
document.writeln("			特码：12.36.08.20.15.39.13.<span style=\'background-color: #FFFF00\'>49</span>.05.41.31.43.18.30</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");

document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>205期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("西天取经前西行<BR>");
document.writeln("红衣野裤怪兽来</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：西天取经解取肖龙虎马猴猪，怪兽来解兽肖蛇兔龙猴鼠虎</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：马<span style=\'background-color: #FFFF00\'>蛇</span>兔龙猴猪鼠虎<br>");
document.writeln("			四肖：马<span style=\'background-color: #FFFF00\'>蛇</span>兔龙<br>");
document.writeln("			特码：10.22.23.47.13.25.12.48.32.44.17.41.16.40.14.38</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>204期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("家中喜事红灯挂<BR>");
document.writeln("夜半三更炮火响</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：家中喜事解家肖牛羊马鸡猪狗，红灯解红肖鼠马鸡兔，夜半解夜肖鼠牛虎鸡狗猪</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：鼠马鸡猪<span style=\'background-color: #FFFF00\'>牛</span>羊狗<br>");
document.writeln("			四肖：鼠马鸡猪<br>");
document.writeln("			特码：04.28.22.34.31.43.05.41.15.39.21.33.0642</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>203期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("四季分明五谷丰<BR>");
document.writeln("风调雨顺拜天神</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：风调雨顺解风肖兔虎龙，雨肖鼠猪牛，天神解天肖兔马猴猪牛龙</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：猪<span style=\'background-color: #FFFF00\'>兔</span>龙虎马鼠猴<br>");
document.writeln("			四肖：猪<span style=\'background-color: #FFFF00\'>兔</span>龙虎<br>");
document.writeln("			特码：17.41.13.49.24.48.02.14.10.22.28.40.32.44</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>201期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("三千歌舞往家处<BR>");
document.writeln("美女如云画中画</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：往家处解家肖马牛鸡羊猪狗，美女解女肖蛇羊鸡猪兔</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：蛇兔马狗<span style=\'background-color: #FFFF00\'>牛</span>鸡猪<br>");
document.writeln("			四肖：蛇兔马狗<br>");
document.writeln("			特码：11.23.13.25.10.22.30.42.15.39.07.19.17.41</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>200期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("天狗食月自古传<BR>");
document.writeln("龙生九子美名谈</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：天狗解天肖兔马猴猪牛龙，美名解美肖兔龙鸡羊蛇马</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：蛇马兔龙鸡羊<span style=\'background-color: #FFFF00\'>猴</span><br>");
document.writeln("			四肖：蛇马兔龙<br>");
document.writeln("			特码：11.23.10.34.13.24.48.31.21.20.<span style=\'background-color: #FFFF00\'>44</span></font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");






document.writeln("</table>");
document.writeln("</tbody>");
