document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>62103c.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『西游谜语』</font></b></table>");
document.writeln("   ");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start--");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>206期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("关注62103c.com<BR>");
document.writeln("关注62103c.com</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：正在来料，关注论坛</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：www.62103c.com<br>");
document.writeln("			四肖：www.62103c.com<br>");
document.writeln("			特码：www.62103c.com			</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>236期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("关注62103c.com<BR>");
document.writeln("关注62103c.com</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：正在来料，关注论坛</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：www.62103c.com<br>");
document.writeln("			四肖：www.62103c.com<br>");
document.writeln("			特码：www.62103c.com			</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");

document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>235期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("白马太子取西经<BR>");
document.writeln("悟空四海闹龙王</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：白马解马肖，太子解蛇，取西经解取经肖马猴虎猪龙，四海解水肖鼠猪</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：蛇马<span style=\'background-color: #FFFF00\'>鼠</span>猪龙虎猴<br>");
document.writeln("			四肖：蛇马<span style=\'background-color: #FFFF00\'>鼠</span>猪<br>");
document.writeln("			特码：11.47.22.46.<span style=\'background-color: #FFFF00\'>04</span>.40.17.41.24.48.02.14.20.44</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");


document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>233期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("三头六臂似猛兽<BR>");
document.writeln("胆小如鼠实则慌</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：似猛兽解兽肖蛇兔猴鼠龙虎，胆小解胆小肖鼠兔龙蛇羊鸡</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：蛇<span style=\'background-color: #FFFF00\'>龙</span>虎兔猴鼠鸡<br>");
document.writeln("			四肖：蛇<span style=\'background-color: #FFFF00\'>龙</span>虎兔<br>");
document.writeln("			特码：11.35.24.48.02.38.13.49.20.44.28.40.31.43</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>231期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("天气渐冷入冬眠<BR>");
document.writeln("狗在门外守护羊</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：天气渐冷解冬肖鼠猪牛，明肖狗羊</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：狗鼠猪牛<span style=\'background-color: #FFFF00\'>羊</span>虎龙<br>");
document.writeln("			四肖：狗鼠猪牛<br>");
document.writeln("			特码：18.30.04.40.17.29.15.39.21.<span style=\'background-color: #FFFF00\'>45</span>.02.38.36.48</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<b>");
document.writeln("			<font style=\'font-size: 13pt\'>230期西游谜语<br><font color=\'#FF0000\'>");
document.writeln("鼠虎牛马对无佳人<BR>");
document.writeln("一路风尘而不染</font>");
document.writeln("			<br></font><font face=\'隶书\'>解析：明肖鼠虎牛马，一路风尘解风肖龙虎兔</font><font style=\'font-size: 13pt\'><br>");
document.writeln("			");
document.writeln("			<br><font color=\'#0000FF\'>七肖：<span style=\'background-color: #FFFF00\'>龙</span>虎兔鼠牛马鸡<br>");
document.writeln("			四肖：<span style=\'background-color: #FFFF00\'>龙</span>虎兔鼠<br>");
document.writeln("			特码：12.<span style=\'background-color: #FFFF00\'>36</span>.02.38.13.25.28.40.15.39.22.34.07.19</font></b></td>");
document.writeln("		</tr>	");
document.writeln("");
document.writeln("<!--头部start-->");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</tbody>");
document.writeln("");