document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'58\'><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=52><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 16pt\'><font color=\'#FFFF00\'>只赚三毛</font><font color=\'#FFFFFF\'>『七肖中特』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>260期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">猴狗马虎龙猪鼠</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">08.20.18.30.10.22.02.14.12.36.05.41.28.40</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>259期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">蛇龙<font color=\'#FF0000\' style=\"font-size: 14pt\">猪虎马鸡牛羊</font><font color=\'#FF0000\' size=\"6\"><span style=\"background-color: #FFFF00\">猪</span></font>狗鼠牛羊</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">11.23.12.48.05.41.30.42.04.40.15.39.21.45</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");

document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>257期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">猪虎马鸡牛羊</font><font color=\'#FF0000\' size=\"6\"><span style=\"background-color: #FFFF00\">龙</span></font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">05.41.14.38.22.46.19.31.03.15.21.45.24</font><font color=\'#FF0000\' size=\"6\"><span style=\"background-color: #FFFF00\">.36</span></font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>255期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">鸡猪马羊</font><font color=\'#FF0000\' size=\"6\"><span style=\"background-color: #FFFF00\">兔</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">牛鼠</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">07.43.05.41.22.34.21.33.15.39.25.49.16.40</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>254期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">狗鼠</font><font color=\'#FF0000\' size=\"6\"><span style=\"background-color: #FFFF00\">兔</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">蛇羊鸡龙</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">06.42.16.28.25.37.23.47.09.45.31.43.24.36</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>253期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">牛猴龙</font><font color=\'#FF0000\' size=\"6\"><span style=\"background-color: #FFFF00\">虎</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">鸡马兔</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">15.39.08.20.24.36.02.38.19.31.22.46.13.25</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388tz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");