document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'58\'><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=52><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 16pt\'><font color=\'#FFFF00\'>只赚三毛</font><font color=\'#FFFFFF\'>『七肖中特』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>290期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">鸡龙蛇牛鼠兔虎</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">07.43.12.48.11.23.15.39.04.40.25.37.14.38</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>289期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">猪鸡</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">龙虎猴蛇</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">05.41.31.43.</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">21</span></font><font color=\'#FF0000\' style=\"font-size: 13pt\">.33.12.48.02.38.20.44.23.47</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>287期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">马鼠龙</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">兔猴猪</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">10.34.04.40.12.48.15.</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">39</span></font><font color=\'#FF0000\' style=\"font-size: 13pt\">.25.37.08.20.17.41</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>285期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">羊狗</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">猪</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">虎鼠龙猴</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">21.45.18.30.05.</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">41</span></font><font color=\'#FF0000\' style=\"font-size: 13pt\">.02.38.16.40.12.36.20.44</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>284期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">鼠马虎羊</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">龙蛇</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">04.40.22.34.02.38.21.45.</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">06</span></font><font color=\'#FF0000\' style=\"font-size: 13pt\">.42.12.36.23.47</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>283期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">蛇猪</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">兔狗猴牛</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">11.47.29.41.09.21.13.25.30.42.20.44.03.15</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388tz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");