document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'58\'><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=52><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 16pt\'><font color=\'#FFFF00\'>只赚三毛</font><font color=\'#FFFFFF\'>『七肖中特』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>220期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">鼠鸡狗牛蛇羊马</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("							<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\' height=\"35\">");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">杀(7.)码:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">04.31.18.39.23.21.10</font></b></td>");
document.writeln("			</tr>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">28.40.07.19.30.42.15.27.11.47.09.33.22.46</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>219期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">兔猪鸡牛猴鼠</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">马</span></font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("							<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\' height=\"35\">");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">杀(7.)码:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">01.41.31.03.20.28.22</font></b></td>");
document.writeln("			</tr>");
document.writeln("	");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>218期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">羊蛇</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">鸡</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">牛虎兔龙</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("							<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\' height=\"35\">");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">杀(7.)码:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">09.11.31.03.38.25.12</font></b></td>");
document.writeln("			</tr>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">21.45.23.35.07.</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">19</span></font><font color=\'#FF0000\' style=\"font-size: 13pt\">.15.27.02.26.37.49.36.48</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>217期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">鼠猴</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">马牛兔龙</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("							<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\' height=\"35\">");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">杀(7.)码:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">04.32.06.22.27.13.36</font></b></td>");
document.writeln("			</tr>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\'>稳赚特码（14码）<BR></font>");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 13pt\">16.40.20.44</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">.18</span></font><font color=\'#FF0000\' style=\"font-size: 13pt\">.42.10.34.03.39.25.37.24.48</font></b></td>");
document.writeln("			</tr>");
document.writeln("							");
document.writeln("						");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始 -->");
document.writeln("        <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("			<tr>");
document.writeln("				<td style=\'text-align:center; background: #FFFF99;\' width=\'100%\'>");
document.writeln("				<b><font size=\'5\' color=\'#6600CC\'>216期</font></b>七肖中特：62103a.com长期跟踪</td>");
document.writeln("			</tr>");
document.writeln("						<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\'>");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">(7.)肖特:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">鼠猴兔</font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><font color=\'#FF0000\' style=\"font-size: 14pt\">虎猪蛇</font></b></td>");
document.writeln("			</tr>");
document.writeln("			");
document.writeln("							<tr>");
document.writeln("				<td style=\'text-align: center\' bgcolor=\'#F4F4F4\' height=\"35\">");
document.writeln("				<b>");
document.writeln("				<font color=\'#000080\' style=\"font-size: 14pt\">杀(7.)码:</font><font color=\'#FF0000\' style=\"font-size: 14pt\">04.20.37.24.02.41.23</font></b></td>");
document.writeln("			</tr>");
document.writeln("								");
document.writeln("									");
document.writeln("</table> ");
document.writeln("			");
document.writeln("<!--结束 -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388tz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");