document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong333 { color: #171817; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #000;}");
document.writeln(".bizhong333-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #0a2cab;}");
document.writeln(".bizhong333-box { display: flex;}");
document.writeln(".bizhong333-box ul {}");
document.writeln(".bizhong333-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong333-box .bizhong333-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong333-box .bizhong333-r { width: 100%;}");
document.writeln(".bizhong333-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong333 { font-size: 16px;}");
document.writeln(".bizhong333-tit { font-size: 18px;}");
document.writeln(".bizhong333-box { display: block;}");
document.writeln(".bizhong333-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong333-box .bizhong333-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong333-box .bizhong333-r { width: 100%;}");
document.writeln(".bizhong333-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln(" 	            <li><font size=\"2\">162期必中18码：</font><font color=\'#FF0000\' size=\'2\'>01.37.49.11.23.47.05.17.29.04.16.40.02.14.26.08.20.32</font></li>");
document.writeln("            	<li>162期必中⑨码：<font color=\'#FF0000\' style=\"font-size: 14pt\">01.37.49.11.23.47.05.17.29</font></li>");
document.writeln("            	<li>162期必中①肖：<font color=\'#FF0000\' size=\'5\'>（龙-01.37.49）</font></li>");
document.writeln("            	<li>162期必中③肖：<font color=\'#FF0000\' size=\'4\'>龙马鼠</font></li>");
document.writeln("            	<li>162期必中⑥肖：<font color=\'#FF0000\' size=\'4\'>龙马鼠牛兔鸡</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong333\'>");
document.writeln("	<div class=\'bizhong333-tit\'>");
document.writeln("		<font size=\"5\">（余生有钱）推荐一肖三码</font></div>");
document.writeln("	<div class=\'bizhong333-box\'>");
document.writeln("    	<div class=\'bizhong333-l\' style=\"background-color: #FFFFFF\">");
document.writeln("        	<ul>");
document.writeln("");
document.writeln("            	<li>161期必中⑨码：<font color=\'#FF0000\' style=\"font-size: 14pt\">05.29.41.01.37.49.11.23.47</font></li>");
document.writeln("            	<li>161期必中①肖：<font color=\'#FF0000\' size=\'5\'>（鼠-05.29.41）</font></li>");
document.writeln("            	<li>161期必中③肖：<font color=\'#FF0000\' size=\'4\'>鼠龙<span style=\'background-color: #FFFF00\'>马</span></font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中end-->");
document.writeln("");