document.writeln("");
document.writeln("");
document.writeln("<a href=\'  https://j.100tzz.com:100\'> <img src=\'           https://d31q194n7fpdes.cloudfront.net/mygai/tp/100/100.gif\' style=\'width: 100%;\' /></a>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".zzhl49-tit {}");
document.writeln(".zzhl49-tit img { width: 100%; height: auto; vertical-align: top;}");
document.writeln("#tabzzhl49 {}");
document.writeln("#tabzzhl49 a {  text-decoration: none;}");
document.writeln("#tabzzhl49 .zzhl49menu { width: 100%; padding: 5px 0; text-align: center; font-weight: bold; font-size: 18px; line-height:40px;}");
document.writeln("#tabzzhl49 .zzhl49menu ul { display: flex; justify-content: space-between;}");
document.writeln("#tabzzhl49 .zzhl49menu li { width: calc(33.33% - 5px); box-sizing: border-box; background: #eee; cursor: pointer;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover { color: #fff;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover span { display: block;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49am { background: #090;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49xg { background: #f00;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49tw { background: #00f;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49xc { background: #FF00FF;}");
document.writeln("#tabzzhl49 .zzhl49box {}");
document.writeln(".zzhl49-list { background: white;font-size: 16px;}");
document.writeln("");
document.writeln(".zzhl49-list ul { display: flex; flex-direction: row; flex-wrap: wrap; justify-content: space-between;}");
document.writeln(".zzhl49-list ul li { width: calc(50% - 5px); border-bottom: solid 1px #ddd; box-sizing: border-box;}");
document.writeln(".zzhl49-list ul li a { display: block; padding: 8px 5px; white-space: nowrap; overflow: hidden;color: black;}");
document.writeln("@media screen and (max-width:800px){");
document.writeln("#tabzzhl49 .zzhl49menu { font-size: 16px; line-height:36px;}");
document.writeln("#tabzzhl49 .zzhl49menu li { width: calc(33.33% - 3px);}");
document.writeln(".zzhl49-list { font-size: 15px;}");
document.writeln(".zzhl49-list ul li { width: 100%;}");
document.writeln(".zzhl49-list ul li a { padding: 8px 5px;}");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln(".zzhl49-list a {");
document.writeln("    font-size: large;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'zzhl49-tit\'><img src=\'https://huidfjfgg.a626102.com:888/images/djhl.jpg\' src=\'\'></div>");
document.writeln("<div id=\"tabzzhl49\">");
document.writeln("<div class=\'zzhl49menu\'>");
document.writeln("    <ul>");
document.writeln("       <li id=\"tabzzhl491\" onClick=\'setTab62(\"tabzzhl49\",1,4)\' class=\'hover\'><span class=\'zzhl49am\'>澳彩精华区</span></li>");
document.writeln("       <li id=\"tabzzhl492\" onClick=\'setTab62(\"tabzzhl49\",2,4)\'><span class=\'zzhl49xg\'>香港精华区</span></li>");
document.writeln("	   <li id=\"tabzzhl493\" onClick=\'setTab62(\"tabzzhl49\",3,4)\'><span class=\'zzhl49tw\'>台湾精华区</span></li>");
document.writeln("	   <li id=\"tabzzhl494\" onClick=\'setTab62(\"tabzzhl49\",4,4)\'><span class=\'zzhl49xc\'>新彩精华区</span></li>");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<div class=\'zzhl49box\'> ");
document.writeln("	<div id=\'con_tabzzhl49_1\'>");
document.writeln("<!--澳门开始-->");
document.writeln("<div class=\'zzhl49-list\'>");
document.writeln("	<ul>");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <!--开始--> ");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'  https://tgtg.pdyde123778.com:2025/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【六合宝典】<font color=\'#FF0000\'>（三期必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("        <!--结束-->  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'      https://tgam.822123aa.com/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【特码大王】<font color=\'#FF0000\'>（二码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734279&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【香山论坛】<font color=\'#FF0000\'>（六加一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734280&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【苍穹剑泣】<font color=\'#FF0000\'>（单双两肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734288&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【排行老六】<font color=\'#FF0000\'>（合数大小）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734299&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【都是逆风】<font color=\'#FF0000\'>（单双二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734307&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【残雪世家】<font color=\'#FF0000\'>（八肖8码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734302&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【帕加尼@】<font color=\'#FF0000\'>（双波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734207&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【干一杯烈】<font color=\'#FF0000\'>（复试三连）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734210&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【物都是你】<font color=\'#FF0000\'>（单双二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734467&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【释看群枭】<font color=\'#FF0000\'>（三行中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734456&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【竹报彡多】<font color=\'#FF0000\'>（④尾八码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'     https://tgtg.pdyde123778.com:2025/#qwt\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【六合宝典】<font color=\'#FF0000\'>（无错单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34734209&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【天朗气清】<font color=\'#FF0000\'>（绝杀五码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34733624&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【宁折不弯】<font color=\'#FF0000\'>（绝杀十码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34733662&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【簪缨世族】<font color=\'#FF0000\'>（绝杀一头）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34733657&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【不吐不快】<font color=\'#FF0000\'>（吃菜草肉）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");



document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://baibai.www68617c.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【澳老黄历】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（三期必开）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://dfdrfr.www56926b.com:8443/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【香山论坛】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34733679&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【英雄战魂】<font color=\'#FF0000\'>（平三中二）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34734215&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【妄自尊大】<font color=\'#FF0000\'>（三头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34734247&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【精力充沛】<font color=\'#FF0000\'>（精力充沛）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://qazsd.www27619b.com:888/#_49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【飞龙在天】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'       https://qt4waw.www73875c.com:8443/#49ttt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>   083期【澳金元宝】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（单双100%）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34733584&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【方寸不乱】<font color=\'#FF0000\'>（精选六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34733476&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【成仁取义】<font color=\'#FF0000\'>（天地中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34733447&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【热气腾腾】<font color=\'#FF0000\'>（复式平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");



document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://xzcsaasc.www68729a.com:888/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【澳利澳@】<font color=\'#FF0000\'>（18码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://dssdfsd.www72385c.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【王中王@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'       https://gfreqasca.www97185c.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【大三八网】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");


document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34734290&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【无出其右】<font color=\'#FF0000\'>（36码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34734301&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【悲愤填膺】<font color=\'#FF0000\'>（稳杀四肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34734278&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【鳞次栉比】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\' https://edcfggvb.www52619c.com:888/#49qwt  \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【御龙英豪】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'     https://gsfsdfdfsg.www73531c.com:8443/#49ttt  \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【澳老钱庄】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（单单双双）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://j.jzxke120.com:888/#49qwt \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【49聊天室】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（一码中特）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733882&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【天上人间】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733793&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【大老爺@】<font color=\'#FF0000\'>（必中大小）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733728&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【酒一壶@】<font color=\'#FF0000\'>（有买必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734042&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【飘零的心】<font color=\'#FF0000\'>（特码３行）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733471&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【玛丽莲梦】<font color=\'#FF0000\'>（必中波色）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733405&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【冷漠哥哥】<font color=\'#FF0000\'>（五肖五码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733818&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【柔情杀手】<font color=\'#FF0000\'>（绝杀一波）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733671&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【六合神算】<font color=\'#FF0000\'>（传奇三肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733408&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【墨羽尘曦】<font color=\'#FF0000\'>（绝杀一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733601&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【谁是谁的】<font color=\'#FF0000\'>（绝杀两肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733394&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【浅月流歌】<font color=\'#FF0000\'>（一肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733569&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【炽羽金尊】<font color=\'#FF0000\'>（单双二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733719&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【乱舞春秋】<font color=\'#FF0000\'>（必中六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733775&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【榜一大哥】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733680&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【南巷清风】<font color=\'#FF0000\'>（原创4肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733893&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【如意特码】<font color=\'#FF0000\'>（必中六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733909&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【天盛长歌】<font color=\'#FF0000\'>（平特①肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733461&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【九次拒绝】<font color=\'#FF0000\'>（成语平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733480&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【至尊天下】<font color=\'#FF0000\'>（灭庄24码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733516&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【好运一点】<font color=\'#FF0000\'>（一肖一码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733981&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【东方神起】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733651&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【奥巴码@】<font color=\'#FF0000\'>（四字平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733800&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【赌神通天】<font color=\'#FF0000\'>（精选13码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733972&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【剑九皇@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734046&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【欢乐男孩】<font color=\'#FF0000\'>（稳杀一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734049&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【冰凝泪烛】<font color=\'#FF0000\'>（平特一尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734051&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【乖囧貓@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734055&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【疏星淡月】<font color=\'#FF0000\'>（一波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734057&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【蔂夢砕@】<font color=\'#FF0000\'>（个半单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734079&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【独单心事】<font color=\'#FF0000\'>（20码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734083&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【嗟梦心海】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734087&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【甜宠软妹】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734096&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【枝上眠@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734117&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【呆傻萌@】<font color=\'#FF0000\'>（10码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734119&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【小喵酱@】<font color=\'#FF0000\'>（1波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734123&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【香蕉不叫】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734124&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【残雪冰心】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734126&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【云倾城@】<font color=\'#FF0000\'>（家野中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734129&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【顾南一@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734156&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【粪小豆@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734167&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【旅清风@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734171&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【年華已逝】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734182&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【那缕阳光】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734202&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【北葵向南】<font color=\'#FF0000\'>（三肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733852&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【洛阳烟雨】<font color=\'#FF0000\'>（八肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733858&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【焦点人物】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733861&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【白展堂@】<font color=\'#FF0000\'>（五码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733864&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【夜阑听雪】<font color=\'#FF0000\'>（②头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733879&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【秋山雪月】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733885&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【小情调@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733890&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【地狱审核】<font color=\'#FF0000\'>（八码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733894&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【酷出界限】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733902&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【爱你无期】<font color=\'#FF0000\'>（三个半波）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733908&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【晚来天欲】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733936&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【兲使笑@】<font color=\'#FF0000\'>（七肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733950&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【淡淡稻花】<font color=\'#FF0000\'>（大小中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733982&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【浪场撩妹】<font color=\'#FF0000\'>（7码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734004&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【诗人诗意】<font color=\'#FF0000\'>（家畜野兽）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733911&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【枉少年@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733517&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【花若兮@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734113&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【酒三生@】<font color=\'#FF0000\'>（6肖必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733964&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【舞城倾@】<font color=\'#FF0000\'>（五肖必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733554&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【小腰精@】<font color=\'#FF0000\'>（五肖必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733817&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【醉千杯@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34734297&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【曲未终@】<font color=\'#FF0000\'>（无敌四肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733572&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【给我滚@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733855&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【猫小柒@】<font color=\'#FF0000\'>（六肖必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733417&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【时不我待】<font color=\'#FF0000\'>（禁二合数）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733441&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【绝无神@】<font color=\'#FF0000\'>（绝杀二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733400&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【我心依旧】<font color=\'#FF0000\'>（绝杀半波）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733514&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【银河系@】<font color=\'#FF0000\'>（9肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733506&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【赢飞纷纷】<font color=\'#FF0000\'>（四行中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733492&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【美丽心雨】<font color=\'#FF0000\'>（双波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733412&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【我的任性】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733509&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【梅菜没肉】<font color=\'#FF0000\'>（必中6肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733466&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【万般皆是】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733522&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【烟雨小镇】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733518&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【想你的液】<font color=\'#FF0000\'>（平特一尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733396&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【花泽烈@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733551&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【想个名字】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733483&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【究极爆马】<font color=\'#FF0000\'>（5肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733462&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【铁山靠@】<font color=\'#FF0000\'>（网红平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733454&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【浴皇大帝】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733449&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【夜袭女儿】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733500&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【中奖期望】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733391&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【村主鈓@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733395&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【温山软水】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733404&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【天如海@】<font color=\'#FF0000\'>（大小中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733411&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【心事痕迹】<font color=\'#FF0000\'>（⑸尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733416&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【风浒涟漪】<font color=\'#FF0000\'>（四季发财）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733443&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【之后醉了】<font color=\'#FF0000\'>（买啥都中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733452&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【风灵的角】<font color=\'#FF0000\'>（前后中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733464&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【孤独比酒】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733470&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【借酒劲吻】<font color=\'#FF0000\'>（天地中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733478&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【山高云阔】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733488&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【转眼花落】<font color=\'#FF0000\'>（尾数大小）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733503&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【朝雾初@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733511&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【冰雪之触】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733515&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【专属那妮】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733521&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【诗雨伊意】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733553&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【和尚爱尼】<font color=\'#FF0000\'>（前后中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733562&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【爱不释手】<font color=\'#FF0000\'>（左右中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733566&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【来碗泪流】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733573&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【孤者傲凡】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733582&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【梦好沉@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733587&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【海未深@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733592&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【妹子跟我】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733602&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【薄情的红】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733608&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【朝槿温雾】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733614&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【血色微光】<font color=\'#FF0000\'>（中特二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733620&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【一向等待】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733625&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【树红树绿】<font color=\'#FF0000\'>（三肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733630&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【朦胧时间】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733647&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【无声拥抱】<font color=\'#FF0000\'>（三字平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733654&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【九点钟的】<font color=\'#FF0000\'>（合数大小）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733666&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【长虹饮涧】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733683&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【感动是毒】<font color=\'#FF0000\'>（一波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733686&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【夏水流萤】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733710&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>083期【初心不负】<font color=\'#FF0000\'>（二头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'     https://thhytht.www72517c.com:8443/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 083期【蓝月亮网】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（四肖中特）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<!--澳门结束-->");
document.writeln("	</div>");
document.writeln("	<div id=\'con_tabzzhl49_2\' style=\'display:none\'>");
document.writeln("<!--香港开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://tgxg.822123aa.com/#49qwt\'>033期【特码大王】<font color=\'#FF0000\'>（二码中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723700&type=3\'>033期【墨染傾城】<font color=\'#FF0000\'>（四头中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723768&type=3\'>033期【通天论坛】<font color=\'#FF0000\'>（一码中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723770&type=3\'>033期【绝世骚神】<font color=\'#FF0000\'>（三期必开）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723776&type=3\'>033期【通天一码】<font color=\'#FF0000\'>（四肖一码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723691&type=3\'>033期【要的是范】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\' https://baibai.www68617c.com:8443/xg/xgindex.html#49qwt\'>033期【港老黄历】<font color=\'#FF0000\'>（一肖一码）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\' https://dffrfdfd.www82712c.com:888/#49qwt\'>033期【通天特码】<font color=\'#FF0000\'>（三肖中特）</font>已公开</a></b></li>");
document.writeln("");


document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723676&type=3\'>033期【诸葛村夫】<font color=\'#FF0000\'>（中特六码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723606&type=3\'>033期【天盛长歌】<font color=\'#FF0000\'>（平特①肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\' https://asddsa.www71873b.com:888/xg/index.html#49qwt\'>033期【百家网港】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723668&type=3\'>033期【浅月流歌】<font color=\'#FF0000\'>（一肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723623&type=3\'>033期【墨羽尘曦】<font color=\'#FF0000\'>（绝杀一肖）</font>已公开</a></b></li>");
document.writeln("");


document.writeln("		<li><b><a target=\'_blank\' href=\'https://wsxxsw.www73125b.com:888/xg/index.html#49qwt\'>033期【港澳宝典】<font color=\'#FF0000\'>（单双100%）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723587&type=3\'>033期【东方神起】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723706&type=3\'>033期【春天菊花】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723683&type=3\'>033期【魍魉影魅】<font color=\'#FF0000\'>（追杀10码）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723044&type=3\'>033期【我爱她他】<font color=\'#FF0000\'>（平特二肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723054&type=3\'>033期【芊茗静语】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723065&type=3\'>033期【紫嫣轻娆】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723089&type=3\'>033期【病态美@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723104&type=3\'>033期【怯霜静@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723114&type=3\'>033期【蓝海噬心】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723124&type=3\'>033期【夕陽風采】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723137&type=3\'>033期【恋飘雪@】<font color=\'#FF0000\'>（七肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723148&type=3\'>033期【馋奶兔@】<font color=\'#FF0000\'>（二头中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723176&type=3\'>033期【雪舞兮@】<font color=\'#FF0000\'>（两头中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723167&type=3\'>033期【凉辰梦瑾】<font color=\'#FF0000\'>（单双中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723181&type=3\'>033期【紫薇児@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723186&type=3\'>033期【似梵音@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723212&type=3\'>033期【柚萌裙摆】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723219&type=3\'>033期【冷沐雪@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723229&type=3\'>033期【发拂霜@】<font color=\'#FF0000\'>（个半单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723240&type=3\'>033期【诗绪里@】<font color=\'#FF0000\'>（大小中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723247&type=3\'>033期【风清淡雅】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723254&type=3\'>033期【雨飞飞@】<font color=\'#FF0000\'>（2个半波）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723262&type=3\'>033期【一人一梦】<font color=\'#FF0000\'>（一波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723293&type=3\'>033期【公紸吥乖】<font color=\'#FF0000\'>（四肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723272&type=3\'>033期【浠旪落埖】<font color=\'#FF0000\'>（合数中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723278&type=3\'>033期【佑铒盯@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723712&type=3\'>033期【博多野@】<font color=\'#FF0000\'>（东南西北）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723720&type=3\'>033期【奶茶限供】<font color=\'#FF0000\'>（风雷云雨）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723221&type=3\'>033期【狂刄星空】<font color=\'#FF0000\'>（琴棋书画）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723233&type=3\'>033期【与日暮同】<font color=\'#FF0000\'>（书画棋琴）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723245&type=3\'>033期【奔跑的灵】<font color=\'#FF0000\'>（3个单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723257&type=3\'>033期【紫色妖媚】<font color=\'#FF0000\'>（力杀五码）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723151&type=3\'>033期【不凡的路】<font color=\'#FF0000\'>（八尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723106&type=3\'>033期【都市逆行】<font color=\'#FF0000\'>（精准９肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723223&type=3\'>033期【续命航@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723260&type=3\'>033期【男绅士@】<font color=\'#FF0000\'>（必中大小）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723051&type=3\'>033期【男人站直】<font color=\'#FF0000\'>（精准八肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723122&type=3\'>033期【静花怡月】<font color=\'#FF0000\'>（伍肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723322&type=3\'>033期【人无少年】<font color=\'#FF0000\'>（吃肉菜草）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34723172&type=3\'>033期【浅唱留雨】<font color=\'#FF0000\'>（发财五肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723860&type=3\'>033期【過河的卒】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723878&type=3\'>033期【南港清风】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723966&type=3\'>033期【天朗气清】<font color=\'#FF0000\'>（绝杀五码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723950&type=3\'>033期【簪缨世族】<font color=\'#FF0000\'>（绝杀一头）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723118&type=3\'>033期【狂飙资本】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723937&type=3\'>033期【不吐不快】<font color=\'#FF0000\'>（吃菜草肉）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723901&type=3\'>033期【项羽雄威】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=34723925&type=3\'>033期【雪兆丰年】<font color=\'#FF0000\'>（四肖八码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<!--香港结束-->");
document.writeln("    </div>");
document.writeln("    <div id=\'con_tabzzhl49_3\' style=\'display:none\'>");
document.writeln("<!--台湾开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733163&type=3\'>083期【二氧化甜】<font color=\'#0000ff\'>（精准杀五）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733166&type=3\'>083期【海滨夏夜】<font color=\'#0000ff\'>（大小爆特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733170&type=3\'>083期【林品如你】<font color=\'#0000ff\'>（单双２码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733206&type=3\'>083期【拉风的小】<font color=\'#0000ff\'>（春夏秋冬）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733208&type=3\'>083期【粉色樱花】<font color=\'#0000ff\'>（八肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733211&type=3\'>083期【歌散酒初】<font color=\'#0000ff\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733212&type=3\'>083期【风过留痕】<font color=\'#0000ff\'>（稳猛六肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733214&type=3\'>083期【好人一生】<font color=\'#0000ff\'>（三半单双）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34732973&type=3\'>083期【你有弟我】<font color=\'#0000ff\'>（平特三肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34732981&type=3\'>083期【风吹花成】<font color=\'#0000ff\'>（单双中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733024&type=3\'>083期【半厦微澜】<font color=\'#0000ff\'>（七尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34732985&type=3\'>083期【盛开的彼】<font color=\'#0000ff\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733029&type=3\'>083期【猥琐欲为】<font color=\'#0000ff\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34732998&type=3\'>083期【野鸡贩大】<font color=\'#0000ff\'>（三行中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34733021&type=3\'>083期【农村混血】<font color=\'#0000ff\'>（24码中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34732989&type=3\'>083期【折花载酒】<font color=\'#0000ff\'>（⑥肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34732965&type=3\'>083期【独望风雨】<font color=\'#0000ff\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("    <div id=\'con_tabzzhl49_4\' style=\'display:none\'>");
document.writeln("<!--新彩开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722353&type=3\'>3959期【扑倒李太】<font color=\'#FF00FF\'>（准杀五码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722307&type=3\'>3959期【悲伤广@】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722362&type=3\'>3959期【南风几经】<font color=\'#FF00FF\'>（七肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722366&type=3\'>3959期【七里香火】<font color=\'#FF00FF\'>（2波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722372&type=3\'>3959期【拱白菜的】<font color=\'#FF00FF\'>（五段中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722311&type=3\'>3959期【沸羊羊@】<font color=\'#FF00FF\'>（琴棋书画）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722315&type=3\'>3959期【水中鬼@】<font color=\'#FF00FF\'>（左右两肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722319&type=3\'>3959期【盖世淫胸】<font color=\'#FF00FF\'>（三半单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722374&type=3\'>3959期【航行远@】<font color=\'#FF00FF\'>（四头中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722377&type=3\'>3959期【中央大帝】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722382&type=3\'>3959期【卑微的苟】<font color=\'#FF00FF\'>（６肖６肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722321&type=3\'>3959期【降龙十九】<font color=\'#FF00FF\'>（精选七肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722386&type=3\'>3959期【逆行呆子】<font color=\'#FF00FF\'>（八肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722405&type=3\'>3959期【七师弟@】<font color=\'#FF00FF\'>（草肉菜肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722408&type=3\'>3959期【月亮邮递】<font color=\'#FF00FF\'>（大小中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722325&type=3\'>3959期【喜欢吃面】<font color=\'#FF00FF\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722326&type=3\'>3959期【给我一杯】<font color=\'#FF00FF\'>（三行中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722328&type=3\'>3959期【性敢之淫】<font color=\'#FF00FF\'>（双波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722335&type=3\'>3959期【爱是一道】<font color=\'#FF00FF\'>（单双四肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=34722330&type=3\'>3959期【倾城佳丽】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("    </div>");
document.writeln("<!--新彩结束-->");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("function setTab62(name,cursel,n){");
document.writeln("	for(i=1;i<=n;i++){");
document.writeln("	var menu=document.getElementById(name+i);");
document.writeln("	var con=document.getElementById(\"con_\"+name+\"_\"+i);");
document.writeln("	menu.className=i==cursel?\"hover\":\"\";");
document.writeln("	con.style.display=i==cursel?\"block\":\"none\";");
document.writeln("	}");
document.writeln("}");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");