document.writeln("");
document.writeln("");
document.writeln("<a href=\'  https://j.100tzz.com:100\'> <img src=\'           https://d31q194n7fpdes.cloudfront.net/mygai/tp/100/100.gif\' style=\'width: 100%;\' /></a>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".zzhl49-tit {}");
document.writeln(".zzhl49-tit img { width: 100%; height: auto; vertical-align: top;}");
document.writeln("#tabzzhl49 {}");
document.writeln("#tabzzhl49 a {  text-decoration: none;}");
document.writeln("#tabzzhl49 .zzhl49menu { width: 100%; padding: 5px 0; text-align: center; font-weight: bold; font-size: 18px; line-height:40px;}");
document.writeln("#tabzzhl49 .zzhl49menu ul { display: flex; justify-content: space-between;}");
document.writeln("#tabzzhl49 .zzhl49menu li { width: calc(33.33% - 5px); box-sizing: border-box; background: #eee; cursor: pointer;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover { color: #fff;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover span { display: block;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49am { background: #090;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49xg { background: #f00;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49tw { background: #00f;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49xc { background: #FF00FF;}");
document.writeln("#tabzzhl49 .zzhl49box {}");
document.writeln(".zzhl49-list { background: white;font-size: 16px;}");
document.writeln("");
document.writeln(".zzhl49-list ul { display: flex; flex-direction: row; flex-wrap: wrap; justify-content: space-between;}");
document.writeln(".zzhl49-list ul li { width: calc(50% - 5px); border-bottom: solid 1px #ddd; box-sizing: border-box;}");
document.writeln(".zzhl49-list ul li a { display: block; padding: 8px 5px; white-space: nowrap; overflow: hidden;color: black;}");
document.writeln("@media screen and (max-width:800px){");
document.writeln("#tabzzhl49 .zzhl49menu { font-size: 16px; line-height:36px;}");
document.writeln("#tabzzhl49 .zzhl49menu li { width: calc(33.33% - 3px);}");
document.writeln(".zzhl49-list { font-size: 15px;}");
document.writeln(".zzhl49-list ul li { width: 100%;}");
document.writeln(".zzhl49-list ul li a { padding: 8px 5px;}");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln(".zzhl49-list a {");
document.writeln("    font-size: large;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'zzhl49-tit\'><img src=\'https://huidfjfgg.a626102.com:888/images/djhl.jpg\' src=\'\'></div>");
document.writeln("<div id=\"tabzzhl49\">");
document.writeln("<div class=\'zzhl49menu\'>");
document.writeln("    <ul>");
document.writeln("       <li id=\"tabzzhl491\" onClick=\'setTab62(\"tabzzhl49\",1,4)\' class=\'hover\'><span class=\'zzhl49am\'>澳彩精华区</span></li>");
document.writeln("       <li id=\"tabzzhl492\" onClick=\'setTab62(\"tabzzhl49\",2,4)\'><span class=\'zzhl49xg\'>香港精华区</span></li>");
document.writeln("	   <li id=\"tabzzhl493\" onClick=\'setTab62(\"tabzzhl49\",3,4)\'><span class=\'zzhl49tw\'>台湾精华区</span></li>");
document.writeln("	   <li id=\"tabzzhl494\" onClick=\'setTab62(\"tabzzhl49\",4,4)\'><span class=\'zzhl49xc\'>新彩精华区</span></li>");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<div class=\'zzhl49box\'> ");
document.writeln("	<div id=\'con_tabzzhl49_1\'>");
document.writeln("<!--澳门开始-->");
document.writeln("<div class=\'zzhl49-list\'>");
document.writeln("	<ul>");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <!--开始--> ");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'   https://kdue.nvytelsju158789.com:2025/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【六合宝典】<font color=\'#FF0000\'>（三期必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("        <!--结束-->  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'      https://tgam.822123aa.com/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【特码大王】<font color=\'#FF0000\'>（二码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960147&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【柔情杀手】<font color=\'#FF0000\'>（绝杀一波）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960508&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【白日沉沦】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960518&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【苍穹剑泣】<font color=\'#FF0000\'>（单双两肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960599&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【帕加尼@】<font color=\'#FF0000\'>（双波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33961069&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【蓝月亮@】<font color=\'#FF0000\'>（六肖12码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33961088&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【释看群枭】<font color=\'#FF0000\'>（三行中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'     https://kdue.nvytelsju158789.com:2025/#qwt\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【六合宝典】<font color=\'#FF0000\'>（无错单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960814&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【過河的卒】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960819&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【港澳百家】<font color=\'#FF0000\'>（主攻九码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960843&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【项羽雄威】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960882&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【天朗气清】<font color=\'#FF0000\'>（绝杀五码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33959906&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【宁折不弯】<font color=\'#FF0000\'>（绝杀十码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33959861&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【不吐不快】<font color=\'#FF0000\'>（吃菜草肉）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960894&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【簪缨世族】<font color=\'#FF0000\'>（绝杀一头）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://frqfecxa.www98217b.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【今日头条】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（三期必开）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://dfdrfr.www56926b.com:8443/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【香山论坛】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960859&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【完美少女】<font color=\'#FF0000\'>（三期出特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960824&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【青丝高挽】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960862&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【南港清风】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960668&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【狂飙资本】<font color=\'#FF0000\'>（六肖中通）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33960850&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【烟雨湖梦】<font color=\'#FF0000\'>（奇特五肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://qazsd.www27619b.com:888/#_49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【飞龙在天】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'       https://edcedc.www71685c.com:8443/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>   027期【澳牛魔王】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（单双100%）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960602&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【祖师爺@】<font color=\'#FF0000\'>（必中单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960036&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【天上人间】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959851&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【野的像风】<font color=\'#FF0000\'>（阳肖阴肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://xzcsaasc.www68729a.com:888/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【澳利澳@】<font color=\'#FF0000\'>（18码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://dssdfsd.www72385c.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【王中王@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'       https://gfreqasca.www97185c.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【大三八网】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959857&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【夏已季末】<font color=\'#FF0000\'>（绝杀一段）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959901&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【时不我待】<font color=\'#FF0000\'>（禁二合数）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959910&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【绝无神@】<font color=\'#FF0000\'>（绝杀二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959948&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【转职六合】<font color=\'#FF0000\'>（2波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\' https://edcfggvb.www52619c.com:888/#49qwt  \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【御龙英豪】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'     https://eeddcc.www71697c.com:8443/#49qwt  \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【澳任我发】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（主攻一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://j.jzxke120.com:888/#49qwt \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【49聊天室】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（一码中特）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959878&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【我心依旧】<font color=\'#FF0000\'>（绝杀半波）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960053&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【银河系@】<font color=\'#FF0000\'>（9肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960592&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【玛丽莲梦】<font color=\'#FF0000\'>（必中波色）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960023&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【中国码王】<font color=\'#FF0000\'>（7肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959969&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【大老爺@】<font color=\'#FF0000\'>（必中大小）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960161&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【半醒半生】<font color=\'#FF0000\'>（段位爆特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960505&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【倾尽天下】<font color=\'#FF0000\'>（天地生肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960493&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【连锁反应】<font color=\'#FF0000\'>（三尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960175&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【夜阑卧听】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960517&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【看看刘郎】<font color=\'#FF0000\'>（精准②头）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960567&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【冰封大地】<font color=\'#FF0000\'>（红蓝绿肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960575&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【莫妮卡@】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960130&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【助人为乐】<font color=\'#FF0000\'>（野兽家禽）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960004&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【赢飞纷纷】<font color=\'#FF0000\'>（四行中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960042&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【彩乐半生】<font color=\'#FF0000\'>（肉菜草肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959940&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【六合佳@】<font color=\'#FF0000\'>（6肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959913&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【夜袭女儿】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959854&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【我命油我】<font color=\'#FF0000\'>（一肖平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960031&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【就菜吃酒】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959870&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【布莱恩特】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959964&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【比天还高】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959954&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【理想还是】<font color=\'#FF0000\'>（5肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960062&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【烟雨小镇】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959920&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【一往无前】<font color=\'#FF0000\'>（前后中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959855&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【手指上旳】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960419&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【南风凉@】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960423&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【零度萤火】<font color=\'#FF0000\'>（7肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960006&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【九点钟的】<font color=\'#FF0000\'>（合数大小）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959975&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【十拿九吻】<font color=\'#FF0000\'>（左右中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959858&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【风起长林】<font color=\'#FF0000\'>（平特二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959923&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【迪丽热巴】<font color=\'#FF0000\'>（双波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959952&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【浅月流歌】<font color=\'#FF0000\'>（一肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960002&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【树大招风】<font color=\'#FF0000\'>（平特１肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960055&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【墨羽尘曦】<font color=\'#FF0000\'>（绝杀一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960159&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【奥巴码@】<font color=\'#FF0000\'>（四字平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960168&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【谁是谁的】<font color=\'#FF0000\'>（绝杀二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960233&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【一点通@】<font color=\'#FF0000\'>（一肖一码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960354&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【南巷清风】<font color=\'#FF0000\'>（原创4肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959876&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【乱舞春秋】<font color=\'#FF0000\'>（必中六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960261&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【淡述昔日】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960274&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【猛琥出山】<font color=\'#FF0000\'>（2波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960303&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【剑九皇@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960344&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【炽羽金尊】<font color=\'#FF0000\'>（单双两肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960339&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【八码神探】<font color=\'#FF0000\'>（四肖八码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960454&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【欢乐男孩】<font color=\'#FF0000\'>（绝杀一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960460&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【吟墨香@】<font color=\'#FF0000\'>（2头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960466&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【越淡呢@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960471&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【那缕阳光】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960474&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【鬓惊秋@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960483&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【甜妹娇羞】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960490&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【憾清线@】<font color=\'#FF0000\'>（11码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960495&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【年華已逝】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960503&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【乖囧貓@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960512&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【呆傻萌@】<font color=\'#FF0000\'>（十码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960521&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【空格晴@】<font color=\'#FF0000\'>（倆头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960580&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【乖囧猫@】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960641&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【红薇染露】<font color=\'#FF0000\'>（一肖平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960648&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【野心家@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960656&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【淩望夜空】<font color=\'#FF0000\'>（八肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960663&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【怎及此@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960676&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【酷出界限】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960687&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【软妹杀手】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960715&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【且笑天下】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960726&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【红遍全球】<font color=\'#FF0000\'>（三肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960730&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【淡淡稻花】<font color=\'#FF0000\'>（大小中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960734&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【川长思鸟】<font color=\'#FF0000\'>（5尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960740&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【鸿卷长篇】<font color=\'#FF0000\'>（四尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960020&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【薄荷音少】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960040&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【无戏配角】<font color=\'#FF0000\'>（成语平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960059&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【来碗泪流】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960065&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【全球焦點】<font color=\'#FF0000\'>（天地中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960072&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【初雪未霁】<font color=\'#FF0000\'>（家野中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960080&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【吹箫望江】<font color=\'#FF0000\'>（平特一尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949596&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【與我無關】<font color=\'#FF0000\'>（平特一尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960121&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【南同学@】<font color=\'#FF0000\'>（天地中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960129&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【寒塘冷月】<font color=\'#FF0000\'>（中特单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960136&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【梦好沉@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960158&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【傲娇小野】<font color=\'#FF0000\'>（12码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960170&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【清酒桃花】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960181&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【淡水深流】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960186&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【梦醉红颜】<font color=\'#FF0000\'>（二头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960213&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【紧拥背影】<font color=\'#FF0000\'>（四尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960221&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【独钓一江】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960227&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【指尖凝香】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960232&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【老衲法号】<font color=\'#FF0000\'>（大小中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960332&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【长虹饮涧】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959859&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【剩老友@】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959875&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【枉少年@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959900&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【百日醉@】<font color=\'#FF0000\'>（两头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959914&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【蓝蝶恋@】<font color=\'#FF0000\'>（精选六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959930&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【尐懶猫@】<font color=\'#FF0000\'>（一头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959947&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【花若兮@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959957&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【猫小柒@】<font color=\'#FF0000\'>（六肖必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959967&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【喔嗨呦@】<font color=\'#FF0000\'>（五尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959998&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【续往事@】<font color=\'#FF0000\'>（必准两头）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960009&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【控制狂@】<font color=\'#FF0000\'>（家野中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960025&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【岚风殇@】<font color=\'#FF0000\'>（天地爆特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960045&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【末言雨@】<font color=\'#FF0000\'>（六肖必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960060&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【颜洛殇@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960071&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【惜流芳@】<font color=\'#FF0000\'>（一肖平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960089&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【听风暖@】<font color=\'#FF0000\'>（必准六尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33960743&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>027期【千堆雪@】<font color=\'#FF0000\'>（火爆六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://popopo.www39871a.com:888/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 027期【蓝月亮网】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（四肖中特）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<!--澳门结束-->");
document.writeln("	</div>");
document.writeln("	<div id=\'con_tabzzhl49_2\' style=\'display:none\'>");
document.writeln("<!--香港开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://tgxg.822123aa.com/#49qwt\'>011期【特码大王】<font color=\'#FF0000\'>（二码中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949914&type=3\'>011期【墨染傾城】<font color=\'#FF0000\'>（四头中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949776&type=3\'>011期【通天论坛】<font color=\'#FF0000\'>（一码中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949800&type=3\'>011期【绝世骚神】<font color=\'#FF0000\'>（三期必开）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949791&type=3\'>011期【通天一码】<font color=\'#FF0000\'>（四肖一码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949893&type=3\'>011期【要的是范】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\' https://dffrfdfd.www82712c.com:888/#49qwt\'>011期【通天特码】<font color=\'#FF0000\'>（三肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949547&type=3\'>011期【小兔子乖】<font color=\'#FF0000\'>（平特二尾）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\' https://asddsa.www71873b.com:888/xg/index.html#49qwt\'>011期【百家网港】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949838&type=3\'>011期【浅月流歌】<font color=\'#FF0000\'>（一肖中特）</font>已公开</a></b></li>");
document.writeln("");


document.writeln("		<li><b><a target=\'_blank\' href=\'https://wsxxsw.www73125b.com:888/xg/index.html#49qwt\'>011期【港澳宝典】<font color=\'#FF0000\'>（单双100%）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949562&type=3\'>011期【不凡的路】<font color=\'#FF0000\'>（八尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949937&type=3\'>011期【春天菊花】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://dffrfdfd.www82712c.com:888/#49qwt\'>011期【神算通天】<font color=\'#FF0000\'>（三期必开）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949953&type=3\'>011期【甜诱少女】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949987&type=3\'>011期【劫持野凯】<font color=\'#FF0000\'>（前后中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950006&type=3\'>011期【紫色妖媚】<font color=\'#FF0000\'>（稳杀五码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950030&type=3\'>011期【谁熋违抗】<font color=\'#FF0000\'>（肉草菜肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949571&type=3\'>011期【都市逆行】<font color=\'#FF0000\'>（精准９肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949873&type=3\'>011期【魍魉影魅】<font color=\'#FF0000\'>（追杀10码）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950043&type=3\'>011期【帝王独撑】<font color=\'#FF0000\'>（有无边肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950058&type=3\'>011期【月亮几点】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949712&type=3\'>011期【我爱她他】<font color=\'#FF0000\'>（平特二肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949731&type=3\'>011期【风清淡雅】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949746&type=3\'>011期【南子妗@】<font color=\'#FF0000\'>（平特①肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949762&type=3\'>011期【芊茗静语】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949768&type=3\'>011期【蓝海噬心】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949778&type=3\'>011期【程染筱@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949787&type=3\'>011期【似梵音@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949790&type=3\'>011期【紫嫣轻娆】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949801&type=3\'>011期【紫薇児@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949806&type=3\'>011期【佑铒盯@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949814&type=3\'>011期【柠萌啵啵】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949824&type=3\'>011期【柚萌裙摆】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949833&type=3\'>011期【薄荷喵@】<font color=\'#FF0000\'>（四肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949848&type=3\'>011期【雪之髻@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949858&type=3\'>011期【怯霜静@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949869&type=3\'>011期【勇敢活@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949882&type=3\'>011期【散青丝@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949890&type=3\'>011期【恋飘雪@】<font color=\'#FF0000\'>（七肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950075&type=3\'>011期【博多野@】<font color=\'#FF0000\'>（东南西北）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950089&type=3\'>011期【她是光芒】<font color=\'#FF0000\'>（三门中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950111&type=3\'>011期【满船清梦】<font color=\'#FF0000\'>（四季生肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950122&type=3\'>011期【无限领域】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950133&type=3\'>011期【执念不在】<font color=\'#FF0000\'>（美丑中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950162&type=3\'>011期【奶茶限供】<font color=\'#FF0000\'>（风雷云雨）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33950171&type=3\'>011期【花残满地】<font color=\'#FF0000\'>（平特一尾）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949810&type=3\'>011期【诸葛村夫】<font color=\'#FF0000\'>（中特六码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949860&type=3\'>011期【天盛长歌】<font color=\'#FF0000\'>（平特①肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949849&type=3\'>011期【墨羽尘曦】<font color=\'#FF0000\'>（绝杀一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949855&type=3\'>011期【东方神起】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949600&type=3\'>011期【平步青云】<font color=\'#FF0000\'>（9肖4码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949611&type=3\'>011期【北孤南荒】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949653&type=3\'>011期【知足者富】<font color=\'#FF0000\'>（必中波色）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949658&type=3\'>011期【听风雨落】<font color=\'#FF0000\'>（特码三头）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949792&type=3\'>011期【续命航@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949721&type=3\'>011期【男人站直】<font color=\'#FF0000\'>（精准八肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33949527&type=3\'>011期【可以哭却】<font color=\'#FF0000\'>（家禽野兽）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49195c.com/#/corpusdetail?id=33950494&type=3\'>011期【過河的卒】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49070a.com/#/corpusdetail?id=33950510&type=3\'>011期【青丝高挽】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49080.com/#/corpusdetail?id=33950506&type=3\'>011期【港澳百家】<font color=\'#FF0000\'>（主攻九码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49329c.com/#/corpusdetail?id=33950519&type=3\'>011期【烟雨江湖】<font color=\'#FF0000\'>（主攻五肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49329.com/#/corpusdetail?id=33950532&type=3\'>011期【南港清风】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49319b.com/#/corpusdetail?id=33950540&type=3\'>011期【天朗气清】<font color=\'#FF0000\'>（绝杀五码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49158b.com/#/corpusdetail?id=33949614&type=3\'>011期【宁折不弯】<font color=\'#FF0000\'>（绝杀十码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://www.49157c.com/#/corpusdetail?id=33950579&type=3\'>011期【簪缨世族】<font color=\'#FF0000\'>（绝杀一头）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<!--香港结束-->");
document.writeln("    </div>");
document.writeln("    <div id=\'con_tabzzhl49_3\' style=\'display:none\'>");
document.writeln("<!--台湾开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959415&type=3\'>027期【二氧化甜】<font color=\'#0000ff\'>（精准杀五）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959457&type=3\'>027期【摘星不得】<font color=\'#0000ff\'>（必中三头）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959461&type=3\'>027期【梦中风几】<font color=\'#0000ff\'>（3行中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959466&type=3\'>027期【南葵思暖】<font color=\'#0000ff\'>（绝杀二肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959530&type=3\'>027期【此用户下】<font color=\'#0000ff\'>（必中双波）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959576&type=3\'>027期【独霸青楼】<font color=\'#0000ff\'>（二波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959471&type=3\'>027期【温暖慕城】<font color=\'#0000ff\'>（大小必中）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959543&type=3\'>027期【喜欢杨幂】<font color=\'#0000ff\'>（二波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959583&type=3\'>027期【月色如水】<font color=\'#0000ff\'>（三头中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959613&type=3\'>027期【猥琐欲为】<font color=\'#0000ff\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959478&type=3\'>027期【狂乱飞舞】<font color=\'#0000ff\'>（金牌六尾）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959510&type=3\'>027期【野味浪友】<font color=\'#0000ff\'>（尾数大小）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959464&type=3\'>027期【元气少妇】<font color=\'#0000ff\'>（个半单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959558&type=3\'>027期【农村混血】<font color=\'#0000ff\'>（24码中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959567&type=3\'>027期【沉寂于曾】<font color=\'#0000ff\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959580&type=3\'>027期【于你悸动】<font color=\'#0000ff\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959538&type=3\'>027期【寂寞学会】<font color=\'#0000ff\'>（精准七肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959572&type=3\'>027期【天生的傲】<font color=\'#0000ff\'>（特码单双）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959524&type=3\'>027期【安妮和小】<font color=\'#0000ff\'>（四肖二肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959535&type=3\'>027期【好人一生】<font color=\'#0000ff\'>（三半单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959553&type=3\'>027期【风过留痕】<font color=\'#0000ff\'>（稳猛六肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959564&type=3\'>027期【粉色樱花】<font color=\'#0000ff\'>（八肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33959569&type=3\'>027期【迷乱浮生】<font color=\'#0000ff\'>（左肖右肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("    <div id=\'con_tabzzhl49_4\' style=\'display:none\'>");
document.writeln("<!--新彩开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948722&type=3\'>3943期【山川志@】<font color=\'#FF00FF\'>（精选双波）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33919487&type=3\'>3943期【七师弟@】<font color=\'#FF00FF\'>（吃草吃肉）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948727&type=3\'>3943期【扑倒李太】<font color=\'#FF00FF\'>（准杀五码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948876&type=3\'>3943期【爱是一道】<font color=\'#FF00FF\'>（单双四肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948883&type=3\'>3943期【悲伤广@】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948734&type=3\'>3943期【南风几经】<font color=\'#FF00FF\'>（七肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948735&type=3\'>3943期【七里香火】<font color=\'#FF00FF\'>（2波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948738&type=3\'>3943期【末代情人】<font color=\'#FF00FF\'>（绝杀三肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948739&type=3\'>3943期【拱白菜的】<font color=\'#FF00FF\'>（五段中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948897&type=3\'>3943期【沸羊羊@】<font color=\'#FF00FF\'>（琴棋书画）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948903&type=3\'>3943期【水中鬼@】<font color=\'#FF00FF\'>（左右两肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948909&type=3\'>3943期【金嗓子@】<font color=\'#FF00FF\'>（传奇六肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948913&type=3\'>3943期【天王盖地】<font color=\'#FF00FF\'>（六尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948918&type=3\'>3943期【盖世淫胸】<font color=\'#FF00FF\'>（三半单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948740&type=3\'>3943期【航行远@】<font color=\'#FF00FF\'>（四头中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948807&type=3\'>3943期【中央大帝】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948809&type=3\'>3943期【卑微的苟】<font color=\'#FF00FF\'>（６肖６肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948924&type=3\'>3943期【赌王之弟】<font color=\'#FF00FF\'>（六尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948813&type=3\'>3943期【蓝色之海】<font color=\'#FF00FF\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948887&type=3\'>3943期【倾城佳丽】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948919&type=3\'>3943期【单恋一枝】<font color=\'#FF00FF\'>（必中双波）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948930&type=3\'>3943期【鲨鱼掉海】<font color=\'#FF00FF\'>（八肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33948939&type=3\'>3943期【降龙十九】<font color=\'#FF00FF\'>（精选七肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("    </div>");
document.writeln("<!--新彩结束-->");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("function setTab62(name,cursel,n){");
document.writeln("	for(i=1;i<=n;i++){");
document.writeln("	var menu=document.getElementById(name+i);");
document.writeln("	var con=document.getElementById(\"con_\"+name+\"_\"+i);");
document.writeln("	menu.className=i==cursel?\"hover\":\"\";");
document.writeln("	con.style.display=i==cursel?\"block\":\"none\";");
document.writeln("	}");
document.writeln("}");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");