document.writeln("");
document.writeln("");
document.writeln("<a href=\'  https://j.100tzz.com:100\'> <img src=\'           https://d31q194n7fpdes.cloudfront.net/mygai/tp/100/100.gif\' style=\'width: 100%;\' /></a>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".zzhl49-tit {}");
document.writeln(".zzhl49-tit img { width: 100%; height: auto; vertical-align: top;}");
document.writeln("#tabzzhl49 {}");
document.writeln("#tabzzhl49 a {  text-decoration: none;}");
document.writeln("#tabzzhl49 .zzhl49menu { width: 100%; padding: 5px 0; text-align: center; font-weight: bold; font-size: 18px; line-height:40px;}");
document.writeln("#tabzzhl49 .zzhl49menu ul { display: flex; justify-content: space-between;}");
document.writeln("#tabzzhl49 .zzhl49menu li { width: calc(33.33% - 5px); box-sizing: border-box; background: #eee; cursor: pointer;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover { color: #fff;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover span { display: block;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49am { background: #090;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49xg { background: #f00;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49tw { background: #00f;}");
document.writeln("#tabzzhl49 .zzhl49menu li.hover .zzhl49xc { background: #FF00FF;}");
document.writeln("#tabzzhl49 .zzhl49box {}");
document.writeln(".zzhl49-list { background: white;font-size: 16px;}");
document.writeln("");
document.writeln(".zzhl49-list ul { display: flex; flex-direction: row; flex-wrap: wrap; justify-content: space-between;}");
document.writeln(".zzhl49-list ul li { width: calc(50% - 5px); border-bottom: solid 1px #ddd; box-sizing: border-box;}");
document.writeln(".zzhl49-list ul li a { display: block; padding: 8px 5px; white-space: nowrap; overflow: hidden;color: black;}");
document.writeln("@media screen and (max-width:800px){");
document.writeln("#tabzzhl49 .zzhl49menu { font-size: 16px; line-height:36px;}");
document.writeln("#tabzzhl49 .zzhl49menu li { width: calc(33.33% - 3px);}");
document.writeln(".zzhl49-list { font-size: 15px;}");
document.writeln(".zzhl49-list ul li { width: 100%;}");
document.writeln(".zzhl49-list ul li a { padding: 8px 5px;}");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln(".zzhl49-list a {");
document.writeln("    font-size: large;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'zzhl49-tit\'><img src=\'https://huidfjfgg.a626102.com:888/images/djhl.jpg\' src=\'\'></div>");
document.writeln("<div id=\"tabzzhl49\">");
document.writeln("<div class=\'zzhl49menu\'>");
document.writeln("    <ul>");
document.writeln("       <li id=\"tabzzhl491\" onClick=\'setTab62(\"tabzzhl49\",1,4)\' class=\'hover\'><span class=\'zzhl49am\'>澳彩精华区</span></li>");
document.writeln("       <li id=\"tabzzhl492\" onClick=\'setTab62(\"tabzzhl49\",2,4)\'><span class=\'zzhl49xg\'>香港精华区</span></li>");
document.writeln("	   <li id=\"tabzzhl493\" onClick=\'setTab62(\"tabzzhl49\",3,4)\'><span class=\'zzhl49tw\'>台湾精华区</span></li>");
document.writeln("	   <li id=\"tabzzhl494\" onClick=\'setTab62(\"tabzzhl49\",4,4)\'><span class=\'zzhl49xc\'>新彩精华区</span></li>");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<div class=\'zzhl49box\'> ");
document.writeln("	<div id=\'con_tabzzhl49_1\'>");
document.writeln("<!--澳门开始-->");
document.writeln("<div class=\'zzhl49-list\'>");
document.writeln("	<ul>");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <!--开始--> ");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'   https://jdhfe.yeisdnue56987.com:2025/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【六合宝典】<font color=\'#FF0000\'>（三期必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("        <!--结束-->  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'      https://tgam.822123aa.com/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【特码大王】<font color=\'#FF0000\'>（二码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802258&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【冰封大地】<font color=\'#FF0000\'>（红蓝绿肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801552&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【柔情杀手】<font color=\'#FF0000\'>（绝杀一波）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'     https://jdhfe.yeisdnue56987.com:2025/#qwt\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【六合宝典】<font color=\'#FF0000\'>（无错单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33802497&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【蓝月亮@】<font color=\'#FF0000\'>（六肖12码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33802222&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【都是逆风】<font color=\'#FF0000\'>（单双二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33802095&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【香山论坛】<font color=\'#FF0000\'>（六加一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33802229&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【帕加尼@】<font color=\'#FF0000\'>（双波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33802193&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【二哥独秀】<font color=\'#FF0000\'>（成语平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217005.com:8443/#/corpusdetail?id=33802294&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【物都是你】<font color=\'#FF0000\'>（单双二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802306&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【祖师爺@】<font color=\'#FF0000\'>（必中单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801402&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【天上人间】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://frqfecxa.www98217b.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【今日头条】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（三期必开）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://dfdrfr.www56926b.com:8443/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【香山论坛】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");


document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://4921755.com/#/corpusdetail?id=33801604&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【鄙人称乌】<font color=\'#FF0000\'>（绝杀一尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://4921722.cc/#/corpusdetail?id=33801534&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【城南以南】<font color=\'#FF0000\'>（前后六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://4921711.com/#/corpusdetail?id=33801491&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【天涯明月】<font color=\'#FF0000\'>（九肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://edcffbb.www86375c.com:888/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【飞龙在天】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'       https://fqdcvrwb.www71685b.com:8443/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>   011期【澳牛魔王】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（单双100%）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");


document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'http://4921700.com/#/corpusdetail?id=33801452&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【女人无才】<font color=\'#FF0000\'>（单双两肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://4921766.com/#/corpusdetail?id=33801617&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【不努力如】<font color=\'#FF0000\'>（强杀一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://4921800.com/#/corpusdetail?id=33801717&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【小飒老师】<font color=\'#FF0000\'>（二期一平）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://xzcsaasc.www68729a.com:888/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【澳利澳@】<font color=\'#FF0000\'>（18码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://dssdfsd.www72385c.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【王中王@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'       https://gfreqasca.www97185c.com:8443/#qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【大三八网】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（平特一肖）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");


document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://4921744.cc/#/corpusdetail?id=33801595&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【东莞市神】<font color=\'#FF0000\'>（绝杀十码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://4921722.com/#/corpusdetail?id=33801521&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【时间飞快】<font color=\'#FF0000\'>（绝杀三肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217001.com:8443/#/corpusdetail?id=33801444&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【带你装杯】<font color=\'#FF0000\'>（一肖一码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\' https://edcfggvb.www52619c.com:888/#49qwt  \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【御龙英豪】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'     https://rrrwww.www71697a.com:8443/#49qwt  \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【澳任我发】<font color=\'#FF0000\'>（主攻一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://j.jzxke120.com:888/#49qwt \'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【49聊天室】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（一码中特）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802218&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【李大爺@】<font color=\'#FF0000\'>（大小中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801598&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【夜阑珊人】<font color=\'#FF0000\'>（左右中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802179&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【连锁反应】<font color=\'#FF0000\'>（三尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801284&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【顾向南@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801294&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【枉少年@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801321&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【胭脂夢@】<font color=\'#FF0000\'>（五肖火爆）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801346&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【小简洁@】<font color=\'#FF0000\'>（吉美凶丑）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801366&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【冷风雨@】<font color=\'#FF0000\'>（两半单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801381&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【江晚吟@】<font color=\'#FF0000\'>（单双必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801403&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【灵之舞@】<font color=\'#FF0000\'>（大小中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801418&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【颜洛殇@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801451&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【清影觅@】<font color=\'#FF0000\'>（左右中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801468&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【载风月@】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802279&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【巴黎醉@】<font color=\'#FF0000\'>（火爆四肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802059&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【墨羽尘曦】<font color=\'#FF0000\'>（绝杀一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802263&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【天盛长歌】<font color=\'#FF0000\'>（平特①肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802071&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【谁是谁的】<font color=\'#FF0000\'>（大小必中）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802377&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【乱舞春秋】<font color=\'#FF0000\'>（必中六肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802045&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【迪丽热巴】<font color=\'#FF0000\'>（双波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802065&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【浅月流歌】<font color=\'#FF0000\'>（一肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802074&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【诸葛村夫】<font color=\'#FF0000\'>（中特六码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802255&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【一点通@】<font color=\'#FF0000\'>（一肖一码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801588&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【最初模样】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802079&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【澳彩一片】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802239&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【哈妮克孜】<font color=\'#FF0000\'>（三行中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801282&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【淡看云卷】<font color=\'#FF0000\'>（三国生肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801283&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【野的像风】<font color=\'#FF0000\'>（阳肖阴肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801343&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【夏已季末】<font color=\'#FF0000\'>（绝杀一段）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801373&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【绝无神@】<font color=\'#FF0000\'>（绝杀二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801435&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【转职六合】<font color=\'#FF0000\'>（2波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801365&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【我心依旧】<font color=\'#FF0000\'>（绝杀半波）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801492&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【银河系@】<font color=\'#FF0000\'>（9肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801290&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【妹子跟我】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802064&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【萌妹妹@】<font color=\'#FF0000\'>（2头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802161&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【水中仴@】<font color=\'#FF0000\'>（精准24码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802278&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【玛丽莲梦】<font color=\'#FF0000\'>（必中波色）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802248&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【东北彩王】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801383&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【中国码王】<font color=\'#FF0000\'>（7肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801379&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【澳彩鼠@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790647&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【精彩飞蝗】<font color=\'#FF0000\'>（平特①肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801547&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【雨化田@】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801447&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【赢飞纷纷】<font color=\'#FF0000\'>（四行中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801450&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【精彩人升】<font color=\'#FF0000\'>（七肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801506&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【烟雨小镇】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801654&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【夜袭女儿】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801297&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【寒塘冷月】<font color=\'#FF0000\'>（中特单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801317&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【烟火色@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801337&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【孤者傲凡】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");

document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802202&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【沙场湫点】<font color=\'#FF0000\'>（五肖五码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802143&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【东方神起】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802246&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【淡述昔日】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802385&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【九次拒绝】<font color=\'#FF0000\'>（成语平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802151&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【顶级特码】<font color=\'#FF0000\'>（精准20码）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802166&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【皇阿玛@】<font color=\'#FF0000\'>（平特二肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801351&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【梦好沉@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801367&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【夏日天浅】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801376&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【手指上旳】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801382&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【山高云阔】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801401&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【初心不负】<font color=\'#FF0000\'>（二头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801409&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【南同学@】<font color=\'#FF0000\'>（天地中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801417&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【日青良月】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801437&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【独钓一江】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801445&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【梦荧光笔】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802077&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【晚来天欲】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802096&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【往复春秋】<font color=\'#FF0000\'>（四尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802104&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【蝶为花舞】<font color=\'#FF0000\'>（10码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802113&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【小情调@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802121&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【重命名@】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802127&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【博学多闻】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802134&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【兰花恋@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802142&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【野心家@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802160&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【风流转@】<font color=\'#FF0000\'>（三肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802177&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【怎及此@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802203&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【缚情陆少】<font color=\'#FF0000\'>（六码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801803&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【乖囧貓@】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801829&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【飛絮殘雪】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801839&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【独单心事】<font color=\'#FF0000\'>（20码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801858&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【南风凉@】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801872&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【依莫相随】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801881&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【香蕉不叫】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801885&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【假快樂@】<font color=\'#FF0000\'>（四尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801889&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【卿烟寒@】<font color=\'#FF0000\'>（二头中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801894&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【矜我意@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801908&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【甜妹娇羞】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801938&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【悔旧日@】<font color=\'#FF0000\'>（一波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801943&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【灵韵飞舞】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801950&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【冰凝泪烛】<font color=\'#FF0000\'>（平特一尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801973&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【灵韵飞五】<font color=\'#FF0000\'>（六肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801982&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【零度萤火】<font color=\'#FF0000\'>（7肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801454&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【薄情的红】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801461&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【伤口撒把】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801486&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【心锁了雾】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801493&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【掌权者@】<font color=\'#FF0000\'>（左右中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801499&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【清风霁月】<font color=\'#FF0000\'>（吉美凶丑）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801541&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【明净日夜】<font color=\'#FF0000\'>（平特一尾）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801551&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【心事痕迹】<font color=\'#FF0000\'>（⑸尾中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801573&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【追忆那片】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801593&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【眼睛有光】<font color=\'#FF0000\'>（合数单双）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801605&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【逆天轩辕】<font color=\'#FF0000\'>（四肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801624&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【九点钟的】<font color=\'#FF0000\'>（合数大小）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801637&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【朝槿温雾】<font color=\'#FF0000\'>（平特一肖）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802801&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【奥巴码@】<font color=\'#FF0000\'>（四字平特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802373&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【猛琥出山】<font color=\'#FF0000\'>（2波中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802052&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【芳心纵火】<font color=\'#FF0000\'>（12码中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801407&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【逐梦之音】<font color=\'#FF0000\'>（五肖中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801384&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【一往无前】<font color=\'#FF0000\'>（前后中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33802046&type=3\' >");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong>011期【我的专业】<font color=\'#FF0000\'>（单双中特）</font>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li> ");
document.writeln("");
document.writeln("");
document.writeln("        <li>");
document.writeln("            <a target=\'_blank\' href=\'        https://popopo.www39871a.com:888/#49qwt\'>");
document.writeln("                <div class=\'zzhl-txt1\' style=\'font-size: large\'><strong> 011期【蓝月亮网】<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>（四肖中特）</font></span>已公开</strong></div>");
document.writeln("            </a>");
document.writeln("        </li>  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<!--澳门结束-->");
document.writeln("	</div>");
document.writeln("	<div id=\'con_tabzzhl49_2\' style=\'display:none\'>");
document.writeln("<!--香港开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://tgxg.822123aa.com/#49qwt\'>004期【特码大王】<font color=\'#FF0000\'>（二码中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790989&type=3\'>004期【墨染傾城】<font color=\'#FF0000\'>（四头中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790753&type=3\'>004期【通天论坛】<font color=\'#FF0000\'>（一码中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790837&type=3\'>004期【绝世骚神】<font color=\'#FF0000\'>（三期必开）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790800&type=3\'>004期【通天一码】<font color=\'#FF0000\'>（四肖一码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790973&type=3\'>004期【要的是范】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\' https://dffrfdfd.www82712c.com:888/#49qwt\'>004期【通天特码】<font color=\'#FF0000\'>（三肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790628&type=3\'>004期【小兔子乖】<font color=\'#FF0000\'>（平特二尾）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790642&type=3\'>004期【姐有金凶】<font color=\'#FF0000\'>（二波中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\' https://6qcvzk.www71873b.com:888/xg/index.html#49qwt\'>004期【百家网港】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790897&type=3\'>004期【浅月流歌】<font color=\'#FF0000\'>（一肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790949&type=3\'>004期【墨羽尘曦】<font color=\'#FF0000\'>（绝杀一肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://ii31yk.www73125b.com:888/xg/index.html#49qwt\'>004期【港澳宝典】<font color=\'#FF0000\'>（单双100%）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790649&type=3\'>004期【不凡的路】<font color=\'#FF0000\'>（八尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791005&type=3\'>004期【春天菊花】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://dffrfdfd.www82712c.com:888/#49qwt\'>004期【神算通天】<font color=\'#FF0000\'>（三期必开）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791018&type=3\'>004期【甜诱少女】<font color=\'#FF0000\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791037&type=3\'>004期【劫持野凯】<font color=\'#FF0000\'>（前后中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791054&type=3\'>004期【紫色妖媚】<font color=\'#FF0000\'>（稳杀五码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791069&type=3\'>004期【谁熋违抗】<font color=\'#FF0000\'>（肉草菜肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791093&type=3\'>004期【狂刄星空】<font color=\'#FF0000\'>（琴棋书画）</font>已公开</a></b></li>");
document.writeln("");


document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790697&type=3\'>004期【都市逆行】<font color=\'#FF0000\'>（精准９肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790938&type=3\'>004期【魍魉影魅】<font color=\'#FF0000\'>（追杀10码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791105&type=3\'>004期【与日暮同】<font color=\'#FF0000\'>（书画棋琴）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791124&type=3\'>004期【帝王独撑】<font color=\'#FF0000\'>（有无边肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791140&type=3\'>004期【月亮几点】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790664&type=3\'>004期【骑猪看海】<font color=\'#FF0000\'>（男女中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791158&type=3\'>004期【提笔画西】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790930&type=3\'>004期【我爱她他】<font color=\'#FF0000\'>（平特二肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790974&type=3\'>004期【风清淡雅】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790993&type=3\'>004期【杏花雨@】<font color=\'#FF0000\'>（合数中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791003&type=3\'>004期【南子妗@】<font color=\'#FF0000\'>（平特①肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791016&type=3\'>004期【芊茗静语】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791041&type=3\'>004期【蓝海噬心】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791048&type=3\'>004期【程染筱@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791056&type=3\'>004期【似梵音@】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791066&type=3\'>004期【夕陽風采】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791076&type=3\'>004期【绿竹猗猗】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791096&type=3\'>004期【紫嫣轻娆】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791108&type=3\'>004期【紫薇児@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791117&type=3\'>004期【佑铒盯@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791145&type=3\'>004期【柠萌啵啵】<font color=\'#FF0000\'>（六肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791156&type=3\'>004期【恋飘雪@】<font color=\'#FF0000\'>（七肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791168&type=3\'>004期【酒当歌@】<font color=\'#FF0000\'>（三肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791178&type=3\'>004期【芮小姐@】<font color=\'#FF0000\'>（四尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791192&type=3\'>004期【寶貝猪唲】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791204&type=3\'>004期【喵咩咩@】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791213&type=3\'>004期【柚萌裙摆】<font color=\'#FF0000\'>（五肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791167&type=3\'>004期【博多野@】<font color=\'#FF0000\'>（东南西北）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791180&type=3\'>004期【她是光芒】<font color=\'#FF0000\'>（三门中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791270&type=3\'>004期【满船清梦】<font color=\'#FF0000\'>（四季生肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790926&type=3\'>004期【诸葛村夫】<font color=\'#FF0000\'>（中特六码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790707&type=3\'>004期【人无少年】<font color=\'#FF0000\'>（吃肉菜草）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33790760&type=3\'>004期【平步青云】<font color=\'#FF0000\'>（9肖4码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791175&type=3\'>004期【爱意潇潇】<font color=\'#FF0000\'>（平特一肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791232&type=3\'>004期【安城如末】<font color=\'#FF0000\'>（野兽家畜）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33791046&type=3\'>004期【如花姐@】<font color=\'#FF0000\'>（四肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<!--香港结束-->");
document.writeln("    </div>");
document.writeln("    <div id=\'con_tabzzhl49_3\' style=\'display:none\'>");
document.writeln("<!--台湾开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800899&type=3\'>011期【路尽隐香】<font color=\'#0000ff\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800892&type=3\'>011期【二氧化甜】<font color=\'#0000ff\'>（精准杀五）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801010&type=3\'>011期【你有弟我】<font color=\'#0000ff\'>（平特三肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800911&type=3\'>011期【风归影@】<font color=\'#0000ff\'>（七尾中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800905&type=3\'>011期【摘星不得】<font color=\'#0000ff\'>（必中三头）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801049&type=3\'>011期【盛开的彼】<font color=\'#0000ff\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800959&type=3\'>011期【梦中风几】<font color=\'#0000ff\'>（3行中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800972&type=3\'>011期【好人一生】<font color=\'#0000ff\'>（三半单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801021&type=3\'>011期【爱咋咋地】<font color=\'#0000ff\'>（绝杀十码）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801056&type=3\'>011期【半朵雲半】<font color=\'#0000ff\'>（二波中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800965&type=3\'>011期【南葵思暖】<font color=\'#0000ff\'>（绝杀二肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801060&type=3\'>011期【半厦微澜】<font color=\'#0000ff\'>（七尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800976&type=3\'>011期【萝莉杀手】<font color=\'#0000ff\'>（双波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801033&type=3\'>011期【此用户下】<font color=\'#0000ff\'>（必中双波）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800983&type=3\'>011期【夕颜浅笑】<font color=\'#0000ff\'>（合单合双）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800975&type=3\'>011期【寂寞学会】<font color=\'#0000ff\'>（精准七肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33800954&type=3\'>011期【粉色樱花】<font color=\'#0000ff\'>（八肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801063&type=3\'>011期【独霸青楼】<font color=\'#0000ff\'>（二波中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801082&type=3\'>011期【天生的傲】<font color=\'#0000ff\'>（特码单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33801144&type=3\'>011期【猥琐欲为】<font color=\'#0000ff\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("    <div id=\'con_tabzzhl49_4\' style=\'display:none\'>");
document.writeln("<!--新彩开始-->");
document.writeln("<div class=\'zzhl49-list\' style=\'font-size: large\'>");
document.writeln("	<ul>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780518&type=3\'>3938期【山川志@】<font color=\'#FF00FF\'>（精选双波）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780626&type=3\'>3938期【七师弟@】<font color=\'#FF00FF\'>（吃草吃肉）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780543&type=3\'>3938期【酒朋诗侣】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780852&type=3\'>3938期【倾城佳丽】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780520&type=3\'>3938期【扑倒李太】<font color=\'#FF00FF\'>（准杀五码）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780813&type=3\'>3938期【爱是一道】<font color=\'#FF00FF\'>（单双四肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780816&type=3\'>3938期【悲伤广@】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780546&type=3\'>3938期【南风几经】<font color=\'#FF00FF\'>（七肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780549&type=3\'>3938期【七里香火】<font color=\'#FF00FF\'>（2波中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780581&type=3\'>3938期【末代情人】<font color=\'#FF00FF\'>（绝杀三肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780585&type=3\'>3938期【拱白菜的】<font color=\'#FF00FF\'>（五段中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780857&type=3\'>3938期【降龙十九】<font color=\'#FF00FF\'>（精选七肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780861&type=3\'>3938期【沸羊羊@】<font color=\'#FF00FF\'>（琴棋书画）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780866&type=3\'>3938期【给我一杯】<font color=\'#FF00FF\'>（三行中特）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780870&type=3\'>3938期【水中鬼@】<font color=\'#FF00FF\'>（左右两肖）</font>已公开</a></b></li>");
document.writeln("");

document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780875&type=3\'>3938期【美锅自由】<font color=\'#FF00FF\'>（经典大小）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33781039&type=3\'>3938期【金嗓子@】<font color=\'#FF00FF\'>（传奇六肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780952&type=3\'>3938期【天王盖地】<font color=\'#FF00FF\'>（六尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780913&type=3\'>3938期【盖世淫胸】<font color=\'#FF00FF\'>（三半单双）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780626&type=3\'>3938期【七师弟@】<font color=\'#FF00FF\'>（八尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780591&type=3\'>3938期【航行远@】<font color=\'#FF00FF\'>（四头中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780596&type=3\'>3938期【吴疑凡@】<font color=\'#FF00FF\'>（六尾中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780660&type=3\'>3938期【中央大帝】<font color=\'#FF00FF\'>（九肖中特）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("		<li><b><a target=\'_blank\' href=\'https://h5.49217002.com:8443/#/corpusdetail?id=33780702&type=3\'>3938期【卑微的苟】<font color=\'#FF00FF\'>（６肖６肖）</font>已公开</a></b></li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("    </div>");
document.writeln("<!--新彩结束-->");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("function setTab62(name,cursel,n){");
document.writeln("	for(i=1;i<=n;i++){");
document.writeln("	var menu=document.getElementById(name+i);");
document.writeln("	var con=document.getElementById(\"con_\"+name+\"_\"+i);");
document.writeln("	menu.className=i==cursel?\"hover\":\"\";");
document.writeln("	con.style.display=i==cursel?\"block\":\"none\";");
document.writeln("	}");
document.writeln("}");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");