document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'103\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>贪狼天尊</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『四肖四码』</font></b></table>");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("            <!--开始--> ");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td height=32 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font color=\'#000000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第195期</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">【兔02.羊22.猴21.蛇48】</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("    <!--结束--> ");
document.writeln("");

document.writeln("");
document.writeln("            <!--开始--> ");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td height=32 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font color=\'#000000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第192期</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">【<span style=\'background-color: #FFFF00\'>狗31</span>.鸡08.蛇12.兔14】</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("    <!--结束--> ");
document.writeln("");




document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始--> ");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td height=32 >");
document.writeln("		<p align=\'cen");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://xn--oecalb2e.xn--hdcn9ajb1dyeua6etcq8g3b.xn--gecrj9c:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://hjyjthjy.www661161c.com:8443/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>37197b.com</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");