document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>流年暮雪</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『二头中特』</font></b></td></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=\"1\" width=\"100%\" id=\"table400923401\">");
document.writeln("");


document.writeln("");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		236期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（1.4.3.2）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		236期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（1.4）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		236期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">11.12.13.14.16.18.41.42.43.45.46.48");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");
document.writeln("");

document.writeln("");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		234期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（1.3.<span style=\'background-color: #FFFF00\'>【0】</span>.2）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		234期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（1.3）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		234期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">11.12.13.15.16.18.31.32.33.35.37.38");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");
document.writeln("");
document.writeln("");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		233期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（0.3.4.<span style=\'background-color: #FFFF00\'>【2】</span>）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		233期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（0.3）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		233期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">01.03.05.06.08.09.31.32.33.35.36.38");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");
document.writeln("");
document.writeln("");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		231期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（3.4.0.<span style=\'background-color: #FFFF00\'>【7】</span>）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		231期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（3.4）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		231期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">32.33.35.37.38.39.41.42.43.45.46.48");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");
document.writeln("");
document.writeln("");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		230期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（<span style=\'background-color: #FFFF00\'>【4】</span>.1.3.2）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		230期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（<span style=\'background-color: #FFFF00\'>【4】</span>.1）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		230期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">40.42.43.45.46.48.11.12.13.15.16.18");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");
document.writeln("");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		229期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（4.<span style=\'background-color: #FFFF00\'>【0】</span>.3.2）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		229期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（4.<span style=\'background-color: #FFFF00\'>【0】</span>）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		229期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">41.42.43.45.46.48.02.03.<span style=\'background-color: #FFFF00\'>【05】</span>.06.08.09");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		228期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（0.2.4.<span style=\'background-color: #FFFF00\'>【3】</span>）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		228期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（0.2）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		228期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">02.03.06.07.08.09.21.23.25.26.28.29");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");
document.writeln("	<!--gavc-->");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\"#FFFFFF\" height=\"38\"> <b>");
document.writeln("		<p align=\"left\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\">");
document.writeln("		227期;四头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（<span style=\'background-color: #FFFF00\'>【2】</span>.1.0.4）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		227期;二头：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\">（<span style=\'background-color: #FFFF00\'>【2】</span>.1）</font><font color=\"#000000\" face=\"微软雅黑\" style=\"font-size: 12pt\"><br>");
document.writeln("		227期;12码：</font><font color=\"#FF0000\" face=\"微软雅黑\" size=\"4\"><span style=\'background-color: #FFFF00\'>【20】</span>.21.23.25.26.28.11.12.13.15.16.18");
document.writeln("		<br></font><font color=\"#0000FF\" face=\"微软雅黑\" size=\"4\">-----</font></p></b></td>");
document.writeln("	</tr>");
document.writeln("	<!--结束-->	");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</table>");