document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong18 { color: #000000; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #f5f5f5;}");
document.writeln(".bizhong18-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #f00;}");
document.writeln(".bizhong18-box { display: flex;}");
document.writeln(".bizhong18-box ul {}");
document.writeln(".bizhong18-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong18-box .bizhong18-l { width: 50%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong18-box .bizhong18-r { width: 50%;}");
document.writeln(".bizhong18-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong18 { font-size: 16px;}");
document.writeln(".bizhong18-tit { font-size: 18px;}");
document.writeln(".bizhong18-box { display: block;}");
document.writeln(".bizhong18-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong18-box .bizhong18-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong18-box .bizhong18-r { width: 100%;}");
document.writeln(".bizhong18-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong18\'>");
document.writeln("	<div class=\'bizhong18-tit\'>弑神者（62103b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong18-box\'>");
document.writeln("    	<div class=\'bizhong18-l\'>");
document.writeln("        	<ul>");
document.writeln(" 	            <li>267期必中一尾：<font color=\'#FF0000\' size=\'4\'>4</font></li>");
document.writeln("            	<li>267期必中二尾：<font color=\'#FF0000\' size=\'4\'>4-5</font></li>");
document.writeln("            	<li>267期必中三尾：<font color=\'#FF0000\' size=\'4\'>4-5-9</font></li>");
document.writeln("            	<li>267期必中四尾：<font color=\'#FF0000\' size=\'4\'>4-5-9-1</font></li>");
document.writeln("            	<li>267期必中五尾：<font color=\'#FF0000\' size=\'4\'>4-5-9-1-2</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("    	<div class=\'bizhong18-r\'>");
document.writeln("        	<ul>");
document.writeln("                <li>必中三码：<font color=\'#FF0000\' size=\'4\'>04.34.44</font></li>");
document.writeln("            	<li>必中六码：<font color=\'#FF0000\' size=\'4\'>15.25.45</font></li>");
document.writeln("            	<li>必中九码：<font style=\'color:#FF0000\' size=\'4\'>19.29.49</font></li>");
document.writeln("            	<li>必中12码：<font style=\'color:#FF0000\' size=\'4\'>21.31.41</font></li>");
document.writeln("            	<li>必中15码：<font color=\'#FF0000\' size=\'4\'>02.32.42</font></li>");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong18-foot\'>267期一尾一码：<font color=\'#FF0000\' size=\'6\'>（34）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("");

document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong18\'>");
document.writeln("	<div class=\'bizhong18-tit\'>弑神者（62103b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong18-box\'>");
document.writeln("    	<div class=\'bizhong18-l\'>");
document.writeln("        	<ul>");
document.writeln(" 	            <li>265期必中一尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【5】</span></font></li>");
document.writeln("            	<li>265期必中二尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【5】</span>-9</font></li>");
document.writeln("            	<li>265期必中三尾：<font color=\'#FF0000\' size=\'4\'<span style=\'background-color: #FFFF00\'>【5】</span>-9-4</font></li>");
document.writeln("            	<li>265期必中四尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【5】</span>-9-4-0</font></li>");
document.writeln("            	<li>265期必中五尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【5】</span>-9-4-0-6</font></li>");
document.writeln(" </ul>");
document.writeln("        </div>");
document.writeln("    	<div class=\'bizhong18-r\'>");
document.writeln("        	<ul>");
document.writeln("                <li>必中三码：<font color=\'#FF0000\' size=\'4\'>05.<span style=\'background-color: #FFFF00\'>25</span>.45</font></li>");
document.writeln("            	<li>必中六码：<font color=\'#FF0000\' size=\'4\'>19.39.49</font></li>");
document.writeln("            	<li>必中九码：<font style=\'color:#FF0000\' size=\'4\'>04.24.44</font></li>");
document.writeln("            	<li>必中12码：<font style=\'color:#FF0000\' size=\'4\'>10.20.40</font></li>");
document.writeln("            	<li>必中15码：<font color=\'#FF0000\' size=\'4\'>16.26.46</font></li>");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong18-foot\'>265期一尾一码：<font color=\'#FF0000\' size=\'6\'><span style=\'background-color: #FFFF00\'>（25）</span></font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中end-->");
document.writeln("");