document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong22 { color: #000000; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #f5f5f5;}");
document.writeln(".bizhong22-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #f00;}");
document.writeln(".bizhong22-box { display: flex;}");
document.writeln(".bizhong22-box ul {}");
document.writeln(".bizhong22-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong22-box .bizhong22-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong22-box .bizhong22-r { width: 100%;}");
document.writeln(".bizhong22-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong22 { font-size: 16px;}");
document.writeln(".bizhong22-tit { font-size: 18px;}");
document.writeln(".bizhong22-box { display: block;}");
document.writeln(".bizhong22-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong22-box .bizhong22-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong22-box .bizhong22-r { width: 100%;}");
document.writeln(".bizhong22-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");
document.writeln("");
document.writeln("");

document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62827b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>249期必中三尾：<font color=\'#FF0000\' size=\'4\'>1-8-5</font></li>");
document.writeln("            	<li>249期必中五尾：<font color=\'#FF0000\' size=\'4\'>1-8-5-4-3</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'>01.31.41.08.28.38.15.25.45.14.34.44.03.13.23</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>01.31.41.08.28.38.15.25.45</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>249期一尾一码：<font color=\'#FF0000\' size=\'6\'>（01）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62827b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>247期必中三尾：<font color=\'#FF0000\' size=\'4\'>6-8-4</font></li>");
document.writeln("            	<li>247期必中五尾：<font color=\'#FF0000\' size=\'4\'>6-8-4-<span style=\'background-color: #FFFF00\'>【1】</span>-3</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'>06.26.36.08.18.28.04.34.44.21.<span style=\'background-color: #FFFF00\'>【31】</span>.41.03.23.33</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>06.26.36.08.18.28.04.34.44</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>247期一尾一码：<font color=\'#FF0000\' size=\'6\'>（06）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62827b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>246期必中三尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【5】</span>-2-7</font></li>");
document.writeln("            	<li>246期必中五尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【5】</span>-2-7-0-9</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'>05.<span style=\'background-color: #FFFF00\'>【15】</span>.35.22.32.42.07.27.47.10.20.30.29.39.49</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>05.<span style=\'background-color: #FFFF00\'>【15】</span>.35.22.32.42.07.27.47</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>246期一尾一码：<font color=\'#FF0000\' size=\'6\'>（05）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");
document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62827b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>244期必中三尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【3】</span>-1-6</font></li>");
document.writeln("            	<li>244期必中五尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【3】</span>-1-6-5-2</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【03】</span>.13.23.11.21.31.26.36.46.05.15.25.02.32.42</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【03】</span>.13.23.11.21.31.26.36.46</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>244期一尾一码：<font color=\'#FF0000\' size=\'6\'>（03）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");

document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62827b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>243期必中三尾：<font color=\'#FF0000\' size=\'4\'>0-7-2</font></li>");
document.writeln("            	<li>243期必中五尾：<font color=\'#FF0000\' size=\'4\'>0-7-2-6-<span style=\'background-color: #FFFF00\'>【1】</span></font></li>");

document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>243期一尾一码：<font color=\'#FF0000\' size=\'6\'>（10）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");




document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中end-->");