document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong22 { color: #000000; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #f5f5f5;}");
document.writeln(".bizhong22-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #f00;}");
document.writeln(".bizhong22-box { display: flex;}");
document.writeln(".bizhong22-box ul {}");
document.writeln(".bizhong22-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong22-box .bizhong22-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong22-box .bizhong22-r { width: 100%;}");
document.writeln(".bizhong22-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong22 { font-size: 16px;}");
document.writeln(".bizhong22-tit { font-size: 18px;}");
document.writeln(".bizhong22-box { display: block;}");
document.writeln(".bizhong22-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong22-box .bizhong22-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong22-box .bizhong22-r { width: 100%;}");
document.writeln(".bizhong22-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");
document.writeln("");

document.writeln("");
document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62109b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>102期必中三尾：<font color=\'#FF0000\' size=\'4\'>2-9-4</font></li>");
document.writeln("            	<li>102期必中五尾：<font color=\'#FF0000\' size=\'4\'>2-9-4-8-7</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'>02.12.32.29.39.49.04.14.34.28.38.48.07.17.27</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>02.12.32.29.39.49.04.14.34</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>102期一尾一码：<font color=\'#FF0000\' size=\'6\'>（02）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");


document.writeln("");
document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62109b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>100期必中三尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【7】</span>-5-1</font></li>");
document.writeln("            	<li>100期必中五尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【7】</span>-5-1-8-3</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'>07.<span style=\'background-color: #FFFF00\'>【17】</span>.37.15.25.35.11.21.31.08.18.38.13.23.33</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>07.<span style=\'background-color: #FFFF00\'>【17】</span>.37.15.25.35.11.21.31</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>100期一尾一码：<font color=\'#FF0000\' size=\'6\'>（07）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");


document.writeln("");
document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62109b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>098期必中三尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【6】</span>-9-1</font></li>");
document.writeln("            	<li>098期必中五尾：<font color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>【6】</span>-9-1-4-3</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'>16.36.<span style=\'background-color: #FFFF00\'>【46】</span>.09.19.29.11.21.31.04.14.44.03.13.23</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>16.36.<span style=\'background-color: #FFFF00\'>【46】</span>.09.19.29.11.21.31</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>098期一尾一码：<font color=\'#FF0000\' size=\'6\'>（16）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");


document.writeln("");
document.writeln("  <!--必中每期开始-->");
document.writeln("<div class=\'bizhong22\'>");
document.writeln("	<div class=\'bizhong22-tit\'>弑神者（62109b.com）15码中特</div>");
document.writeln("	<div class=\'bizhong22-box\'>");
document.writeln("    	<div class=\'bizhong22-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li>097期必中三尾：<font color=\'#FF0000\' size=\'4\'>4-5-6</font></li>");
document.writeln("            	<li>097期必中五尾：<font color=\'#FF0000\' size=\'4\'>4-5-6-<span style=\'background-color: #FFFF00\'>【0】</span>-1</font></li>");
document.writeln("                <li>必中15码：<font color=\'#FF0000\' size=\'4\'>04.14.24.15.25.45.26.36.46.<span style=\'background-color: #FFFF00\'>【10】</span>.20.30.21.31.41</font></li>");
document.writeln("            	<li>必中九码：<font color=\'#FF0000\' size=\'4\'>04.14.24.15.25.45.26.36.46</font></li>");
document.writeln("");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'bizhong22-foot\'>097期一尾一码：<font color=\'#FF0000\' size=\'6\'>（04）</font>单车变宝马~</div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期开始-->");




document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中end-->");