document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'zzhl-tit\' style=\'margin: 0px; padding: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;\'>");
document.writeln("	<img src=\'/images/fyb.jpg\' style=\'margin: 0px; padding: 0px; border: 0px; width: 100%; height: auto; vertical-align: middle;\'></div>");
document.writeln("<div class=\'zzhl\' style=\'margin: 0px; padding: 0px; font-size: 16px; line-height: 1.6; color: rgb(51, 51, 51); background: rgb(255, 255, 255); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;\'>");
document.writeln("	<ul style=\'margin: 0px; padding: 0px; list-style: none;\'>");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0022.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【四肖中特】</font>霸气骑手</div>");
document.writeln("		</a></li>");
document.writeln("		");
document.writeln("	<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0021.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【发财平特】</font>理财助手</div>");
document.writeln("		</a></li>");
document.writeln("");
document.writeln("	<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0020.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【五肖十码】</font>三前三后</div>");
document.writeln("		</a></li>");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("	<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0019.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【4.尾中特】</font>山村大汉</div>");
document.writeln("		</a></li>");
document.writeln("		");
document.writeln("");
document.writeln("	<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/xin02.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【五肖中特】</font>鬼破才</div>");
document.writeln("		</a></li>");
document.writeln("		");
document.writeln("");
document.writeln("	<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0017.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【㈠波防⒉码】</font>左面相爷</div>");
document.writeln("		</a></li>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("	<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0016.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【九肖中特】</font>师出长安</div>");
document.writeln("		</a></li>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0015.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【稳杀五码】</font>悟空嫖娼</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0014.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【八尾中特】</font>小马过河</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0013.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【绝杀一段】</font>长度三十</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0012.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【绝杀一肖】</font>全年无错</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0011.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【绝杀半波】</font>百进不出</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0010.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【绝杀一行】</font>求个妹子</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0009.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【稳杀10码】</font>红色肚兜</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0008.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【无错十肖】</font>肖中肖</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0007.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【绝杀一合】</font>稳打稳中</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0006.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【铁杀一肖】</font>一哥杀肖</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0005.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【杀1肖1尾】</font>富婆留步</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0004.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【稳杀5码】</font>胖哥来了</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0003.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【稳杀一头】</font>姐爱玩彩</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0002.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【绝杀半头】</font>长凌五代</div>");
document.writeln("		</a></li>");
document.writeln("		<li style=\'margin: 0px; padding: 0px; list-style: none; width: 360px; float: left; border-bottom: 1px solid rgb(238, 238, 238);\'>");
document.writeln("		<a target=\'_blank\' style=\'margin: 0px; padding: 10px; color: inherit; outline: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-decoration: none; display: block;\' href=\'/6dgsb/0001.html\'>");
document.writeln("		<div class=\'zzhl-img\' style=\'margin: 0px 8px 0px 0px; padding: 0px; float: left;\'>");
document.writeln("			<img src=\'/images/zhong.gif\' style=\'margin: 0px; padding: 0px; border: 0px; vertical-align: middle; width: 40px; height: 40px; border-radius: 50%;\'></div>");
document.writeln("		<div class=\'zzhl-txt1\' style=\'margin: 0px; padding: 0px;\'>");
document.writeln("			204期:<font color=\'#FF0000\' style=\'margin: 0px; padding: 0px; font-size: 16pt;\'>【乖禁一肖】</font>乖乖禁肖</div>");
document.writeln("		</a></li>");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("");
document.writeln("");