document.writeln("<table style=\'border-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>帅得流油</font><font color=\'#FFFFFF\'>『35组2中2』</font></font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center>");
document.writeln("			<strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("			<span style=font-family:楷体;color:#FF0000>10元一组本金350，中1组得700元，2组得1400元，3组2100元.（连本）</span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-size: 14pt\'>");
document.writeln("<span style=\'color: #00F;\'>190期</span>:<span style=\'color: #008000;\'>平特二肖拖一尾</span>〖<span style=\'color: #FF3300\'>中？组</span>〗</font></td></tr>");
document.writeln("");
document.writeln("  <tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-size: 14pt\'>");
document.writeln("");
document.writeln("鼠羊拖5尾<br>");
document.writeln("【04.16.28.40.09.21.33】<br>");
document.writeln("拖【05.15.25.35.45】<br><font color=\'#FF00FF\'>(本金350，收入？00)</font></font></td></tr>");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-size: 14pt\'>");
document.writeln("<span style=\'color: #00F;\'>188期</span>:<span style=\'color: #008000;\'>平特二肖拖一尾</span>〖<span style=\'color: #FF3300\'>中？组</span>〗</font></td></tr>");
document.writeln("");
document.writeln("  <tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-size: 14pt\'>");
document.writeln("");
document.writeln("猪牛拖6尾<br>");
document.writeln("【05.17.29.41.03.15.<span style=\'background-color: #FFFF00\'>27</span>.39】<br>");
document.writeln("拖【06.16.26.36.<span style=\'background-color: #FFFF00\'>46</span>】<br><font color=\'#FF00FF\'>(本金350，收入？00)</font></font></td></tr>");
document.writeln("");
document.writeln("<!--开始-->");

document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-size: 14pt\'>");
document.writeln("<span style=\'color: #00F;\'>187期</span>:<span style=\'color: #008000;\'>平特二肖拖一尾</span>〖<span style=\'color: #FF3300\'>中？组</span>〗</font></td></tr>");
document.writeln("");
document.writeln("  <tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font style=\'font-size: 14pt\'>");
document.writeln("");
document.writeln("马羊拖9尾<br>");
document.writeln("【10.22<span style=\'background-color: #FFFF00\'>.34</span>.46.21.33.45】<br>");
document.writeln("拖【09.<span style=\'background-color: #FFFF00\'>19</span>.29.39.49】<br><font color=\'#FF00FF\'>(本金350，收入？00)</font></font></td></tr>");
document.writeln("");
document.writeln("<!--开始-->");


document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("   ");