document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>多人来料【稳赚八肖】</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln("");
document.writeln(".ys114 {text-align: center;}");
document.writeln(".ys112 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'ys114\'>");
document.writeln("	");
document.writeln("<font color=\"#FFFFFF\">");
document.writeln("	");
document.writeln("<b><span style=\'background-color: #000000\'>大围是用来参考组合的，只要够稳！便是好料！<br>跑遍全网，集齐来料，仅供参考</span></b></font><strong><br>");
document.writeln(" ");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	</strong>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<b>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【家野四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");



document.writeln("220期家【羊马牛狗】野【蛇虎龙兔】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--家禽牛马羊鸡猪狗，野兽龙蛇猴虎鼠兔-->");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【单双四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");

document.writeln("217期单【龙猴<span style=\'background-color: #FFFF00\'>虎</span>狗】双【兔蛇羊猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("218期单【<span style=\'background-color: #FFFF00\'>龙</span>猴虎狗】双【兔蛇羊猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("219期单【鼠虎龙马】双【鸡猪蛇牛】<font color=\"#FF0000\">×</font><br>	");
document.writeln("220期单【鼠马猴龙】双【羊牛鸡兔】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--单数：龙虎狗马猴鼠，双数：蛇羊牛鸡兔猪-->");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【凶吉四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");
document.writeln("212期吉【羊兔马<span style=\'background-color: #FFFF00\'>龙</span>】凶【牛猴狗猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("213期吉【马<span style=\'background-color: #FFFF00\'>兔</span>蛇龙】凶【牛猴狗猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("214期吉【兔龙马鸡】凶【<span style=\'background-color: #FFFF00\'>猪</span>牛鼠狗】<font color=\"#FF0000\">√</font><br>	");
document.writeln("215期吉【<span style=\'background-color: #FFFF00\'>鸡</span>龙蛇马】凶【猴鼠牛虎】<font color=\"#FF0000\">√</font><br>	");
document.writeln("216期吉【羊马龙兔】凶【猪<span style=\'background-color: #FFFF00\'>虎</span>鼠狗】<font color=\"#FF0000\">√</font><br>	");
document.writeln("217期吉【蛇马鸡龙】凶【<span style=\'background-color: #FFFF00\'>虎</span>鼠狗猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("218期吉【兔蛇<span style=\'background-color: #FFFF00\'>龙</span>羊】凶【虎鼠牛狗】<font color=\"#FF0000\">√</font><br>	");
document.writeln("219期吉【羊鸡蛇马】凶【猪猴牛狗】<font color=\"#FF0000\">×</font><br>	");
document.writeln("219期吉【鸡羊蛇龙】凶【龙虎猴狗】<font color=\"#FF0000\">√</font><br>	");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--吉肖：龙蛇马羊鸡兔，凶肖：牛猪猴虎鼠狗-->");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【天地四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");

document.writeln("216期天【猪兔牛猴】地【<span style=\'background-color: #FFFF00\'>虎</span>蛇鸡羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("217期天【猴兔猪牛】地【鸡鼠狗蛇】<font color=\"#FF0000\">×</font><br>	");
document.writeln("218期天【<span style=\'background-color: #FFFF00\'>龙</span>牛兔马】地【狗鸡鼠羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("219期天【马猴龙牛】地【羊鸡鼠狗】<font color=\"#FF0000\">√</font><br>	");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--天肖：牛猪猴龙马兔，地肖：蛇羊鸡虎鼠狗-->");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【无错八肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");


document.writeln("208期【猪羊马蛇虎狗鼠<span style=\'background-color: #FFFF00\'>牛</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("209期【马鸡猪兔<span style=\'background-color: #FFFF00\'>猴</span>龙鼠蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("210期【马猴牛<span style=\'background-color: #FFFF00\'>狗</span>蛇虎猪兔】<font color=\"#FF0000\">√</font><br>	");
document.writeln("211期【蛇猴龙狗鼠<span style=\'background-color: #FFFF00\'>鸡</span>羊牛】<font color=\"#FF0000\">√</font><br>	");
document.writeln("212期【羊兔猴猪蛇虎<span style=\'background-color: #FFFF00\'>龙</span>狗】<font color=\"#FF0000\">√</font><br>	");
document.writeln("213期【鼠<span style=\'background-color: #FFFF00\'>兔</span>狗猪蛇虎猴马】<font color=\"#FF0000\">√</font><br>	");
document.writeln("214期【羊<span style=\'background-color: #FFFF00\'>猪</span>鼠猴虎马鸡蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("215期【羊龙兔牛狗猪<span style=\'background-color: #FFFF00\'>鸡</span>鼠】<font color=\"#FF0000\">√</font><br>	");
document.writeln("216期【兔龙羊狗鼠蛇猪猴】<font color=\"#FF0000\">×</font><br>	");
document.writeln("217期【狗羊猴兔猪蛇鸡<span style=\'background-color: #FFFF00\'>虎</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("218期【兔猴<span style=\'background-color: #FFFF00\'>龙</span>狗猪鸡马蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("219期【马牛龙蛇虎<span style=\'background-color: #FFFF00\'>兔</span>羊猴】<font color=\"#FF0000\">√</font><br>	");
document.writeln("220期【蛇猴羊虎龙牛猪鼠】<font color=\"#FF0000\">√</font><br>	");

document.writeln("	");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("	</div>");
document.writeln("	");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><font style=\'font-size: 16pt\'>");
document.writeln("				<strong>");
document.writeln("				<a target=\"_blank\" style=\"text-decoration: none\" href=\"https://xn--mdcx6gra7cc.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#62827\"><span style=font-family:楷体;color:#00f>更多好料请关注</span><font color=\'#FF0000\'><span style=font-family:楷体;font-size:17pt;>62827b.com</span></font></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("	");