document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>多人来料【稳赚八肖】</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln("");
document.writeln(".ys114 {text-align: center;}");
document.writeln(".ys112 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'ys114\'>");
document.writeln("	");
document.writeln("<font color=\"#FFFFFF\">");
document.writeln("	");
document.writeln("<b><span style=\'background-color: #000000\'>大围是用来参考组合的，只要够稳！便是好料！<br>跑遍全网，集齐来料，仅供参考</span></b></font><strong><br>");
document.writeln(" ");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	</strong>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<b>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【家野四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");


document.writeln("157期家【牛马猪羊】野【龙兔鼠虎】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--家禽牛马羊鸡猪狗，野兽龙蛇猴虎鼠兔-->");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【单双四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");
document.writeln("");
document.writeln("");



document.writeln("134期单【鼠虎猴<span style=\'background-color: #FFFF00\'>狗</span>】双【猪兔蛇牛】<font color=\"#FF0000\">√</font><br>	");
document.writeln("135期单【鼠虎猴狗】双【猪<span style=\'background-color: #FFFF00\'>羊</span>鸡牛】<font color=\"#FF0000\">√</font><br>	");
document.writeln("136期单【虎龙狗鼠】双【蛇<span style=\'background-color: #FFFF00\'>鸡</span>羊兔】<font color=\"#FF0000\">√</font><br>	");
document.writeln("137期单【狗猴马鼠】双【羊<span style=\'background-color: #FFFF00\'>牛</span>蛇鸡】<font color=\"#FF0000\">√</font><br>	");
document.writeln("138期单【马虎狗猴】双【<span style=\'background-color: #FFFF00\'>兔</span>鸡羊猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("139期单【虎鼠马猴】双【鸡<span style=\'background-color: #FFFF00\'>兔</span>羊猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("140期单【龙狗<span style=\'background-color: #FFFF00\'>马</span>虎】双【鸡猪羊兔】<font color=\"#FF0000\">√</font><br>	");
document.writeln("141期单【虎鼠马猴】双【猪鸡兔蛇】<font color=\"#FF0000\">×</font><br>	");
document.writeln("142期单【龙鼠<span style=\'background-color: #FFFF00\'>虎</span>狗】双【兔羊鸡蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("143期单【虎龙鼠狗】双【牛鸡<span style=\'background-color: #FFFF00\'>蛇</span>羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("144期单【狗虎猴鼠】双【鸡蛇<span style=\'background-color: #FFFF00\'>牛</span>羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("145期单【龙虎狗马】双【羊蛇<span style=\'background-color: #FFFF00\'>兔</span>猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("146期单【鼠虎龙马】双【羊兔牛猪】<font color=\"#FF0000\">×</font><br>	");
document.writeln("147期单【狗猴虎龙】双【蛇猪<span style=\'background-color: #FFFF00\'>兔</span>牛】<font color=\"#FF0000\">√</font><br>	");
document.writeln("148期单【鼠马<span style=\'background-color: #FFFF00\'>虎</span>龙】双【蛇兔猪羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("149期单【龙马虎狗】双【蛇猪鸡<span style=\'background-color: #FFFF00\'>羊</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("150期单【<span style=\'background-color: #FFFF00\'>猴</span>虎马狗】双【兔蛇羊猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("151期单【龙马猴鼠】双【兔牛<span style=\'background-color: #FFFF00\'>蛇</span>猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("152期单【狗鼠<span style=\'background-color: #FFFF00\'>猴</span>虎】双【牛羊兔猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("153期单【猴龙鼠狗】双【羊蛇牛猪】<font color=\"#FF0000\">×</font><br>	");
document.writeln("154期单【鼠猴马虎】双【<span style=\'background-color: #FFFF00\'>羊</span>鸡牛兔】<font color=\"#FF0000\">√</font><br>	");
document.writeln("155期单【鼠马虎龙】双【<span style=\'background-color: #FFFF00\'>鸡</span>猪牛蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("156期单【龙狗马虎】双【兔鸡羊<span style=\'background-color: #FFFF00\'>猪</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("157期单【鼠龙马狗】双【牛蛇羊兔】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--单数：龙虎狗马猴鼠，双数：蛇羊牛鸡兔猪-->");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【凶吉四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");

document.writeln("157期吉【羊马鸡龙】凶【猪虎猴狗】<font color=\"#FF0000\">√</font><br>	");

document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--吉肖：龙蛇马羊鸡兔，凶肖：牛猪猴虎鼠狗-->");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【天地四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");


document.writeln("153期天【龙马兔猴】地【蛇虎羊<span style=\'background-color: #FFFF00\'>鸡</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("154期天【牛龙猪兔】地【蛇鸡<span style=\'background-color: #FFFF00\'>羊</span>虎】<font color=\"#FF0000\">√</font><br>	");
document.writeln("155期天【牛猪马兔】地【<span style=\'background-color: #FFFF00\'>鸡</span>虎蛇鼠】<font color=\"#FF0000\">√</font><br>	");
document.writeln("156期天【龙<span style=\'background-color: #FFFF00\'>猪</span>猴兔】地【狗虎鸡羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("157期天【龙兔马猴】地【羊鸡鼠狗】<font color=\"#FF0000\">√</font><br>	");


document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--天肖：牛猪猴龙马兔，地肖：蛇羊鸡虎鼠狗-->");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【无错八肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");


document.writeln("142期【<span style=\'background-color: #FFFF00\'>虎</span>鼠鸡猴兔马狗蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("143期【<span style=\'background-color: #FFFF00\'>蛇</span>鼠虎兔狗猪猴羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("144期【猴兔<span style=\'background-color: #FFFF00\'>牛</span>鼠马虎蛇羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("145期【猪龙<span style=\'background-color: #FFFF00\'>兔</span>蛇鸡狗牛马】<font color=\"#FF0000\">√</font><br>	");
document.writeln("146期【兔猪鸡虎<span style=\'background-color: #FFFF00\'>狗</span>蛇牛猴】<font color=\"#FF0000\">√</font><br>	");
document.writeln("147期【虎鸡狗猴<span style=\'background-color: #FFFF00\'>兔</span>龙羊蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("148期【鸡牛马<span style=\'background-color: #FFFF00\'>虎</span>龙羊狗兔】<font color=\"#FF0000\">√</font><br>	");
document.writeln("149期【蛇兔猪<span style=\'background-color: #FFFF00\'>羊</span>猴龙狗虎】<font color=\"#FF0000\">√</font><br>	");
document.writeln("150期【猪羊狗蛇虎<span style=\'background-color: #FFFF00\'>猴</span>鸡鼠】<font color=\"#FF0000\">√</font><br>	");
document.writeln("151期【猴马牛狗羊猪兔龙】<font color=\"#FF0000\">×</font><br>	");
document.writeln("152期【狗兔鼠<span style=\'background-color: #FFFF00\'>猴</span>鸡羊猪马】<font color=\"#FF0000\">√</font><br>	");
document.writeln("153期【<span style=\'background-color: #FFFF00\'>鸡</span>牛蛇兔猴羊猪马】<font color=\"#FF0000\">√</font><br>	");
document.writeln("154期【龙牛鸡虎兔<span style=\'background-color: #FFFF00\'>羊</span>猴马】<font color=\"#FF0000\">√</font><br>	");
document.writeln("155期【猴牛虎猪<span style=\'background-color: #FFFF00\'>鸡</span>羊马鼠】<font color=\"#FF0000\">√</font><br>	");
document.writeln("156期【兔鼠狗猴虎蛇龙马】<font color=\"#FF0000\">×</font><br>	");
document.writeln("157期【兔虎猪鼠蛇龙羊猴】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("	</div>");
document.writeln("	");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><font style=\'font-size: 16pt\'>");
document.writeln("				<strong>");
document.writeln("				<a target=\"_blank\" style=\"text-decoration: none\" href=\"https://dierdier.www62635a.com:8443/#62635\"><span style=font-family:楷体;color:#00f>更多好料请关注</span><font color=\'#FF0000\'><span style=font-family:楷体;font-size:17pt;>62635b.com</span></font></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("	");