document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>多人来料【稳赚八肖】</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln("");
document.writeln(".ys114 {text-align: center;}");
document.writeln(".ys112 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'ys114\'>");
document.writeln("	");
document.writeln("<font color=\"#FFFFFF\">");
document.writeln("	");
document.writeln("<b><span style=\'background-color: #000000\'>大围是用来参考组合的，只要够稳！便是好料！<br>跑遍全网，集齐来料，仅供参考</span></b></font><strong><br>");
document.writeln(" ");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	</strong>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<b>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【家野四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");


document.writeln("193期家【狗猪马牛】野【龙鼠兔虎】<font color=\"#FF0000\">√</font><br>	");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--家禽牛马羊鸡猪狗，野兽龙蛇猴虎鼠兔-->");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【单双四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");
document.writeln("192期单【马鼠龙<span style=\'background-color: #FFFF00\'>狗</span>】双【猪鸡羊兔】<font color=\"#FF0000\">√</font><br>	");
document.writeln("193期单【马狗猴龙】双【鸡羊牛蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--单数：龙虎狗马猴鼠，双数：蛇羊牛鸡兔猪-->");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【凶吉四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");



document.writeln("193期吉【羊马蛇龙】凶【猪虎鼠猴】<font color=\"#FF0000\">√</font><br>	");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--吉肖：龙蛇马羊鸡兔，凶肖：牛猪猴虎鼠狗-->");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【天地四肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");


document.writeln("184期天【<span style=\'background-color: #FFFF00\'>猪</span>牛猴龙】地【狗蛇鸡虎】<font color=\"#FF0000\">√</font><br>	");
document.writeln("185期天【牛猴<span style=\'background-color: #FFFF00\'>猪</span>兔】地【鸡羊狗虎】<font color=\"#FF0000\">√</font><br>	");
document.writeln("186期天【马牛猴兔】地【虎蛇<span style=\'background-color: #FFFF00\'>鼠</span>狗】<font color=\"#FF0000\">√</font><br>	");
document.writeln("187期天【龙猴兔马】地【羊蛇狗鼠】<font color=\"#FF0000\">×</font><br>	");
document.writeln("188期天【龙猴马牛】地【虎鸡<span style=\'background-color: #FFFF00\'>羊</span>鸡】<font color=\"#FF0000\">√</font><br>	");
document.writeln("189期天【猪兔牛猴】地【鸡<span style=\'background-color: #FFFF00\'>狗</span>蛇羊】<font color=\"#FF0000\">√</font><br>	");
document.writeln("190期天【牛猪兔马】地【鸡虎<span style=\'background-color: #FFFF00\'>鼠</span>蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("191期天【兔龙猪牛】地【<span style=\'background-color: #FFFF00\'>虎</span>鼠狗蛇】<font color=\"#FF0000\">√</font><br>	");
document.writeln("192期天【龙猪牛兔】地【蛇虎羊<span style=\'background-color: #FFFF00\'>狗</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("193期天【猪牛兔猴】地【蛇狗羊虎】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--天肖：牛猪猴龙马兔，地肖：蛇羊鸡虎鼠狗-->");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【无错八肖】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");

document.writeln("183期【猪羊猴马<span style=\'background-color: #FFFF00\'>龙</span>狗蛇牛】<font color=\"#FF0000\">√</font><br>	");
document.writeln("184期【<span style=\'background-color: #FFFF00\'>猪</span>虎牛蛇马兔狗猴】<font color=\"#FF0000\">√</font><br>	");
document.writeln("185期【龙狗鼠虎鸡马羊牛】<font color=\"#FF0000\">×</font><br>	");
document.writeln("186期【<span style=\'background-color: #FFFF00\'>鼠</span>牛鸡蛇马狗羊猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("187期【马兔<span style=\'background-color: #FFFF00\'>虎</span>蛇鼠狗鸡龙】<font color=\"#FF0000\">√</font><br>	");
document.writeln("188期【鸡猪兔虎龙牛蛇猴】<font color=\"#FF0000\">×</font><br>	");
document.writeln("189期【鸡猪兔猴<span style=\'background-color: #FFFF00\'>狗</span>鼠牛马】<font color=\"#FF0000\">√</font><br>	");
document.writeln("190期【<span style=\'background-color: #FFFF00\'>鼠</span>牛马虎羊蛇龙猪】<font color=\"#FF0000\">√</font><br>	");
document.writeln("191期【<span style=\'background-color: #FFFF00\'>虎</span>猴牛鼠马羊鸡龙】<font color=\"#FF0000\">√</font><br>	");
document.writeln("192期【猪虎龙兔鼠<span style=\'background-color: #FFFF00\'>狗</span>羊牛】<font color=\"#FF0000\">√</font><br>	");
document.writeln("193期【狗猪马兔羊龙鸡鼠】<font color=\"#FF0000\">√</font><br>	");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("	</div>");
document.writeln("	");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><font style=\'font-size: 16pt\'>");
document.writeln("				<strong>");
document.writeln("				<a target=\"_blank\" style=\"text-decoration: none\" href=\"https://xn--mdcx6gra7cc.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#62827\"><span style=font-family:楷体;color:#00f>更多好料请关注</span><font color=\'#FF0000\'><span style=font-family:楷体;font-size:17pt;>62827b.com</span></font></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("	");