document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『九肖九码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong5 { color: #00ff00; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #000;}");
document.writeln(".bizhong5-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #f00;}");
document.writeln(".bizhong5-box { display: flex;}");
document.writeln(".bizhong5-box ul {}");
document.writeln(".bizhong5-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong5-box .bizhong5-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong5-box .bizhong5-r { width: 100%;}");
document.writeln(".bizhong5-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong5 { font-size: 16px;}");
document.writeln(".bizhong5-tit { font-size: 18px;}");
document.writeln(".bizhong5-box { display: block;}");
document.writeln(".bizhong5-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong5-box .bizhong5-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong5-box .bizhong5-r { width: 100%;}");
document.writeln(".bizhong5-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");
document.writeln("");


document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>148期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>马鼠兔牛狗蛇龙羊鸡</font></li>");
document.writeln("            	<li><font size=\'3\'>148期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>马鼠兔牛狗蛇龙</font></li>");
document.writeln("            	<li><font size=\'3\'>148期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>马鼠兔牛狗</font></li>");
document.writeln("            	<li><font size=\'2\'>148期必中18码：</font><font size=\'2\' color=\'#FF0000\'>23.47.05.41.02.14.04.40.31.43.12.36.25.37.22.46.08.20</span></font></li>");
document.writeln("             	<li><font size=\'2\'>148期必中九码：</font><font size=\'2\' color=\'#FF0000\'>23.41.14.04.43.12.37.22.20</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>148期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>马23</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>147期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>鼠蛇羊<span style=\'background-color: #FFFF00\'>【兔】</span>马虎牛猴狗</font></li>");
document.writeln("            	<li><font size=\'3\'>147期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>鼠蛇羊<span style=\'background-color: #FFFF00\'>【兔】</span>马虎牛</font></li>");
document.writeln("            	<li><font size=\'3\'>147期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>鼠蛇羊<span style=\'background-color: #FFFF00\'>【兔】</span>马</font></li>");
document.writeln("            	<li><font size=\'2\'>147期必中18码：</font><font size=\'2\' color=\'#FF0000\'>05.17.24.36.22.34.<span style=\'background-color: #FFFF00\'>【02】</span>.14.11.23.15.27.16.28.21.33.19.43</span></font></li>");
document.writeln("             	<li><font size=\'2\'>147期必中九码：</font><font size=\'2\' color=\'#FF0000\'>05.24.34.14.23.27.28.33.19</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>147期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>鼠05</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>146期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>猪猴牛兔鼠鸡龙马<span style=\'background-color: #FFFF00\'>【狗】</span></font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>146期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猪06</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>145期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>虎<span style=\'background-color: #FFFF00\'>【兔】</span>鼠鸡猪龙狗蛇羊</font></li>");
document.writeln("            	<li><font size=\'3\'>145期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>虎<span style=\'background-color: #FFFF00\'>【兔】</span>鼠鸡猪龙狗</font></li>");
document.writeln("            	<li><font size=\'3\'>145期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>虎<span style=\'background-color: #FFFF00\'>【兔】</span>鼠鸡猪</font></li>");
document.writeln("            	<li><font size=\'2\'>145期必中18码：</font><font size=\'2\' color=\'#FF0000\'>15.27.<span style=\'background-color: #FFFF00\'>【02】</span>.14.29.41.20.32.30.42.13.49.19.31.12.36.22.34</span></font></li>");
document.writeln("             	<li><font size=\'2\'>145期必中九码：</font><font size=\'2\' color=\'#FF0000\'>15.<span style=\'background-color: #FFFF00\'>【02】</span>.29.32.42.13.31.12.22</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>145期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>虎15</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>144期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>猴羊狗鼠鸡马<span style=\'background-color: #FFFF00\'>【牛】</span>兔龙</font></li>");
document.writeln("            	<li><font size=\'3\'>144期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>猴羊狗鼠鸡马<span style=\'background-color: #FFFF00\'>【牛】</span></font></li>");
document.writeln("            	<li><font size=\'3\'>144期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>猴羊狗鼠鸡</font></li>");
document.writeln("            	<li><font size=\'2\'>144期必中18码：</font><font size=\'2\' color=\'#FF0000\'>09.45.10.22.07.31.17.41.20.32.11.23.04.<span style=\'background-color: #FFFF00\'>【16】</span>.02.38.13.37</span></font></li>");
document.writeln("             	<li><font size=\'2\'>144期必中九码：</font><font size=\'2\' color=\'#FF0000\'>09.22.31.41.20.11.<span style=\'background-color: #FFFF00\'>【16】</span>.38.13</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>144期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猴09</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>143期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>猪猴龙鸡狗<span style=\'background-color: #FFFF00\'>【蛇】</span>马虎兔</font></li>");
document.writeln("            	<li><font size=\'3\'>143期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>猪猴龙鸡狗<span style=\'background-color: #FFFF00\'>【蛇】</span>马</font></li>");
document.writeln("            	<li><font size=\'3\'>143期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>猪猴龙鸡狗</font></li>");
document.writeln("            	<li><font size=\'2\'>143期必中18码：</font><font size=\'2\' color=\'#FF0000\'>06.30.21.33.13.25.08.20.31.43.<span style=\'background-color: #FFFF00\'>【12】</span>.36.11.23.03.15.14.38</span></font></li>");
document.writeln("             	<li><font size=\'2\'>143期必中九码：</font><font size=\'2\' color=\'#FF0000\'>06.21.13.08.31.<span style=\'background-color: #FFFF00\'>【12】</span>.11.03.14</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>143期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猪06</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>142期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>猴羊鼠牛鸡兔猪蛇<span style=\'background-color: #FFFF00\'>【虎】</span></font></li>");

document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>142期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猴09</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong5\'>");
document.writeln("	<div class=\'bizhong5-tit\'>澳门资料网（62635a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong5-box\'>");
document.writeln("    	<div class=\'bizhong5-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>141期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>虎马羊<span style=\'background-color: #FFFF00\'>【狗】</span>猴牛蛇猪鸡</font></li>");
document.writeln("            	<li><font size=\'3\'>141期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>虎马羊<span style=\'background-color: #FFFF00\'>【狗】</span>猴牛蛇</font></li>");
document.writeln("            	<li><font size=\'3\'>141期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>虎马羊<span style=\'background-color: #FFFF00\'>【狗】</span>猴</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong5-foot\'><font color=\'#00FFFF\'>141期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>虎03</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");