document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『九肖九码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong2 { color: #00ff00; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #000;}");
document.writeln(".bizhong2-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #f00;}");
document.writeln(".bizhong2-box { display: flex;}");
document.writeln(".bizhong2-box ul {}");
document.writeln(".bizhong2-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong2-box .bizhong2-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong2-box .bizhong2-r { width: 100%;}");
document.writeln(".bizhong2-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong2 { font-size: 16px;}");
document.writeln(".bizhong2-tit { font-size: 18px;}");
document.writeln(".bizhong2-box { display: block;}");
document.writeln(".bizhong2-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong2-box .bizhong2-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong2-box .bizhong2-r { width: 100%;}");
document.writeln(".bizhong2-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");


document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62103a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>282期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>马龙猴虎猪蛇羊鸡牛</font></li>");
document.writeln("            	<li><font size=\'3\'>282期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>马龙猴虎猪蛇羊</font></li>");
document.writeln("            	<li><font size=\'3\'>282期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>马龙猴虎猪</font></li>");
document.writeln("            	<li><font size=\'2\'>282期必中18码：</font><font size=\'2\' color=\'#FF0000\'>10.46.12.36.32.44.26.38.29.41.23.47.09.21.31.43.03.15</span></font></li>");
document.writeln("             	<li><font size=\'2\'>282期必中九码：</font><font size=\'2\' color=\'#FF0000\'>10.36.32.38.29.23.09.31.03</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>282期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>马10</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62103a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>281期必中九肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【鼠】</span>牛兔羊蛇狗龙马鸡</font></li>");
document.writeln("            	<li><font size=\'3\'>281期必中七肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【鼠】</span>牛兔羊蛇狗龙</font></li>");
document.writeln("            	<li><font size=\'3\'>281期必中五肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【鼠】</span>牛兔羊蛇</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>281期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>鼠04</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");


document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62103a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>280期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>兔<span style=\'background-color: #FFFF00\'>【马】</span>龙牛鼠狗虎猴猪</font></li>");
document.writeln("            	<li><font size=\'3\'>280期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>兔<span style=\'background-color: #FFFF00\'>【马】</span>龙牛鼠狗虎</font></li>");
document.writeln("            	<li><font size=\'3\'>280期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>兔<span style=\'background-color: #FFFF00\'>【马】</span>龙牛鼠</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>280期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>兔13</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62103a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>279期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>牛羊狗鼠猪兔<span style=\'background-color: #FFFF00\'>【马】</span>蛇猴</font></li>");
document.writeln("            	<li><font size=\'3\'>279期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>牛羊狗鼠猪兔<span style=\'background-color: #FFFF00\'>【马】</span></font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>279期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>牛03</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62103a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>278期必中九肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【牛】</span>猴龙虎羊马鼠蛇鸡</font></li>");
document.writeln("            	<li><font size=\'3\'>278期必中七肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【牛】</span>猴龙虎羊马鼠</font></li>");
document.writeln("            	<li><font size=\'3\'>278期必中五肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【牛】</span>猴龙虎羊</font></li>");
document.writeln("            	<li><font size=\'2\'>278期必中18码：</font><font size=\'2\' color=\'#FF0000\'>15.<span style=\'background-color: #FFFF00\'>【39】</span>.08.20.24.36.02.38.21.33.10.34.16.28.23.47.31.43</span></font></li>");
document.writeln("             	<li><font size=\'2\'>278期必中九码：</font><font size=\'2\' color=\'#FF0000\'>15.20.24.38.21.34.16.23.31</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>278期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>牛15</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62103a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>277期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>龙猪<span style=\'background-color: #FFFF00\'>【狗】</span>蛇鸡猴马鼠兔</font></li>");
document.writeln("            	<li><font size=\'3\'>277期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>龙猪<span style=\'background-color: #FFFF00\'>【狗】</span>蛇鸡猴马</font></li>");
document.writeln("            	<li><font size=\'3\'>277期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>龙猪<span style=\'background-color: #FFFF00\'>【狗】</span>蛇鸡</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>277期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>龙12</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62103a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>276期必中九肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>鸡虎羊马狗猪龙鼠</font></li>");
document.writeln("            	<li><font size=\'3\'>276期必中七肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>鸡虎羊马狗猪</font></li>");
document.writeln("            	<li><font size=\'3\'>276期必中五肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>鸡虎羊马</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>276期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猴20</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");




document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388tz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("");

