document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『九肖九码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln(".bizhong2 { color: #00ff00; font-size: 18px; font-weight: bold; border: solid 1px #7d7d7d; background: #000;}");
document.writeln(".bizhong2-tit { padding: 5px 0; color: #ff0; font-size: 24px; text-align: center; border-bottom: solid 1px #7d7d7d; background: #f00;}");
document.writeln(".bizhong2-box { display: flex;}");
document.writeln(".bizhong2-box ul {}");
document.writeln(".bizhong2-box ul li { padding: 5px 0; padding-left: 10px; border-bottom: solid 1px #7d7d7d;}");
document.writeln(".bizhong2-box .bizhong2-l { width: 100%; border-right: solid 1px #7d7d7d; box-sizing: border-box;}");
document.writeln(".bizhong2-box .bizhong2-r { width: 100%;}");
document.writeln(".bizhong2-foot { padding: 5px 0; font-size: 24px; text-align: center;}");
document.writeln("@media screen and (max-width:800px) {");
document.writeln(".bizhong2 { font-size: 16px;}");
document.writeln(".bizhong2-tit { font-size: 18px;}");
document.writeln(".bizhong2-box { display: block;}");
document.writeln(".bizhong2-box ul li { padding: 5px 0; padding-left: 6px;}");
document.writeln(".bizhong2-box .bizhong2-l { width: 100%; border-right: 0;}");
document.writeln(".bizhong2-box .bizhong2-r { width: 100%;}");
document.writeln(".bizhong2-foot { font-size: 18px;}");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<!--必中start-->");
document.writeln("<div class=\'box\'>");


document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>304期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>蛇狗鸡猪虎兔鼠羊猴</font></li>");
document.writeln("            	<li><font size=\'3\'>304期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>蛇狗鸡猪虎兔鼠</font></li>");
document.writeln("            	<li><font size=\'3\'>304期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>蛇狗鸡猪虎</font></li>");
document.writeln("            	<li><font size=\'2\'>304期必中18码：</font><font size=\'2\' color=\'#FF0000\'>11.23.30.42.31.43.05.41.02.38.13.49.16.28.21.33.08.32</span></font></li>");
document.writeln("             	<li><font size=\'2\'>304期必中九码：</font><font size=\'2\' color=\'#FF0000\'>11.30.31.05.02.13.16.21.32</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>304期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>蛇11</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>303期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>猴狗龙猪鼠兔羊马<span style=\'background-color: #FFFF00\'>【牛】</span></font></li>");
document.writeln("            	<li><font size=\'3\'>303期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>猴狗龙猪鼠兔羊</font></li>");
document.writeln("            	<li><font size=\'3\'>303期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>猴狗龙猪鼠</font></li>");
document.writeln("            	<li><font size=\'2\'>303期必中18码：</font><font size=\'2\' color=\'#FF0000\'>08.20.30.42.12.48.05.41.16.40.13.25.21.33.34.46.<span style=\'background-color: #FFFF00\'>【15】</span>.39</span></font></li>");
document.writeln("             	<li><font size=\'2\'>303期必中九码：</font><font size=\'2\' color=\'#FF0000\'>08.32.12.41.16.25.21.46.<span style=\'background-color: #FFFF00\'>15</span></span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>303期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猴08</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>302期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>蛇马兔鼠<span style=\'background-color: #FFFF00\'>【猴】</span>鸡羊猪虎</font></li>");
document.writeln("            	<li><font size=\'3\'>302期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>蛇马兔鼠<span style=\'background-color: #FFFF00\'>【猴】</span>鸡羊</font></li>");
document.writeln("            	<li><font size=\'3\'>302期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>蛇马兔鼠<span style=\'background-color: #FFFF00\'>【猴】</span></font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>302期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>蛇11</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>301期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>鼠猪虎狗龙蛇<span style=\'background-color: #FFFF00\'>【兔】</span>马猴</font></li>");
document.writeln("            	<li><font size=\'3\'>301期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>鼠猪虎狗龙蛇<span style=\'background-color: #FFFF00\'>【兔】</span></font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>301期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>鸡31</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>300期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>鸡蛇马猴羊狗兔猪<span style=\'background-color: #FFFF00\'>【龙】</span></font></li>");
document.writeln("            	<li><font size=\'3\'>300期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>鸡蛇马猴羊狗兔</font></li>");
document.writeln("            	<li><font size=\'3\'>300期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>鸡蛇马猴羊</font></li>");
document.writeln("            	<li><font size=\'2\'>300期必中18码：</font><font size=\'2\' color=\'#FF0000\'>31.43.11.47.10.22.08.20.21.33.06.30.13.49.05.41.<span style=\'background-color: #FFFF00\'>【36】</span>.48</span></font></li>");
document.writeln("             	<li><font size=\'2\'>300期必中九码：</font><font size=\'2\' color=\'#FF0000\'>31.11.10.08.21.30.13.41.<span style=\'background-color: #FFFF00\'>【36】</span></span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>300期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>鸡31</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");

document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>298期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>羊狗马蛇<span style=\'background-color: #FFFF00\'>【猴】</span>鸡猪龙鼠</font></li>");
document.writeln("            	<li><font size=\'3\'>298期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>羊狗马蛇<span style=\'background-color: #FFFF00\'>【猴】</span>鸡猪</font></li>");
document.writeln("            	<li><font size=\'3\'>298期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>羊狗马蛇<span style=\'background-color: #FFFF00\'>【猴】</span></font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>298期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>羊21</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");





document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>296期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>鸡龙蛇</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>狗牛马兔猪</font></li>");
document.writeln("            	<li><font size=\'3\'>296期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>鸡龙蛇</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>狗牛马</font></li>");
document.writeln("            	<li><font size=\'3\'>296期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>鸡龙蛇</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>狗</font></li>");
document.writeln("            	<li><font size=\'2\'>296期必中18码：</font><font size=\'2\' color=\'#FF0000\'>19.31.12.36.11.47.08.</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【20】</span>.30.42.03.15.22.46.13.49.05.41</span></font></li>");
document.writeln("             	<li><font size=\'2\'>296期必中九码：</font><font size=\'2\' color=\'#FF0000\'>19.36.11.</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【20】</span>.32.15.22.49.41</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>296期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>19</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");



document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>295期必中九肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>鸡牛鼠龙猪兔蛇狗</font></li>");
document.writeln("            	<li><font size=\'3\'>295期必中七肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>鸡牛鼠龙猪兔</font></li>");
document.writeln("            	<li><font size=\'3\'>295期必中五肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【猴】</span>鸡牛鼠龙</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>295期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猴08</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>294期必中九肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【蛇】</span>兔狗牛龙鼠马猴猪</font></li>");
document.writeln("            	<li><font size=\'3\'>294期必中七肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【蛇】</span>兔狗牛龙鼠马</font></li>");
document.writeln("            	<li><font size=\'3\'>294期必中五肖：</font><font size=\'3\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>【蛇】</span>兔狗牛龙</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>294期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>蛇11</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>293期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>猪<span style=\'background-color: #FFFF00\'>【猴】</span>羊狗蛇牛虎鼠马</font></li>");
document.writeln("            	<li><font size=\'3\'>293期必中七肖：</font><font size=\'3\' color=\'#FF0000\'>猪<span style=\'background-color: #FFFF00\'>【猴】</span>羊狗蛇牛虎</font></li>");
document.writeln("            	<li><font size=\'3\'>293期必中五肖：</font><font size=\'3\' color=\'#FF0000\'>猪<span style=\'background-color: #FFFF00\'>【猴】</span>羊狗蛇</font></li>");
document.writeln("            	<li><font size=\'2\'>293期必中18码：</font><font size=\'2\' color=\'#FF0000\'>05.17.<span style=\'background-color: #FFFF00\'>【20】</span>.44.21.33.30.42.11.47.03.39.14.38.28.40.10.46</span></font></li>");
document.writeln("             	<li><font size=\'2\'>293期必中九码：</font><font size=\'2\' color=\'#FF0000\'>05.<span style=\'background-color: #FFFF00\'>【20】</span>.21.42.11.39.14.28.46</span></font></li>");
document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>293期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>猪05</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");
document.writeln("<!--必中每期开始-->");
document.writeln("<div class=\'bizhong2\'>");
document.writeln("	<div class=\'bizhong2-tit\'>澳门资料网（62361a.com）九肖九码</div>");
document.writeln("	<div class=\'bizhong2-box\'>");
document.writeln("    	<div class=\'bizhong2-l\'>");
document.writeln("        	<ul>");
document.writeln("            	<li><font size=\'3\'>291期必中九肖：</font><font size=\'3\' color=\'#FF0000\'>牛鸡鼠猪兔狗马<span style=\'background-color: #FFFF00\'>【龙】</span> 蛇</font></li>");

document.writeln("");
document.writeln("            	");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("      <div class=\'bizhong2-foot\'><font color=\'#00FFFF\'>291期一肖一码：</font><font color=\'#FFFF00\'>（<font color=\'#FFFF00\'>牛15</font>）</font><font color=\'#00FF00\'></font></div>");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--必中每期结束-->");




document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388tz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("");

