document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--紧急通知start-->");
document.writeln("<div class=\'white-box\'>");
document.writeln("<style>");
document.writeln(".jrtzao{ cursor: pointer; padding: 10px 0; border: solid 12px #ff0000; background: #fff; font-family: \'微软雅黑\';font-size: 13pt; text-align: center; color: #000;font-weight: 700;text-align: center;}");
document.writeln(".jrtzao .jrtzao-tit { font-size: 19pt; color: #22ac38;}");
document.writeln(".jrtzao .jrtzao-box { padding: 5px 0 8px 0; font-weight: normal;}");
document.writeln(".jrtzao .jrtzao-box font { color: #f00;  font-weight: bold;}");
document.writeln(".jrtzao .jrtzao-btn { display: inline-block; margin: 0 auto; color: #fff; padding: 5px 20px; border-radius: 5px; background: #2a2a2b;}");
document.writeln(".jrtzao:hover .jrtzao-btn { background: #f00;}");
document.writeln("</style>");
document.writeln("<div class=\'jrtzao\'>");
document.writeln("    <div class=\'jrtzao-tit\'><font color=\'#000000\' style=\'font-size: 21pt\'>");
document.writeln("		<span style=\'background-color: #FFFF00\'>★今日推荐271期★★</span></font></div>");
document.writeln("    <div class=\'jrtzao-box\'>");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\'_blank\' href=\'https://guhjgvf.www53923a.com/#jrtj \'>");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/dingjian.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>百万高手【稳赚九码】<br>【49中40！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><a target=\'_blank\' href=\'https://www.39895a.com/AMgsb/208.htm\'></font></a><br><br />");
document.writeln("<!--结束-->	");
document.writeln("					");
document.writeln("		");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\'_blank\' href=\'https://asdfrgtqd.www68729c.com:888/#jrtj \'>");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/dingjian.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>澳利澳【稳赚18码】<br>【100中89！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><a target=\'_blank\' href=\'https://www.39895a.com/AMgsb/208.htm\'></font></a><br><br />");
document.writeln("<!--结束-->	");
document.writeln("					");
document.writeln("");
document.writeln("");
document.writeln("					");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\'_blank\' href=\'https://vdfsdf.www72965b.com:888/#62jrtg\'>");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/dingjian.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>六合专家【平特一肖】<br>【10中09！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><a target=\'_blank\' href=\'https://www.39895a.com/AMgsb/208.htm\'></font></a><br><br />");
document.writeln("<!--结束-->	");
document.writeln("			");
document.writeln("	");
document.writeln("					");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\'_blank\' href=\'https://fhfgdgdfg.www96289c.com:8443/#62jrtg\'>");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/dingjian.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>小龙女网【爆庄一肖】<br>【22中21！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><a target=\'_blank\' href=\'https://www.39895a.com/AMgsb/208.htm\'></font></a><br><br />");
document.writeln("<!--结束-->	");
document.writeln("							");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\"_blank\" href=\"https://gfffffd.www63713c.com:8443/gsb/36.html\">");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/dingjian.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>刻苦铭心【一波中特】<br>【07中07！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><a target=\'_blank\' href=\'https://www.39895a.com/AMgsb/208.htm\'></font></a><br><br />");
document.writeln("<!--结束-->	");
document.writeln("			");
document.writeln("		");
document.writeln("					");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\"_blank\" href=\"https://asdqweq.www82693b.com:888/tie/111.html\">");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/niubi.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>冷暖自知【家野中特】<br>【10中09！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><br><br />");
document.writeln("<!--结束-->											");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("					");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\'_blank\' href=\'https://fgffrra.www28397a.com:8443/gsb/z71.html\'>");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/dingjian.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>静听年华【⒊肖⒉码】<br>【08中07！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><a target=\'_blank\' href=\'https://www.39895a.com/AMgsb/208.htm\'></font></a><br><br />");
document.writeln("<!--结束-->	");
document.writeln("					");
document.writeln("	");
document.writeln("					");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\"_blank\" href=\"https://thtttr.www29591c.com:8443/gsb/0037.html\">");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/dingjian.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>榴莲牛奶【四肖中特】<br>【09中09稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><a target=\'_blank\' href=\'https://www.39895a.com/AMgsb/208.htm\'></font></a><br><br />");
document.writeln("<!--结束-->	");
document.writeln("					");
document.writeln("			");
document.writeln("									");
document.writeln("");
document.writeln("		");
document.writeln("					");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\"_blank\" href=\"https://fgrtfbb.www61985a.com:8443/gsb/36.html\">");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/niubi.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>哈雷彗星〖四肖中特〗<br>【07中07！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><br><br />");
document.writeln("<!--结束-->											");
document.writeln("	");
document.writeln("					");
document.writeln("<!--开始-->");
document.writeln("<font color=\'#6600CC\'>");
document.writeln("<a target=\"_blank\" href=\"https://tututuu.www62102.com:888/gsb/074.html\">");
document.writeln("<span style=\'text-decoration: none\' font color=\'#c20deff2\'>	");
document.writeln("		<img border=\'0\' src=\'https://www.49896b.com/images/niubi.png\'  style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>鲜哥胡蝶〖波色八码〗<br>【09中08！稳赚】<font color=\'#FF00FF\'>点击查看</font></b></span></a></font><br><br />");
document.writeln("<!--结束-->											");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("				");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--结束-->	");
document.writeln("<font color=\'#000000\' style=\'font-size: 15pt\'>");
document.writeln("		<font color=\'#FFFF00\'><img border=\'0\' src=\'https://www.49896b.com/images/mashen.png\' style=\'width:73px; height:28px\' style=\'margin: 0px; padding: 0px; outline: 0px; word-wrap: break-word; border: 0px; vertical-align: middle;\'>本期推荐</font><span style=\'background-color: #FFFF00\'><font color=\'#000000\' size=\'4\'>【后肖】</font></span><br>");
document.writeln("	【平特龙12.36】</font><font color=\'#000000\' style=\'font-size: 15pt\'></span></font></font><br><br> ");
document.writeln("");
document.writeln("   ");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table id=table3 border=0 width=100% cellspacing=0 cellpadding=0 bgcolor=#ff0000 height=\'150\'><tbody>");
document.writeln("<tr><td style=\'border:10px double #ff0\';background=\'rad\' align=center height=\'250\' bgcolor=\'#000000\'>");
document.writeln("	<strong><span style=font-family:方正粗黑宋简体;font-size:16pt;color:#ff0>");
document.writeln("	<a target=\'_blank\' href=\'https://tututuu.www62102.com:888/#ty353563\'>");
document.writeln("	<span style=\'text-decoration: none\'><font color=\'#FFFF00\'>澳门资料网</font><font color=\'#FF0000\'>62103b.com</font><font color=\'#FFFF00\'>论坛的<br>正确打开方式:<br>①手动输入全网址:<br></font><font color=\'#FF0000\'>http://www.62103b.com</font><font color=\'#FFFF00\'><br>②打开后等待一分钟加载完成<br>③再进行论坛浏览<br>就不会有论坛卡顿评论区白屏情况</font><font color=\'#FF0000\'><br>点击这里<img src=\'https://www.123966b.com/images/zu.gif\' style=\'width:32px; height:21px\' >进入查看</font></span></a></span></strong></table>  ");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" ");