document.writeln("<table border=\'0\' width=\'100%\' bgcolor=\'#ffffff\'><tbody>");
document.writeln("<td style=\'border:1px double #000080\' bgcolor=\'#000080\' height=\'30\'><p align=center>");
document.writeln("<b><font face=\'楷体\' size=\'6\' color=\'#FF00FF\'>p.29863.com</font><font face=\'楷体\' style=\'font-size: 22pt\' color=\'#00FFFF\'></font><font color=\'#FFFFFF\' face=\'楷体\' size=\'5\'>（九肖十八码）</font></b></tr></td></table>");
document.writeln("");





document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#FFFF00\' width=\'98%\' height=\'35\'>");
document.writeln("		<p>");
document.writeln("		<span style=\'font-weight:700\'><strong> 220期澳门雷锋心水网【<font color=\'#FF0000\' size=\'5\'>9肖18码</font>】p.29863.com</strong></span></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>18码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 9pt\'>10.46.06.42.05.17.02.26.28.40.13.37.32.44.21.33.07.19</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>12码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 10pt\'>10.46.06.42.05.17.02.26.28.40.13.37</span></b></td>");
document.writeln("    </tr>");
document.writeln("        	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>06码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 10pt\'>10.46.06.42.05.17</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>二肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>猴鼠</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>四肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>猴鼠牛龙</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>七肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>猴鼠牛龙虎蛇狗</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>九肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>猴鼠牛龙虎蛇狗鸡猪</b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");





document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#FFFF00\' width=\'98%\' height=\'35\'>");
document.writeln("		<p>");
document.writeln("		<span style=\'font-weight:700\'><strong> 219期澳门雷锋心水网【<font color=\'#FF0000\' size=\'5\'>9肖18码</font>】p.29863.com</strong></span></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>18码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 9pt\'><span style=\'background-color: #FFFF00\'>09</span>.33.10.22.32.44.12.48.02.38.11.35.05.29.04.28.13.25</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>12码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 10pt\'><span style=\'background-color: #FFFF00\'>09</span>.33.10.22.32.44.12.48.02.38.11.35</span></b></td>");
document.writeln("    </tr>");
document.writeln("        	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>06码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 10pt\'><span style=\'background-color: #FFFF00\'>09</span>.33.10.22.32.44</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>二肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'background-color: #FFFF00\'>鸡</span>猴</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>四肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'background-color: #FFFF00\'>鸡</span>猴狗马</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>七肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'background-color: #FFFF00\'>鸡</span>猴狗马龙羊牛</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>九肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'background-color: #FFFF00\'>鸡</span>猴狗马龙羊牛虎蛇</b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");





document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#FFFF00\' width=\'98%\' height=\'35\'>");
document.writeln("		<p>");
document.writeln("		<span style=\'font-weight:700\'><strong> 217期澳门雷锋心水网【<font color=\'#FF0000\' size=\'5\'>9肖18码</font>】p.29863.com</strong></span></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>四肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>虎鼠<span style=\'background-color: #FFFF00\'>猴</span>龙</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>七肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>虎鼠<span style=\'background-color: #FFFF00\'>猴</span>龙牛马鸡</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>九肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>虎鼠<span style=\'background-color: #FFFF00\'>猴</span>龙牛马鸡兔狗</b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");




document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table border=\'1\' width=\'100%\'>");
document.writeln("    <tbody>");
document.writeln("    <tr>");
document.writeln("        <td colspan=\'2\' align=\'center\' bgcolor=\'#FFFF00\' width=\'98%\' height=\'35\'>");
document.writeln("		<p>");
document.writeln("		<span style=\'font-weight:700\'><strong> 216期澳门雷锋心水网【<font color=\'#FF0000\' size=\'5\'>9肖18码</font>】p.29863.com</strong></span></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>18码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 9pt\'>08.20.03.15.12.24.11.<span style=\'background-color: #FFFF00\'>23</span>.04.16.05.17.22.34.30.42.13.25</span></b></td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>12码</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b><span style=\'font-size: 10pt\'>08.20.03.15.12.24.11.<span style=\'background-color: #FFFF00\'>23</span>.04.16.05.17</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>四肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>狗兔马<span style=\'background-color: #FFFF00\'>羊</span></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>七肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>狗兔马<span style=\'background-color: #FFFF00\'>羊</span>虎牛猴</b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("        <td align=\'center\' width=\'17%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<span style=\'font-size: 10pt; font-weight: 700\'>九肖</span></td>");
document.writeln("		<td align=\'left\' width=\'65%\' height=\'35\' bgcolor=\'#FFFFFF\'>");
document.writeln("		<b>狗兔马<span style=\'background-color: #FFFF00\'>羊</span>虎牛猴鼠蛇</b></td>");
document.writeln("    </tr>");
document.writeln("    </tbody> ");
document.writeln("</table>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.w