document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>搬运哥</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『统计高手资料』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.manolotron.com:49\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>49图库<font color=\'#FF0000\'>49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                   <b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font style=\"font-size: 15pt\">");
document.writeln("		");
document.writeln("");



document.writeln("                   <font color=\'#0000FF\'>（070期）</font><Br>");
document.writeln("		特肖【兔鼠鸡猴<span style=\'background-color: #FFFF00\'>猪</span>马】<br> 	<br>	");

document.writeln("                   <font color=\'#0000FF\'>（071期）</font><Br>");
document.writeln("		特肖【羊牛蛇狗<span style=\'background-color: #FFFF00\'>虎</span>兔】<br> 	<br>	");

document.writeln("                   <font color=\'#0000FF\'>（073期）</font><Br>");
document.writeln("		特肖【虎马狗龙<span style=\'background-color: #FFFF00\'>羊</span>鸡】<br> 	<br>	");

document.writeln("                   <font color=\'#0000FF\'>（074期）</font><Br>");
document.writeln("		特肖【羊猴猪鼠<span style=\'background-color: #FFFF00\'>牛</span>龙】<br> 	<br>	");

document.writeln("                   <font color=\'#0000FF\'>（076期）</font><Br>");
document.writeln("		特肖【狗鸡虎<span style=\'background-color: #FFFF00\'>鼠</span>猴马】<br> 	<br>	");

document.writeln("                   <font color=\'#0000FF\'>（077期）</font><Br>");
document.writeln("		特肖【马鼠猴猪牛鸡】<br> 	<br>	");

document.writeln("		</font>	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					<span style=\"font-size: 15pt\">	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<br>");
document.writeln("");
document.writeln("");
document.writeln("					</span>");
document.writeln("");
document.writeln("");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 15pt\">【码友初心】</font><span style=\"font-size: 15pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					</span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font style=\"font-size: 15pt\"><br>	");

document.writeln("		063期必中平特【马+<span style=\'background-color: #FFFF00\'>狗</span>】√<br>	");
document.writeln("		064期必中平特【<span style=\'background-color: #FFFF00\'>兔+牛</span>】√<br>	");
document.writeln("		065期必中平特【羊+<span style=\'background-color: #FFFF00\'>猴</span>】√<br>	");
document.writeln("		066期必中平特【<span style=\'background-color: #FFFF00\'>狗</span>+猴】√<br>	");
document.writeln("		067期必中平特【<span style=\'background-color: #FFFF00\'>鸡</span>+猴】√<br>	");
document.writeln("		068期必中平特【<span style=\'background-color: #FFFF00\'>猪</span>+狗】√<br>	");

document.writeln("		070期必中平特【马+<span style=\'background-color: #FFFF00\'>猪</span>】√<br>	");
document.writeln("		071期必中平特【<span style=\'background-color: #FFFF00\'>鼠</span>+羊】√<br>	");
document.writeln("		072期必中平特【<span style=\'background-color: #FFFF00\'>狗</span>+鼠】√<br>	");
document.writeln("		073期必中平特【<span style=\'background-color: #FFFF00\'>狗+羊</span>】√<br>	");
document.writeln("		074期必中平特【虎+<span style=\'background-color: #FFFF00\'>狗</span>】√<br>	");

document.writeln("		076期必中平特【龙+<span style=\'background-color: #FFFF00\'>猪</span>】√<br>	");
document.writeln("		077期必中平特【马+羊】√<br>	");
document.writeln("			</font>	");
document.writeln("					<span style=\"font-size: 15pt\">	");
document.writeln("			<br>");
document.writeln("		");
document.writeln("");
document.writeln("					</span>");
document.writeln("		");
document.writeln("");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 15pt\">【码友心云】</font><span style=\"font-size: 15pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					</span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font style=\"font-size: 15pt\"><br>	");
document.writeln("");



document.writeln("		076期杀【06.07.35.41.08.31.34】√<br>");
document.writeln("");
document.writeln("			</font>	");
document.writeln("<br>");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("			</span>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    ");
document.writeln("     </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("      <!--结束--> ");
document.writeln("    ");
document.writeln("      ");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>");
document.writeln("            ");
document.writeln("");
document.writeln("<b>");
document.writeln("            ");
document.writeln("");
document.writeln("<span style=\'font-size: 14pt\'>");
document.writeln("            ");
document.writeln("");
document.writeln("<br></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友七郎】	</font>	");
document.writeln("<font style=\'font-size: 14pt\'>	<br>	");
    
document.writeln("		077期（红肖）√<br>			");  
document.writeln("");
document.writeln("   ");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("             <span style=\'font-size: 14pt\'>");
document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("");
document.writeln("<br></font><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友六彩道友】</font><font style=\'font-size: 14pt\'><br>	");

document.writeln("		072期【<span style=\'background-color: #FFFF00\'>9</span>567尾】√<br>				");
document.writeln("		073期【91<span style=\'background-color: #FFFF00\'>4</span>7尾】√<br>				");
document.writeln("		074期【574<span style=\'background-color: #FFFF00\'>6</span>尾】√<br>				");
document.writeln("		075期【0912尾】×<br>				");
document.writeln("		076期【4961尾】×<br>				");
document.writeln("		077期【0615尾】√<br>				");
document.writeln("");
document.writeln("				");
document.writeln("		</font></b><font size=\'4\'><br>		");
document.writeln("		");
document.writeln("		             <br></font></span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </ul></td> </tr>");
document.writeln("        </div>");
document.writeln("  ");
document.writeln("		        <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("             <b>");
document.writeln("             <br></font></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友巧儿】</font><font style=\'font-size: 14pt\'><br>");
document.writeln("		");
document.writeln("");


document.writeln("		071期（1.<span style=\'background-color: #FFFF00\'>0</span>头）√<br>	");
document.writeln("		072期（4.<span style=\'background-color: #FFFF00\'>1</span>头）√<br>	");
document.writeln("		073期（<span style=\'background-color: #FFFF00\'>3</span>.2头）√<br>	");
document.writeln("		074期（0.3头）×<br>	");
document.writeln("		075期（0.<span style=\'background-color: #FFFF00\'>1</span>头）√<br>	");
document.writeln("		076期（<span style=\'background-color: #FFFF00\'>1</span>.4头）√<br>	");
document.writeln("		077期（1.3头）√<br>	");
document.writeln("		");
document.writeln("		");
document.writeln("		</font><span style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("");
document.writeln("				<font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友财迷】</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");

document.writeln("		065期<span style=\'background-color: #FFFF00\'>蓝波</span>+绿双<br>	");
document.writeln("		066期<span style=\'background-color: #FFFF00\'>蓝波</span>+红单<br>	");
document.writeln("		067期<span style=\'background-color: #FFFF00\'>红波</span>+绿双<br>	");
document.writeln("		068期<span style=\'background-color: #FFFF00\'>蓝波</span>+红单<br>	");
document.writeln("		069期蓝波+<span style=\'background-color: #FFFF00\'>红双</span><br>	");
document.writeln("		070期红波+蓝单<br>	");
document.writeln("		071期<span style=\'background-color: #FFFF00\'>蓝波</span>+绿双<br>	");
document.writeln("		072期蓝波+绿单<br>	");
document.writeln("		073期绿波+<span style=\'background-color: #FFFF00\'>红双</span><br>	");
document.writeln("		074期<span style=\'background-color: #FFFF00\'>绿波</span>+蓝双<br>	");
document.writeln("		075期<span style=\'background-color: #FFFF00\'>绿波</span>+蓝单<br>	");
document.writeln("		076期红波+蓝双<br>	");
document.writeln("		077期蓝波+绿单<br>	");
document.writeln("		");
document.writeln("		    ");
document.writeln("	    </b>	");
document.writeln("		");
document.writeln("				</font><br>		");
document.writeln("			");
document.writeln("			</td>		");
document.writeln("    </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("<body>");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>           ");
document.writeln("<b>            ");
document.writeln("<span style=\'font-size: 14pt\'>           ");
document.writeln("<br></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友一夜春风】	</font>	");
document.writeln("<font style=\'font-size: 14pt\'>	<br>	");
document.writeln("");



document.writeln("		067期杀龙马√<br>");
document.writeln("		068期杀猪兔√<br>");
document.writeln("		069期杀虎马√<br>");
document.writeln("		070期杀蛇鼠√<br>");
document.writeln("		071期杀狗鼠√<br>");
document.writeln("		072期杀兔猴√<br>");
document.writeln("		073期杀猴狗√<br>");
document.writeln("		074期杀虎马√<br>");
document.writeln("		075期杀猴鼠√<br>");
document.writeln("		076期杀马狗√<br>");
document.writeln("		077期杀兔虎√<br>");
document.writeln("		");
document.writeln("			 ");
document.writeln(" <span style=\'font-size: 14pt\'>");
document.writeln("<br></font><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友书阳】</font><font style=\'font-size: 14pt\'><br>	");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("		073期杀绿双√<br>");
document.writeln("		074期杀蓝单√<br>");
document.writeln("		075期杀红双√<br>");
document.writeln("		076期杀红单√<br>");
document.writeln("		077期杀红双√<br>");


document.writeln("						");
document.writeln("		</font></b><font size=\'4\'><br>		");
document.writeln(" <br></font></span>");
document.writeln(" </ul></td> </tr>");
document.writeln("");
document.writeln("<td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>  ");
document.writeln("<b>");
document.writeln(" <br></font></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友老阿姨】</font><font style=\'font-size: 14pt\'><br>");
document.writeln("");



document.writeln("		060期杀1头单√<br>	");
document.writeln("		061期杀0头双√<br>	");
document.writeln("		062期杀4头双√<br>	");
document.writeln("		063期杀2头单√<br>	");
document.writeln("		064期杀3头双√<br>	");
document.writeln("		065期杀0头单√<br>	");
document.writeln("		066期杀1头双√<br>	");
document.writeln("		067期杀4头单√<br>	");
document.writeln("		068期杀3头双√<br>	");
document.writeln("		069期杀2头单√<br>	");
document.writeln("		070期杀2头双√<br>	");
document.writeln("		071期杀3头双√<br>	");
document.writeln("		072期杀1头双√<br>	");
document.writeln("		073期杀4头单√<br>	");
document.writeln("		074期杀0头单√<br>	");
document.writeln("		075期杀4头双√<br>	");
document.writeln("		076期杀0头单√<br>	");
document.writeln("		077期杀3头双√<br>	");

document.writeln("						");
document.writeln("		</font><br>		");
document.writeln("		");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友左耳】</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("");

document.writeln("		077期杀5.9尾√<br>");
document.writeln("		");
document.writeln("");
document.writeln("			    ");
document.writeln("	    </b><br>	");
document.writeln("		");
document.writeln("				</font><br>		");
document.writeln("		</td>			");
document.writeln("  </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("<!-- 结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!-- 网址推广 -->");
document.writeln(" <tr>");
document.writeln(" <td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>    ");
document.writeln("  ");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td>");
document.writeln("	<p align=\'center\'><b><font size=\'4\' color=\'#FF0000\'>");
document.writeln("	<a target=\'_blank\' href=\'https://popopo.www21689a.com:888/#112\'>");
document.writeln("	<span style=\'text-decoration: none\'>");
document.writeln("	<img style=\'height: 34px; width:32px\' src=\'https://popopo.www21689a.com:888/images/t01acb3648e0bce6d10.gif\'></span></a></font><a target=\'_blank\' href=\'https://popopo.www21689a.com:888/#112\'><font size=\'4\' color=\'#0000FF\'><span style=\'text-decoration: none\'>金牌</span></font><span style=\'text-decoration: none\'><font color=\'#FF0000\' style=\'font-size: 20pt\'>谜</font><font color=\'#008000\' style=\'font-size: 20pt\'>语</font><font size=\'4\' color=\'#0000FF\'>网：</font><font size=\'6\' color=\'#FF0000\'>2</font><font color=\'#FF0000\' style=\'font-size: 23pt\'>1</font><font color=\'#FF0000\' style=\'font-size: 22pt\'>6</font><font color=\'#008000\' style=\'font-size: 20pt\'>8</font><font color=\'#008000\' style=\'font-size: 19pt\'>9</font></span><font size=\'4\' color=\'#0000FF\'><span style=\'text-decoration: none\'>.com</span></font></a></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("  </table>");
document.writeln("<!--  网址推广 -->");
document.writeln(" ");
document.writeln("  </div>");