document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>搬运哥</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『统计高手资料』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                   <b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font style=\"font-size: 15pt\">");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("                   <font color=\'#0000FF\'>（180期）</font><Br>");
document.writeln("		特肖【羊兔鸡龙蛇虎】<br> 	<br>	");
document.writeln("");

document.writeln("		</font>	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					<span style=\"font-size: 15pt\">	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<br>");
document.writeln("");
document.writeln("");
document.writeln("					</span>");
document.writeln("");
document.writeln("");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 15pt\">【码友初心】</font><span style=\"font-size: 15pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					</span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font style=\"font-size: 15pt\"><br>	");
document.writeln("");

document.writeln("		173期必中平特【<span style=\'background-color: #FFFF00\'>龙+鼠</span>】√<br>	");
document.writeln("		174期必中平特【<span style=\'background-color: #FFFF00\'>蛇</span>+猪】√<br>	");
document.writeln("		175期必中平特【<span style=\'background-color: #FFFF00\'>龙+兔</span>】√<br>	");
document.writeln("		176期必中平特【<span style=\'background-color: #FFFF00\'>蛇+龙</span>】√<br>	");
document.writeln("		177期必中平特【<span style=\'background-color: #FFFF00\'>龙</span>+虎】√<br>	");
document.writeln("		180期必中平特【马+虎】√<br>	");

document.writeln("");
document.writeln("			</font>	");
document.writeln("					<span style=\"font-size: 15pt\">	");
document.writeln("			<br>");
document.writeln("		");
document.writeln("");
document.writeln("					</span>");
document.writeln("		");
document.writeln("");
document.writeln("				<font color=\'#FF0000\' style=\"font-size: 15pt\">【码友心云】</font><span style=\"font-size: 15pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					</span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font style=\"font-size: 15pt\"><br>	");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("		173期杀【31.39.28.22.21.15.33】√<br>");
document.writeln("		174期杀【17.18.30.38.25.07.14】√<br>");
document.writeln("		175期杀【39.22.19.43.07.41.38】√<br>");
document.writeln("		176期杀【02.14.46.43.28.17.35】√<br>");
document.writeln("		177期杀【19.17.05.25.43.15.40】√<br>");
document.writeln("		178期杀【17.36.01.04.29.38.22】√<br>");
document.writeln("		179期杀【01.12.31.47.17.49.44】×<br>");
document.writeln("		180期杀【05.35.36.26.32.37.07】√<br>");

document.writeln("");
document.writeln("			</font>	");
document.writeln("<br>");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("			</span>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    ");
document.writeln("     </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("      <!--结束--> ");
document.writeln("    ");
document.writeln("      ");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>");
document.writeln("            ");
document.writeln("");
document.writeln("<b>");
document.writeln("            ");
document.writeln("");
document.writeln("<span style=\'font-size: 14pt\'>");
document.writeln("            ");
document.writeln("");
document.writeln("<br></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友七郎】	</font>	");
document.writeln("<font style=\'font-size: 14pt\'>	<br>	");
document.writeln("");
document.writeln("		171期<span style=\'background-color: #FFFF00\'>（绿肖）</span>√<br>			");
document.writeln("		172期<span style=\'background-color: #FFFF00\'>（红肖）</span>√<br>			");
document.writeln("		173期<span style=\'background-color: #FFFF00\'>（绿肖</span>）√<br>			");
document.writeln("		174期（绿肖）×<br>			");
document.writeln("		175期（红肖）×<br>			");
document.writeln("		176期<span style=\'background-color: #FFFF00\'>（蓝肖）</span>√<br>			");
document.writeln("		177期（绿肖）×<br>			");
document.writeln("		178期<span style=\'background-color: #FFFF00\'>（红肖）</span>√<br>			");
document.writeln("		180期（绿肖）×<br>			");
document.writeln("		180期（蓝肖）√<br>			");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("             <span style=\'font-size: 14pt\'>");
document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("");
document.writeln("<br></font><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友六彩道友】</font><font style=\'font-size: 14pt\'><br>	");
document.writeln("");


document.writeln("		177期【8<span style=\'background-color: #FFFF00\'>1</span>54尾】√<br>				");
document.writeln("		178期【<span style=\'background-color: #FFFF00\'>0</span>345尾】√<br>				");
document.writeln("		179期【<span style=\'background-color: #FFFF00\'>1</span>930尾】√<br>				");
document.writeln("		180期【1625尾】√<br>				");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("				");
document.writeln("		</font></b><font size=\'4\'><br>		");
document.writeln("		");
document.writeln("		             <br></font></span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </ul></td> </tr>");
document.writeln("        </div>");
document.writeln("  ");
document.writeln("		        <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("             <b>");
document.writeln("             <br></font></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友巧儿】</font><font style=\'font-size: 14pt\'><br>");
document.writeln("		");

document.writeln("		178期（3.<span style=\'background-color: #FFFF00\'>2</span>头）√<br>	");
document.writeln("		179期（1.<span style=\'background-color: #FFFF00\'>0</span>头）√<br>	");
document.writeln("		180期（1.2头）√<br>	");
document.writeln("");
document.writeln("		");
document.writeln("		");
document.writeln("		</font><span style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("");
document.writeln("				<font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友财迷】</font></span></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");
document.writeln("");

document.writeln("		164期蓝波+<span style=\'background-color: #FFFF00\'>绿双</span><br>");
document.writeln("		165期红波+<span style=\'background-color: #FFFF00\'>蓝单</span><br>");
document.writeln("		166期蓝波+<span style=\'background-color: #FFFF00\'>绿双</span><br>");
document.writeln("		167期<span style=\'background-color: #FFFF00\'>蓝波</span>+红单<br>");
document.writeln("		168期<span style=\'background-color: #FFFF00\'>蓝波</span>+红双<br>");
document.writeln("		169期绿波+<span style=\'background-color: #FFFF00\'>红单</span><br>");
document.writeln("		170期红波+绿双<br>");
document.writeln("		171期蓝波+红单<br>");
document.writeln("		172期红波+<span style=\'background-color: #FFFF00\'>绿双</span><br>");
document.writeln("		173期<span style=\'background-color: #FFFF00\'>绿波</span>+红单<br>");
document.writeln("		174期<span style=\'background-color: #FFFF00\'>蓝波</span>+绿双<br>");
document.writeln("		175期蓝波+红单<br>");
document.writeln("		176期绿波+红波<br>");
document.writeln("		177期<span style=\'background-color: #FFFF00\'>绿波</span>+蓝双<br>");
document.writeln("		178期红波+蓝单<br>");
document.writeln("		179期<span style=\'background-color: #FFFF00\'>红波</span>+蓝双<br>");
document.writeln("		180期绿波+红单<br>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		</b></font></td>		");
document.writeln("    </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("<body>");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>           ");
document.writeln("<b>            ");
document.writeln("<span style=\'font-size: 14pt\'>           ");
document.writeln("<br></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友一夜春风】	</font>	");
document.writeln("<font style=\'font-size: 14pt\'>	<br>	");
document.writeln("");
document.writeln("");

document.writeln("		174期杀龙猪√<br>");
document.writeln("		175期杀鸡虎√<br>");
document.writeln("		176期杀马龙√<br>");
document.writeln("		177期杀虎鸡√<br>");
document.writeln("		178期杀鸡狗×<br>");
document.writeln("		179期杀蛇牛√<br>");
document.writeln("		180期杀马鼠√<br>");

document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("			 ");
document.writeln(" <span style=\'font-size: 14pt\'>");
document.writeln("<br></font><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友书阳】</font><font style=\'font-size: 14pt\'><br>	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");


document.writeln("		173期杀红单√<br>");
document.writeln("		174期杀蓝单√<br>");
document.writeln("		175期杀绿双√<br>");
document.writeln("		176期杀红双√<br>");
document.writeln("		177期杀蓝单√<br>");
document.writeln("		178期杀绿双√<br>");
document.writeln("		179期杀蓝双√<br>");
document.writeln("		180期杀蓝单√<br>");


document.writeln("		</font></b><font size=\'4\'><br>		");
document.writeln(" <br></font></span>");
document.writeln(" </ul></td> </tr>");
document.writeln("");
document.writeln("<td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>  ");
document.writeln("<b>");
document.writeln(" <br></font></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友老阿姨】</font><font style=\'font-size: 14pt\'><br>");
document.writeln("");
document.writeln("");

document.writeln("		174期杀0头双√<br>	");
document.writeln("		175期杀1头双√<br>	");
document.writeln("		176期杀3头双√<br>	");
document.writeln("		177期杀4头单√<br>	");
document.writeln("		178期杀2头双×<br>	");
document.writeln("		179期杀1头双√<br>	");
document.writeln("		180期杀4头单√<br>	");

document.writeln("");
document.writeln("");
document.writeln("	</font><br>		");
document.writeln("		");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友左耳】</font></b><font style=\'font-size: 14pt\'><b><br>");

document.writeln("		178期杀9.6尾√<br>");
document.writeln("		179期杀6.0尾√<br>");
document.writeln("		180期杀7.8尾√<br>");

document.writeln("");
document.writeln("	    </b><br>	");
document.writeln("		");
document.writeln("				</font><br>		");
document.writeln("		</td>			");
document.writeln("  </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("<!-- 结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!-- 网址推广 -->");
document.writeln(" <tr>");
document.writeln(" <td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>    ");
document.writeln("  ");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td>");
document.writeln("	<p align=\'center\'><b><font size=\'4\' color=\'#FF0000\'>");
document.writeln("	<a target=\'_blank\' href=\'https://dss77.www73289b.com:8443/#112\'>");
document.writeln("	<span style=\'text-decoration: none\'>");
document.writeln("	<img style=\'height: 34px; width:32px\' src=\'https://dss77.www73289b.com:8443/images/t01acb3648e0bce6d10.gif\'></span></a></font><a target=\'_blank\' href=\'https://dss77.www73289b.com:8443/#112\'><font size=\'4\' color=\'#0000FF\'><span style=\'text-decoration: none\'>金牌</span></font><span style=\'text-decoration: none\'><font color=\'#FF0000\' style=\'font-size: 20pt\'>谜</font><font color=\'#008000\' style=\'font-size: 20pt\'>语</font><font size=\'4\' color=\'#0000FF\'>网：</font><font size=\'6\' color=\'#FF0000\'>2</font><font color=\'#FF0000\' style=\'font-size: 23pt\'>1</font><font color=\'#FF0000\' style=\'font-size: 22pt\'>6</font><font color=\'#008000\' style=\'font-size: 20pt\'>8</font><font color=\'#008000\' style=\'font-size: 19pt\'>9</font></span><font size=\'4\' color=\'#0000FF\'><span style=\'text-decoration: none\'>.com</span></font></a></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("  </table>");
document.writeln("<!--  网址推广 -->");
document.writeln(" ");
document.writeln("  </div>");