document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>搬运哥</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『统计高手资料』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>49图库<font color=\'#FF0000\'>49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                   <b>");
document.writeln("		");
document.writeln("");

document.writeln("");
document.writeln("                   <font color=\'#0000FF\'>（210期）</font></b><Br>");
document.writeln("		<b>特肖【蛇<span style=\'background-color: #FFFF00\'>鸡</span>马猪鼠虎】<br>		");
document.writeln("		<br>");
document.writeln("");
document.writeln("                   <font color=\'#0000FF\'>（211期）</font></b><Br>");
document.writeln("		<b>特肖【兔蛇鸡狗马牛】<br>		");
document.writeln("		<br>");
document.writeln("");
document.writeln("");
document.writeln("				<font size=\'5\' color=\'#FF0000\'>【码友初心】</font><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		209期必中平特【猪+<span style=\'background-color: #FFFF00\'>鼠</span>】√<br>");
document.writeln("		210期必中平特【鼠+<span style=\'background-color: #FFFF00\'>鸡</span>】√<br>	");
document.writeln("		211期必中平特【鸡+狗】√<br>	");
document.writeln("			<br>");
document.writeln("		");
document.writeln("");
document.writeln("				<font size=\'5\' color=\'#FF0000\'>【码友心云】</font><br>");
document.writeln("		208期杀【35.48.17.20.04.11.44】√<br>	");
document.writeln("		209期杀【46.12.11.48.35.18.38】√<br>");
document.writeln("		210期杀【34.43.48.47.06.44.01】√<br>");
document.writeln("		211期杀【06.04.44.30.41.32.25】√<br>");
document.writeln("	");
document.writeln("");
document.writeln("		换了跟踪高手，以下都是长跟高手，以前记录就不上了，重在未来<br>	");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("			</span>");
document.writeln("		</b></font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    ");
document.writeln("     </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("      <!--结束--> ");
document.writeln("    ");
document.writeln("      ");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>");
document.writeln("            ");
document.writeln("");
document.writeln("<b>");
document.writeln("            ");
document.writeln("");
document.writeln("<span style=\'font-size: 14pt\'>");
document.writeln("            ");
document.writeln("");
document.writeln("<br></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友七郎】	</font>	");
document.writeln("<font style=\'font-size: 14pt\'>	<br>	");
document.writeln("");
document.writeln("");
document.writeln("		209期红蓝绿肖（红肖）√<br>			");
document.writeln("		211期红蓝绿肖（绿肖）√<br>			");
document.writeln("");
document.writeln("   ");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("             <span style=\'font-size: 14pt\'>");
document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("");
document.writeln("<br></font><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友六彩道友】</font><font style=\'font-size: 14pt\'><br>	");
document.writeln("");
document.writeln("		210期单双四尾【13<span style=\'background-color: #FFFF00\'>7</span>5尾】√<br>				");
document.writeln("		211期单双四尾【3579尾】√<br>				");
document.writeln("");
document.writeln("				");
document.writeln("		</font></b><font size=\'4\'><br>		");
document.writeln("		");
document.writeln("		             <br></font></span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          </ul></td> </tr>");
document.writeln("        </div>");
document.writeln("  ");
document.writeln("		        <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("             <b>");
document.writeln("             <br></font></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友巧儿】</font><font style=\'font-size: 14pt\'><br>");
document.writeln("		");
document.writeln("		209期巧儿二头（3.4头）开40√<br>	");
document.writeln("		210期巧儿二头（2.0头）开07√<br>	");
document.writeln("		211期巧儿二头（1.0头）开00√<br>	");
document.writeln("		");
document.writeln("		");
document.writeln("		</font><span style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("");
document.writeln("				<font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友财迷】</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");
document.writeln("		209期财迷1.波（红波+绿单）开红40√<br>	");
document.writeln("		211期财迷1.波（绿波+蓝单）开？00√<br>	");
document.writeln("		");
document.writeln("		    ");
document.writeln("	    </b><br>	");
document.writeln("		");
document.writeln("				</font><br>		");
document.writeln("			");
document.writeln("			</td>		");
document.writeln("    </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("<body>");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("          <ul style=\'margin-left:5px;padding-left:0px;\'>           ");
document.writeln("<b>            ");
document.writeln("<span style=\'font-size: 14pt\'>           ");
document.writeln("<br></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友一夜春风】	</font>	");
document.writeln("<font style=\'font-size: 14pt\'>	<br>	");
document.writeln("");

document.writeln("		211期杀鸡马√<br>");
document.writeln("		");
document.writeln("			 ");
document.writeln(" <span style=\'font-size: 14pt\'>");
document.writeln("<br></font><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友书阳】</font><font style=\'font-size: 14pt\'><br>	");
document.writeln("");
document.writeln("");
document.writeln("				");
document.writeln("		208期杀蓝单√<br>");
document.writeln("		209期杀蓝双√<br>");
document.writeln("		210期杀绿单√<br>");
document.writeln("		211期杀红单√<br>");
document.writeln("		");
document.writeln("						");
document.writeln("		</font></b><font size=\'4\'><br>		");
document.writeln(" <br></font></span>");
document.writeln(" </ul></td> </tr>");
document.writeln("");
document.writeln("<td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>  ");
document.writeln("<b>");
document.writeln(" <br></font></span><font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友老阿姨】</font><font style=\'font-size: 14pt\'><br>");
document.writeln("		206期杀2头双√<br>			");
document.writeln("		207期杀0头单√<br>			");
document.writeln("		208期杀4头双√<br>	");
document.writeln("		209期杀0头单√<br>	");
document.writeln("		210期杀4头单√<br>	");
document.writeln("		211期杀2头双√<br>	");
document.writeln("						");
document.writeln("		</font><br>		");
document.writeln("		");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\'font-size: 14pt\'>【码友左耳】</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		206期杀9.5尾√<br>			    ");
document.writeln("		207期杀3.5尾√<br>			    ");
document.writeln("		208期杀6.5尾√<br>");
document.writeln("		209期杀9.2尾√<br>");
document.writeln("		210期杀1.8尾√<br>");
document.writeln("		211期杀5.8尾√<br>");
document.writeln("		");
document.writeln("");
document.writeln("			    ");
document.writeln("	    </b><br>	");
document.writeln("		");
document.writeln("				</font><br>		");
document.writeln("		</td>			");
document.writeln("  </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("<!-- 结束 -->");
document.writeln("");
document.writeln("");
document.writeln("<!-- 网址推广 -->");
document.writeln(" <tr>");
document.writeln(" <td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>    ");
document.writeln("  ");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td>");
document.writeln("	<p align=\'center\'><b><font size=\'4\' color=\'#FF0000\'>");
document.writeln("	<a target=\'_blank\' href=\'https://popopo.www21689a.com:888/#112\'>");
document.writeln("	<span style=\'text-decoration: none\'>");
document.writeln("	<img style=\'height: 34px; width:32px\' src=\'https://popopo.www21689a.com:888/images/t01acb3648e0bce6d10.gif\'></span></a></font><a target=\'_blank\' href=\'https://popopo.www21689a.com:888/#112\'><font size=\'4\' color=\'#0000FF\'><span style=\'text-decoration: none\'>金牌</span></font><span style=\'text-decoration: none\'><font color=\'#FF0000\' style=\'font-size: 20pt\'>谜</font><font color=\'#008000\' style=\'font-size: 20pt\'>语</font><font size=\'4\' color=\'#0000FF\'>网：</font><font size=\'6\' color=\'#FF0000\'>2</font><font color=\'#FF0000\' style=\'font-size: 23pt\'>1</font><font color=\'#FF0000\' style=\'font-size: 22pt\'>7</font><font color=\'#008000\' style=\'font-size: 20pt\'>5</font><font color=\'#008000\' style=\'font-size: 19pt\'>6</font></span><font size=\'4\' color=\'#0000FF\'><span style=\'text-decoration: none\'>.com</span></font></a></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("  </table>");
document.writeln("<!--  网址推广 -->");
document.writeln(" ");
document.writeln("  </div>");