document.writeln("<div style=\'display:none\'>");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    <!--62开始结束--> ");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 16pt\'>澳门玄机86281『独平二码』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->  ");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\"#FFFFFF\" >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("			<a target=\'_blank\' href=\'https://ghhg.www86281a.com:8443/#1239\' style=\'text-decoration: none\'>");
document.writeln("		<span style=font-family:楷体;color:#008000><font style=\'font-size: 16pt\'>已更新在86281c.com点击进入论坛<br>首页方可找到</font></span></a></b></td>");
document.writeln("    </tr>        ");
document.writeln("</table> 			");
document.writeln("    <!--结束--> ");
document.writeln("      <table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\' class=\'qxtable\' id=\'table1661\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>298期：独平</font><font color=\'#FF0000\' size=\'5\'>【20.44】</font><font color=\'#000000\' size=\'4\'>开00准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>297期：独平</font><font color=\'#FF0000\' size=\'5\'>【<span style=\'background-color: #FFFF00\'>16</span>.39】</font><font color=\'#000000\' size=\'4\'>开16准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>295期：独平</font><font color=\'#FF0000\' size=\'5\'>【10.<span style=\'background-color: #FFFF00\'>34</span>】</font><font color=\'#000000\' size=\'4\'>开34准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>294期：独平</font><font color=\'#FF0000\' size=\'5\'>【<span style=\'background-color: #FFFF00\'>16</span>.28】</font><font color=\'#000000\' size=\'4\'>开40准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>291期：独平</font><font color=\'#FF0000\' size=\'5\'>【<span style=\'background-color: #FFFF00\'>14</span>.38】</font><font color=\'#000000\' size=\'4\'>开14准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>289期：独平</font><font color=\'#FF0000\' size=\'5\'>【<span style=\'background-color: #FFFF00\'>02</span>.38】</font><font color=\'#000000\' size=\'4\'>开02准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>288期：独平</font><font color=\'#FF0000\' size=\'5\'>【22.<span style=\'background-color: #FFFF00\'>46</span>】</font><font color=\'#000000\' size=\'4\'>开46准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>286期：独平</font><font color=\'#FF0000\' size=\'5\'>【<span style=\'background-color: #FFFF00\'>02</span>.38】</font><font color=\'#000000\' size=\'4\'>开02准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\' bgcolor=\"#FFFFFF\">");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#000000\'>284期：独平</font><font color=\'#FF0000\' size=\'5\'>【20.<span style=\'background-color: #FFFF00\'>44</span>】</font><font color=\'#000000\' size=\'4\'>开44准</font><font color=\"#000000\"></b></font></td>");
document.writeln("		</tr>");
document.writeln("<!--结束-->");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table> ");
document.writeln("    <!--开始-->  ");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\"#FFFFFF\" >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<span style=font-family:楷体;color:#008000><font style=\'font-size: 16pt\'>");
document.writeln("		<a target=\"_blank\" style=\"text-decoration: none\" href=\"https://ghhg.www86281a.com:8443/#1239\"><span style=\'background-color: #FFFF00\'>这里从不推假料</span>！<br>更多记录请到86281c.com</a></font></span></b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln(" 		</span></a></font> ");
document.writeln("");
document.writeln("    ");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("");