
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62103b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『彩哥心水』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>258期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【兔猪狗鸡羊】</font><font color=\'#000000\'>开？00准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>256期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【鸡狗鼠蛇牛】</font><font color=\'#000000\'>开马34准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>255期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【猪鼠狗蛇羊】</font><font color=\'#000000\'>开兔01准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>254期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【狗鸡龙猪虎】</font><font color=\'#000000\'>开兔49准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>253期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【兔马鼠羊牛】</font><font color=\'#000000\'>开虎26准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>252期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【马狗蛇猴猪】</font><font color=\'#000000\'>开羊09准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");

document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>250期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【猴蛇羊猪牛】</font><font color=\'#000000\'>开虎14准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");

document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>248期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【蛇猴鸡虎鼠】</font><font color=\'#000000\'>开羊21准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>247期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【龙鼠猪猴兔】</font><font color=\'#000000\'>开牛03准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>246期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【猪鸡龙蛇鼠】</font><font color=\'#000000\'>开兔13准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>245期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【蛇牛猴鼠马】</font><font color=\'#000000\'>开兔37准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>244期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【鸡羊蛇龙牛】</font><font color=\'#000000\'>开兔25准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>243期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【猴牛龙鸡马】</font><font color=\'#000000\'>开狗18准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->  ");


document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");