document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62109b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『彩哥心水』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>082期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【蛇鸡牛鼠羊】</font><font color=\'#000000\'>开？00准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>081期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【马猴蛇虎牛】</font><font color=\'#000000\'>开龙13准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>079期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【牛鼠猴猪马】</font><font color=\'#000000\'>开鸡44准 </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>078期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【鸡猪猴蛇虎】</font><font color=\'#000000\'>开鼠05准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>077期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【兔牛鼠龙羊】</font><font color=\'#000000\'>开鸡32准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>075期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【兔羊鼠猪猴】</font><font color=\'#000000\'>开牛16准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>074期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【猴马鸡羊虎】</font><font color=\'#000000\'>开牛16准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>073期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【马龙狗鸡猪】</font><font color=\'#000000\'>开羊34准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>072期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【牛兔蛇鼠马】</font><font color=\'#000000\'>开狗19准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>069期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【狗蛇兔猪羊】</font><font color=\'#000000\'>开鸡08准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>068期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【猴鼠虎蛇龙】</font><font color=\'#000000\'>开鸡20准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>067期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【龙狗虎猪鸡】</font><font color=\'#000000\'>开羊34准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>066期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【虎鸡蛇羊猴】</font><font color=\'#000000\'>开猪42准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>065期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【马鼠猪狗虎】</font><font color=\'#000000\'>开牛04准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>064期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【马蛇猴鼠龙】</font><font color=\'#000000\'>开羊46准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>063期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【猴龙马虎猪】</font><font color=\'#000000\'>开狗31准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>062期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【蛇马虎猴鸡】</font><font color=\'#000000\'>开龙49准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>061期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【虎马狗蛇鼠】</font><font color=\'#000000\'>开猴33准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font color=\'#000000\'>060期绝杀五肖</font><font color=\'#008000\' style=\'font-size: 14pt\'>【龙猴兔马牛】</font><font color=\'#000000\'>开鸡44准</font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束-->");





document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.manolotron.com:49\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>49图库<font color=\'#FF0000\'>49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");