document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;} ");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62103c.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『奇缘解析』</font></b></p></td></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");

document.writeln("<!--开始--");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#000000\'>264期【财神奇缘】解析</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>开？00准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' style=\'font-size: 14pt\'>『</font><font color=\'#FF00FF\' style=\'font-size: 14pt\'>稍后来料中</font><font color=\'#000000\' style=\'font-size: 14pt\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>&#10146;&#10146;</font><font color=\'#008000\'>解:关注澳门六合彩资料网62103c.com</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;综合生肖：62103c.com</font></b></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;四肖中特：62103c.com</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#000000\'>267期【财神奇缘】解析</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>开？00准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' style=\'font-size: 14pt\'>『</font><font color=\'#FF00FF\' style=\'font-size: 14pt\'>稍后来料中</font><font color=\'#000000\' style=\'font-size: 14pt\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>&#10146;&#10146;</font><font color=\'#008000\'>解:关注澳门六合彩资料网62103c.com</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;综合生肖：62103c.com</font></b></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;四肖中特：62103c.com</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln("");

document.writeln(" ");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#000000\'>266期【财神奇缘】解析</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>开虎02准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' style=\'font-size: 14pt\'>『</font><font color=\'#FF00FF\' style=\'font-size: 14pt\'>龙宫满地是金</font><font color=\'#000000\' style=\'font-size: 14pt\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>&#10146;&#10146;</font><font color=\'#008000\'>解:明肖龙，金解猴鸡，满地解地肖蛇羊鸡虎鼠狗</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;综合生肖：龙鸡蛇<span style=\'background-color: #FFFF00\'>虎</span>鼠狗</font></b></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;四肖中特：龙鸡蛇<span style=\'background-color: #FFFF00\'>虎</span></font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");


document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#000000\'>263期【财神奇缘】解析</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>开牛39准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' style=\'font-size: 14pt\'>『</font><font color=\'#FF00FF\' style=\'font-size: 14pt\'>金鸡独立</font><font color=\'#000000\' style=\'font-size: 14pt\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>&#10146;&#10146;</font><font color=\'#008000\'>解:明肖鸡，独解独肖虎牛鼠羊兔马</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;综合生肖：虎<font face=\'微软雅黑\' size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font>鼠羊兔鸡</font></b></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;四肖中特：虎<font face=\'微软雅黑\' size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font>鼠羊</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln(" ");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#000000\'>262期【财神奇缘】解析</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>开鸡31准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' style=\'font-size: 14pt\'>『</font><font color=\'#FF00FF\' style=\'font-size: 14pt\'>买一根大鸡腿</font><font color=\'#000000\' style=\'font-size: 14pt\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>&#10146;&#10146;</font><font color=\'#008000\'>解:明肖鸡，大解大肖牛猪虎狗马羊</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;综合生肖：<font face=\'微软雅黑\' size=\"5\"><span style=\"background-color: #FFFF00\">鸡</span></font>牛虎狗马羊</font></b></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;四肖中特：<font face=\'微软雅黑\' size=\"5\"><span style=\"background-color: #FFFF00\">鸡</span></font>牛虎狗</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln(" ");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#000000\'>261期【财神奇缘】解析</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>开猴20准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' style=\'font-size: 14pt\'>『</font><font color=\'#FF00FF\' style=\'font-size: 14pt\'>龙鼠飞天比丑</font><font color=\'#000000\' style=\'font-size: 14pt\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>&#10146;&#10146;</font><font color=\'#008000\'>解:明肖龙鼠，比丑解丑肖牛猪猴虎狗蛇</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;综合生肖：牛猪</font><font face=\'微软雅黑\' size=\"5\"><span style=\"background-color: #FFFF00\">猴</span></font><font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>虎狗蛇</font></b></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>&raquo;四肖中特：牛猪</font><font face=\'微软雅黑\' size=\"5\"><span style=\"background-color: #FFFF00\">猴</span></font><font color=\'#993399\' style=\'font-size: 11pt\' face=\'微软雅黑\'>虎</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</div> ");