document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『春夏秋冬』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font color=\'#FF0000\'><b>");
document.writeln("	<font size=\'4\' face=\'楷体\'>");
document.writeln("	春：兔虎龙 夏：蛇马羊<br> 秋：猴鸡狗 冬：鼠猪牛</font></b></font></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("298期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>春夏冬</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>？00</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("						<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("297期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>夏秋<span style=\'background-color: #FFFF00\'>冬</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>牛39</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("	<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("296期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>春夏<span style=\'background-color: #FFFF00\'>秋</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>猴20</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->				");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("294期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>春<span style=\'background-color: #FFFF00\'>夏</span>秋</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>蛇35</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("	<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("293期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>夏<span style=\'background-color: #FFFF00\'>秋</span>冬</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>猴20</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->			");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("292期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>春</span>秋冬</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>兔25</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("						");
document.writeln("						");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("289期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>春<span style=\'background-color: #FFFF00\'>夏</span>秋</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>羊21</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("");
document.writeln("						<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("288期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>夏</span>秋冬</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>蛇23</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("						<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("287期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>春秋<span style=\'background-color: #FFFF00\'>冬</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>牛39</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("");
document.writeln("						<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("285期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>春秋<span style=\'background-color: #FFFF00\'>冬</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>猪41</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("");
document.writeln("						<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("284期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>夏<span style=\'background-color: #FFFF00\'>秋</span>冬</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>狗06</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("");
document.writeln("						<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("283期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>春<span style=\'background-color: #FFFF00\'>夏</span>秋</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>羊33</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("						<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("282期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>春</span>秋冬</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>虎38</span>准</font></font></b></font></table>");
document.writeln("						<!--开始-->");
document.writeln("");
document.writeln("");