document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<!--https://tk2.zaojiao365.net:4949/col/344/amnm.jpg-->");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>六合彩</font><font color=\'#FFFFFF\'>『传真20码』</font></font></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<font color=\'#FF00FF\'><span style=\"font-size: 14pt\">093期内幕传真20码开？00</span></font><span style=\"font-size: 14pt\"><br> ");
document.writeln("特码玄机358 249(狗31)16+21=?   <br>特码：越权附势人被迷，鹰犬之才趁时机<br>");
document.writeln("</span><font color=\'#800000\'>提供20码：<br>");
document.writeln("21 10 22 20 46 04 17 13 19 34<br>   ");
document.writeln("08 48 35 16 02 28 29 38 36 14</font> </span> </p>         ");
document.writeln("<table style=border-collapse:collapse border=0 width=100% height=\'38\'>");
document.writeln("  <tbody><tr>");
document.writeln("	<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>心心相印【18码中特11中09】点击查看</a></strong></tr></table>");
document.writeln("</td>");
document.writeln("  <!--结束-->");
document.writeln("");

document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<font color=\'#FF00FF\'><span style=\"font-size: 14pt\">091期内幕传真20码开羊34</span></font><span style=\"font-size: 14pt\"><br> ");
document.writeln("特码玄机419 306(猴21)10+27=?   <br>特码：马走牛来是时机，此时相遇别无期<br>");
document.writeln("</span><font color=\'#800000\'>提供20码：<br>");
document.writeln("02 31 37 47 42 29 30 39 33 36<br>   ");
document.writeln("21 05 08 27 38 26 41 04 <span style=\'background-color: #FFFF00\'>34</span> 10</font> </span> </p>         ");
document.writeln("<table style=border-collapse:collapse border=0 width=100% height=\'38\'>");
document.writeln("  <tbody><tr>");
document.writeln("	<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>心心相印【18码中特11中09】点击查看</a></strong></tr></table>");
document.writeln("</td>");
document.writeln("  <!--结束-->");
document.writeln("");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>  ");