document.writeln("<style>");
document.writeln(".neimu { line-height: 1.5; font-size: 18px; font-weight: bold;}");
document.writeln(".neimu table { color: #0F0; background: #000;}");
document.writeln(".neimu table thead th { padding: 5px 10px; font-size: 24px; color: #f00; background: #ff0;}");
document.writeln(".neimu table td { padding: 5px 10px;}");
document.writeln("@media screen and (max-width:800px){ ");
document.writeln(".neimu { font-size: 16px;}");
document.writeln(".neimu table thead th { font-size: 20px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『一肖一码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("           ");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--资料开始-->     ");
document.writeln("<div class=\'neimu\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("  <thead>");
document.writeln("  <tr>");
document.writeln("    <th align=\'left\' style=\'background-color: #FFFFCC\'>");
document.writeln("	<p align=\'center\'>");
document.writeln("	<font face=\'微软雅黑\'>153期一肖一码<font size=\'4\'>（62635b.com）</font></font></th>");
document.writeln("  </tr>");
document.writeln("  </thead>");
document.writeln("  <tr>");
document.writeln("    <td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>153期推荐⑥肖:</font><font color=\'#FF0000\'>龙虎羊马蛇猪</font><font color=\'#0000FF\'>-平均压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left; height: 37px;\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>153期推荐③肖:</font><font color=\'#FF0000\'>龙虎羊</font><font color=\'#0000FF\'>~~稳准狠</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>153期推荐①肖:</font><font color=\'#FF0000\'>龙</font><font color=\'#0000FF\'>~~重点多压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  ");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\' size=\"2\">153期精选12码:</font><font color=\'#FF0000\' style=\"font-size: 11pt\">13.37.03.15.22.34.11.47.12.48.06.30</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>153期精选⑥码:</font><font color=\'#FF0000\'>13.15.34.47.48.30</font><font color=\'#0000FF\'>~已确定</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\' style=\'text-align: left\' bgcolor=\'#FFFFFF\'>");
document.writeln("	<p style=\'text-align: center\'><font face=\'微软雅黑\'><font color=\'#000000\'>");
document.writeln("	第153期推荐一肖一码:(</font><font color=\'#FF0000\' style=\'font-size: 1.5em;\'>龙13</font><font color=\'#000000\'>)信心100%,中！</font></font></td>");
document.writeln("  </tr>");
document.writeln("  </table>");
document.writeln("</div>");
document.writeln("<!--资料结束-->     ");
document.writeln("");
document.writeln("<!--资料开始-->     ");
document.writeln("<div class=\'neimu\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("  <thead>");
document.writeln("  <tr>");
document.writeln("    <th align=\'left\' style=\'background-color: #FFFFCC\'>");
document.writeln("	<p align=\'center\'>");
document.writeln("	<font face=\'微软雅黑\'>152期一肖一码<font size=\'4\'>（62635b.com）</font></font></th>");
document.writeln("  </tr>");
document.writeln("  </thead>");
document.writeln("  <tr>");
document.writeln("    <td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>152期推荐⑥肖:</font><font color=\'#FF0000\'>虎<span style=\'background-color: #FFFF00\'>猴</span>鸡狗牛兔</font><font color=\'#0000FF\'>-平均压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left; height: 37px;\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>152期推荐③肖:</font><font color=\'#FF0000\'>虎<span style=\'background-color: #FFFF00\'>猴</span>鸡</font><font color=\'#0000FF\'>~~稳准狠</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>152期推荐①肖:</font><font color=\'#FF0000\'>虎</font><font color=\'#0000FF\'>~~重点多压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  ");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\' size=\"2\">152期精选12码:</font><font color=\'#FF0000\' style=\"font-size: 11pt\">15.39.<span style=\'background-color: #FFFF00\'>21</span>.33.20.32.19.31.16.40.02.14</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>152期精选⑥码:</font><font color=\'#FF0000\'>15<span style=\'background-color: #FFFF00\'>.21</span>.32.19.16.02</font><font color=\'#0000FF\'>~已确定</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\' style=\'text-align: left\' bgcolor=\'#FFFFFF\'>");
document.writeln("	<p style=\'text-align: center\'><font face=\'微软雅黑\'><font color=\'#000000\'>");
document.writeln("	第152期推荐一肖一码:(</font><font color=\'#FF0000\' style=\'font-size: 1.5em;\'>虎15</font><font color=\'#000000\'>)信心100%,中！</font></font></td>");
document.writeln("  </tr>");
document.writeln("  </table>");
document.writeln("</div>");
document.writeln("<!--资料结束-->     ");
document.writeln("");
document.writeln("<!--资料开始-->     ");
document.writeln("<div class=\'neimu\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("  <thead>");
document.writeln("  <tr>");
document.writeln("    <th align=\'left\' style=\'background-color: #FFFFCC\'>");
document.writeln("	<p align=\'center\'>");
document.writeln("	<font face=\'微软雅黑\'>151期一肖一码<font size=\'4\'>（62635b.com）</font></font></th>");
document.writeln("  </tr>");
document.writeln("  </thead>");
document.writeln("  <tr>");
document.writeln("    <td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>151期推荐⑥肖:</font><font color=\'#FF0000\'>猴兔鼠<span style=\"background-color: #FFFF00\">蛇</span>狗猪</font><font color=\'#0000FF\'>-平均压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left; height: 37px;\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>151期推荐③肖:</font><font color=\'#FF0000\'>猴兔鼠</font><font color=\'#0000FF\'>~~稳准狠</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>151期推荐①肖:</font><font color=\'#FF0000\'>猴</font><font color=\'#0000FF\'>~~重点多压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  ");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\' style=\'text-align: left\' bgcolor=\'#FFFFFF\'>");
document.writeln("	<p style=\'text-align: center\'><font face=\'微软雅黑\'><font color=\'#000000\'>");
document.writeln("	第151期推荐一肖一码:(</font><font color=\'#FF0000\' style=\'font-size: 1.5em;\'>猴09</font><font color=\'#000000\'>)信心100%,中！</font></font></td>");
document.writeln("  </tr>");
document.writeln("  </table>");
document.writeln("</div>");
document.writeln("<!--资料结束-->     ");
document.writeln("");
document.writeln("<!--资料开始-->     ");
document.writeln("<div class=\'neimu\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("  <thead>");
document.writeln("  <tr>");
document.writeln("    <th align=\'left\' style=\'background-color: #FFFFCC\'>");
document.writeln("	<p align=\'center\'>");
document.writeln("	<font face=\'微软雅黑\'>149期一肖一码<font size=\'4\'>（62635b.com）</font></font></th>");
document.writeln("  </tr>");
document.writeln("  </thead>");
document.writeln("  <tr>");
document.writeln("    <td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>149期推荐⑥肖:</font><font color=\'#FF0000\'>龙蛇<span style=\'background-color: #FFFF00\'>羊</span>猴猪狗</font><font color=\'#0000FF\'>-平均压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left; height: 37px;\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>149期推荐③肖:</font><font color=\'#FF0000\'>龙蛇<span style=\'background-color: #FFFF00\'>羊</span></font><font color=\'#0000FF\'>~~稳准狠</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>149期推荐①肖:</font><font color=\'#FF0000\'>龙</font><font color=\'#0000FF\'>~~重点多压</font></font></td>");
document.writeln("  </tr>");
document.writeln("  ");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\' size=\"2\">149期精选12码:</font><font color=\'#FF0000\' style=\"font-size: 11pt\">13.49.12.36.10.<span style=\'background-color: #FFFF00\'>22</span>.21.33.06.42.19.31</font></font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("	<td style=\'text-align: left\' bgcolor=\'#FFFFFF\'><font face=\'微软雅黑\'>");
document.writeln("	<font color=\'#000000\'>149期精选⑥码:</font><font color=\'#FF0000\'>13.49.12.36.10.<span style=\'background-color: #FFFF00\'>22</span></font><font color=\'#0000FF\'>~已确定</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\' style=\'text-align: left\' bgcolor=\'#FFFFFF\'>");
document.writeln("	<p style=\'text-align: center\'><font face=\'微软雅黑\'><font color=\'#000000\'>");
document.writeln("	第149期推荐一肖一码:(</font><font color=\'#FF0000\' style=\'font-size: 1.5em;\'>龙13</font><font color=\'#000000\'>)信心100%,中！</font></font></td>");
document.writeln("  </tr>");
document.writeln("  </table>");
document.writeln("</div>");
document.writeln("<!--资料结束-->     ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("<p style=\"text-align: center\"><strong>&nbsp;</strong></p>");
document.writeln("");
document.writeln("");
document.writeln("");