document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>小娘子</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『独合三肖』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777/\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'41\'><tbody><tr>");
document.writeln("	<td width=100% height=41><p align=center><font face=\'楷体\'><b>");
document.writeln("	<font color=\'#008000\' size=\'4\'><span style=\'background-color: #FFFF00\'>");
document.writeln("合肖：龙蛇猴鸡狗猪<br>");
document.writeln("独肖：鼠牛虎兔马羊</span></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'41\'><tbody><tr>");
document.writeln("	<td width=100% height=41><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>164期</font>【<font color=\'#FF0000\'>独肖:鼠牛羊</font>】开<font color=\'#FF00FF\'>(？00)</font></font></b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'41\'><tbody><tr>");
document.writeln("	<td width=100% height=41><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>162期</font>【<font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>合肖</span>:猴狗猪</font>】开<font color=\'#FF00FF\'>(龙01)</font></font></b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'41\'><tbody><tr>");
document.writeln("	<td width=100% height=41><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>161期</font>【<font color=\'#FF0000\'>独肖:羊<span style=\'background-color: #FFFF00\'>马</span>兔</font>】开<font color=\'#FF00FF\'>(马35)</font></font></b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'41\'><tbody><tr>");
document.writeln("	<td width=100% height=41><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>159期</font>【<font color=\'#FF0000\'>合肖:猴<span style=\'background-color: #FFFF00\'>狗</span>蛇</font>】开<font color=\'#FF00FF\'>(狗43)</font></font></b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("  </table>");
document.writeln("");
document.writeln("");