document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){ ");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>玄机解特</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『独家玄机』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");

document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>221期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开？00准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>风月场中多妖娆，龙飞凤舞红半边</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖龙鸡。风肖虎兔龙肖，妖娆一般形容女子解羊兔鸡蛇。红肖是鼠,兔,马,鸡。心水诗讲的大意是，虽然身在红尘中，是女儿身，虽然妖娆，但却也能顶起半天边，这一说就明显了是羊肖。羊（杨家将）这是个人解法，你们有什么不同的也可以说一说哟。本人主羊鸡龙虎防鼠马狗兔蛇</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：羊鸡龙虎鼠马</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>220期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开猴20准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>守猪待兔观八方，鼠目寸光金在前</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖猪兔鼠。八解八位羊八岁猴。金解金肖猴鸡。心水诗大意是：鼠目寸光的人不愿意动脑子，一次偶然的得到却想当一辈子的运气。虽然表面看起来是聪明，但目光短浅，只在乎眼前的利益得失。综合得主兔猪鼠羊防马<span style=\'background-color: #FFFF00\'>猴</span>鸡狗牛</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：兔猪鼠羊马<span style=\'background-color: #FFFF00\'>猴</span></font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>219期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开马10准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>鸡犬有缘见天日，龙腾虎跃福佳音</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖鸡狗龙虎。符合心水诗的关键字天和福的生肖是兔马龙。我们来解心水诗：一般正常情况下鸡和犬都是生存在陆地上，没有机会得道上天，但有一句话叫一人得道鸡犬升天，也就是说跟的主人对了，也就能荣华富贵得升天。这里看好鸡，鸡还有后宫之首的意思，是某一层意义的主人。综合得主鸡龙虎兔防<span style=\'background-color: #FFFF00\'>马</span>狗鼠蛇猴</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：鸡龙虎兔<span style=\'background-color: #FFFF00\'>马</span>狗</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");

document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>218期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开鸡19准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>风月场中多妖娆，龙飞凤舞红半边</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖龙鸡。风肖虎兔龙肖，妖娆一般形容女子解羊兔鸡蛇。红肖是鼠,兔,马,鸡。心水诗讲的大意是，虽然身在红尘中，是女儿身，虽然妖娆，但却也能顶起半天边，这一说就明显了是羊肖。羊（杨家将）这是个人解法，你们有什么不同的也可以说一说哟。本人主羊<span style=\'background-color: #FFFF00\'>鸡</span>龙虎防鼠马狗兔蛇。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：羊<span style=\'background-color: #FFFF00\'>鸡</span>龙虎鼠马</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");

document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>217期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开狗18准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>好山好水游美景，两心相许兔蛇情</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖兔蛇。山解土肖牛龙羊狗。水解水肖鼠猪。美字解美肖蛇羊兔鸡。两解二位牛二岁虎。生肖诗大意是两个情投意合的情侣幸福的游山玩水，美哉乐哉。综合得主兔蛇羊<span style=\'background-color: #FFFF00\'>狗</span>防牛龙鼠猪虎。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：兔蛇羊<span style=\'background-color: #FFFF00\'>狗</span>牛龙</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");

document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>216期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开龙36准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>河东龙吼蛇豪门,喜雨匠心荣草木</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖龙蛇.东解东肖虎兔龙.雨解雨肖鼠牛猪.草为木解木肖虎兔.心水诗大意龙和蛇是天生豪门.在好的环境中一片祥和.综合得主<span style=\'background-color: #FFFF00\'>龙</span>蛇虎兔防鼠牛猪猴鸡</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：<span style=\'background-color: #FFFF00\'>龙</span>蛇虎兔鼠牛</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");

document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>215期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开兔49准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>初雨深秋来寒气,冷风严清爽牛羊</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖牛羊.雨解雨肖鼠牛猪.秋解秋肖猴鸡狗.心水诗大意是秋天的雨水特别的寒冷.但是牛羊却喜欢.其实秋天是收获果实的季节.解出来的生肖中猴应该是最喜欢的.猴喜欢吃水果.综合得主猴鸡狗牛防羊鼠猪<span style=\'background-color: #FFFF00\'>兔</span>龙</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：猴鸡狗牛羊鼠</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");

document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>214期【独家玄机】解析</font><font color=\'#FFFFFF\'><span style=\'background-color: #000000\'>开？00准</span></font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>两朵红花羊犬争，九宵祥龙坐云中</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("			解析:预先解明肖羊狗龙。两解二位牛二岁虎。九解九位猴九岁羊。红解红肖鼠马鸡兔。云肖猴鸡狗肖。心水诗大意可解释为：当羊犬为了红花而争抢的时候，龙在渔翁得利静静观看。意思是比喻双方争执不下，两败俱伤，让第三者占了便宜。心水诗后句点了便宜，后句可解出来的生肖有猴蛇鸡狗龙，本人更看好这几肖。综合得主猴蛇鸡狗防龙羊<span style=\'background-color: #FFFF00\'>虎</span>兔马</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>解特肖：猴蛇鸡狗龙羊</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");



document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </table>");
document.writeln("</div>");