document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){ ");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>玄机解特</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『独家玄机』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("<!---->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>014期【独家玄机】解析</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>两朵红花羊犬争，九宵祥龙坐云中</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("解析：解明肖羊狗龙。两解二位牛二岁鼠。九解九位猴九岁蛇。红解红肖鼠马鸡兔。云肖猴鸡狗肖。心水诗大意可解释为：当羊犬为了红花而争抢的时候，龙在渔翁得利静静观看。意思是比喻双方争执不下，两败俱伤，让第三者占了便宜。心水诗后句点了便宜，后句可解出来的生肖有猴蛇鸡狗龙，本人更看好这几肖。综合得主猴蛇鸡狗防龙牛鼠兔马</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("	解特肖：猴蛇鸡狗龙牛<br>");
document.writeln("	特码：20.32.11.47.31.43.18.30.12.48.03.15</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>013期【独家玄机】解析</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>羊入虎口难逃生,蛇入竹筒身难转</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("解析：预先解明肖羊虎蛇。心水诗的大意事，再厉害的，不管是动物还是人，万物都有它的弱点。找到弱点就很容易击败它。生肖中最厉害的应该是王肖虎龙猴。综合得主虎羊蛇龙防猴鸡<span style=\'background-color: #FFFF00\'>狗</span>猪马</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("	解特肖：虎羊蛇龙猴鸡<br>");
document.writeln("	特码：02.14.21.33.11.23.12.36.08.20.07.43</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>012期【独家玄机】解析</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>获兔烹狗君王事，人间丑恶猪马</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("解析：预先解明肖兔狗猪马。君王解虎龙猴。生肖诗大意是君王事成之后排斥以至杀害有功之臣，人这间的丑恶很多。多希望人间美好没有丑恶，人人善良。综合得主兔狗猪<span style=\'background-color: #FFFF00\'>马</span>防虎龙猴鸡羊</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("	解特肖：兔狗猪<span style=\'background-color: #FFFF00\'>马</span>虎龙<br>");
document.writeln("	特码：01.37.06.18.05.41.10.34.02.14.24.36</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>011期【独家玄机】解析</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>不沾十指衣冠好，声色犬马任自由</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("解析：预先解明肖狗马,十解十岁马十位鸡,好偏看吉美肖兔龙蛇马羊鸡.综合得主狗马<span style=\'background-color: #FFFF00\'>鸡</span>兔防龙蛇羊鼠牛</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("	解特肖：狗马<span style=\'background-color: #FFFF00\'>鸡</span>兔龙蛇<br>");
document.writeln("	特码：06.18.10.34.07.<span style=\'background-color: #FFFF00\'>43</span>.13.25.12.48.23.47</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");


document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>009期【独家玄机】解析</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>云年花里逢君别，笑迎山色有苍穹</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("解析：预先解君解王肖猴虎龙。云肖猴鸡狗。山解土肖牛龙羊狗。花偏看女肖蛇羊鸡兔 。生肖诗大意是在某年与君一别，剩下的是天天笑着等待君王再次出现在自己的世界里。苍穹是苍天，广阔的天空的意思，这里指君王。综合得主虎猴龙鸡防<span style=\'background-color: #FFFF00\'>狗</span>牛羊兔蛇。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("	解特肖：虎猴龙鸡<span style=\'background-color: #FFFF00\'>狗</span>牛<br>");
document.writeln("	特码：02.14.20.32.24.36.19.43.<span style=\'background-color: #FFFF00\'>06</span>.18.15.39</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");


document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'139\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\'><font color=\'#000000\'>007期【独家玄机】解析</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#FF00FF\' style=\'font-size: 12pt\'>火爆脾气牛羊配，七嘴八舌鸡啼晨</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'>");
document.writeln("解析：预先解明肖牛羊鸡。火解火肖蛇马。七解鸡肖，八解羊猴。心肖诗大意是什么样的性格搭配什么，什么样的属性做什么事。比如牛羊食草他们可以搭配，比如鸡会啼晨告诉大家新的一天开始了。各有各的属性。综合得主牛羊<span style=\'background-color: #FFFF00\'>鸡</span>马防蛇兔龙猪狗</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b>");
document.writeln("	<font style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("	解特肖：牛羊<span style=\'background-color: #FFFF00\'>鸡</span>马蛇兔<br>");
document.writeln("	特码：03.15.21.33.07.43.10.34.11.23.13.49</font></b></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--开始-->");




document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388ttz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </table>");
document.writeln("</div>");