document.writeln("<!--图库 start-->");
document.writeln("    <div id=\"tk\"></div>");
document.writeln("<style>");
document.writeln("#gsgl-black { display:table; background: rgba(0,0,0,.2); width:100%; height:100%; overflow:hidden; _position:relative; position: fixed; z-index:10000;left: 0px;top: 0px;}");
document.writeln("@media screen and (min-width: 320px) {#gsgl-out {font-size: 14px; line-height: 20px;}}");
document.writeln("@media screen and (min-width: 360px) {#gsgl-out {font-size: 14px; line-height: 20px;}}");
document.writeln("@media screen and (min-width: 400px) {#gsgl-out {font-size: 16px; line-height: 24px;}}");
document.writeln("@media screen and (min-width: 440px) {#gsgl-out {font-size: 16px; line-height: 24px;}}");
document.writeln("@media screen and (min-width: 480px) {#gsgl-out {font-size: 16px; line-height: 24px;}}");
document.writeln("@media screen and (min-width: 640px) {#gsgl-out {font-size: 16px; line-height: 24px;}}");
document.writeln("#gsgl-out { vertical-align:middle; display:table-cell; text-align:center; _position: fixed; _top:50%; _left:50%;}");
document.writeln("#gsgl-out p { margin: 0 auto;} ");
document.writeln("#gsgl-out img { border: 0;}");
document.writeln("#gsgl-con { color: #444; background: #fff; border-radius: 5px; overflow: hidden; box-shadow: 0 5px 20px rgba(0,0,0,.2); display:inline-block; _position:relative; _top:-50%; _left:-50%;} ");
document.writeln(".gsgl-tit { line-height: 1.5em; padding: 0.5em 0.7em; font-size: 16px; font-weight: bold; text-align: left; background: #f5f5f5;}");
document.writeln(".gsgl-tit img { width: 26px; height: 26px; vertical-align: text-bottom; margin-right: 10px;}");
document.writeln(".gsgl-close { float: right; font-size: 14px; font-weight: normal; display: inline-block; cursor: pointer;}");
document.writeln(".gsgl-close:hover { background-position: 0 -34px;}");
document.writeln(".gsgl-box { text-align: left; padding: 10px;}");
document.writeln(".gsgl-box img { max-width: 100%; height: auto;}</style>");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln(".gsgl123-box { text-align: left; padding: 10px;}");
document.writeln(".gsgl123-box img { max-width: 100%; max-height: 500px;height: auto; }</style>");
document.writeln("<style>");
document.writeln("#tanxpg-black { display:none; background: rgba(0,0,0,.2); width:100%; height:100%; overflow:hidden; _position:relative; position: fixed; z-index:10000;left: 0px;top: 0px;}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div id=\"tanxpg-black\"><div id=\"gsgl-out\"><div id=\"gsgl-con\"> ");
document.writeln("");
document.writeln("<div class=\"gsgl-tit\"><span class=\"gsgl-close\" onclick=\"hidetanxpg();\">");
document.writeln("	关闭</span>六合资料网：正版图片，值得信赖。</div>");
document.writeln("<div class=\"gsgl123-box\">");
document.writeln("<p align=\"center\"><a target=\"_blank\" onclick=\"hidetanxpg();\"></a><a href=\"javascript:;\"><img id=\"tctp3\" src=\"\"></a></p>");
document.writeln("</div></div></div></div> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<script>");
document.writeln("function hidetanxpg(){");
document.writeln("	document.getElementById(\"tanxpg-black\").style.display=\"none\";");
document.writeln("}");
document.writeln("</script>");
document.writeln("");
document.writeln("<style>");
document.writeln("/*主页图库*/");
document.writeln(".tuku ul {");
document.writeln("	display: flex;");
document.writeln("	flex-wrap: wrap;");
document.writeln("	justify-content: space-around;");
document.writeln("}");
document.writeln("");
document.writeln(".tuku ul li {");
document.writeln("	width: 26%;");
document.writeln("	margin: .22rem;");
document.writeln("	text-align: center;");
document.writeln("}");
document.writeln("");
document.writeln(".tuku ul li img {");
document.writeln("	width: 100%;");
document.writeln("        height: 85px;");
document.writeln("        border: 0;");
document.writeln("	margin: 8px 0;");
document.writeln("}");

document.writeln(".klj {border:solid 1px grey collapse;font-weight:700; font-size:18pt; font-family:微软雅黑; background:#000; color:#fff; width:100%; text-align:center;}");
document.writeln(".coll {color:#ffff00;}");
document.writeln("</style>");
document.writeln("");
document.writeln("<a target=\"_blank\" href=\"https://x3.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\"><img src=\"/images/gsgl.png\" width=\"100%\"></a>");
document.writeln("<table width=\"100%\">");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td class=\"klj\" height=\"45px\" style=\"background-color: #00f\">");
document.writeln("<font color=\"#FFFF00\">62827b</font>.com→<font class=\"coll\" color=\"#FFFFFF\">点击看大图</font></td>");
document.writeln("</tr>");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"tuku  section\" id=\"channel04\">");
document.writeln("                    <ul class=\"mj_body mj_body_select\" id=\"mj01\" style=\"display: block;\">");
document.writeln("<ul>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"tuku  section\" id=\"channel04\">");
document.writeln("                    <ul class=\"mj_body mj_body_select\" id=\"mj01\" style=\"display: block;\">");
document.writeln("<ul>");
document.writeln("");
document.writeln("");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/1.jpg\"></a>");
document.writeln("		<p>规律一</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/2.jpg\"></a>");
document.writeln("		<p>规律二</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/3.jpg\"></a>");
document.writeln("		<p>规律三</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/4.jpg\"></a>");
document.writeln("		<p>规律四</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/5.jpg\"></a>");
document.writeln("		<p>规律五</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/6.jpg\"></a>");
document.writeln("		<p>规律六</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/7.jpg\"></a>");
document.writeln("		<p>规律七</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/8.jpg\"></a>");
document.writeln("		<p>规律八</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/9.jpg\"></a>");
document.writeln("		<p>规律九</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/10.jpg\"></a>");
document.writeln("		<p>规律十</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/11.jpg\"></a>");
document.writeln("		<p>规律11</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/12.jpg\"></a>");
document.writeln("		<p>规律12</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/13.jpg\"></a>");
document.writeln("		<p>规律13</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/14.jpg\"></a>");
document.writeln("		<p>规律14</p>");
document.writeln("		</div>");
document.writeln("	</li>");


document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/15.jpg\"></a>");
document.writeln("		<p>规律15</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/16.jpg\"></a>");
document.writeln("		<p>规律16</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/17.jpg\"></a>");
document.writeln("		<p>规律17</p>");
document.writeln("		</div>");
document.writeln("	</li>");


document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://xn--iecev4ddk.xn--odcxbaa3d4c0bya3cxftb2ed7g.xn--gecrj9c:8443/img/18.jpg\"></a>");
document.writeln("		<p>规律18</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("			</ul>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("     //弹出一个iframe层 ");
document.writeln("    $(\'#mj01 a\').on(\'click\', function(e){");
document.writeln("    var val=$(this).children(\'img\').attr(\'src\');");
document.writeln("    var path=val;");
document.writeln("    $(\'#tctp3\').attr(\'src\',path); ");
document.writeln("    document.getElementById(\'tanxpg-black\').style.display=\'table\';");
document.writeln("    });");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--图库 end-->");