document.writeln("<table style=\'border-collapse:collapse;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'font-weight:700;border:1px solid #000; height: 60px;\' colspan=4 align=center bgcolor=#000000 width=100%>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『单双四肖』</font></font></b></table></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>325期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>虎马龙狗/font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>羊鸡猪蛇</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>？00</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>323期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'><span style=\'background-color: #FFFF00\'>虎</span>鼠龙狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>鸡猪蛇兔</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>虎02</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>322期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>马虎鼠<span style=\'background-color: #FFFF00\'>猴</span></font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>羊兔猪蛇</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>猴32</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>321期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>猴龙虎狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>猪羊<span style=\'background-color: #FFFF00\'>鸡</span>兔</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>鸡19</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>320期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>猴鼠狗龙</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>牛<span style=\'background-color: #FFFF00\'>蛇</span>羊鸡</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>蛇23</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");

document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>319期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>猴马鼠<span style=\'background-color: #FFFF00\'>狗</span></font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>兔蛇羊鸡</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>狗42</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");







document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table><b></b>");