document.writeln("<table style=\'border-collapse:collapse;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'font-weight:700;border:1px solid #000; height: 60px;\' colspan=4 align=center bgcolor=#000000 width=100%>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『单双四肖』</font></font></b></table></td></tr>");

document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>075期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>猴鼠马狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>牛兔羊猪</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>？00</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>074期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>龙马鼠猴</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>蛇兔<span style=\'background-color: #FFFF00\'>牛</span>羊</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>牛16</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>073期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>猴马虎龙</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'><span style=\'background-color: #FFFF00\'>羊</span>兔鸡猪</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>羊34</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>072期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>龙<span style=\'background-color: #FFFF00\'>狗</span>猴鼠</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>牛猪蛇兔</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>狗19</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>071期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>龙马<span style=\'background-color: #FFFF00\'>虎</span>狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>鸡牛羊蛇</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>虎03</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>070期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>虎龙马猴</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>兔牛羊<span style=\'background-color: #FFFF00\'>猪</span></font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>猪06</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");

document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>069期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>龙鼠猴狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'><span style=\'background-color: #FFFF00\'>鸡</span>牛兔蛇</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>鸡08</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");

document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>067期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>鼠龙虎狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>蛇<span style=\'background-color: #FFFF00\'>羊</span>鸡兔</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>羊34</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>065期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>龙猴鼠狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'><span style=\'background-color: #FFFF00\'>牛</span>兔蛇羊</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>牛04</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>064期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>鼠虎猴狗</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>牛蛇兔<span style=\'background-color: #FFFF00\'>羊</span></font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>羊46</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");
document.writeln("<!--------->");
document.writeln("<tr>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font color=\'#00F\' size=\'3\'>063期</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>龙马虎<span style=\'background-color: #FFFF00\'>狗</span></font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=30% height=50>");
document.writeln("<font size=\'3\'>兔牛羊鸡</font></td>");
document.writeln("<td style=\'font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=20% height=50>");
document.writeln("<font size=\'3\' color=\'#FF0000\'>狗31</font></td></tr>");
document.writeln("");
document.writeln("<!--------->");








document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table><b></b>");