document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>平特一肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『单双五肖』</font></font></b></table>");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>203期</font><font color=\'#006600\'>【马猴虎狗鼠】【牛羊猪蛇鸡】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>202期</font><font color=\'#006600\'>【猴龙<span style=\'background-color: #FFFF00\'>鼠</span>虎马】【猪鸡羊牛兔】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>200期</font><font color=\'#006600\'>【马虎龙狗<span style=\'background-color: #FFFF00\'>猴</span>】【鸡猪羊兔牛】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>199期</font><font color=\'#006600\'>【鼠虎龙<span style=\'background-color: #FFFF00\'>猴</span>狗】【牛羊猪鸡蛇】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>198期</font><font color=\'#006600\'>【<span style=\'background-color: #FFFF00\'>狗</span>龙马猴鼠】【蛇鸡牛兔猪】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>197期</font><font color=\'#006600\'>【<span style=\'background-color: #FFFF00\'>猴</span>龙狗鼠马】【兔猪牛羊蛇】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>196期</font><font color=\'#006600\'>【虎狗猴鼠马】【鸡羊猪牛<span style=\'background-color: #FFFF00\'>蛇</span>】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>194期</font><font color=\'#006600\'>【鼠马虎龙猴】【<span style=\'background-color: #FFFF00\'>鸡</span>蛇羊牛猪】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>193期</font><font color=\'#006600\'>【虎鼠狗<span style=\'background-color: #FFFF00\'>猴</span>马】【羊蛇兔牛鸡】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>192期</font><font color=\'#006600\'>【龙狗虎马<span style=\'background-color: #FFFF00\'>猴</span>】【蛇兔猪羊牛】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>191期</font><font color=\'#006600\'>【虎猴鼠<span style=\'background-color: #FFFF00\'>龙</span>马】【猪羊兔蛇鸡】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>190期</font><font color=\'#006600\'>【鼠马龙猴狗】【猪羊<span style=\'background-color: #FFFF00\'>牛</span>兔蛇】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>189期</font><font color=\'#006600\'>【龙猴狗虎<span style=\'background-color: #FFFF00\'>马</span>】【蛇牛兔鸡猪】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>188期</font><font color=\'#006600\'>【猴虎<span style=\'background-color: #FFFF00\'>马</span>鼠狗】【羊猪兔牛蛇】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>187期</font><font color=\'#006600\'>【龙虎狗猴马】【猪兔蛇牛<span style=\'background-color: #FFFF00\'>鸡</span>】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>186期</font><font color=\'#006600\'>【虎狗鼠龙马】【猪蛇<span style=\'background-color: #FFFF00\'>兔</span>羊鸡】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>185期</font><font color=\'#006600\'>【狗鼠马<span style=\'background-color: #FFFF00\'>猴</span>龙】【牛猪羊兔蛇】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>184期</font><font color=\'#006600\'>【狗鼠虎马<span style=\'background-color: #FFFF00\'>龙</span>】【牛兔羊猪鸡】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody11><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	<font color=\'#0000FF\'>183期</font><font color=\'#006600\'>【马狗猴虎龙】【蛇<span style=\'background-color: #FFFF00\'>鸡</span>羊猪兔】</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");




document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://mnbvctrs.www58317a.com:888/#62102\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57185</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");