
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>一妓之长</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『大小肖八码』</font></b></table>");
document.writeln("");
document.writeln("    <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font face=\'隶书\' color=\'#0000FF\' style=\'font-size: 16pt\'>");
document.writeln("										大肖：牛虎马羊狗猪<br>");
document.writeln("										小肖：鼠兔龙蛇猴鸡</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("  ");
document.writeln("    <!--结束-->  ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第044期八码中特开(？00)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：大肖（牛虎马羊狗猪）<br>	");
document.writeln("		主四肖：牛虎马狗<br>			");
document.writeln("17.41.28.40.12.36.20.44</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第043期八码中特开(蛇37)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：小肖（鼠兔龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>猴鸡）<br>	");
document.writeln("		主四肖：鼠蛇猴鸡<br>			");
document.writeln("30.42.01.25.10.34.09.45</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");


document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第042期八码中特开(鼠42)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：小肖（<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font>兔龙蛇猴鸡）<br>	");
document.writeln("		主四肖：兔龙蛇猴<br>			");
document.writeln("15.27.02.38.13.49.10.34</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第041期八码中特开(虎28)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：大肖（牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>马羊狗猪）<br>	");
document.writeln("		主四肖：<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>马羊猪<br>			");
document.writeln("04.16.12.36.23.47.07.31</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第040期八码中特开(狗20)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：大肖（牛虎马羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font>猪）<br>	");
document.writeln("		主四肖：虎马羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font><br>			");
document.writeln("17.41.04.16.11.23.32.44</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第039期八码中特开(虎40)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：大肖（牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>马羊狗猪）<br>	");
document.writeln("		主四肖：牛马羊猪<br>			");
document.writeln("05.17.24.48.23.35.07.31</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第038期八码中特开(狗20)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：大肖（牛虎马羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font>猪）<br>	");
document.writeln("		主四肖：虎马羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font><br>			");
document.writeln("16.28.12.48.11.23.32.44</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' style=\"font-size: 16pt\">第037期八码中特开(蛇25)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 16pt\">");
document.writeln("		特肖：小肖（鼠兔龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>猴鸡）<br>	");
document.writeln("		主四肖：鼠<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>猴鸡<br>			");
document.writeln("06.18.13.49.10.22.33.45</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");







document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("");