document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>六肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『大小中特』</font></font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</a></strong></tr></table>");
document.writeln("<!--推广结束-->");

document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("237期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>？00</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("236期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>鸡19</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("235期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>鼠04</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("234期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>兔13</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("233期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>龙12</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("230期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>龙36</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("229期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>羊33</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("227期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>牛03</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("226期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>猴20</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("225期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>猪29</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("223期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>羊09</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("222期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>鸡31</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("221期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>虎38</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("219期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>马10</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("218期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>鸡19</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("217期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>狗18</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("216期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>龙36</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("215期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>兔49</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("214期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>小小小</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>虎14</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("213期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>狗42</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");

document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("212期<font color=\'#9933FF\'>大小中特</font><font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>大大大</font><font color=\'#0000FF\'>】开</font><font color=\'#FFFF00\'><span style=\'background-color: #800000\'>马34</span></font><font color=\'#0000FF\'>中</font></font></b></font></table>");
document.writeln("		<!--结束-->	");




document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://aaallleee.www29769a.com:888/#62102c12\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;font-size:17pt;color:#00f>进入雷锋论坛</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>628282.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("<!--推广结束-->	");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");