document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>六肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『复式连尾』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777/\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("254期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>2-5-7-1-4-6</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>0</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("252期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>6</span>-5-<span style=\'background-color: #FFFF00\'>2-1-8</span>-9</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("251期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>4</span>-5-3-7-<span style=\'background-color: #FFFF00\'>6-2</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");

document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("249期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>5-8-4-7</span>-0-<span style=\'background-color: #FFFF00\'>6</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>5</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("248期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>9</span>-7-<span style=\'background-color: #FFFF00\'>5</span>-8-<span style=\'background-color: #FFFF00\'>2-4</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("247期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>8-<span style=\'background-color: #FFFF00\'>1-9</span>-7-<span style=\'background-color: #FFFF00\'>3-6</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("246期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>1-<span style=\'background-color: #FFFF00\'>8-9</span>-0-<span style=\'background-color: #FFFF00\'>2-6</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("245期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>1</span>-9-0-8-<span style=\'background-color: #FFFF00\'>3-6</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("244期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>1-<span style=\'background-color: #FFFF00\'>5-3-6</span>-4-0</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");



document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");