document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>六肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『复式连尾』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700/\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("273期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>5-1-2-3-0-9</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>0</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("272期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>1</span>-4-3-0-<span style=\'background-color: #FFFF00\'>2-8</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("271期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>3</span>-5-4-<span style=\'background-color: #FFFF00\'>9-1-2</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("269期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>3-1-0-8</span>-6-<span style=\'background-color: #FFFF00\'>2</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>5</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("268期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>2-0-<span style=\'background-color: #FFFF00\'>1-9-5-3</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("267期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>6-<span style=\'background-color: #FFFF00\'>0-5-4</span>-9-7</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("266期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>6-2</span>-5-<span style=\'background-color: #FFFF00\'>8</span>-3-0</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("265期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>3-<span style=\'background-color: #FFFF00\'>7-0-8</span>-1-6</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("264期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>6</span>-5-<span style=\'background-color: #FFFF00\'>9-0</span>-1-<span style=\'background-color: #FFFF00\'>3</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("263期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>2-<span style=\'background-color: #FFFF00\'>4-5</span>-8-0-<span style=\'background-color: #FFFF00\'>6</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("262期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>6-4</span>-2-<span style=\'background-color: #FFFF00\'>3-5-1</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>5</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("261期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>5</span>-2-6-<span style=\'background-color: #FFFF00\'>9</span>-4-<span style=\'background-color: #FFFF00\'>7</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("260期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>4-2-9-<span style=\'background-color: #FFFF00\'>5</span>-1-<span style=\'background-color: #FFFF00\'>0</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>2</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("259期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>2-<span style=\'background-color: #FFFF00\'>9</span>-6-<span style=\'background-color: #FFFF00\'>8</span>-3-<span style=\'background-color: #FFFF00\'>0</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("258期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>7-1-6-2</span>-0-8</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("257期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>3-<span style=\'background-color: #FFFF00\'>6</span>-5-<span style=\'background-color: #FFFF00\'>9-4</span>-2</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("255期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>5-9</span>-4-0-<span style=\'background-color: #FFFF00\'>6-1</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("254期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>1-<span style=\'background-color: #FFFF00\'>5-4-7</span>-6-2</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("253期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>5-3-1-<span style=\'background-color: #FFFF00\'>9-8-2</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("252期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>8</span>-5-0-<span style=\'background-color: #FFFF00\'>2-6-3</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("251期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>8</span>-7-<span style=\'background-color: #FFFF00\'>2</span>-5-3-<span style=\'background-color: #FFFF00\'>4</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("250期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>6-0</span>-2-<span style=\'background-color: #FFFF00\'>7</span>-9-<span style=\'background-color: #FFFF00\'>4</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("249期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>5-1</span>-8-<span style=\'background-color: #FFFF00\'>6-9-7</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>5</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("248期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>1</span>-6-<span style=\'background-color: #FFFF00\'>7</span>-0-5-<span style=\'background-color: #FFFF00\'>9</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("246期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>9-5-4</span>-1-0-7</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("244期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>7</span>-8-<span style=\'background-color: #FFFF00\'>1</span>-2-9-<span style=\'background-color: #FFFF00\'>0</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("240期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>0</span>-4-<span style=\'background-color: #FFFF00\'>2</span>-9-<span style=\'background-color: #FFFF00\'>5-3</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("239期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>1-2</span>-6-<span style=\'background-color: #FFFF00\'>3-4</span>-7</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("238期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>8-<span style=\'background-color: #FFFF00\'>7-4-3-0</span>-6</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("237期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>3</span>-0-<span style=\'background-color: #FFFF00\'>6-5</span>-1-<span style=\'background-color: #FFFF00\'>8</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("236期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>8-0-<span style=\'background-color: #FFFF00\'>7</span>-5-<span style=\'background-color: #FFFF00\'>9-2</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("235期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>1-2-9-<span style=\'background-color: #FFFF00\'>6-0-4</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("234期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>4-7</span>-2-9-5-<span style=\'background-color: #FFFF00\'>3</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("233期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>0-<span style=\'background-color: #FFFF00\'>5-1</span>-6-<span style=\'background-color: #FFFF00\'>2</span>-8</font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>3</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("232期<font color=\'#0000FF\'>【</font><font color=\'#FF0000\'>5-<span style=\'background-color: #FFFF00\'>4-3-0</span>-8-<span style=\'background-color: #FFFF00\'>7</span></font><font color=\'#0000FF\'>】开<span style=\'background-color: #FFFF00\'>4</span>个</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>49图库<font color=\'#FF0000\'>49.com</font>图纸最全-最快</a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");