document.writeln("");
document.writeln("          <!--https://tk2.zaojiao365.net:4949/col/340/amgjp.jpg-->");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>(管家婆一句话赢大钱)</font></b></td></body></table>");
document.writeln("           ");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=43 ><p align=\'center\'>");
document.writeln("		<b>");
document.writeln("		<font face=\'隶书\' size=\'5\'>");
document.writeln("		<a style=\'text-decoration: none\' target=\'_blank\' href=\'https://www.49252a.com/#/picture/28015\'>");
document.writeln("		<font color=\'#FF0000\'>点击查看管家婆原图</font></a></font><font size=\'4\' face=\'微软雅黑\' color=\'#FF0000\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>094期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(六字顺意有财迎)(偷鸡摸狗)</font><font style=\'font-size: 12pt; font-weight:700\'>开特00平00</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>093期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(二七相见六思意)(车水马龙)</font><font style=\'font-size: 12pt; font-weight:700\'>开特鼠平47</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>092期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(水木特行特在单)(狼心狗肺)</font><font style=\'font-size: 12pt; font-weight:700\'>开特蛇平31</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>091期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(四零落波其中选)(鼠目寸光)</font><font style=\'font-size: 12pt; font-weight:700\'>开特羊平17</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>090期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(双来红绿挡不住)(牛鬼蛇神)</font><font style=\'font-size: 12pt; font-weight:700\'>开特45平00</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>089期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(蓝天白云鸟儿飞)(呆若木鸡)</font><font style=\'font-size: 12pt; font-weight:700\'>开特龙平00</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>088期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(负犁带耙五谷丰)(笔走龙蛇)</font><font style=\'font-size: 12pt; font-weight:700\'>开特龙平48</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>087期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(三七二一先下注)(春冰虎尾)</font><font style=\'font-size: 12pt; font-weight:700\'>开特猪平00</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>086期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(透码有一连八数)(鸡零狗碎)</font><font style=\'font-size: 12pt; font-weight:700\'>开特马平31</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>085期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(合单之数放心中)(叶公好龙)</font><font style=\'font-size: 12pt; font-weight:700\'>开特马平01</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>084期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(凌霄意志兴三春)(九牛一毛)</font><font style=\'font-size: 12pt; font-weight:700\'>开特鼠平00</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>083期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(山南山北不见五)(狗急跳墙)</font><font style=\'font-size: 12pt; font-weight:700\'>开特羊平19</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>082期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(五心十八千万端)(一马当先)</font><font style=\'font-size: 12pt; font-weight:700\'>开特羊平35</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>081期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(放之四海而皆准)(十羊九牧)</font><font style=\'font-size: 12pt; font-weight:700\'>开特龙平22</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("");
document.writeln("	<tr>"); 
document.writeln("      <td align=\'left\' height=45 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt; font-weight:700\'>080期</font><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>(千金一诺吼十七)(照猫画虎)</font><font style=\'font-size: 12pt; font-weight:700\'>开特兔平03</font></font></td>");
document.writeln("    </tr>    ");
document.writeln("    <!--结束-->");
document.writeln("");




document.writeln("");
document.writeln("   ");
document.writeln("    ");
document.writeln("    </tbody> </table> ");