document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' bgcolor=\'#ffffff\' height=\'55\'><tbody>");
document.writeln("<tr><td style=\'border:10px double #00f; height: 49px;\' bgcolor=\'#0000FF\'><p align=\'center\'>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>62635b.com</font><font color=\'#FFFFFF\'>『挂牌解析』</font></font></b></p></td></tr></tbody></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px;  word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#0000FF\'><b>162期挂牌《一统天下》<br>");
document.writeln("解释：意思是原指统一的国家,现多指某一地区或某一机构不贯彻上级意图而形成的独立王国。<br>");
document.writeln("解：天肖牛猪猴龙马兔，挂:34爆:鼠<br>");
document.writeln("</b></font>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'3\'>七肖：牛猪猴龙马兔羊</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://j.9898dz.com:9898/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击这里免费</span><font color=\'#FFFF00\'><span style=\'font-family: 楷体; font-size: 17pt; background-color: #FF0000\'>注册9898.cc</span></font><span style=font-family:楷体;font-size:17pt;color:#00f><br>点击这里投注六合彩</span></font></strong></a></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px;  word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#0000FF\'><b>161期挂牌《声东击西》<br>");
document.writeln("解释： 面声称要攻击东边，而实际却攻击西边。现指故意迷惑对方，使其产生错觉的一种策略和方法。。<br>");
document.writeln("解：羊牛虎马猴鼠，挂:25爆:鸡<br>");
document.writeln("</b></font>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'3\'>七肖：羊牛虎<span style=\'background-color: #FFFF00\'>马</span>猴鼠鸡</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://j.9898dz.com:9898/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击这里免费</span><font color=\'#FFFF00\'><span style=\'font-family: 楷体; font-size: 17pt; background-color: #FF0000\'>注册9898.cc</span></font><span style=font-family:楷体;font-size:17pt;color:#00f><br>点击这里投注六合彩</span></font></strong></a></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px;  word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#0000FF\'><b>160期挂牌《三心二意》<br>");
document.writeln("解释： 心里想这样又想那样。形容犹豫不决或意志不坚定。<br>");
document.writeln("解：鼠兔羊龙鸡虎，挂:25爆:猪<br>");
document.writeln("</b></font>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'3\'>七肖：鼠兔羊龙鸡<span style=\'background-color: #FFFF00\'>虎</span>蛇</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://j.9898dz.com:9898/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击这里免费</span><font color=\'#FFFF00\'><span style=\'font-family: 楷体; font-size: 17pt; background-color: #FF0000\'>注册9898.cc</span></font><span style=font-family:楷体;font-size:17pt;color:#00f><br>点击这里投注六合彩</span></font></strong></a></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px;  word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#0000FF\'><b>159期挂牌《茅塞顿开》<br>");
document.writeln("解释：原意为心里好像有茅草堵塞着,现在忽然被打开了。现在形容闭塞的思路,。<br>");
document.writeln("解：兔羊蛇狗龙马，挂:36爆:虎<br>");
document.writeln("</b></font>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'3\'>七肖：兔羊蛇<span style=\'background-color: #FFFF00\'>狗</span> 龙马牛</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://j.9898dz.com:9898/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击这里免费</span><font color=\'#FFFF00\'><span style=\'font-family: 楷体; font-size: 17pt; background-color: #FF0000\'>注册9898.cc</span></font><span style=font-family:楷体;font-size:17pt;color:#00f><br>点击这里投注六合彩</span></font></strong></a></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>");
document.writeln("<!--结束-->");
document.writeln("");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px;  word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#0000FF\'><b>157期挂牌《双喜临门》<br>");
document.writeln("解释：意思是指两件喜事一齐到来。<br>");
document.writeln("解：马猪羊鸡牛狗，挂:47爆:鸡<br>");
document.writeln("</b></font>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'3\'>七肖：马猪羊鸡牛狗<span style=\'background-color: #FFFF00\'>猴</span></font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://j.9898dz.com:9898/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击这里免费</span><font color=\'#FFFF00\'><span style=\'font-family: 楷体; font-size: 17pt; background-color: #FF0000\'>注册9898.cc</span></font><span style=font-family:楷体;font-size:17pt;color:#00f><br>点击这里投注六合彩</span></font></strong></a></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>");
document.writeln("<!--结束-->");
document.writeln("");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</table>");
document.writeln("");