document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' bgcolor=\'#ffffff\' height=\'55\'><tbody>");
document.writeln("<tr><td style=\'border:10px double #00f; height: 49px;\' bgcolor=\'#0000FF\'><p align=\'center\'>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>62109b.com</font><font color=\'#FFFFFF\'>『挂牌解析』</font></font></b></p></td></tr></tbody></table>");
document.writeln("");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px;  word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#0000FF\'><b>130期挂牌《四面楚歌》<br>");
document.writeln("解释：指四周都是楚人的歌声。比喻四面受敌，孤立无援，陷入绝境。<br>");
document.writeln("解：战肖牛马虎狗，四解牛，挂:33 爆:牛<br>");
document.writeln("</b></font>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'3\'>七肖：牛马虎狗鸡龙猴</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://j.9898dz.com:9898/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击这里免费</span><font color=\'#FFFF00\'><span style=\'font-family: 楷体; font-size: 17pt; background-color: #FF0000\'>注册9898.cc</span></font><span style=font-family:楷体;font-size:17pt;color:#00f><br>点击这里投注六合彩</span></font></strong></a></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px;  word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#0000FF\'><b>128期挂牌《大闹天宫》<br>");
document.writeln("解释：指在西游记中，孙悟空上天，在天庭大闹一番。也可以指向旧势力宣战的造反精神。<br>");
document.writeln("解：兔马蛇牛狗猪，挂:08 爆:马<br>");
document.writeln("</b></font>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'3\'>七肖：<span style=\'background-color: #FFFF00\'>兔</span>马蛇牛狗猪羊</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://j.9898dz.com:9898/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击这里免费</span><font color=\'#FFFF00\'><span style=\'font-family: 楷体; font-size: 17pt; background-color: #FF0000\'>注册9898.cc</span></font><span style=font-family:楷体;font-size:17pt;color:#00f><br>点击这里投注六合彩</span></font></strong></a></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>");
document.writeln("<!--结束-->");


document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</table>");
document.writeln("");