document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>杨家佬爷</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【四尾中特】</font></b></td></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("             <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 14pt\'>今日推荐【杨家佬爷】的好料</font></b></td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("");
document.writeln("");
document.writeln("                  ");
document.writeln(" <font face=\"微软雅黑\" size=\"4\">");
document.writeln("");
document.writeln("");
document.writeln("                  ");
document.writeln(" <b>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<span style=\"font-size: 16pt\">352期");
document.writeln("杨家七尾<font color=\"#FF0000\">【4-0-2-7-8-9-3】</font><BR>");
document.writeln("杨家四尾<font color=\"#FF0000\">【4-0-2-7】</font>开？00<BR>");
document.writeln("<font color=\"#0000FF\">（稳中才能稳赢）</font></span><BR><BR>");
document.writeln("");
document.writeln("");
document.writeln("<span style=\"font-size: 16pt\">351期");
document.writeln("杨家七尾<font color=\"#FF0000\">【3-1-5-<span style=\"background-color: #FFFF00\">4</span>-2-7-9】</font><BR>");
document.writeln("杨家四尾<font color=\"#FF0000\">【3-1-5-<span style=\"background-color: #FFFF00\">4</span>】</font>开猴44<BR>");
document.writeln("<font color=\"#0000FF\">（稳中才能稳赢）</font></span><BR><BR>");
document.writeln("");
document.writeln("<span style=\"font-size: 16pt\">350期");
document.writeln("杨家七尾<font color=\"#FF0000\">【<span style=\"background-color: #FFFF00\">4</span>-7-3-8-9-0-2】</font><BR>");
document.writeln("杨家四尾<font color=\"#FF0000\">【<span style=\"background-color: #FFFF00\">4</span>-7-3-8】</font>开虎14<BR>");
document.writeln("<font color=\"#0000FF\">（稳中才能稳赢）</font></span><BR><BR>");
document.writeln("");
document.writeln("<span style=\"font-size: 16pt\">349期");
document.writeln("杨家七尾<font color=\"#FF0000\">【0-4-3-<span style=\"background-color: #FFFF00\">8</span>-9-2-5】</font><BR>");
document.writeln("杨家四尾<font color=\"#FF0000\">【0-4-3-<span style=\"background-color: #FFFF00\">8</span>】</font>开鼠28<BR>");
document.writeln("<font color=\"#0000FF\">（稳中才能稳赢）</font></span><BR><BR>");
document.writeln("");
document.writeln("<span style=\"font-size: 16pt\">348期");
document.writeln("杨家七尾<font color=\"#FF0000\">【8-2-0-<span style=\"background-color: #FFFF00\">7</span>-1-5-3】</font><BR>");
document.writeln("杨家四尾<font color=\"#FF0000\">【8-2-0-<span style=\"background-color: #FFFF00\">7</span>】</font>开兔37<BR>");
document.writeln("<font color=\"#0000FF\">（稳中才能稳赢）</font></span><BR><BR>");
document.writeln("");
document.writeln("");
document.writeln("<span style=\"font-size: 16pt\">347期");
document.writeln("杨家七尾<font color=\"#FF0000\">【4-9-<span style=\"background-color: #FFFF00\">6</span>-0-1-5-3】</font><BR>");
document.writeln("杨家四尾<font color=\"#FF0000\">【4-9-<span style=\"background-color: #FFFF00\">6</span>-0】</font>开马46<BR>");
document.writeln("<font color=\"#0000FF\">（稳中才能稳赢）</font></span><BR><BR>");
document.writeln("");
document.writeln("");
document.writeln("				");
document.writeln("");
document.writeln("  </td></tr>");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("             <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 14pt\'>今日推荐平特专区【不忘初心】的好料</font></b></td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("");
document.writeln("");
document.writeln("                  ");
document.writeln(" <font face=\"微软雅黑\" size=\"4\">");
document.writeln("");
document.writeln("");
document.writeln("                  ");
document.writeln(" <b>");
document.writeln("");
document.writeln("");
document.writeln("343期平<b><font color=\"#FF0000\" size=\"5\">【虎】</font></b>开虎38准<br>");
document.writeln("344期平<b><font color=\"#FF0000\" size=\"5\">【龙】</font></b>开發00错<br>");
document.writeln("345期平<b><font color=\"#FF0000\" size=\"5\">【狗】</font></b>开狗18准<br>");
document.writeln("346期平<b><font color=\"#FF0000\" size=\"5\">【狗】</font></b>开狗06准<br>");
document.writeln("347期平<b><font color=\"#FF0000\" size=\"5\">【猴】</font></b>开猴44准<br>");
document.writeln("348期平<b><font color=\"#FF0000\" size=\"5\">【龙】</font></b>开龙36准<br>");
document.writeln("349期平<b><font color=\"#FF0000\" size=\"5\">【蛇】</font></b>开蛇23准<br>");
document.writeln("350期平<b><font color=\"#FF0000\" size=\"5\">【狗】</font></b>开發00错<br>");
document.writeln("351期平<b><font color=\"#FF0000\" size=\"5\">【马】</font></b>开马34准<br>");
document.writeln("352期平<b><font color=\"#FF0000\" size=\"5\">【鸡】</font></b>开發00准<br>");
document.writeln("");
document.writeln("");
document.writeln("				");
document.writeln("");
document.writeln("  </td></tr>");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center>");
document.writeln("				<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://kayouyou.www62361a.com:8443/\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 16pt\'><span style=font-family:楷体;>记住保存62815.com<br>常回来看看有你想要的<br>这里只推荐最好的资料</a></tr></table>");
document.writeln("<!--推广结束-->");