document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--一开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>论坛主推【连准好料】</font></b></td></table>");
document.writeln("           ");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("             <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 14pt\'>");
document.writeln("		<span style=\"text-decoration: none\">");
document.writeln("		<font color=\"#FF00FF\">今日推荐【小妖女】(2+1肖)的好料</font></span></font></b></td>");
document.writeln("    </tr>  ");
document.writeln("    ");
document.writeln("   <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<p align=\"center\"><b>");
document.writeln("			<font style=\'font-size: 15pt\'>");
document.writeln("");
document.writeln("			069期【龙<span style=\'background-color: #FFFF00\'>鸡</span>+狗】<br><br>");
document.writeln("			070期【鸡猴+<span style=\'background-color: #FFFF00\'>猪</span>】<br><br>");
document.writeln("			073期【狗羊+龙】<br>");
document.writeln("				");
document.writeln("");
document.writeln("			<font color=\"#FF0000\">小妖女，又连中，好腻害，求关注！</font><br>此料在首页【诚聘特肖】处能找到</font></p></td>	</tr>	");
document.writeln("	");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("             <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 14pt\'>");
document.writeln("		<span style=\"text-decoration: none\">");
document.writeln("		<font color=\"#FF00FF\">今日推荐【雨虎雨虎】(平特一肖)的好料</font></span></font></b></td>");
document.writeln("    </tr>  ");
document.writeln("    ");
document.writeln("   <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--头部start-->");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td align=\'left\' height=90>");
document.writeln("			<p align=\"center\"><b>");
document.writeln("			<font style=\'font-size: 15pt\'>");
document.writeln("067期平特一肖【龙】开龙01准<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("068期平特一肖【兔】开兔38准<br>");
document.writeln("");
document.writeln("");
document.writeln("069期平特一肖【虎】开虎03准<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("070期平特一肖【猴】开猴09准<br>");
document.writeln("");
document.writeln("071期平特一肖【猪】开猪06准<br>");
document.writeln("072期平特一肖【鼠】开發00准<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("此料在导航【平特专区】处能找到</font></p></td>	</tr>	");
document.writeln("	");
document.writeln("<!--头部start-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center>");
document.writeln("				<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://diyidiyi.www62109b.com:8443/\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 16pt\'><span style=font-family:楷体;>记住保存62109.com<br>常回来看看有你想要的<br>这里只推荐最好的资料</a></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("");