document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>本站推荐</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【两个半波】</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("             <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 14pt\'>（投资有风险，理性参考）</font></b></td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("             <!--开始--> ");
document.writeln("		<tr>");
document.writeln("      <td align=\'center\' height=40 bgcolor=\'#FFFFFF\' >");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<font face=\"微软雅黑\">");
document.writeln("		");
document.writeln("<p style=\"border-bottom:solid 1px #ffeda4;padding:8px 0;\">");
document.writeln(" <b>");
document.writeln(" <font face=\"微软雅黑\">");
document.writeln(" 293期:（两个半波）开？00准<br>");
document.writeln("	<font color=\"#FF0000\">主：【绿双、红单】<br></font>");
document.writeln("<font color=\"#0000FF\">长期跟踪！理性参考</font></b></font></p>  ");
document.writeln("");
document.writeln("	");
document.writeln("<p style=\"border-bottom:solid 1px #ffeda4;padding:8px 0;\">");
document.writeln(" <b>");
document.writeln(" <font face=\"微软雅黑\">");
document.writeln(" 292期:（两个半波）开兔25准<br>");
document.writeln("	<font color=\"#FF0000\">主：【<span style=\"background-color: #FFFF00\">蓝单</span>、红双】<br></font>");
document.writeln("<font color=\"#0000FF\">长期跟踪！理性参考</font></b></font></p>  ");
document.writeln("");
document.writeln("	");
document.writeln("<p style=\"border-bottom:solid 1px #ffeda4;padding:8px 0;\">");
document.writeln(" <b>");
document.writeln(" <font face=\"微软雅黑\">");
document.writeln(" 291期:（两个半波）开龙48准<br>");
document.writeln("	<font color=\"#FF0000\">主：【<span style=\"background-color: #FFFF00\">蓝双</span>、绿双】<br></font>");
document.writeln("<font color=\"#0000FF\">长期跟踪！理性参考</font></b></font></p>  ");
document.writeln("");
document.writeln("<p style=\"border-bottom:solid 1px #ffeda4;padding:8px 0;\">");
document.writeln(" <b>");
document.writeln(" <font face=\"微软雅黑\">");
document.writeln(" 290期:（两个半波）开狗42准<br>");
document.writeln("	<font color=\"#FF0000\">主：【<span style=\"background-color: #FFFF00\">蓝双</span>、绿单】<br></font>");
document.writeln("<font color=\"#0000FF\">长期跟踪！理性参考</font></b></font></p>  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</span>");
document.writeln("");
document.writeln("</b></td>");
document.writeln("    </tr>  ");
document.writeln("   <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("				<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://tututu.www62102.com:888\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 16pt\'><span style=font-family:楷体;color:#00f>关注62103b.com长期发表</a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body> ");