document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>奔三阿姨</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『公式特码』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<span style=\"font-size: 13pt\">		");
document.writeln("");
document.writeln("");
document.writeln("		<br>		");
document.writeln("");
document.writeln("");




document.writeln("  172期（平5*4+特-D2+平5+正3-2）=杀蛇猪√<br>		");
document.writeln("  173期（平5*4+特-D2+平5+正3-2）=杀鸡羊√<br>		");
document.writeln("  174期（平5*4+特-D2+平5+正3-2）=杀鸡羊√<br>		");

document.writeln("		");
document.writeln("<br>		");
document.writeln("");
document.writeln("      	<br>	");
document.writeln("");
document.writeln("");

document.writeln("      162期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      163期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("      164期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("      165期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      166期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      167期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      168期（平4*2+正1-D3+正6+正3-特）=杀木×<br>			");
document.writeln("      169期（平4*2+正1-D3+正6+正3-特）=杀金√<br>			");
document.writeln("      170期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      171期（平4*2+正1-D3+正6+正3-特）=杀金√<br>			");
document.writeln("      172期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      173期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      174期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");

document.writeln("		");
document.writeln("<br>	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<br>		");
document.writeln("");
document.writeln("");



document.writeln("		162期（平5-2-D2+正4）=杀08尾√<br>		");
document.writeln("		163期（平5-2-D2+正4）=杀16尾√<br>		");
document.writeln("		164期（平5-2-D2+正4）=杀95尾√<br>		");
document.writeln("		165期（平5-2-D2+正4）=杀80尾√<br>		");
document.writeln("		167期（平5-2-D2+正4）=杀78尾√<br>		");
document.writeln("		168期（平5-2-D2+正4）=杀32尾√<br>		");
document.writeln("		169期（平5-2-D2+正4）=杀46尾√<br>		");
document.writeln("		170期（平5-2-D2+正4）=杀01尾×<br>		");
document.writeln("		171期（平5-2-D2+正4）=杀59尾√<br>		");
document.writeln("		172期（平5-2-D2+正4）=杀89尾√<br>		");
document.writeln("		173期（平5-2-D2+正4）=杀51尾√<br>		");
document.writeln("		174期（平5-2-D2+正4）=杀30尾√<br>		");
document.writeln("		");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");


document.writeln("		164期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		165期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		166期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		167期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		168期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		169期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		170期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		171期（平4+3-D1+正2-平3）=杀0头√<br>		");
document.writeln("		172期（平4+3-D1+正2-平3）=杀3头×<br>		");
document.writeln("		173期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		174期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("<br>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        </span>		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 16pt\"><br>	");
document.writeln("");
document.writeln("");


document.writeln("        <font color=\'#0000FF\'>162期四头=243<span style=\'background-color: #FFFF00\'>0</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>163期四头=0<span style=\'background-color: #FFFF00\'>4</span>12√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>164期四头=<span style=\'background-color: #FFFF00\'>4</span>032√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>165期四头=<span style=\'background-color: #FFFF00\'>0</span>432√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>166期四头=24<span style=\'background-color: #FFFF00\'>3</span>1√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>167期四头=204<span style=\'background-color: #FFFF00\'>1</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>168期四头=2340×</font><br>	");
document.writeln("        <font color=\'#0000FF\'>169期四头=213<span style=\'background-color: #FFFF00\'>4</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>170期四头=423<span style=\'background-color: #FFFF00\'>1</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>171期四头=42<span style=\'background-color: #FFFF00\'>1</span>3√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>172期四头=3201×</font><br>	");
document.writeln("        <font color=\'#0000FF\'>173期四头=3<span style=\'background-color: #FFFF00\'>4</span>02√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>174期四头=4230√</font><br>	");
document.writeln("		");
document.writeln("<br>	");

document.writeln("		<font color=\'#0000FF\'>172期七肖=牛龙猴<span style=\'background-color: #FFFF00\'>鸡</span>兔猪虎√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>173期七肖=蛇牛虎鼠羊马兔×</font><br>		");
document.writeln("		<font color=\'#0000FF\'>174期七肖=猴牛龙马兔蛇虎√</font><br>		");
document.writeln("		");
document.writeln("		");
document.writeln("<br>	");
document.writeln("		");

document.writeln("		<font color=\'#0000FF\'>166期三行=木<span style=\'background-color: #FFFF00\'>金</span>水√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>167期三行=<span style=\'background-color: #FFFF00\'>木</span>金土√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>168期三行=水火<span style=\'background-color: #FFFF00\'>木</span>√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>169期三行=水土<span style=\'background-color: #FFFF00\'>木</span>√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>170期三行=<span style=\'background-color: #FFFF00\'>金</span>火土√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>171期三行=木水土×</font><br>			");
document.writeln("		<font color=\'#0000FF\'>172期三行=木<span style=\'background-color: #FFFF00\'>金</span>土√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>173期三行=金<span style=\'background-color: #FFFF00\'>土</span>木√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>174期三行=火木水√</font><br>			");
document.writeln("		");
document.writeln("		</span>		<br>		");
document.writeln("");
document.writeln("        </span>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 16pt\">172期六尾=4<span style=\'background-color: #FFFF00\'>2</span>0193√</span></font><br>");
document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 16pt\">173期六尾=715324×</span></font><br>");
document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 16pt\">174期六尾=624908√</span></font><br>");


document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	</span>");
document.writeln("		</b></font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://buyao77.www37197b.com:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://ffrrrsfsf.www661161a.com:8443/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>37197c.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");