document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>奔三阿姨</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『公式特码』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388ttz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<span style=\"font-size: 13pt\">		");


document.writeln("	321期（平5*4+特-D2+平5+正3-2）=杀牛鼠√<br>		");
document.writeln("	322期（平5*4+特-D2+平5+正3-2）=杀马蛇√<br>		");
document.writeln("	323期（平5*4+特-D2+平5+正3-2）=杀猪牛√<br>		");
document.writeln("	324期（平5*4+特-D2+平5+正3-2）=杀羊蛇√<br>		");
document.writeln("	325期（平5*4+特-D2+平5+正3-2）=杀马龙√<br>		");
document.writeln("	326期（平5*4+特-D2+平5+正3-2）=杀牛猪√<br>		");
document.writeln("	327期（平5*4+特-D2+平5+正3-2）=杀猴龙√<br>		");
document.writeln("	328期（平5*4+特-D2+平5+正3-2）=杀龙虎√<br>		");
document.writeln("	329期（平5*4+特-D2+平5+正3-2）=杀虎羊√<br>		");
document.writeln("	330期（平5*4+特-D2+平5+正3-2）=杀鸡虎√<br>		");
document.writeln("	331期（平5*4+特-D2+平5+正3-2）=杀马狗√<br>		");
document.writeln("		");
document.writeln("<br>		");

document.writeln("      317期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      318期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      319期（平4*2+正1-D3+正6+正3-特）=杀金√<br>			");
document.writeln("      320期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      321期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      322期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("      323期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      324期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      325期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      326期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      327期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      328期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("      329期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      330期（平4*2+正1-D3+正6+正3-特）=杀土×<br>			");
document.writeln("      331期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("		");
document.writeln("<br>	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");


document.writeln("		326期（平5-2-D2+正4）=杀98尾√<br>		");
document.writeln("		327期（平5-2-D2+正4）=杀10尾×<br>		");
document.writeln("		328期（平5-2-D2+正4）=杀53尾√<br>		");
document.writeln("		329期（平5-2-D2+正4）=杀57尾×<br>		");
document.writeln("		330期（平5-2-D2+正4）=杀09尾√<br>		");
document.writeln("		331期（平5-2-D2+正4）=杀98尾√<br>		");
document.writeln("		");
document.writeln("<br>");
document.writeln("");

document.writeln("		314期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		315期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		316期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		317期（平4+3-D1+正2-平3）=杀0头√<br>		");
document.writeln("		318期（平4+3-D1+正2-平3）=杀1头√<br>		");
document.writeln("		319期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		320期（平4+3-D1+正2-平3）=杀1头√<br>		");
document.writeln("		321期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		322期（平4+3-D1+正2-平3）=杀0头√<br>		");
document.writeln("		323期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		324期（平4+3-D1+正2-平3）=杀1头√<br>		");
document.writeln("		325期（平4+3-D1+正2-平3）=杀0头√<br>		");
document.writeln("		326期（平4+3-D1+正2-平3）=杀3头×<br>		");
document.writeln("		327期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		328期（平4+3-D1+正2-平3）=杀0头×<br>		");
document.writeln("		329期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		330期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		331期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("<br>");
document.writeln("		");




document.writeln("        <font color=\'#0000FF\'>326期四头=40<span style=\'background-color: #FFFF00\'>3</span>2√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>327期四头=134<span style=\'background-color: #FFFF00\'>2</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>328期四头=<span style=\'background-color: #FFFF00\'>0</span>234√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>329期四头=02<span style=\'background-color: #FFFF00\'>3</span>1√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>330期四头=<span style=\'background-color: #FFFF00\'>1</span>342√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>331期四头=0234√</font><br>	");
document.writeln("		");
document.writeln("<br>	");
document.writeln("");
document.writeln("		<font color=\'#0000FF\'>321期七肖=蛇<span style=\'background-color: #FFFF00\'>鸡</span>兔鼠牛羊猪√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>322期七肖=鼠兔羊猪马牛龙×</font><br>		");
document.writeln("		<font color=\'#0000FF\'>323期七肖=<span style=\'background-color: #FFFF00\'>虎</span>狗龙兔蛇鼠马√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>324期七肖=龙狗马<span style=\'background-color: #FFFF00\'>虎</span>鼠牛羊√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>325期七肖=猪鼠马<span style=\'background-color: #FFFF00\'>鸡</span>猴牛蛇√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>326期七肖=鸡牛狗鼠<span style=\'background-color: #FFFF00\'>蛇</span>猴龙√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>327期七肖=猪牛兔龙虎<span style=\'background-color: #FFFF00\'>羊</span>狗√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>328期七肖=鼠鸡猴<span style=\'background-color: #FFFF00\'>兔</span>猪马蛇√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>329期七肖=羊鸡兔狗牛<span style=\'background-color: #FFFF00\'>蛇</span>虎√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>330期七肖=鸡猪蛇马<span style=\'background-color: #FFFF00\'>狗</span>猴兔√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>331期七肖=狗蛇马鸡猴牛猪√</font><br>		");
document.writeln("		");
document.writeln("		");
document.writeln("<br>	");


document.writeln("		<font color=\'#0000FF\'>323期三行=<span style=\'background-color: #FFFF00\'>金</span>火水√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>324期三行=木水<span style=\'background-color: #FFFF00\'>土</span>√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>325期三行=水木<span style=\'background-color: #FFFF00\'>火</span>√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>326期三行=金火<span style=\'background-color: #FFFF00\'>木</span>√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>327期三行=<span style=\'background-color: #FFFF00\'>木</span>金土√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>328期三行=水火土×</font><br>			");
document.writeln("		<font color=\'#0000FF\'>329期三行=<span style=\'background-color: #FFFF00\'>木</span>水金√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>330期三行=水<span style=\'background-color: #FFFF00\'>土</span>金√</font><br>			");
document.writeln("		<font color=\'#0000FF\'>331期三行=木金火√</font><br>			");
document.writeln("		");
document.writeln("<br>		");
document.writeln("");
document.writeln("        </span>		");


document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 14pt\">328期六尾=180964√</span></font><br>	");
document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 14pt\">329期六尾=083142×</span></font><br>	");
document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 14pt\">330期六尾=152083√</span></font><br>	");
document.writeln("        <font color=\'#0000FF\'><span style=\"font-size: 14pt\">331期六尾=697850√</span></font><br>	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	</span>");
document.writeln("		</b></font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://www.65935c.com/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://www.496688a.com/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>65935c.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");