document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>奔三阿姨</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『公式特码』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("");
document.writeln("");


document.writeln("	269期（平5*4+特-D6+平2+正3-2）=杀猪鼠√<br>		");
document.writeln("	270期（平5*4+特-D6+平2+正3-2）=杀马鸡√<br>		");
document.writeln("		");
document.writeln("<br>		");
document.writeln("      253期（平4*2+正1-D3+正6+正3-特）=杀金√<br>			");
document.writeln("      254期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      255期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      256期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      257期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      258期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("      259期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      260期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      261期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      262期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("      263期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      264期（平4*2+正1-D3+正6+正3-特）=杀水√<br>			");
document.writeln("      265期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      266期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      267期（平4*2+正1-D3+正6+正3-特）=杀火√<br>			");
document.writeln("      268期（平4*2+正1-D3+正6+正3-特）=杀木√<br>			");
document.writeln("      269期（平4*2+正1-D3+正6+正3-特）=杀土√<br>			");
document.writeln("      270期（平4*2+正1-D3+正6+正3-特）=杀金√<br>			");
document.writeln("		");
document.writeln("<br>	");
document.writeln("");
document.writeln("");

document.writeln("		267期（平5-2-D2+正4）=杀95尾√<br>		");
document.writeln("		268期（平5-2-D2+正4）=杀89尾√<br>		");
document.writeln("		269期（平5-2-D2+正4）=杀85尾√<br>		");
document.writeln("		270期（平5-2-D2+正4）=杀37尾√<br>		");
document.writeln("		");
document.writeln("<br>");
document.writeln("");

document.writeln("		253期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		254期（平4+3-D1+正2-平3）=杀1头√<br>		");
document.writeln("		255期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		256期（平4+3-D1+正2-平3）=杀0头√<br>		");
document.writeln("		257期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		258期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		259期（平4+3-D1+正2-平3）=杀1头√<br>		");
document.writeln("		260期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		261期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		262期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		263期（平4+3-D1+正2-平3）=杀0头√<br>		");
document.writeln("		264期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		265期（平4+3-D1+正2-平3）=杀4头√<br>		");
document.writeln("		266期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		267期（平4+3-D1+正2-平3）=杀2头√<br>		");
document.writeln("		268期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		269期（平4+3-D1+正2-平3）=杀3头√<br>		");
document.writeln("		270期（平4+3-D1+正2-平3）=杀1头√<br>		");
document.writeln("<br>");
document.writeln("		");

document.writeln("        <font color=\'#0000FF\'>265期四头=031<span style=\'background-color: #FFFF00\'>2</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>266期四头=21<span style=\'background-color: #FFFF00\'>0</span>4√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>267期四头=2<span style=\'background-color: #FFFF00\'>3</span>10√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>268期四头=214<span style=\'background-color: #FFFF00\'>0</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>269期四头=2<span style=\'background-color: #FFFF00\'>1</span>03√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>270期四头=0423√</font><br>	");
document.writeln("		");
document.writeln("<br>");
document.writeln("		<font color=\'#0000FF\'>266期七肖=鸡马蛇<span style=\'background-color: #FFFF00\'>虎</span>牛猪狗√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>267期七肖=鸡<span style=\'background-color: #FFFF00\'>猴</span>马兔虎龙狗√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>268期七肖=鸡马虎蛇龙鼠<span style=\'background-color: #FFFF00\'>牛</span>√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>269期七肖=龙猴猪鼠<span style=\'background-color: #FFFF00\'>兔</span>羊蛇√</font><br>		");
document.writeln("		<font color=\'#0000FF\'>270期七肖=牛羊马蛇猴龙鼠√</font><br>		");
document.writeln("		");
document.writeln("		");
document.writeln("<br>	");


document.writeln("		<font color=\'#0000FF\'>270期三行=水土木√</font><br>			");
document.writeln("		");
document.writeln("<br>		");

document.writeln("        <font color=\'#0000FF\'>264期六尾=658<span style=\'background-color: #FFFF00\'>9</span>04√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>265期六尾=7436<span style=\'background-color: #FFFF00\'>5</span>2√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>266期六尾=56397<span style=\'background-color: #FFFF00\'>2</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>267期六尾=37954<span style=\'background-color: #FFFF00\'>2</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>268期六尾=79586<span style=\'background-color: #FFFF00\'>3</span>√</font><br>	");
document.writeln("        <font color=\'#0000FF\'>269期六尾=587614×</font><br>	");
document.writeln("        <font color=\'#0000FF\'>270期六尾=569312√</font><br>	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	</span>");
document.writeln("		</b></font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://www.65935c.com/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://www.496688a.com/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>65935c.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");