document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62361b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『参考理财』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln("");
document.writeln("");
document.writeln("");



document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>320期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：鸡鸡鸡（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：333（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：41.04.32.40（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：鸡龙蛇羊马鼠（2倍）开</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>319期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>狗狗狗</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>666</span>（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：30.37.34.16（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：<span style=\'background-color: #FFFF00\'>狗</span>鸡鼠蛇猴牛（2倍）开</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>318期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>兔兔兔</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>000</span>（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：25.<span style=\'background-color: #FFFF00\'>20</span>.16.<span style=\'background-color: #FFFF00\'>01</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：蛇鸡羊鼠狗龙（2倍）开</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>317期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>羊羊羊</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：666（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：09.21.16.46（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：鼠羊鸡狗牛兔（2倍）开猪41</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>316期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：猴猴猴（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>777</span>（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：08.32.27.47（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：猴鼠蛇<span style=\'background-color: #FFFF00\'>龙</span>羊兔（2倍）开龙48</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>315期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>虎虎虎</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>999</span>（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：<span style=\'background-color: #FFFF00\'>02</span>.38.29.49（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：虎<span style=\'background-color: #FFFF00\'>猪</span>龙兔牛羊（2倍）开猪29</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");


document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>314期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>猴猴猴</span>（2.1倍）开32</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>222</span>（1.8倍）开32</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：13.49.24.44（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：兔<span style=\'background-color: #FFFF00\'>虎</span>猴蛇马龙（2倍）开虎26</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>313期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：兔兔兔（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：444（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：13.49.24.44（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：兔虎猴蛇<span style=\'background-color: #FFFF00\'>马</span>龙（2倍）开马10</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>312期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>猪猪猪</span>（2.1倍）开猪05</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>333</span>（1.8倍）开03</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：<span style=\'background-color: #FFFF00\'>05</span>.41.33.43（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：猴羊<span style=\'background-color: #FFFF00\'>猪</span>蛇鸡虎（2倍）开猪05</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>310期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：鸡鸡鸡（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>444</span>（1.8倍）开44.24</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：31.43.<span style=\'background-color: #FFFF00\'>24.44</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头六肖中特：虎鸡蛇鼠马狗（2倍）开</font></font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln("  ");






document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>49图库<font color=\'#FF0000\'>49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("      ");
document.writeln("  </tbody>");
document.writeln("</table>");