
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62827b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『参考理财』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");


document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>053期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：蛇蛇蛇（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：888（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：13.25.28.48（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：虎鼠狗鸡兔蛇（2倍）开</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>052期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>猴猴猴</span>（2.1倍）开10</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：蛇猪龙鼠<span style=\'background-color: #FFFF00\'>猴</span>虎（2倍）开猴10</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>051期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>888</span>（1.8倍）开18</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：牛<span style=\'background-color: #FFFF00\'>蛇</span>兔马虎羊（2倍）开蛇49</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>050期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：猪羊<span style=\'background-color: #FFFF00\'>牛</span>兔龙猴（2倍）开牛05</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>049期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>555</span>（1.8倍）开05</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：猴<span style=\'background-color: #FFFF00\'>猪</span>兔虎羊龙（2倍）开猪43</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>048期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>羊羊羊</span>（2.1倍）开23.35</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：羊鸡蛇<span style=\'background-color: #FFFF00\'>鼠</span>狗虎（2倍）开</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>047期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>马马马</span>（2.1倍）开12</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>333</span>（1.8倍）开13</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("  ");
document.writeln(" <!--开始--> ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>046期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>鸡鸡鸡</span>（2.1倍）开33</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>444</span>（1.8倍）开24.34</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：21.33.<span style=\'background-color: #FFFF00\'>24</span>.44（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：<span style=\'background-color: #FFFF00\'>马</span>鼠虎狗羊猴（2倍）开马12</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");


document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>045期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>马马马</span>（2.1倍）开马48</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>111</span>（1.8倍）开31</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("  ");
document.writeln(" <!--开始--> ");


document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>044期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>444</span>（1.8倍）开14.34.24</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：01.37.<span style=\'background-color: #FFFF00\'>24</span>.44（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：羊鼠<span style=\'background-color: #FFFF00\'>猪</span>龙狗牛（2倍）开猪07</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>043期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>444</span>（1.8倍）开04</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：牛猪<span style=\'background-color: #FFFF00\'>蛇</span>兔龙狗（2倍）开蛇37</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>042期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：龙狗<span style=\'background-color: #FFFF00\'>鼠</span>猴羊牛（2倍）开鼠42</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>041期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>222</span>（1.8倍）开22</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：17.29.<span style=\'background-color: #FFFF00\'>22</span>.32（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：马猪鸡羊狗<span style=\'background-color: #FFFF00\'>虎</span>（2倍）开虎28</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");


document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>040期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>狗狗狗</span>（2.1倍）开08.20</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：<span style=\'background-color: #FFFF00\'>20</span>.32.27.47（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：鸡兔猴牛<span style=\'background-color: #FFFF00\'>狗</span>蛇（2倍）开狗20</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln(" <!--开始--> ");


document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>039期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>猪猪猪</span>（2.1倍）开43</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>777</span>（1.8倍）开17</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：07.31.27.37（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln(" <!--开始--> ");







document.writeln("");
document.writeln("      ");
document.writeln("  </tbody>");
document.writeln("</table>");