document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62815b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『参考理财』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>361期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：猪猪猪（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：111（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：05.41.21.31（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：马蛇鸡猪牛狗（2倍）开</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>360期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：兔猪<span style=\'background-color: #FFFF00\'>虎</span>牛马龙（2倍）开虎26</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>359期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>555</span>（1.8倍）开15</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：22.34.05.<span style=\'background-color: #FFFF00\'>15</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：羊<span style=\'background-color: #FFFF00\'>猴</span>狗蛇鼠兔（2倍）开</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>358期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>999</span>（1.8倍）开49.19</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：11.23.29.<span style=\'background-color: #FFFF00\'>49</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>357期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>虎虎虎</span>（2.1倍）开26</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("  ");
document.writeln("    <!--结束--> ");

document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>355期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>000</span>（1.8倍）开30.10</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：15.39.20.<span style=\'background-color: #FFFF00\'>30</span>（2.1倍）开30</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>354期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");

document.writeln("    	<tr>"); 
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>666</span>（1.8倍）开46.06</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：21.33.16.<span style=\'background-color: #FFFF00\'>46</span>（2.1倍）开46</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>353期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>马马马</span>（2.1倍）开马10</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>888</span>（1.8倍）开08</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：<span style=\'background-color: #FFFF00\'>10</span>.34.28.48（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>352期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：狗狗狗（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：<span style=\'background-color: #FFFF00\'>333</span>（1.8倍）开13.23</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：06.42.33.43（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=39 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\"4\" face=\"微软雅黑\">光头六肖中特：<span style=\'background-color: #FFFF00\'>猪</span>鼠蛇鸡狗兔（2倍）开猪41</font></b></td>");
document.writeln("    </tr>     ");
document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>351期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>马马马</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");
document.writeln(" <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFF00\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("		<font color=\'#000000\'>350期<font color=\'#FF0000\' face=\'隶书\' size=\'6\'>光头平特</font><font color=\'#000000\'>兔年大中！</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一肖：<span style=\'background-color: #FFFF00\'>龙龙龙</span>（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>光头平特一尾：555（1.8倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("    	<tr>");
document.writeln("      <td height=38 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<font face=\'微软雅黑\' size=\"4\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>必中平码：12.<span style=\'background-color: #FFFF00\'>36</span>.25.45（2.1倍）</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");

document.writeln("  ");
document.writeln("     ");
document.writeln("  ");
document.writeln("    <!--结束--> ");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.manolotron.com:49\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>49图库<font color=\'#FF0000\'>49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("      ");
document.writeln("  </tbody>");
document.writeln("</table>");