document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>民间彩友</font><font color=\'#FFFFFF\'>『解红字肖』</font></font></b></table>");
document.writeln("");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>021期红字暗码【旁敲侧击】【07 15 22 34】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：比喻说话、写文章不从正面直接说明，而是用或明或暗的语言影射、讽刺、攻击，或转弯抹角地表达出来。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：蛇兔马猪羊猴鼠<br>");
document.writeln("主特14码：11.23.01.37.10.34.05.17.21.33.08.20.04.40");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>018期红字暗码【吊儿浪荡】【07 11 22 49】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：浪荡:放浪。形容散漫放浪</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：鸡狗兔鼠虎猴<span style=\'background-color: #FFFF00\'>蛇</span><br>");
document.writeln("主特14码：07.31.18.30.01.13.16.28.02.38.20.44.11.<span style=\'background-color: #FFFF00\'>47</span>");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>017期红字暗码【挖空心思】【04 16 27 43】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：想方设法，费尽心机（多含贬义）</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：鼠虎<span style=\'background-color: #FFFF00\'>蛇</span>鸡龙羊马<br>");
document.writeln("主特14码：04.40.02.38.<span style=\'background-color: #FFFF00\'>23</span>.47.31.43.12.36.09.21.10.34");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>015期红字暗码【六根清净】【08 11 25 32】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：意思是佛家以达到远离烦恼的境界为六根清静。比喻已没有任何欲念。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：兔<span style=\'background-color: #FFFF00\'>牛</span>马蛇鼠猴猪<br>");
document.writeln("主特14码：13.49.03.15.22.34.11.23.04.40.32.44.05.41");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>014期红字暗码【志趣不凡】【05 18 36 47】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：不凡:不寻常,不平凡。志向很不平常。形容超凡。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：<span style=\'background-color: #FFFF00\'>猴</span>马牛虎狗猪鸡<br>");
document.writeln("主特14码：<span style=\'background-color: #FFFF00\'>20</span>.32.10.34.03.15.02.14.06.30.05.29.31.43");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>013期红字暗码【饱其私囊】【09 14 32 41】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：饱：满足；囊：口袋。指非法侵吞钱财，装入自己腰包。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：猪兔<span style=\'background-color: #FFFF00\'>狗</span>羊牛龙马<br>");
document.writeln("主特14码：05.17.25.37.<span style=\'background-color: #FFFF00\'>18</span>.30.21.45.03.15.24.36.10.46");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>012期红字暗码【一息尚存】【02 19 34 43】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：只要还有一口气。指还活着。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：虎<span style=\'background-color: #FFFF00\'>马</span>蛇龙猴兔狗<br>");
document.writeln("主特14码：14.26.10.34.23.47.12.36.08.20.13.49.06.30");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</span> ");
document.writeln("</b>");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</body>");
document.writeln("</html>");