document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>民间彩友</font><font color=\'#FFFFFF\'>『解红字肖』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>034期红字暗码【灯火万家】【06 13 20 34】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：家家都点上灯。指天黑上灯的时候。亦形容城镇夜晚的景象。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：龙虎牛鸡羊狗鼠<br>");
document.writeln("主特14码：12.36.02.38.15.39.31.43.09.21.06.30.16.28");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>032期红字暗码【奄奄一息】【18 23 31 46】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：奄奄：呼吸微弱的样子。只剩下一口气。形容临近死亡。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：马<span style=\'background-color: #FFFF00\'>鼠</span>牛兔龙羊虎<br>");
document.writeln("主特14码：10.34.04.<span style=\'background-color: #FFFF00\'>40.</span>15.27.13.49.24.36.21.33.02.14");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>030期红字暗码【温柔体贴】【04 23 30 48】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：温顺关怀体贴</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：虎猴蛇兔猪狗<span style=\'background-color: #FFFF00\'>牛</span><br>");
document.writeln("主特14码：02.14.20.32.11.23.13.25.05.41.30.42.15.39");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>029期红字暗码【惊慌失措】【03 14 25 44】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：也说惊惶失措。害怕、慌张，举止失去常态，不知怎么办好。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：龙虎鸡羊猪<span style=\'background-color: #FFFF00\'>鼠</span>猴<br>");
document.writeln("主特14码：12.36.02.38.19.43.33.45.05.17.04.40.20.44");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>028期红字暗码【眼明手快】【09 22 31 40】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：眼力好，动作快，形容反应快。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：龙<span style=\'background-color: #FFFF00\'>羊</span>虎蛇猴牛兔<br>");
document.writeln("主特14码：24.36.<span style=\'background-color: #FFFF00\'>09</span>.21.02.14.11.23.08.20.15.39.13.49");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");




document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</span> ");
document.writeln("</b>");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</body>");
document.writeln("</html>");