document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>民间彩友</font><font color=\'#FFFFFF\'>『解红字肖』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>046期红字暗码【百感交集】【06 17 22 45】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：各种各样的感触交织在一起</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：鸡羊狗马蛇猴兔<br>");
document.writeln("主特14码：08.20.22.34.19.31.23.47.24.36.09.21.14.38");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>045期红字暗码【风声鹤唳】【03 16 29 46】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：后用来形容人在非常害怕时听到一点声音，就十分恐慌紧张</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：龙<span style=\'background-color: #FFFF00\'>牛</span>猪猴鼠羊狗<br>");
document.writeln("主特14码：01.13.16.<span style=\'background-color: #FFFF00\'>28</span>.18.30.21.33.05.41.22.34.19.43");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>044期红字暗码【逢场作戏】【07 18 21 44】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：原指卖艺的人遇到合适场所就进行表演。后指为应酬或凑热闹，偶尔玩玩，并不认真。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：羊牛狗鼠蛇马<span style=\'background-color: #FFFF00\'>兔</span><br>");
document.writeln("主特14码：10.22.16.28.19.31.05.41.24.36.11.23.<span style=\'background-color: #FFFF00\'>02</span>.38");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font color=\'#0000FF\' size=\'3\'>043期红字暗码【寸步不让】【05 19 28 30】</font></b><br> ");
document.writeln("<b><font color=\'#008000\'>解：连寸步也不让给别人。形容丝毫不肯让步、妥协。</font></b><br>");
document.writeln("<b><font color=\'#800000\' size=\'4\'>");
document.writeln("解取特肖：虎鼠马鸡牛羊<span style=\'background-color: #FFFF00\'>猪</span><br>");
document.writeln("主特14码：03.39.17.41.11.23.32.44.16.28.10.22.30.<span style=\'background-color: #FFFF00\'>42</span>");
document.writeln("</font></b><table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center>");
document.writeln("			。<a target=\'_blank\' href=\'https://jjjcccc.tryththtthghgfhgfh.com:888/#626969\'><img src=/images/33567.gif width=20 height=19><font color=\'#FF0000\'>更多跑狗解析进37859.com查看</font></a></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</span> ");
document.writeln("</b>");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</body>");
document.writeln("</html>");