document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>神秘大叔</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【浅解解码图】</font></b></td></table>");
document.writeln(" <table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("          ");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>044期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【8.5.9.1】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开？00】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字8591尾或者解特猪羊猴虎马鼠龙蛇牛</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>043期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【6.7.1.5】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开蛇37】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字6<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">7</span></font>15尾或者解特兔<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>猴鸡牛虎羊鼠马</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>042期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【8.4.3.7】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开鼠42】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字8437尾或者解特羊虎蛇<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font>兔马鸡狗牛</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>041期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【1.3.5.0】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开虎28】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字1350尾或者解特兔猪鼠马羊牛龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>猴</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>039期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【6.7.3.0】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开虎40】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字673<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">0</span></font>尾或者解特鸡龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>马牛猴鼠羊兔</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>038期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【2.3.4.7】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开狗20】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字2347尾或者解特羊虎猪马牛鼠龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font>兔</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>037期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【9.1.0.6】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开蛇25】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字9106尾或者解特羊猪鼠马狗鸡<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>猴虎</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>036期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【3.5.7.6】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开牛29】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字3576尾或者解特虎马龙鼠羊<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">牛</span></font>蛇猪狗</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://x7.xn--hdcl2bk2m1bc.xn--gecrj9c:8443\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("         ");
document.writeln("");
document.writeln("");