document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>神秘大叔</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【浅解解码图】</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100/\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");

document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>010期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【7.6.9.4】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开？00】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字7694尾或者解特龙蛇牛猴猪兔狗马羊</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>009期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【5.9.2.4】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开狗06】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字5924尾或者解特鸡猪虎蛇羊鼠猴<span style=\'background-color: #FFFF00\'>狗</span>牛</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>008期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【5.2.8.0】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开猴20】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字528<span style=\'background-color: #FFFF00\'>0</span>尾或者解特马鼠龙鸡<span style=\'background-color: #FFFF00\'>猴</span>羊虎狗牛</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>007期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【5.2.4.1】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开鸡19】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字5241尾或者解特虎蛇龙猴<span style=\'background-color: #FFFF00\'>鸡</span>狗猪兔鼠</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>006期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【9.7.3.4】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开蛇23】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字97<span style=\'background-color: #FFFF00\'>3</span>4尾或者解特猴龙羊<span style=\'background-color: #FFFF00\'>蛇</span>虎兔鼠牛鸡</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>005期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【9.6.1.4】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开鸡19】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字<span style=\'background-color: #FFFF00\'>9</span>614尾或者解特牛龙<span style=\'background-color: #FFFF00\'>鸡</span>狗马羊猪鼠蛇</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>004期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【1.4.8.9】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开鼠40】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字1489尾或者解特猴狗马猪牛虎<span style=\'background-color: #FFFF00\'>鼠</span>蛇兔</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>003期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【9.2.7.1】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开鸡19】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字<span style=\'background-color: #FFFF00\'>9</span>271尾或者解特鼠虎马猴兔猪蛇<span style=\'background-color: #FFFF00\'>鸡</span>牛</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>002期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【8.4.6.7】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开虎26】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字84<span style=\'background-color: #FFFF00\'>6</span>7尾或者解特马兔龙猪鸡<span style=\'background-color: #FFFF00\'>虎</span>羊鼠狗</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>001期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【5.6.2.4】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开狗06】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字5<span style=\'background-color: #FFFF00\'>6</span>24尾或者解特虎蛇羊马牛猴鼠<span style=\'background-color: #FFFF00\'>狗</span>兔</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>365期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【3.5.0.6】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开？00】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字<span style=\'background-color: #FFFF00\'>3</span>506尾或者解特兔猴猪牛马蛇虎狗<span style=\'background-color: #FFFF00\'>鸡</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>364期：数字</font><font color=\'#FF0000\' style=\'font-size: 16pt; font-weight:700\'>【9.6.1.4】<font color=\'#FFFFFF\' size=\'3\'><span style=\'background-color: #000000\'>【开兔01】</span></font></font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		解：数字96<span style=\'background-color: #FFFF00\'>1</span>4尾或者解特<span style=\'background-color: #FFFF00\'>兔</span>狗牛马虎鸡猴鼠羊</font></b></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://qahghh.www62361b.com:888\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388ttz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("    ");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("         ");
document.writeln("");
document.writeln("");
document.writeln("");