document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>六肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>62102b.com</font><font color=\'#FFFFFF\'>『金牌谜语』</font></font></b></table>");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("181期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>？00</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("此物细又长，成群落下方。<br>");
document.writeln("落地就不见，不知啥模样。</font></b></font></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("180期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>马34</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("一块油糕真稀奇，不咸不甜不能吃。<br>");
document.writeln("帮助大家搞清洁，除污去垢最得力。</font></b></font></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("179期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>鼠04</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("小时青青似野草，老来满头金珠宝。<br>");
document.writeln("珠宝人人都珍惜，天下无人不依靠。</font></b></font></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("178期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>虎02</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("脚踏千江水，手扬满天沙。<br>");
document.writeln("惊起林中鸟，折断园里花。</font></b></font></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("177期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猴44</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("背上还有一个背，脚边还有四只脚。<br>");
document.writeln("走路睡觉用不着，写字画画要它帮。</font></b></font></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("176期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猴32</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("脚踏千江水，手扬满天沙。<br>");
document.writeln("惊起林中鸟，折断园里花。</font></b></font></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("175期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>狗06</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("夜里林中一哨兵，眼睛好像两盏灯。<br>");
document.writeln("瞧瞧西来望望东，抓住盗贼不放松。</font></b></font></table>");
document.writeln("");

document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("174期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猪41</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("散步在小溪，睡觉在池塘。<br>");
document.writeln("奔跑在江河，咆哮在海洋。</font></b></font></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("173期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>龙36</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("一物不倒立得正，春夏秋冬不弯腰。<br>");
document.writeln("三国之中助一阵，从古到今留美名。</font></b></font></table>");
document.writeln("");

document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("172期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>龙12</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("一个圆圆饼，一个蓝蓝盘。<br>");
document.writeln("一个火火热，一个冰冰冷。</font></b></font></table>");
document.writeln("");


document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("171期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>马10</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("铁打心肠一枝花，我是主人好管家。<br>");
document.writeln("主人一来我开心，不是主人不理他。</font></b></font></table>");
document.writeln("");



document.writeln("");
document.writeln("");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40>");
document.writeln("			<p style=text-align:center><strong>");
document.writeln("			<a target=\"_blank\" href=\"https://21689.com/#62\">");
document.writeln("			<span style=\"text-decoration: none\"><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>更多金牌谜语历史记录<Br></span>");
document.writeln("			</span><span style=font-family:楷体;font-size:17pt;>");
document.writeln("			<font color=\"#FF0000\"><span style=\"text-decoration: none\">请到21689.com</span></font></span></a></strong></tr></table>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
document.writeln("");
document.writeln(" ");