document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>六肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFFFF\'>『金牌谜语』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("022期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>？00</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">此物细又长，成群落下方<br>");
document.writeln("落地就不见，不知啥模样</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("021期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>蛇35</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">一座军营百个兵，列好队伍等命令<br>");
document.writeln("一旦需要就出去，牺牲自己换光明</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("020期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猪29</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">小来针眼大，大来满山坡<br>");
document.writeln("能过千山岭，不能过小河</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("019期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猪17</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">脚踏千江水，手扬满天沙<br>");
document.writeln("惊起林中鸟，折断园里花</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("018期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>蛇47</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">一个小黑人，跳进洗澡盆<br>");
document.writeln("越洗越不净，长人变短人</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("017期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>蛇23</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">说它多大有多大，日月星球全容纳<br>");
document.writeln("无人知它始和终，也没左右和上下</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("016期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猪17</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">天热外边度酷暑，天冷屋里来过冬<br>");
document.writeln("勤恳服务心里红，待人接物挺热情</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("015期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>牛39</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">一对小小船，载客各五员<br>");
document.writeln("无水走一下，有水不开船</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("014期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猴20</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">叮铃铃，叮铃铃，一头说，一头听<br>");
document.writeln("两人对，不见面，说话字，听得清</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("013期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>狗18</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">黑头黑脚，无病吃药<br>");
document.writeln("怒吼一声，比虎还恶</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("012期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>马22</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">天天不休息，一走十二里<br>");
document.writeln("有人来找我，看看我脸皮</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("011期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>鸡43</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">十八好汉二三倒，刺骨悬梁一九志<br>");
document.writeln("里面有长也有短，能装棉来能装钢</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("010期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>龙36</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">身穿紫花白战袍，海里将军只一招<br>");
document.writeln("每遇敌人来袭击，急放墨汁当法宝家</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("009期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>狗06</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">东海一朵花，牵藤西山洼<br>");
document.writeln("花开人出门，花谢人回家</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");
document.writeln("");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'39\'><tbody><tr>");
document.writeln("	<td width=100% height=39><p align=center><b><font face=\'楷体\'>");
document.writeln("	<font size=\'4\' color=\'#008000\'>");
document.writeln("008期澳门【金牌谜语】</font><font color=\'#008000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>猴20</font></span><font color=\'#0000FF\'>	</font><br>");
document.writeln("	<span style=\"font-size: 13pt\">白天到处跑，晚上找不到<br>");
document.writeln("人人喜欢它，万物都需要</span></font></b><span style=\"font-size: 13pt\"></font></span></table>");
document.writeln("");

document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40>");
document.writeln("			<p style=text-align:center><strong>");
document.writeln("			<a target=\"_blank\" href=\"https://21689b.com/#62\">");
document.writeln("			<span style=\"text-decoration: none\"><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>更多金牌谜语历史记录<Br></span>");
document.writeln("			</span><span style=font-family:楷体;font-size:17pt;>");
document.writeln("			<font color=\"#FF0000\"><span style=\"text-decoration: none\">请到21689.com</span></font></span></a></strong></tr></table>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
document.writeln("");
document.writeln(" ");