document.writeln(" ");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62103b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『绝杀12码』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>280期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【22.49.24.07.43.23.21.47.20.42.02.37】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>00√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>279期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【33.49.11.41.46.35.34.04.29.22.20.19】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>10√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>278期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【42.07.13.19.20.26.16.22.05.38.09.45】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>39√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");

document.writeln("     <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>276期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【40.49.15.05.23.28.17.11.46.31.44.02】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>08√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束--> ");
document.writeln("       <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>275期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【11.31.39.42.07.15.06.33.40.08.49.36】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>10√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束--> ");
document.writeln("     <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>274期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【40.05.28.27.29.33.31.12.06.44.12.35】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>13√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束--> ");
document.writeln("     <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>273期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【22.27.31.38.46.03.33.15.40.02.29.30】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>28√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束--> ");
document.writeln("     <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>272期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【23.05.29.11.14.36.30.18.22.21.07.45】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>27√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束--> ");
document.writeln("    <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>271期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【31.06.12.28.25.21.10.09.41.44.27.42】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>39√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->    ");
document.writeln("               <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>270期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【13.15.40.24.03.14.47.43.20.07.38.10】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>08√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->    ");
document.writeln("               <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>269期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【13.38.23.10.05.25.47.29.32.15.39.36】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>13√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->    ");
document.writeln("");
document.writeln("               <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>268期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【32.14.25.44.17.33.34.09.35.24.19.37】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>03√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->    ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");