document.writeln(" ");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62519b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『绝杀12码』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388ttz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>343期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【12.04.01.20.38.18.08.33.25.14.26.42】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>00√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>342期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【48.30.16.18.08.07.06.24.03.01.31.22】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>05√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>341期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【45.17.29.41.32.12.38.09.06.07.11.27】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>34√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>340期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【03.21.47.48.01.16.11.26.13.22.44.12】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>46√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>339期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【49.20.43.19.47.38.28.17.46.24.29.40】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>10√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("");

document.writeln("");
document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>338期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【11.43.16.33.04.14.32.05.44.20.03.09】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>41√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("");

document.writeln("           <!--开始-->");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' style=\'font-size: 11pt\'>337期</font><font color=\'#FF0000\' style=\'font-size: 11pt\'>【33.28.45.30.44.36.31.14.20.41.43.05】</font><font color=\'#000000\' style=\'font-size: 11pt\'>开<span style=\'background-color: #FFFF00\'>16√</span></font></b></font></td>");
document.writeln("    </tr>");
document.writeln("    <!--结束-->");
document.writeln("");




document.writeln("");
document.writeln("  ");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");