document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>流浪高手</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『绝杀一行』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>241期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【土行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>？00</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>239期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【土行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>狗31</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>238期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【水行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>猪18</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>237期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【金行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>猪06</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");

document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>236期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【木行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>虎03</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");

document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>234期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【火行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>狗07</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>233期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【火行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>马23</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>232期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【火行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>兔02</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>231期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【水行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>鼠17</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");
document.writeln("  <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>230期<font color=\'#0000FF\'>绝杀五行</font><font color=\'#FF00FF\'>【金行】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#808000\'>龙49</font>准</span></font></b></td>");
document.writeln("    </tr>");
document.writeln("  <!--开始-->");



document.writeln("");
document.writeln(" ");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td colspan=\'3\'><a target=\'_blank\' href=\'https://xn--oecalb2e.xn--hdcn9ajb1dyeua6etcq8g3b.xn--gecrj9c:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://hjyjthjy.www661161c.com:8443/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>37197c.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");