document.writeln(" ");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62109b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『绝杀平码』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'><img src=images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");


document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>135期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【33.26】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>134期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【24.13】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>132期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【06.26】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>131期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【15.47】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>129期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【29.16】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>128期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【01.20】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>127期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【05.10】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");


document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>124期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【25.27】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>122期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【21.28】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>121期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【13.43】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>120期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【27.07】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>119期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【31.34】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' >");
document.writeln("		<p align=\'center\'>");
document.writeln("		<font face=\'微软雅黑\'><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\' size=\'3\'>118期绝杀平码</font><font color=\'#008000\' style=\'font-size: 16pt\'>【14.35】</font><font color=\'#000000\' size=\'3\'>开</font><font size=\'3\'>00</font><font color=\'#FF0000\' size=\'5\'>√</font></b></font></td>");
document.writeln("    </tr>");
document.writeln("<!--开始--> ");





document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");