document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<META http-equiv=Content-Type content=\'text/html; charset=utf-8\'>");
document.writeln("<meta name=\'referrer\' content=\'never\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width,initial-scale=1, maximum-scale=1, user-scalable=no\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!------------------------------插件代码开始-以上都不要-------------------------------------->");
document.writeln("<style>");
document.writeln(".lhl { font-size: 14px; border-collapse: collapse; background: #f9f0df;}");
document.writeln(".lhl tr {}");
document.writeln(".lhl th { padding: 5px; font-size: 24px; background: #d2b493;}");
document.writeln(".lhl td { padding: 5px;}");
document.writeln(".lhl td.lhl-tit { background: #edd4be;}");
document.writeln(".lhl td.lhl-tit strong { color: #00f;}");
document.writeln(".lhl td.lhl-tit em { font-style: normal; color: #f00;}");
document.writeln(".lhl td span { background: #ff0;}");
document.writeln("</style>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'6\'>澳门资料·老黄历</font></b></table>");
document.writeln("");
document.writeln("<!--日历网址：https://www.8s8s.com/shop/list.php");
document.writeln("2024年五行号码：");
document.writeln("金行：02.03.10.11.24.25.32.33.40.41");
document.writeln("木行：06.07.14.15.22.23.36.37.44.45");
document.writeln("水行：12.13.20.21.28.29.42.43");
document.writeln("火行：01.08.09.16.17.30.31.38.39.46.47");
document.writeln("土行：04.05.18.19.26.27.34.35.48.49 -->");
document.writeln("");
document.writeln("<table class=\'lhl\' width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>147期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>05月26号，四月十九</font><font color=\'#000000\'>，吉日五行:松柏木;虎日冲(甲申)猴 ");
document.writeln("	煞北,宿名：南方星日马</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:凶,五行:木行：06.07.14.15.22.23.36.37.44.45冲煞:猴虎 煞北:鼠猪牛,星宿杀肖：羊,综合：兔马狗虎牛鸡猴鼠猪 ");
document.writeln("	本期主攻:兔马狗虎牛，号码02.14.23.35.19.43.15.39.28.40</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>146期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>05月25号，四月十八</font><font color=\'#000000\'>，吉日五行:霹雷火;牛日冲(癸未)羊 ");
document.writeln("	煞东 ,宿名：南方柳土獐</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:凶,五行:火行：01.08.09.16.17.30.31.38.39.46.47冲煞:羊牛 煞东:兔虎龙,星宿杀肖：鼠,综合：牛马猴猪兔龙鸡虎</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">狗</span></font><font style=\"font-size: 13pt\">");
document.writeln("	本期主攻:牛马猴猪兔，号码04.28.11.23.21.33.30.42.02.14</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>145期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>05月24号，四月十七</font><font color=\'#000000\'>，吉日五行:霹雷火;鼠日冲(壬午)马 ");
document.writeln("	煞西 ,宿名：南方井木犴</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:吉,五行:土行：04.05.18.19.26.27.34.35.48.49冲煞:鼠马 煞南:蛇羊马,星宿杀肖：羊,综合：猪</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">兔</span></font><font style=\"font-size: 13pt\">鸡狗马猴蛇鼠龙 ");
document.writeln("	本期主攻:猪</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">兔</span></font><font style=\"font-size: 13pt\">鸡狗马，号码06.30.</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">02</span></font><font style=\"font-size: 13pt\">.14.20.32.31.43.11.23</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>144期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>05月23号，四月十六</font><font color=\'#000000\'>，吉日五行:屋上土;猪日冲(辛巳)蛇 ");
document.writeln("	煞西 ,宿名：南方井木犴</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:吉,五行:土行：04.05.18.19.26.27.34.35.48.49冲煞:蛇猪 煞西:猴鸡狗,星宿杀肖：蛇,综合：猴羊马鸡龙兔鼠虎<font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">牛</span></font> ");
document.writeln("	本期主攻:猴羊马鸡龙，号码09.21.10.22.23.35.08.20.13.49</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>143期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>05月22号，四月十五</font><font color=\'#000000\'>，吉日五行:屋上土;狗日冲(庚辰)龙 ");
document.writeln("	煞北 ,宿名：西方参水猿</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:凶,五行:土行：04.05.18.19.26.27.34.35.48.49冲煞:狗龙 煞北:鼠猪牛,星宿杀肖：牛,综合：鸡猴鼠</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">蛇</span></font><font style=\"font-size: 13pt\">兔猪马狗龙 ");
document.writeln("	本期主攻:鸡猴鼠</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">蛇</span></font><font style=\"font-size: 13pt\">兔，号码08.20.21.33.17.41.</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">12</span></font><font style=\"font-size: 13pt\">.36.02.38</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>142期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>05月21号，四月十四</font><font color=\'#000000\'>，吉日五行:泉中水;鸡日冲(己卯)兔 ");
document.writeln("	煞东 ,宿名：西方觜火猴</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:凶,五行:水行：12.13.20.21.28.29.42.43冲煞:兔鸡 煞东:兔虎龙,星宿杀肖：羊,综合：猴猪兔鸡牛狗龙</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">虎</span></font><font style=\"font-size: 13pt\">鼠 ");
document.writeln("	本期主攻:猴猪兔鸡牛，号码09.21.30.42.02.14.20.32.04.16</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("<!------------------------------插件代码结束-以下都不要-------------------------------------->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");