document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<META http-equiv=Content-Type content=\'text/html; charset=utf-8\'>");
document.writeln("<meta name=\'referrer\' content=\'never\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width,initial-scale=1, maximum-scale=1, user-scalable=no\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!------------------------------插件代码开始-以上都不要-------------------------------------->");
document.writeln("<style>");
document.writeln(".lhl { font-size: 14px; border-collapse: collapse; background: #f9f0df;}");
document.writeln(".lhl tr {}");
document.writeln(".lhl th { padding: 5px; font-size: 24px; background: #d2b493;}");
document.writeln(".lhl td { padding: 5px;}");
document.writeln(".lhl td.lhl-tit { background: #edd4be;}");
document.writeln(".lhl td.lhl-tit strong { color: #00f;}");
document.writeln(".lhl td.lhl-tit em { font-style: normal; color: #f00;}");
document.writeln(".lhl td span { background: #ff0;}");
document.writeln("</style>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'6\'>澳门资料·老黄历</font></b></table>");
document.writeln("");
document.writeln("<!--日历网址：https://www.8s8s.com/shop/list.php");
document.writeln("2024年五行号码：");
document.writeln("金行：02.03.10.11.24.25.32.33.40.41");
document.writeln("木行：06.07.14.15.22.23.36.37.44.45");
document.writeln("水行：12.13.20.21.28.29.42.43");
document.writeln("火行：01.08.09.16.17.30.31.38.39.46.47");
document.writeln("土行：04.05.18.19.26.27.34.35.48.49 -->");
document.writeln("");
document.writeln("<table class=\'lhl\' width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>072期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月12号，二月初三</font><font color=\'#000000\'>，吉日五行:山头火; 猪日冲(己巳)蛇煞西 ");
document.writeln("	,宿名：东方心月狐</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:大吉,五行:火行：01.08.09.16.17.30.31.38.39.46.47 冲煞:蛇猪 煞西:猴鸡狗,星宿杀肖：羊,综合：猴鼠狗马龙虎兔鸡蛇");
document.writeln("	本期主攻:猴鼠狗马龙，号码09.21.17.29.31.43.11.23.25.37</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>071期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月11号，二月初二</font><font color=\'#000000\'>，吉日五行:山头火; 狗日冲(戊辰)龙煞北 ");
document.writeln("	,宿名：东方心月狐</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:小吉,五行:火行：01.08.09.16.17.30.31.38.39.46.47 冲煞:龙狗 煞北:鼠猪牛,星宿杀肖：猴,综合：牛兔羊虎鼠鸡蛇狗猪 ");
document.writeln("	本期主攻:牛兔羊</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">虎</span></font><font style=\"font-size: 13pt\">鼠，号码16.28.14.38.22.34.15.39.29.41</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>070期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月10号，二月初一</font><font color=\'#000000\'>，吉日五行:剑锋金;鸡日冲(丁卯)兔煞东 ");
document.writeln("	,宿名：东方房日兔</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:大凶,五行:金行：02.03.10.11.24.25.32.33.40.41 冲煞:鸡兔 煞东:兔虎龙,星宿杀肖：鼠,综合：猴兔马鸡羊牛狗龙</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">猪</span></font><font style=\"font-size: 13pt\">");
document.writeln("	本期主攻:猴兔马鸡羊，号码09.21.14.38.23.35.20.32.10.34</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>069期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月09号，正月廿九</font><font color=\'#000000\'>，吉日五行:剑锋金;猴日冲(丙寅)虎煞南 ");
document.writeln("	,宿名：东方氐土貉</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:小凶,五行:金行：02.03.10.11.24.25.32.33.40.41 冲煞:虎猴 煞南:蛇马羊,星宿杀肖：鼠,综合：羊狗猴猪虎马</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">鸡</span></font><font style=\"font-size: 13pt\">牛兔 ");
document.writeln("	本期主攻:羊狗猴猪虎，号码10.22.31.43.09.21.18.30.15.39</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>068期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月08号，正月廿八</font><font color=\'#000000\'>，吉日五行:路旁土;羊日冲(乙丑)牛煞西 ");
document.writeln("	,宿名：东方亢金龙</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:大吉,五行:土行：04.05.18.19.26.27.34.35.48.495 冲煞:羊牛 煞西:猴鸡狗,星宿杀肖：牛,综合：蛇兔猴羊龙虎猪狗</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">鸡</span></font><font style=\"font-size: 13pt\">");
document.writeln("	本期主攻:蛇兔猴羊龙，号码12.36.02.14.09.21.10.22.13.49</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>067期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月07号，正月廿七</font><font color=\'#000000\'>，吉日五行:路旁土;马日冲(甲子)鼠煞北 ");
document.writeln("	,宿名：东方角木蛟</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:小凶,五行:土行：04.05.18.19.26.27.34.35.48.495 冲煞:马鼠 煞北:鼠猪牛,星宿杀肖：虎,综合：</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">羊</span></font><font style=\"font-size: 13pt\">蛇猪龙马鼠牛兔狗 ");
document.writeln("	本期主攻:</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">羊</span></font><font style=\"font-size: 13pt\">蛇猪龙马，号码22.</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">34</span></font><font style=\"font-size: 13pt\">.12.36.06.18.13.49.11.23</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>065期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月05号，正月廿五</font><font color=\'#000000\'>，吉日五行:大林木;龙日冲(壬戌)狗煞南 ");
document.writeln("	,宿名：南方翼火蛇</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:大吉,五行:木行：06.07.14.15.22.23.36.37.44.45 冲煞:龙狗煞南:蛇马羊,星宿杀肖：鸡,综合：蛇</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">牛</span></font><font style=\"font-size: 13pt\">羊猴狗鼠马兔猪 ");
document.writeln("	本期主攻:蛇</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">牛</span></font><font style=\"font-size: 13pt\">羊猴狗，号码12.36.16.40.22.34.21.33.07.43</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\' height=\"30\"><strong>064期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>03月04号，正月廿四</font><font color=\'#000000\'>，吉日五行:炉中火;兔日冲(辛酉)鸡煞西 ");
document.writeln("	,宿名：南方星日马</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font style=\"font-size: 13pt\">");
document.writeln("	预测:小凶,五行:火行：01.08.09.16.17.30.31.38.39.46.47 冲煞:鸡兔煞西:猴鸡狗,星宿杀肖：鼠,综合：鸡</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">羊</span></font><font style=\"font-size: 13pt\">虎马龙狗牛兔猴 ");
document.writeln("	本期主攻:鸡</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">羊</span></font><font style=\"font-size: 13pt\">虎马龙，号码08.20.22.34.15.39.23.47.13.49</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("<!------------------------------插件代码结束-以下都不要-------------------------------------->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");