document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<META http-equiv=Content-Type content=\'text/html; charset=utf-8\'>");
document.writeln("<meta name=\'referrer\' content=\'never\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width,initial-scale=1, maximum-scale=1, user-scalable=no\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!------------------------------插件代码开始-以上都不要-------------------------------------->");
document.writeln("<style>");
document.writeln(".lhl { font-size: 14px; border-collapse: collapse; background: #f9f0df;}");
document.writeln(".lhl tr {}");
document.writeln(".lhl th { padding: 5px; font-size: 24px; background: #d2b493;}");
document.writeln(".lhl td { padding: 5px;}");
document.writeln(".lhl td.lhl-tit { background: #edd4be;}");
document.writeln(".lhl td.lhl-tit strong { color: #00f;}");
document.writeln(".lhl td.lhl-tit em { font-style: normal; color: #f00;}");
document.writeln(".lhl td span { background: #ff0;}");
document.writeln("</style>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'6\'>澳门资料·老黄历</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<table class=\'lhl\' width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\'><strong>311期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>11月07号，九月");
document.writeln("	廿四</font><font color=\'#000000\'>，吉日五行:大林木;蛇日冲(癸亥)猪煞东 ");
document.writeln("	,廿八星宿：宿名：西方觜火猴</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font size=\'3\'>");
document.writeln("	预测:大吉,五行:木：05 06 13 14 21 22 35 36 43 44冲煞:猪蛇煞东:兔虎龙,星宿杀肖:羊,综合：蛇猴狗鼠兔虎马猪鸡 ");
document.writeln("	本期主攻:蛇猴狗鼠兔，号码11.23.08.20.18.30.04.40.25.49</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\'><strong>310期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>11月06号，九月");
document.writeln("	廿三</font><font color=\'#000000\'>，吉日五行:大林木;龙日冲(壬戌)狗煞南 ");
document.writeln("	,廿八星宿：宿名：西方毕月乌</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font size=\'3\'>");
document.writeln("	预测:大吉,五行:木：05 06 13 14 21 22 35 36 43 44冲煞:龙狗煞南:蛇马羊,星宿杀肖:龙,综合：</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">兔</span></font><font size=\'3\'>虎鼠猴马羊鸡猪蛇 ");
document.writeln("	本期主攻:</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">兔</span></font><font size=\'3\'>虎鼠猴马，号码</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">13</span></font><font size=\'3\'>.25.02.38.16.28.20.44.34.46</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\'><strong>309期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>11月05号，九月");
document.writeln("	廿二</font><font color=\'#000000\'>，吉日五行:炉中火;兔日冲(辛酉)鸡煞西 ");
document.writeln("	,廿八星宿：宿名：西方昴日鸡</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font size=\'3\'>");
document.writeln("	预测:小吉,五行:火：07 08 15 16 29 30 37 38 45 46冲煞:兔鸡煞西:猴鸡狗,星宿杀肖:牛,综合：猴龙狗牛虎</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">鼠</span></font><font size=\'3\'>猪鸡蛇 ");
document.writeln("	本期主攻:猴龙狗牛虎，号码08.20.12.36.18.42.15.39.14.38</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\'><strong>308期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>11月04号，九月");
document.writeln("	廿一</font><font color=\'#000000\'>，吉日五行:炉中火;虎日冲(庚申)猴煞北 ");
document.writeln("	,廿八星宿：宿名：西方胃土雉</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font size=\'3\'>");
document.writeln("	预测:小凶,五行:火：07 08 15 16 29 30 37 38 45 46冲煞:虎猴煞北:鼠猪牛,星宿杀肖:牛,综合：马兔猪鸡狗猴虎蛇</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">龙</span></font><font size=\'3\'>");
document.writeln("	本期主攻:马兔猪鸡狗，号码10.34.13.25.05.41.31.43.06.42</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\'><strong>307期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>11月03号，九月廿</font><font color=\'#000000\'>，吉日五行:海中金;牛日冲(己未)羊煞东 ");
document.writeln("	,廿八星宿：宿名：西方娄金狗</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font size=\'3\'>");
document.writeln("	预测:大吉,五行:金：01 02 09 10 23 24 31 32 39 40冲煞:牛羊煞东:兔虎龙,星宿杀肖:猴,综合：鸡龙</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">鼠</span></font><font size=\'3\'>马牛蛇虎兔羊 ");
document.writeln("	本期主攻:鸡龙</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">鼠</span></font><font size=\'3\'>马牛，号码31.43.12.48.04.40.10.22.15.39</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\'><strong>305期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>11月01号，九月十八</font><font color=\'#000000\'>，吉日五行:大海水;猪日冲(丁巳)蛇煞西 ");
document.writeln("	,廿八星宿：宿名：北方壁水貐</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font size=\'3\'>");
document.writeln("	预测:大吉,五行:水：11 12 19 20 27 28 41 42 49冲煞:猪蛇煞西:猴鸡狗,星宿杀肖:羊,综合：龙鼠狗虎蛇</font><font color=\"#FFFF00\" size=\"5\"><span style=\"font-weight: 700; background-color: #008000\">马</span></font><font size=\'3\'>牛兔猪 ");
document.writeln("	本期主攻:龙鼠狗虎蛇，号码12.36.04.40.18.30.02.38.23.47</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("<!--每期开始-->");
document.writeln("  <tr>");
document.writeln("    <td class=\'lhl-tit\'><strong>304期:<font color=\'#000000\'>开奖日</font><font color=\'#FF0000\'>10月31号，九月十七</font><font color=\'#000000\'>，吉日五行:大海水;狗日冲(丙辰)龙煞北 ");
document.writeln("	,廿八星宿：宿名：北方室火猪</font></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td><font size=\'3\'>");
document.writeln("	预测:小吉,五行:水：11 12 19 20 27 28 41 42 49冲煞:狗龙煞北:鼠猪牛,星宿杀肖:龙,综合：兔虎鸡羊狗马猴牛</font><font color=\"#FFFF00\" size=\"5\"><span style=\"background-color: #008000\">鼠</span></font><font size=\'3\'>");
document.writeln("	本期主攻:兔虎鸡羊狗，号码13.49.02.38.31.43.21.33.18.42</font></td>");
document.writeln("  </tr>");
document.writeln("<!--每期结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("<!------------------------------插件代码结束-以下都不要-------------------------------------->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");