document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>资料网62827</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『另版挂牌』</font></b></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>221期另版挂牌</font><font size=\'4\' color=\'#008000\'>【鱼龙混杂】</font><font color=\'#0033CC\'>开？00<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：甲辰日；五行属性：火；地支六冲：龙冲狗，无鼠；六合：鸡；三合：鼠猴。空亡肖：鼠狗。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：狗猪牛蛇马鸡猴虎龙<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：07.31.18.30.04.16.12.36.23.35.08.20.21.33.15.39.13.49</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>220期另版挂牌</font><font size=\'4\' color=\'#008000\'>【九牛一毛】</font><font color=\'#0033CC\'>开猴21<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：癸卯日；五行属性：金；地支六冲：兔冲鸡，无猪；六合：狗；三合：羊猪。空亡肖：羊鸡。。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：狗马虎鼠兔<span style=\'background-color: #FFFF00\'>猴</span>猪羊牛<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：31.43.11.23.03.15.05.17.14.38.<span style=\'background-color: #FFFF00\'>21</span>.33.06.30.22.34.04.16</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>219期另版挂牌</font><font size=\'4\' color=\'#008000\'>【走马观花】</font><font color=\'#0033CC\'>开兔14<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：壬寅日；五行属性：土；地支六冲：虎冲猴，无狗；六合：猪；三合：马狗。空亡肖：羊猴。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：<span style=\'background-color: #FFFF00\'>兔</span>马猪羊猴龙牛鼠蛇<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：02.<span style=\'background-color: #FFFF00\'>14</span>.23.35.18.30.22.34.09.21.13.49.04.16.17.41.24.48</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>218期另版挂牌</font><font size=\'4\' color=\'#008000\'>【四二相合】</font><font color=\'#0033CC\'>开龙37<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：辛丑日；五行属性：土；地支六冲：牛冲羊，无鸡；六合：鼠；三合：蛇鸡。空亡肖：虎羊。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猪羊蛇兔牛猴狗鸡<span style=\'background-color: #FFFF00\'>龙</span><br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：06.30.22.34.12.36.02.14.16.40.21.33.31.43.08.20.01.49</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>217期另版挂牌</font><font size=\'4\' color=\'#008000\'>【四二相合】</font><font color=\'#0033CC\'>开？00<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：庚子日；五行属性：土；地支六冲：鼠冲马，无鸡；六合：牛；三合：龙猴。空亡肖：虎马。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猴马羊<span style=\'background-color: #FFFF00\'>虎</span>狗鼠猪牛蛇<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：09.21.23.35.10.22.03.<span style=\'background-color: #FFFF00\'>15</span>.31.43.05.41.30.42.04.16.12.36</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>216期另版挂牌</font><font size=\'4\' color=\'#008000\'>【湖中涌泉】</font><font color=\'#0033CC\'>开虎15<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：己亥日；五行属性：木；地支六冲：猪冲蛇，无猴；六合：虎；三合：兔羊。空亡肖：猪猴。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猪鼠牛龙<span style=\'background-color: #FFFF00\'>虎</span>羊鸡蛇马<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：18.30.05.41.16.40.13.25.03.<span style=\'background-color: #FFFF00\'>15</span>.22.34.20.32.12.36.23.35</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>215期另版挂牌</font><font size=\'4\' color=\'#008000\'>【湖中涌泉】</font><font color=\'#0033CC\'>开鸡20<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：戊戌日；五行属性：木；地支六冲：狗冲龙，无鼠；六合：兔；三合：马虎。空亡肖：虎龙。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：兔马狗<span style=\'background-color: #FFFF00\'>鸡</span>蛇牛龙虎猪<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：02.14.11.23.31.43.08.<span style=\'background-color: #FFFF00\'>20</span>.12.36.16.40.13.49.03.15.18.30</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>214期另版挂牌</font><font size=\'4\' color=\'#008000\'>【赶尽杀绝】</font><font color=\'#0033CC\'>开猪06<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：丁酉日；五行属性：火；地支六冲：鸡冲兔，无蛇；六合：龙；三合：牛蛇。空亡肖：兔猪。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：羊鸡蛇龙马猴虎<span style=\'background-color: #FFFF00\'>猪</span>兔<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：10.22.08.20.12.36.13.49.11.23.09.21.15.39.18.30.02.14</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");


document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>213期另版挂牌</font><font size=\'4\' color=\'#008000\'>【欲横沙场】</font><font color=\'#0033CC\'>开兔38<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：丙申日；五行属性：火；地支六冲：猴冲虎，无龙；六合：蛇；三合：鼠龙。空亡肖：虎猪。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：羊<span style=\'background-color: #FFFF00\'>兔</span>猪龙马鼠鸡猴牛<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：10.22.02.14.18.30.11.23.05.41.20.32.21.33.04.16</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");


document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>212期另版挂牌</font><font size=\'4\' color=\'#008000\'>【厉兵秣马】</font><font color=\'#0033CC\'>开龙49<br>");
document.writeln("	</font><font color=\'#000000\'>");
document.writeln("◎生肖属性：乙未日；五行属性：金；地支六冲：羊冲牛，无狗；六合：马；三合：猪兔。空亡肖：龙蛇。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：兔<span style=\'background-color: #FFFF00\'>龙</span>蛇鸡羊猴狗鼠猪<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：02.14.13.<span style=\'background-color: #FFFF00\'>49</span>.12.36.20.32.22.34.09.21.31.43.05.41.30.42</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</div>");