document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>资料网62361</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『另版挂牌』</font></b></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>348期另版挂牌</font><font size=\'4\' color=\'#008000\'>【才高八斗】</font><font color=\'#0033CC\'>开？00<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：丙午日 属性：木 地支六冲：马日：冲鼠，克牛，破牛，无虎； 六合：羊；三合：虎狗。空亡肖：鼠鸡</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：虎龙鼠牛猴羊狗鸡猪<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：02.38.12.48.04.40.15.39.08.20.21.33.30.42.19.43.05.41</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>347期另版挂牌</font><font size=\'4\' color=\'#008000\'>【牛鬼蛇神】</font><font color=\'#0033CC\'>开？00<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：乙巳日：五行属性：火：地支六冲：蛇冲猪无牛：六合：猴：三合：牛鸡。空亡肖：虎猪。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：鼠鸡猴龙兔蛇猪<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">鸡</span></font>虎<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：04.40.31.43.08.20.12.36.13.49.11.23.05.41.10.34.14.38</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>345期另版挂牌</font><font size=\'4\' color=\'#008000\'>【一前七后】</font><font color=\'#0033CC\'>开鸡07<br>");
document.writeln("	</font><font color=\'#000000\'>生肖屬性：◎生肖属性：癸卯日 属性：木 地支六冲：兔日：冲鸡，克龙，破狗，无猪； 六合：狗；三合：羊猪。空亡肖：羊鸡</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：羊牛猴<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">鸡</span></font>马虎蛇猪兔<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：09.45.15.39.08.20.19.43.02.38.11.35.05.29.01.49</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>344期另版挂牌</font><font size=\'4\' color=\'#008000\'>【五谷丰登】</font><font color=\'#0033CC\'>开蛇47<br>");
document.writeln("	</font><font color=\'#000000\'>生肖屬性：壬寅日 属性：火 地支六冲：虎日：冲猴，克蛇，破鸡，无狗； 六合：猪；三合：马狗。空亡肖：猴猪</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猴<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">蛇</span></font>兔鼠猪鸡狗虎羊<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：08.20.11.23.01.49.16.28.17.41.31.43.06.18.02.38.09.45</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>343期另版挂牌</font><font size=\'4\' color=\'#008000\'>【五谷丰登】</font><font color=\'#0033CC\'>开？00<br>");
document.writeln("	</font><font color=\'#000000\'>生肖屬性：辛丑日 屬性：水（鼠猪） 地支六沖：牛日：沖羊，克馬，破猴，無雞， 六合：鼠；三合：蛇雞。空亡肖：羊雞</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：鼠猪牛羊马猴鸡狗</font><font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">兔</span></font><font size=\'3\' color=\'#FF0000\'><br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：04.40.05.41.15.39.21.33.10.34.08.20.31.43.06.30.13.49</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</div>");