document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>资料网62361</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『另版挂牌』</font></b></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>338期另版挂牌</font><font size=\'4\' color=\'#008000\'>【人中豪杰】</font><font color=\'#0033CC\'>开？00<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性： ◎生肖属性：戊申日；五行属性：土（牛羊龙狗）；地支六冲：猴冲虎无龙；六和：蛇；三合：鼠龙。空亡肖：兔虎。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：牛羊龙狗猴虎蛇鼠兔<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：15.39.09.45.12.36.30.42.08.20.14.26.23.47.04.40.13.49</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>337期另版挂牌</font><font size=\'4\' color=\'#008000\'>【暴虎冯河】</font><font color=\'#0033CC\'>开鼠16<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性： 乙未日 属性：木（虎兔） 地支六冲：羊日：冲牛，克鼠，破虎，无兔； 六合：马；三合：兔猪。空亡肖：牛鸡</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：虎兔羊牛<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">鼠</span></font>马猪鸡狗<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：02.14.25.37.21.33.15.39.04.40.22.34.05.41.31.43.18.42</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>336期另版挂牌</font><font size=\'4\' color=\'#008000\'>【三面楚歌】</font><font color=\'#0033CC\'>开鸡31<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：甲午日 属性：金（猴鸡） 地支六冲：马日：冲鼠，克牛，破牛，无虎； 六合：羊；三合：虎狗。空亡肖：鼠龙。</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猴<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">鸡</span></font>马鼠牛虎羊狗龙<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：08.20.<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">31</span></font>.43.10.34.04.40.15.39.02.38.21.33.30.42.12.48</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>334期另版挂牌</font><font size=\'4\' color=\'#008000\'>【分合有术】</font><font color=\'#0033CC\'>开？00<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：壬辰日 属性：金（猴鸡） 地支六冲：龙日：冲狗，克兔，破猪，无鼠， 六合：鸡；三合：鼠猴。空亡肖：鸡狗</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猴鸡<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">狗</span></font>兔猪鼠马羊牛<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：08.20.31.43.18.30.25.49.15.39.04.40.34.46.21.33.15.39</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>333期另版挂牌</font><font size=\'4\' color=\'#008000\'>【五谷丰登】</font><font color=\'#0033CC\'>开兔37<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：辛卯日 属性：木（虎兔） 地支六冲：兔日：冲鸡，克龙，破狗，无猪； 六合：狗；三合：羊猪。空亡肖：羊鸡</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：虎<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">兔</span></font>鸡龙狗猪羊蛇马<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：14.38.13.49.31.43.12.36.30.42.17.41.21.33.23.47.34.46</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>332期另版挂牌</font><font size=\'4\' color=\'#008000\'>【一马当先】</font><font color=\'#0033CC\'>开猴08<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：庚寅日 属性：火（虎兔） 地支六冲：虎日：冲猴，克蛇，破鸡，无狗； 六合：猪；三合：马狗。空亡肖：猴猪</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：虎兔<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">猴</span></font>蛇鸡狗猪马羊<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：02.14.13.25.32.44.11.23.31.43.06.30.05.41.10.34.21.33</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>331期另版挂牌</font><font size=\'4\' color=\'#008000\'>【各不相见】</font><font color=\'#0033CC\'>开马46<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：乙丑日 属性：金（猴鸡） 地支六冲：牛日：冲羊，克马，破猴，无鸡， 六合：鼠；三合：蛇鸡。空亡肖：羊蛇</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猴鸡牛羊<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">马</span></font>鼠蛇虎兔<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：08.20.31.43.15.39.21.33.10.<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">46</span></font>.16.40.11.23.02.38.13.49</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>330期另版挂牌</font><font size=\'4\' color=\'#008000\'>【绿林暴容】</font><font color=\'#0033CC\'>开狗18<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性：戊子日；五行属性：土（牛羊龙狗）；地支六冲：鼠冲马无猴；六合：牛；三合：猴龙。空亡肖：虎马</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：牛羊龙<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">狗</span></font>鼠猴虎马猪<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：15.39.21.33.12.36.30.42.04.16.32.44.02.38.10.34.05.41</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>329期另版挂牌</font><font size=\'4\' color=\'#008000\'>【威镇一方】</font><font color=\'#0033CC\'>开蛇35<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖屬性：丁亥日 屬性：金（猴鸡） 地支六沖：豬日：沖蛇，克猴，破馬，無羊； 六合：虎；三合：兔羊。空亡肖：兔蛇</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：猴鸡猪<font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">蛇</span></font>羊马虎兔狗<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：08.20.31.43.05.41.11.23.21.33.10.34.02.38.13.49.06.30</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>");
document.writeln("	<p><font color=\'#0033CC\'>328期另版挂牌</font><font size=\'4\' color=\'#008000\'>【一举两得】</font><font color=\'#0033CC\'>开兔01<br>");
document.writeln("	</font><font color=\'#000000\'>◎生肖属性： 丙戌日 属性：木（虎兔） 地支六冲：狗日冲龙无马； 六合：兔；三合：虎马。空亡肖：龙蛇</p>");
document.writeln("	</font>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特肖：虎</font><font size=\'5\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">兔</span></font><font size=\'3\' color=\'#FF0000\'>狗龙马蛇鸡猪牛<br>");
document.writeln("	</p>");
document.writeln("	<font size=\'3\' color=\'#FF0000\'>推荐特码：14.38.13.49.30.42.24.36.34.46.11.23.31.43.05.41.15.39</font></font></div>");
document.writeln("    </td></tr>");
document.writeln("   <!--结束-->");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</div>");