document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>雷锋站长</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『澳彩心水』</font></b></table>");
document.writeln("      ");
document.writeln("");

document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第053期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("羊11.23狗20.44鼠06.18<br>");
document.writeln("马24.36兔03.15牛29.41<br>");
document.writeln("猴10.22蛇01.37虎16.40<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第052期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("牛17.41兔15.39鼠06.18<br>");
document.writeln("蛇25.37鸡09.21龙26.38<br>");
document.writeln("马12.36<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猴10</span></font>.22虎16.40<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第051期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("兔27.39马12.36牛05.17<br>");
document.writeln("鼠30.42龙14.38鸡21.45<br>");
document.writeln("猪31.43狗20.44<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>13.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">49</span></font><br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln(" <!--开始-->  ");





document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("  </table>");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://xn--secaq5b.xn--0dcaaz1ff5bzcvdxdtb1af.xn--gecrj9c:8443/#62827\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57386</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </div>　");
document.writeln("  </body>");