document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>雷锋站长</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『澳彩心水』</font></b></table>");
document.writeln("      ");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></b></p></a></td></tr>");
document.writeln("");


document.writeln("");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第203期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    牛04.40猪30.42马11.23<br>");
document.writeln("		龙13.49狗31.43羊22.34<br>");
document.writeln("		鸡08.20蛇12.36虎15.39<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln("");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第202期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    鼠05.17蛇12.36虎03.15<br>");
document.writeln("		牛28.40马23.47龙25.37<br>");
document.writeln("		猴09.21<span style=\'background-color: #FFFF00\'>狗</span>31.<span style=\'background-color: #FFFF00\'>43</span>兔02.14<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第201期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    羊10.22<span style=\'background-color: #FFFF00\'>龙</span>13.<span style=\'background-color: #FFFF00\'>25</span>鼠05.17<br>");
document.writeln("		牛16.28马11.23兔02.14<br>");
document.writeln("		猪30.42鸡20.32狗19.43<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln("");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第199期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    <span style=\'background-color: #FFFF00\'>虎15</span>.27马23.47鼠05.41<br>");
document.writeln("		狗31.43猪06.42鸡20.32<br>");
document.writeln("		龙13.49牛04.16兔02.14<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln("");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第197期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    兔02.14蛇24.36马23.35<br>");
document.writeln("		龙13.25猪30.42鸡20.44<br>");
document.writeln("		<span style=\'background-color: #FFFF00\'>羊</span>22.34牛04.16猴21.33<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第196期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    狗07.31鸡20.44猴21.33<br>");
document.writeln("		龙01.13兔02.14<span style=\'background-color: #FFFF00\'>虎</span>15.27<br>");
document.writeln("		马11.23鼠05.17蛇12.36<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("  </table>");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://xn--secaq5b.xn--0dcaaz1ff5bzcvdxdtb1af.xn--gecrj9c:8443/#62827\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57386</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </div>　");
document.writeln("  </body>");