document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>雷锋站长</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『澳彩心水』</font></b></table>");
document.writeln("      ");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("");


document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第327期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    狗06.30牛15.39虎02.14<br>");
document.writeln("		猪17.41马22.46蛇23.47<br>");
document.writeln("		猴08.20鼠16.28龙24.36<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第326期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    <font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">蛇</span></font>11.23猴08.20狗30.42<br>");
document.writeln("		兔13.49鸡19.43猪05.41<br>");
document.writeln("		羊21.33虎02.38龙12.36<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第324期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    牛15.39<font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">虎</span></font>14.38鼠28.40<br>");
document.writeln("		猴20.44马10.46狗30.42<br>");
document.writeln("		龙12.48猪05.41鸡31.43<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第323期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    狗06.30龙12.48<font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">虎02</span></font>.38<br>");
document.writeln("		蛇11.23猴08.20羊21.33<br>");
document.writeln("		马10.34牛15.39兔13.49<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");
document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第322期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    牛15.39龙12.36马22.46<br>");
document.writeln("		<font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">猴</span></font>08.20虎14.38鸡31.43<br>");
document.writeln("		蛇11.23猪05.17鼠16.28<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第321期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    兔13.49牛15.39蛇23.35<br>");
document.writeln("		马10.34龙15.27鼠04.40<br>");
document.writeln("		羊33.45<font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">鸡</span></font>07.43猴20.32<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第320期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    <font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">蛇23</span></font>.35猴08.20狗18.30<br>");
document.writeln("		羊21.45鼠16.28鸡07.43<br>");
document.writeln("		牛03.27虎14.26猪29.41<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第319期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    牛15.27<font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">狗</span></font>30.<font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">42</span></font>蛇11.35<br>");
document.writeln("		羊21.45马10.34猪17.29<br>");
document.writeln("		鼠16.28鸡07.43猴20.32<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");

document.writeln(" <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'4\'>第318期<font color=\'#FF00FF\'>【雷锋站长独家心水】</font></font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' size=\'5\' color=\'#0000FF\'>");
document.writeln("		【参考18码】<br>");
document.writeln("	    猪17.41狗06.18猴20.44<br>");
document.writeln("		蛇23.47马22.34<font face=\'隶书\' size=\'6\' color=\'#FF0000\'><span style=\"background-color: #FFFF00\">兔</span></font>13.37<br>");
document.writeln("		鼠28.40虎26.38羊09.21<br>");
document.writeln("		  </font>  ");
document.writeln("	");
document.writeln("		</b></td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->  ");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("  </table>");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://mnbvctrs.www58317a.com:888/#62102\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57185</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </div>　");
document.writeln("  </body>");