document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>62102b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『老胡18码』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>208期<font color=\'#800000\'>【隔壁老胡18码】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#FF0000\'>？00</font>准<font color=\'#000000\'><br>");
document.writeln("		</font> <font color=\'#008000\'>");
document.writeln("		【39.22.30.16.18.36.04.15.47】<br>");
document.writeln("		【01.41.49.29.35.43.33.13.40】</font><font color=\'#0000FF\'> </font> </span>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");
document.writeln("");

document.writeln("   <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>206期<font color=\'#800000\'>【隔壁老胡18码】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#FF0000\'>虎38</font>准<font color=\'#000000\'><br>");
document.writeln("		</font> <font color=\'#008000\'>");
document.writeln("		【20.06.08.41.42.48.10.<span style=\'background-color: #FFFF00\'>38</span>.27】<br>");
document.writeln("		【49.45.30.37.07.05.31.02.40】</font><font color=\'#0000FF\'> </font> </span>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>202期<font color=\'#800000\'>【隔壁老胡18码】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#FF0000\'>鼠04</font>准<font color=\'#000000\'><br>");
document.writeln("		</font> <font color=\'#008000\'>");
document.writeln("		【34.39.35.02.20.24.25.<span style=\'background-color: #FFFF00\'>04</span>.44】<br>");
document.writeln("		【19.40.23.31.09.49.43.06.38】</font><font color=\'#0000FF\'> </font> </span>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>201期<font color=\'#800000\'>【隔壁老胡18码】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#FF0000\'>牛03</font>准<font color=\'#000000\'><br>");
document.writeln("		</font> <font color=\'#008000\'>");
document.writeln("		【29.08.07.<span style=\'background-color: #FFFF00\'>03</span>.11.20.05.23.31】<br>");
document.writeln("		【12.30.06.39.34.13.19.09.49】</font><font color=\'#0000FF\'> </font> </span>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'center\'><b>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'>199期<font color=\'#800000\'>【隔壁老胡18码】</font></font><span style=\'font-size: 14pt\'>开<font color=\'#FF0000\'>猴08</font>准<font color=\'#000000\'><br>");
document.writeln("		</font> <font color=\'#008000\'>");
document.writeln("		【34.23.24.49.<span style=\'background-color: #FFFF00\'>08</span>.39.16.19.15】<br>");
document.writeln("		【02.42.22.20.38.40.48.37.13】</font><font color=\'#0000FF\'> </font> </span>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln(" <!--结束--> ");



document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://www.65935c.com#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://493388.com/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>65935.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");