document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<style>");
document.writeln(".bzlx { font-size: 18px; text-align: center;white-space: normal; background: #fff;}");
document.writeln(".bzlx th { height: 60px; border: 1px solid #1f9b7d; color: #fff; background: #1f9b7d;}");
document.writeln(".bzlx td { height: 60px; border: 1px solid #df0000; font-weight: bold;}");
document.writeln(".bzlx td:nth-child(2){ color: #00f;}");
document.writeln(".bzlx td span { color: #f00; background: #ff0;}");
document.writeln("@media screen and (max-width:720px){");
document.writeln(".bzlx { font-size: 16px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'box pad\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'0\' width=\'100%\' bordercolor=\'#008000\'>");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\'#C0C0C0\'>");
document.writeln("		<div style=\"background-color: #FFFF00\">");
document.writeln("		<div style=\"background-color: #FFFFFF\">");
document.writeln("		<p align=\'center\'>");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("<b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("<a target=\"_blank\" href=\"https://x15.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#dbtt\">");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("		");
document.writeln("		<font style=\"text-decoration: none\" size=\"5\">");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("【我是牛马】(综合特码)</font><br><font style=\"font-size: 14pt; text-decoration: none\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("143期：18.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">10</span></font>.12.16.28.20.22.26<br><br>");
document.writeln("144期：48.09.06.03.45.42<br><br>");

document.writeln("");
document.writeln("</font></a>		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("		</div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("<p align=\'center\'><span style=\"text-decoration: none; font-weight:700\">");
document.writeln("<a target=\"_blank\" href=\"https://x15.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#dbtt\">");
document.writeln("<font color=\"#000000\" size=\"4\">进入澳门资料网首页查看更多记录</font></a></span><p align=\'center\'>");
document.writeln("		<span style=\"text-decoration: none; font-weight:700\">");
document.writeln("		<a target=\"_blank\" href=\"https://x15.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#dbtt\"><font size=\"4\" color=\"#000000\">谨记网址</font><font size=\"4\" color=\"#FF0000\">【a.62785.com】</font></a></span></p></td>");
document.writeln("	</tr>");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");