document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<style>");
document.writeln(".bzlx { font-size: 18px; text-align: center;white-space: normal; background: #fff;}");
document.writeln(".bzlx th { height: 60px; border: 1px solid #1f9b7d; color: #fff; background: #1f9b7d;}");
document.writeln(".bzlx td { height: 60px; border: 1px solid #df0000; font-weight: bold;}");
document.writeln(".bzlx td:nth-child(2){ color: #00f;}");
document.writeln(".bzlx td span { color: #f00; background: #ff0;}");
document.writeln("@media screen and (max-width:720px){");
document.writeln(".bzlx { font-size: 16px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'box pad\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'0\' width=\'100%\' bordercolor=\'#008000\'>");
document.writeln("");
document.writeln("");
document.writeln("    <tr>");
document.writeln("    <td class=\'ymgg-tit1\' bgcolor=\"#FF0000\">");
document.writeln("	<p align=\'center\'><font style=\"font-size: 16pt; font-weight: 700\">");
document.writeln("	271-275期特码:（五期必中）</font><font color=\"#FFFF00\"><span style=\"font-size: 16pt\"><br>");
document.writeln("	</span><font style=\"font-size: 18pt; font-weight: 700\">");
document.writeln("	02.09.13.23.25.38.<span style=\'background-color: #000000\'>44</span>.<span style=\"background-color: #000000\">45</span> ");
document.writeln("	 </font>");
document.writeln("	</font></font></td>");
document.writeln("  </tr>");
document.writeln("  ");
document.writeln("      <tr>");
document.writeln("    <td class=\'ymgg-tit1\' bgcolor=\"#FF0000\">");
document.writeln("	<p align=\'center\'><font style=\"font-size: 16pt; font-weight: 700\">");
document.writeln("	276-280期特码:（五期必中）</font><font color=\"#FFFF00\"><span style=\"font-size: 16pt\"><br>");
document.writeln("	</span><font style=\"font-size: 18pt; font-weight: 700\">");
document.writeln("	02.<span style=\'background-color: #000000\'>09</span>.13.23.25.38.44.45");
document.writeln("	 </font>");
document.writeln("	</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("  ");
document.writeln("      <tr>");
document.writeln("    <td class=\'ymgg-tit1\' bgcolor=\"#FF0000\">");
document.writeln("	<p align=\'center\'><font style=\"font-size: 16pt; font-weight: 700\">");
document.writeln("	281-285期特码:（五期必中）</font><font color=\"#FFFF00\"><span style=\"font-size: 16pt\"><br>");
document.writeln("	</span><font style=\"font-size: 18pt; font-weight: 700\">");
document.writeln("	02.09.13.23.25.38.44.<span style=\'background-color: #000000\'>45</span>");
document.writeln("	 </font>");
document.writeln("	</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("  ");
document.writeln("      <tr>");
document.writeln("    <td class=\'ymgg-tit1\' bgcolor=\"#FF0000\">");
document.writeln("	<p align=\'center\'><font style=\"font-size: 16pt; font-weight: 700\">");
document.writeln("	286-290期特码:（五期必中）</font><font color=\"#FFFF00\"><span style=\"font-size: 16pt\"><br>");
document.writeln("	</span><font style=\"font-size: 18pt; font-weight: 700\">");
document.writeln("	02.09.13.23.25.38.44.45");
document.writeln("	 </font>");
document.writeln("	</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("	<tr>");
document.writeln("		<td>");
document.writeln("		<div style=\"background-color: #FFFF00\">");
document.writeln("		<div style=\"background-color: #FFFFFF\">");
document.writeln("		<p align=\'center\'>");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("<b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("<a target=\"_blank\" href=\"https://x626969.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#g5\">");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("		");
document.writeln("		<font style=\"text-decoration: none\" size=\"5\" color=\"#000000\">");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("澳彩资料网『单双中特』</font><br>");
document.writeln("<font style=\"font-size: 18pt; text-decoration: none\"><br>");
document.writeln("");
document.writeln("");
document.writeln("<font color=\"#FF0000\">点击进入首页查看更多记录</font><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!----开始--->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font size=\'3\'>");
document.writeln("<span style=\'color: #00F;\'>291期</span>:<span style=\'color: #800000;\'>精准单双</span>〖<span style=\'color: #F00;\'>单数</span>〗开：<span style=\'background-color: #FFFF00; color: #F00;\'>？00准</span></font></td></tr>");
document.writeln("<!-----结束--->");
document.writeln("<!----开始--->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font size=\'3\'>");
document.writeln("<span style=\'color: #00F;\'>290期</span>:<span style=\'color: #800000;\'>精准单双</span>〖<span style=\'color: #F00;\'>单数</span>〗开：<span style=\'background-color: #FFFF00; color: #F00;\'>猪19准</span></font></td></tr>");
document.writeln("<!-----结束--->");
document.writeln("");
document.writeln("<!----开始--->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font size=\'3\'>");
document.writeln("<span style=\'color: #00F;\'>289期</span>:<span style=\'color: #800000;\'>精准单双</span>〖<span style=\'color: #F00;\'>双数</span>〗开：<span style=\'background-color: #FFFF00; color: #F00;\'>鼠42准</span></font></td></tr>");
document.writeln("<!-----结束--->");
document.writeln("");
document.writeln("<!----开始--->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font size=\'3\'>");
document.writeln("<span style=\'color: #00F;\'>288期</span>:<span style=\'color: #800000;\'>精准单双</span>〖<span style=\'color: #F00;\'>双数</span>〗开：<span style=\'background-color: #FFFF00; color: #F00;\'>龙14准</span></font></td></tr>");
document.writeln("<!-----结束--->");
document.writeln("");
document.writeln("<!----开始--->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font size=\'3\'>");
document.writeln("<span style=\'color: #00F;\'>287期</span>:<span style=\'color: #800000;\'>精准单双</span>〖<span style=\'color: #F00;\'>双数</span>〗开：<span style=\'background-color: #FFFF00; color: #F00;\'>猴34准</span></font></td></tr>");
document.writeln("<!-----结束--->");
document.writeln("");
document.writeln("<!----开始--->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font size=\'3\'>");
document.writeln("<span style=\'color: #00F;\'>286期</span>:<span style=\'color: #800000;\'>精准单双</span>〖<span style=\'color: #F00;\'>单数</span>〗开：<span style=\'background-color: #FFFF00; color: #F00;\'>兔03准</span></font></td></tr>");
document.writeln("<!-----结束--->");
document.writeln("");
document.writeln("<!----开始--->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:2px solid #000\' align=center width=100% height=50>");
document.writeln("<font size=\'3\'>");
document.writeln("<span style=\'color: #00F;\'>285期</span>:<span style=\'color: #800000;\'>精准单双</span>〖<span style=\'color: #F00;\'>双数</span>〗开：<span style=\'background-color: #FFFF00; color: #F00;\'>马24准</span></font></td></tr>");
document.writeln("<!-----结束--->");
document.writeln("");
document.writeln("");
document.writeln("		</font>		</font>	");
document.writeln("");
document.writeln("");
document.writeln("</a>");
document.writeln("</div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("<p align=\'center\'><span style=\"text-decoration: none; font-weight:700\">");
document.writeln("<a target=\"_blank\" href=\"https://x626969.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#g5\">");
document.writeln("<font color=\"#000000\" size=\"4\">进入澳门资料网论坛查看更多记录</font></a></span><p align=\'center\'>");
document.writeln("		<span style=\"text-decoration: none; font-weight:700\">");
document.writeln("		<a target=\"_blank\" href=\"https://x626969.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#g5\"><font size=\"4\" color=\"#000000\">谨记网址</font><font size=\"4\" color=\"#FF0000\">【a.62785.com】</font></a></span></p>");
document.writeln("		");
document.writeln("		</td>");
document.writeln("	</tr>");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("<!--结束-->");
document.writeln("");