document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<style>");
document.writeln(".bzlx { font-size: 18px; text-align: center;white-space: normal; background: #fff;}");
document.writeln(".bzlx th { height: 60px; border: 1px solid #1f9b7d; color: #fff; background: #1f9b7d;}");
document.writeln(".bzlx td { height: 60px; border: 1px solid #df0000; font-weight: bold;}");
document.writeln(".bzlx td:nth-child(2){ color: #00f;}");
document.writeln(".bzlx td span { color: #f00; background: #ff0;}");
document.writeln("@media screen and (max-width:720px){");
document.writeln(".bzlx { font-size: 16px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'box pad\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'0\' width=\'100%\' bordercolor=\'#008000\'>");
document.writeln("");
document.writeln("");
document.writeln("    <tr>");
document.writeln("    <td class=\'ymgg-tit1\' bgcolor=\"#FF0000\">");
document.writeln("	<p align=\'center\'><font style=\"font-size: 16pt; font-weight: 700\">");
document.writeln("	206-210期特码:（五期必中）</font><font color=\"#FFFF00\"><span style=\"font-size: 16pt\"><br>");
document.writeln("	</span><font style=\"font-size: 18pt; font-weight: 700\">02.<span style=\"background-color: #000000\">09.13</span>.23.25.38.44.45 ");
document.writeln("	 </font>");
document.writeln("	</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("    <tr>");
document.writeln("    <td class=\'ymgg-tit1\' bgcolor=\"#FF0000\">");
document.writeln("	<p align=\'center\'><font style=\"font-size: 16pt; font-weight: 700\">");
document.writeln("	211-215期特码:（五期必中）</font><font color=\"#FFFF00\"><span style=\"font-size: 16pt\"><br>");
document.writeln("	</span><font style=\"font-size: 18pt; font-weight: 700\">");
document.writeln("	<span style=\"background-color: #000000\">02</span>.09.13.23.25.38.44.45 ");
document.writeln("	 </font>");
document.writeln("	</font></font></td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("    <tr>");
document.writeln("    <td class=\'ymgg-tit1\' bgcolor=\"#FF0000\">");
document.writeln("	<p align=\'center\'><font style=\"font-size: 16pt; font-weight: 700\">");
document.writeln("	216-220期特码:（五期必中）</font><font color=\"#FFFF00\"><span style=\"font-size: 16pt\"><br>");
document.writeln("	</span><font style=\"font-size: 18pt; font-weight: 700\">");
document.writeln("	02.09.13.<span style=\"background-color: #000000\">23</span>.25.38.44.45 ");
document.writeln("	 </font>");
document.writeln("	</font></font></td>");
document.writeln("  </tr>");



document.writeln("	<tr>");
document.writeln("		<td>");
document.writeln("		<div style=\"background-color: #FFFF00\">");
document.writeln("		<div style=\"background-color: #FFFFFF\">");
document.writeln("		<p align=\'center\'>");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("<b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("<a target=\"_blank\" href=\"https://x18.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#dbtt\">");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("		");
document.writeln("		<font style=\"text-decoration: none\" size=\"5\" color=\"#000000\">");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("赚点小钱【两面投资】</font><br><font style=\"font-size: 16pt; text-decoration: none\"><br>");
document.writeln("");
document.writeln("");

document.writeln("215期【家禽】(投资500元<font color=\"#FF0000\">盈</font>)<font color=\"#FF0000\">猪羊狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font></font><br>");

document.writeln("216期【家禽】(投资500元<font color=\"#FF0000\">盈</font>)<font color=\"#FF0000\">牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">羊</span></font>马猪</font><br>");

document.writeln("217期【野兽】(投资500元<font color=\"#FF0000\">盈</font>)<font color=\"#FF0000\">龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猴</span></font>虎兔</font><br>");

document.writeln("218期【家禽】(投资500元<font color=\"#FF0000\">？</font>)<font color=\"#FF0000\">牛马狗猪</font><br>");




document.writeln("</font></a>		");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</font><br>");
document.writeln("<!--一段结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("		</div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("<p align=\'center\'><span style=\"text-decoration: none; font-weight:700\">");
document.writeln("<a target=\"_blank\" href=\"https://x18.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#dbtt\">");
document.writeln("<font color=\"#000000\" size=\"4\">进入澳门资料网首页查看更多记录</font></a></span><p align=\'center\'>");
document.writeln("		<span style=\"text-decoration: none; font-weight:700\">");
document.writeln("		<a target=\"_blank\" href=\"https://x18.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#dbtt\"><font size=\"4\" color=\"#000000\">谨记网址</font><font size=\"4\" color=\"#FF0000\">【a.62785.com】</font></a></span></p>");
document.writeln("		");
document.writeln("		</td>");
document.writeln("	</tr>");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");