document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>职业玩家</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【解龙门客栈】</font></b></table>");
document.writeln("           ");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\' height=\'200\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                                        <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<span style=\'font-weight: 700\'><font face=\'微软雅黑\'>168期：【职业玩家】破解龙门客栈</font><br>");
document.writeln("		<font face=\'华文楷体\'><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>掌柜：【单枪匹马】<br>小二：【客官，今天休息呀】<br>");
document.writeln("		客官：【是啊，难得】</font></font></font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=34 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>解：单枪匹马，解单肖猴虎龙马鼠狗</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\'  bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'华文楷体\' style=\'font-size: 14pt; font-weight:700\' color=\'#008000\'>");
document.writeln("				综合特肖：猴虎龙马鼠狗</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999zx.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("                                        <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<span style=\'font-weight: 700\'><font face=\'微软雅黑\'>166期：【职业玩家】破解龙门客栈</font><br>");
document.writeln("		<font face=\'华文楷体\'><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>掌柜：【信口开河】<br>小二：【客官，吃饭还是住店】<br>");
document.writeln("		客官：【来吃点便饭】</font></font></font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=34 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>解：信口开河，解狗鸡猴虎兔猪</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\'  bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'华文楷体\' style=\'font-size: 14pt; font-weight:700\' color=\'#008000\'>");
document.writeln("				综合特肖：狗<span style=\'background-color: #FFFF00\'>鸡</span>猴虎兔猪</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999zx.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("                                        <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<span style=\'font-weight: 700\'><font face=\'微软雅黑\'>164期：【职业玩家】破解龙门客栈</font><br>");
document.writeln("		<font face=\'华文楷体\'><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>掌柜：【平分秋色】<br>小二：【客官，今天吃点什么】<br>");
document.writeln("		客官：【清蒸鱼，红烧土鸡】</font></font></font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=34 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>解：平分秋色，解秋肖猴鸡狗</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\'  bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'华文楷体\' style=\'font-size: 14pt; font-weight:700\' color=\'#008000\'>");
document.writeln("				综合特肖：猴<span style=\'background-color: #FFFF00\'>鸡</span>狗鼠猪牛</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999zx.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("                                        <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<span style=\'font-weight: 700\'><font face=\'微软雅黑\'>163期：【职业玩家】破解龙门客栈</font><br>");
document.writeln("		<font face=\'华文楷体\'><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>掌柜：【时来运转】<br>小二：【客官，今天有新菜哦】<br>");
document.writeln("		客官：【可以的，上来试试】</font></font></font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=34 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>解：时来运转，解牛蛇鸡兔龙马</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\'  bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'华文楷体\' style=\'font-size: 14pt; font-weight:700\' color=\'#008000\'>");
document.writeln("				综合特肖：<span style=\'background-color: #FFFF00\'>牛</span>蛇鸡兔龙马</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999zx.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("<!--开始-->");

document.writeln("");
document.writeln("                                        <!--开始-->");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<span style=\'font-weight: 700\'><font face=\'微软雅黑\'>162期：【职业玩家】破解龙门客栈</font><br>");
document.writeln("		<font face=\'华文楷体\'><font color=\'#FF0000\' style=\'font-size: 12pt; font-weight:700\'>掌柜：【金蝉脱壳】<br>小二：【客官，今天上新菜了哦】<br>");
document.writeln("		客官：【可以安排上，我来试试】</font></font></font></span></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=34 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>解：金蝉脱壳，金肖猴鸡。</font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\'  bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'华文楷体\' style=\'font-size: 14pt; font-weight:700\' color=\'#008000\'>");
document.writeln("				综合特肖：猴鸡马羊蛇<span style=\'background-color: #FFFF00\'>龙</span></font></td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999zx.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62827a.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("<!--开始-->");





document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body> ");