document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>拐特大师</font><font color=\'#FFFFFF\'>『独解传真』</font></font></b></td></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' style=\'font-size: 14pt\'>传真300期</font><font color=\'#0000FF\'><br>");
document.writeln("</font></font>");
document.writeln("<font size=\'4\'>");
document.writeln("今期生肖排第一，一二三头好玄机。<br>");
document.writeln("双双蓝波错不了，六宮羅袖一時招。<br>");
document.writeln("合单之数放心中，水远山遥难信实。<br>");
document.writeln("猪狗相合相克出，想见四五除九码。");
document.writeln("");
document.writeln("");
document.writeln("<br>草长莺飞</font><font color=\'#0000FF\'><br>解：");
document.writeln("今期生肖排第一，一二三头好玄机。第一，鼠兔，123头。");
document.writeln("双双蓝波错不了，六宮羅袖一時招。双蓝，猴虎，");
document.writeln("合单之数放心中，水远山遥难信实。合单，水鼠猪，");
document.writeln("猪狗相合相克出，想见四五除九码。明肖猪狗，四五羊。");
document.writeln("");
document.writeln("</font><font color=\'#008000\'><br> ");
document.writeln("");
document.writeln("");
document.writeln("<font size=\'4\'>");
document.writeln("拐特九肖：鼠兔猴虎猪狗羊马蛇<br>");
document.writeln("拐特五肖：鼠兔猴虎猪</font><br>");
document.writeln("</font>");
document.writeln("</b>");
document.writeln("");
document.writeln("<span style=\'color: #FF00FF; font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("主特：04.40.13.49.08.20.14.26.17.41.30.42.21.33.34.46.23.47</span><br>");
document.writeln("");
document.writeln("<span style=\'background-color: #FFFF00\'><font color=\'#FF0000\'>");
document.writeln("越前越主，如有雷同，我是原创！你抄袭~</font></span><font color=\'#800000\'><br>");
document.writeln("");
document.writeln("以上分析只代表个人理解，对错误怪</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr>");
document.writeln("			<td height=40 bgcolor=\'#FFFFFF\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://mnbvctrs.www58317a.com:888/#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>更多解析进入</span><font color=\'#FF0000\'><span style=\'font-family:楷体;font-size:17pt; \'>58317.com</span></font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</a></tr></table></td> ");
document.writeln(" <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("");
document.writeln("          ");