document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>闽南五兄弟</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【稳博六合】√</font></b></table>");
document.writeln("           ");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln("");
document.writeln(".ys114 {text-align: center;}");
document.writeln(".ys112 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'ys114\'>");
document.writeln("	");
document.writeln("<b><span style=\'background-color: #FFFF00\'>兄弟几人初来驾到，献上我们最拿手的心水。望各路高手多多关照，对错勿怪！</span></b><strong><br>");
document.writeln(" ");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<font color=\'#FF0000\'>____________★____________</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	</strong>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<b>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#0000FF\'>【老大主十肖】√</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 14pt\'>");
document.writeln("");


document.writeln("218期【马狗鸡羊虎牛<span style=\'background-color: #FFFF00\'>龙</span>鼠猪猴】√<br>		");
document.writeln("219期【猪羊龙狗马鼠鸡虎<span style=\'background-color: #FFFF00\'>兔</span>猴】√<br>		");
document.writeln("220期【鸡羊兔鼠猪龙狗虎<span style=\'background-color: #FFFF00\'>猴</span>牛】√<br>		");
document.writeln("221期【虎猪蛇羊兔鸡鼠<span style=\'background-color: #FFFF00\'>龙</span>猴牛】√<br>		");
document.writeln("222期【<span style=\'background-color: #FFFF00\'>狗</span>蛇龙马兔羊虎鸡鼠猪】√<br>		");
document.writeln("223期【兔鸡羊蛇猴鼠狗虎龙牛】√<br>		");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("");
document.writeln("");
document.writeln("</span><font color=\'#FF0000\'><span style=\'font-size: 14pt\'>____________★____________");
document.writeln("	</span></font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--四头-->");
document.writeln("	");
document.writeln("	");
document.writeln("	<font size=\'4\' color=\'#0000FF\'>【老二主四头】√</font><font size=\'4\'><br>");
document.writeln("");


document.writeln("	221期【143<span style=\'background-color: #FFFF00\'>0</span>头】√<br>		");
document.writeln("	222期【3420头】×<br>		");
document.writeln("	223期【2341头】√<br>		");

document.writeln("	</font>");
document.writeln("	");
document.writeln("	    ");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--四行-->");
document.writeln("	");
document.writeln("<font size=\'4\' color=\'#0000FF\'>【老三主四行】√</font><font size=\'4\'><br>");


document.writeln("220期【火<span style=\'background-color: #FFFF00\'>水</span>土木】√<br>			");
document.writeln("221期【木金<span style=\'background-color: #FFFF00\'>火</span>土】√<br>			");
document.writeln("222期【木金水火】×<br>			");
document.writeln("223期【金土水木】√<br>			");

document.writeln("	</font>");
document.writeln("	");
document.writeln("");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--八尾-->");
document.writeln("");
document.writeln("<font size=\'4\' color=\'#0000FF\'>【老四主八尾】√</font><font size=\'4\'><br>");
document.writeln("");
document.writeln("");
document.writeln("	<br>");
document.writeln("");

document.writeln(" 220期【673<span style=\'background-color: #FFFF00\'>1</span>9024】√<br>	");
document.writeln(" 221期【793802<span style=\'background-color: #FFFF00\'>1</span>6】√<br>	");
document.writeln(" 222期【1685<span style=\'background-color: #FFFF00\'>9</span>273】√<br>	");
document.writeln(" 223期【27915830】√<br>	");

document.writeln("	</font>");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("<!--双波-->");
document.writeln("	<font size=\'4\' color=\'#0000FF\'>【老五主双波】√</font><font size=\'4\'><br>     ");
document.writeln("");
document.writeln("");

document.writeln("218期【<span style=\'background-color: #FFFF00\'>蓝波</span>红波】√<br>  	");
document.writeln("219期【<span style=\'background-color: #FFFF00\'>蓝波</span>绿波】√<br>  	");
document.writeln("220期【<span style=\'background-color: #FFFF00\'>绿波</span>红波】√<br>  	");
document.writeln("221期【<span style=\'background-color: #FFFF00\'>红波</span>蓝波】√<br>  	");
document.writeln("222期【蓝波<span style=\'background-color: #FFFF00\'>红波</span>】√<br>  	");
document.writeln("223期【绿波蓝波】√<br>  	");


document.writeln("");
document.writeln("           ");
document.writeln("  </font>");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("		");
document.writeln("	");
document.writeln("	");
document.writeln("	</font></b>");
document.writeln("	</div>");
document.writeln("	");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("	");