document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>闽南五兄弟</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【稳博六合】√</font></b></table>");
document.writeln("           ");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln("");
document.writeln(".ys114 {text-align: center;}");
document.writeln(".ys112 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'ys114\'>");
document.writeln("	");
document.writeln("<b><span style=\'background-color: #FFFF00\'>兄弟几人初来驾到，献上我们最拿手的心水。望各路高手多多关照，对错勿怪！</span></b><strong><br>");
document.writeln(" ");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<font color=\'#FF0000\'>____________★____________</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	</strong>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<b>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#0000FF\'>【老大主十肖】√</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 14pt\'>");
document.writeln("");

document.writeln("298期【蛇兔马狗猪羊龙<span style=\'background-color: #FFFF00\'>猴</span>虎鼠】√<br>		");
document.writeln("299期【虎鼠狗<span style=\'background-color: #FFFF00\'>龙</span>马兔蛇牛羊猴】√<br>		");
document.writeln("300期【蛇牛虎鸡狗猪<span style=\'background-color: #FFFF00\'>龙</span>猴马兔】√<br>		");
document.writeln("301期【<span style=\'background-color: #FFFF00\'>兔</span>龙蛇虎马鼠猪牛羊狗】√<br>		");
document.writeln("302期【猪狗龙虎兔鼠牛<span style=\'background-color: #FFFF00\'>猴</span>蛇鸡】√<br>		");
document.writeln("303期【猪马蛇虎鸡龙狗兔鼠<span style=\'background-color: #FFFF00\'>牛</span>】√<br>		");
document.writeln("304期【猪狗羊鸡兔蛇<span style=\'background-color: #FFFF00\'>鼠</span>猴虎牛】√<br>		");
document.writeln("305期【羊虎蛇狗猪鼠兔鸡猴<span style=\'background-color: #FFFF00\'>马</span>】√<br>		");
document.writeln("306期【猪马鼠鸡牛虎狗龙蛇羊】√<br>		");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("");
document.writeln("");
document.writeln("</span><font color=\'#FF0000\'><span style=\'font-size: 14pt\'>____________★____________");
document.writeln("	</span></font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--四头-->");
document.writeln("	");
document.writeln("	");
document.writeln("	<font size=\'4\' color=\'#0000FF\'>【老二主四头】√</font><font size=\'4\'><br>");


document.writeln("	295期【023<span style=\'background-color: #FFFF00\'>4</span>头】√<br>		");
document.writeln("	296期【4<span style=\'background-color: #FFFF00\'>2</span>03头】√<br>		");
document.writeln("	297期【12<span style=\'background-color: #FFFF00\'>3</span>4头】√<br>		");
document.writeln("	298期【02<span style=\'background-color: #FFFF00\'>3</span>1头】√<br>		");
document.writeln("	299期【40<span style=\'background-color: #FFFF00\'>2</span>1头】√<br>		");
document.writeln("	300期【20<span style=\'background-color: #FFFF00\'>3</span>1头】√<br>		");
document.writeln("	301期【014<span style=\'background-color: #FFFF00\'>2</span>头】√<br>		");
document.writeln("	302期【<span style=\'background-color: #FFFF00\'>3</span>142头】√<br>		");
document.writeln("	303期【<span style=\'background-color: #FFFF00\'>1</span>402头】√<br>		");
document.writeln("	304期【<span style=\'background-color: #FFFF00\'>2</span>034头】√<br>		");
document.writeln("	305期【0124头】×<br>		");
document.writeln("	306期【0124头】√<br>		");
document.writeln("	</font>");
document.writeln("	");
document.writeln("	    ");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--四行-->");
document.writeln("	");
document.writeln("<font size=\'4\' color=\'#0000FF\'>【老三主四行】√</font><font size=\'4\'><br>");

document.writeln("304期【金火木<span style=\'background-color: #FFFF00\'>水</span>】√<br>			");
document.writeln("305期【<span style=\'background-color: #FFFF00\'>土</span>木金水】√<br>			");
document.writeln("306期【金水火木】√<br>			");
document.writeln("	</font>");
document.writeln("	");
document.writeln("");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--八尾-->");
document.writeln("");
document.writeln("<font size=\'4\' color=\'#0000FF\'>【老四主八尾】√</font><font size=\'4\'><br>");
document.writeln("");
document.writeln("");
document.writeln("	<br>");



document.writeln("	295期【58<span style=\'background-color: #FFFF00\'>4</span>79612】√<br>	");
document.writeln("	296期【7<span style=\'background-color: #FFFF00\'>0</span>951684】√<br>	");
document.writeln("	297期【4256<span style=\'background-color: #FFFF00\'>9</span>810】√<br>	");
document.writeln("	298期【4817950<span style=\'background-color: #FFFF00\'>2</span>】√<br>	");
document.writeln("	299期【8531<span style=\'background-color: #FFFF00\'>4</span>962】√<br>	");
document.writeln("	300期【721<span style=\'background-color: #FFFF00\'>6</span>5943】√<br>	");
document.writeln("	301期【2<span style=\'background-color: #FFFF00\'>2</span>498761】√<br>	");
document.writeln("	302期【95<span style=\'background-color: #FFFF00\'>2</span>76130】√<br>	");
document.writeln("	303期【64902<span style=\'background-color: #FFFF00\'>5</span>17】√<br>	");
document.writeln("	304期【35071926】×<br>	");
document.writeln("	305期【023198<span style=\'background-color: #FFFF00\'>4</span>6】√<br>	");
document.writeln("	306期【82135790】√<br>	");
document.writeln("	</font>");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("<!--双波-->");
document.writeln("	<font size=\'4\' color=\'#0000FF\'>【老五主双波】√</font><font size=\'4\'><br>     ");
document.writeln("");

document.writeln("290期【<span style=\'background-color: #FFFF00\'>蓝波</span>绿波】√<br>  	");
document.writeln("291期【绿波<span style=\'background-color: #FFFF00\'>蓝波</span>】√<br>  	");
document.writeln("292期【绿波<span style=\'background-color: #FFFF00\'>蓝波</span>】√<br>  	");
document.writeln("294期【蓝波<span style=\'background-color: #FFFF00\'>红波</span>】√<br>  	");
document.writeln("295期【<span style=\'background-color: #FFFF00\'>绿波</span>红波】√<br>  	");
document.writeln("297期【红波<span style=\'background-color: #FFFF00\'>绿波</span>】√<br>  	");
document.writeln("298期【蓝波<span style=\'background-color: #FFFF00\'>绿波</span>】√<br>  	");
document.writeln("299期【<span style=\'background-color: #FFFF00\'>红波</span>绿波】√<br>  	");
document.writeln("300期【<span style=\'background-color: #FFFF00\'>蓝波</span>绿波】√<br>  	");
document.writeln("302期【<span style=\'background-color: #FFFF00\'>绿波</span>蓝波】√<br>  	");
document.writeln("304期【蓝波<span style=\'background-color: #FFFF00\'>绿波</span>】√<br>  	");
document.writeln("305期【蓝波<span style=\'background-color: #FFFF00\'>红波</span>】√<br>  	");
document.writeln("306期【红波蓝波】√<br>  	");
document.writeln("");
document.writeln("           ");
document.writeln("  </font>");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("		");
document.writeln("	");
document.writeln("	");
document.writeln("	</font></b>");
document.writeln("	</div>");
document.writeln("	");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388tz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("	");