document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>闽南五兄弟</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>【稳博六合】√</font></b></table>");
document.writeln("           ");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击最具权威实力平台</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln("");
document.writeln(".ys114 {text-align: center;}");
document.writeln(".ys112 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'ys114\'>");
document.writeln("	");
document.writeln("<b><span style=\'background-color: #FFFF00\'>兄弟几人初来驾到，献上我们最拿手的心水。望各路高手多多关照，对错勿怪！</span></b><strong><br>");
document.writeln(" ");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<font color=\'#FF0000\'>____________★____________</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	</strong>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<b>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<!--十肖-->");
document.writeln("");
document.writeln("<font color=\'#0000FF\'>【老大主十肖】√</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 14pt\'>");
document.writeln("");

document.writeln("336期【<span style=\'background-color: #FFFF00\'>鸡</span>马蛇狗龙猪鼠虎牛羊】√<br>		");
document.writeln("337期【蛇羊狗龙<span style=\'background-color: #FFFF00\'>鼠</span>鸡兔马虎猪】√<br>		");
document.writeln("338期【虎鸡猴<span style=\'background-color: #FFFF00\'>猪</span>龙马蛇牛羊鼠】√<br>		");
document.writeln("339期【鼠蛇虎牛鸡龙羊猴狗兔】×<br>		");
document.writeln("340期【<span style=\'background-color: #FFFF00\'>马</span>鼠鸡牛狗虎猴蛇猪兔】√<br>		");
document.writeln("341期【猪牛<span style=\'background-color: #FFFF00\'>马</span>蛇龙羊兔鸡猴鼠】√<br>		");
document.writeln("342期【兔狗牛羊虎鼠马<span style=\'background-color: #FFFF00\'>猪</span>龙猴】√<br>		");
document.writeln("343期【猴鼠猪兔蛇虎马龙羊牛】√<br>		");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("");
document.writeln("");
document.writeln("</span><font color=\'#FF0000\'><span style=\'font-size: 14pt\'>____________★____________");
document.writeln("	</span></font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--四头-->");
document.writeln("	");
document.writeln("	");
document.writeln("	<font size=\'4\' color=\'#0000FF\'>【老二主四头】√</font><font size=\'4\'><br>");
document.writeln("");
document.writeln("");


document.writeln("	343期【2341头】√<br>		");
document.writeln("	</font>");
document.writeln("	");
document.writeln("	    ");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--四行-->");
document.writeln("	");
document.writeln("<font size=\'4\' color=\'#0000FF\'>【老三主四行】√</font><font size=\'4\'><br>");

document.writeln("341期【<span style=\'background-color: #FFFF00\'>土</span>火水木】√<br>			");
document.writeln("342期【土水金<span style=\'background-color: #FFFF00\'>木</span>】√<br>			");
document.writeln("343期【水火木土】√<br>			");
document.writeln("	</font>");
document.writeln("	");
document.writeln("");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("<!--八尾-->");
document.writeln("");
document.writeln("<font size=\'4\' color=\'#0000FF\'>【老四主八尾】√</font><font size=\'4\'><br>");
document.writeln("");
document.writeln("");
document.writeln("	<br>");
document.writeln("");
document.writeln("");

document.writeln("	332期【107<span style=\'background-color: #FFFF00\'>8</span>2345】√<br>	");
document.writeln("	333期【08924<span style=\'background-color: #FFFF00\'>7</span>61】√<br>	");
document.writeln("	334期【43<span style=\'background-color: #FFFF00\'>6</span>75920】√<br>	");
document.writeln("	335期【<span style=\'background-color: #FFFF00\'>4</span>2763509】√<br>	");
document.writeln("	336期【<span style=\'background-color: #FFFF00\'>1</span>0675943】√<br>	");
document.writeln("	337期【491287<span style=\'background-color: #FFFF00\'>6</span>5】√<br>	");
document.writeln("	338期【9<span style=\'background-color: #FFFF00\'>1</span>426583】√<br>	");
document.writeln("	339期【16987<span style=\'background-color: #FFFF00\'>0</span>34】√<br>	");
document.writeln("	340期【01279358】×<br>	");
document.writeln("	341期【671582<span style=\'background-color: #FFFF00\'>4</span>3】√<br>	");
document.writeln("	342期【263<span style=\'background-color: #FFFF00\'>5</span>4819】√<br>	");
document.writeln("	343期【39067125】√<br>	");
document.writeln("	</font>");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	</font>");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("<!--双波-->");
document.writeln("	<font size=\'4\' color=\'#0000FF\'>【老五主双波】√</font><font size=\'4\'><br>     ");
document.writeln("");
document.writeln("");

document.writeln("342期【<span style=\'background-color: #FFFF00\'>绿波</span>红波】√<br>  	");
document.writeln("343期【蓝波红波】√<br>  	");
document.writeln("");
document.writeln("           ");
document.writeln("  </font>");
document.writeln("<font color=\'#FF0000\'>____________★____________");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("		");
document.writeln("	");
document.writeln("	");
document.writeln("	</font></b>");
document.writeln("	</div>");
document.writeln("	");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388ttz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("	");