document.writeln("  ");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62102</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『精准破成语』</font></b></table>");
document.writeln("    <tr>");
document.writeln("      <td height=40 bgcolor=\'#008000\' ><p align=\'center\'>");
document.writeln("		<font size=\'5\' face=\'微软雅黑\'>");
document.writeln("		<b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>六合【破成语】</font></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第073期：双喜临门<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：关注62109b.com</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");

document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第071期：此乃凶地<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：凶肖，地肖（虎03）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");

document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第070期：天下丑闻<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：天肖，丑肖（猪06）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第067期：大同天下<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：大肖（羊34）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第066期：家有土地<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：家禽（猪42）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第064期：合家欢乐<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：家禽（羊46）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第063期：野地求财<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：地肖（狗31）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第061期：后者为大<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：后肖（猴33）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第060期：阴森之地<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：地肖（鸡44）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第058期：地大物博<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：大肖（马11）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");
document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第057期：野外之地<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：地肖（羊46）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");


document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第056期：阳刚男人<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：男肖（马23）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");


document.writeln("");
document.writeln(" <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFF00\' ><b>");
document.writeln("");
document.writeln("		<font face=\'微软雅黑\' size=\'5\'>");
document.writeln("		<font color=\'#FF0000\'>第055期：家有凶狗<Br></font>  ");
document.writeln("		</font>  ");
document.writeln("		<font face=\'隶书\' style=\'font-size: 18pt\' color=\'#000000\'>");
document.writeln("		解：凶肖（狗31）</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'>");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("  <!--开始--> ");







document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");