document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");

document.writeln("         <!--https://tk2.zaojiao365.net:4949/col/340/ampm.jpg-->");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'55\'><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 49px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 16pt\'><font color=\'#FFFF00\'>夜上小晨</font><font color=\'#FFFFFF\'>『独解跑马测字玄机』</font></font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>360期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>？00</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【佬】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：佬，称成年男子，解男肖牛虎鼠马狗猴龙<br>⑵：佬，五行火，解火肖蛇马</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：牛虎鼠马狗龙<br>");
document.writeln("主攻特肖：牛虎鼠马<br>");
document.writeln("主攻特码：15.27.02.38.16.28.10.34.30.42.12.36</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999zx.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");

document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>359期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>猴08</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【信】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：信，把言语写成文字传达给特定对象的书面文件，解书肖虎龙马<br>⑵：信，五行金，解金肖猴鸡</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：虎龙马<span style=\'background-color: #FFFF00\'>猴</span>鸡狗<br>");
document.writeln("主攻特肖：虎龙马<span style=\'background-color: #FFFF00\'>猴</span><br>");
document.writeln("主攻特码：02.38.12.36.10.34.<span style=\'background-color: #FFFF00\'>08</span>.20.31.43.30.42</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999zx.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");

document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>358期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>兔01</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【机】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：机，机器，解狗龙羊兔猴<br>⑵：机，五行木，解木肖虎兔</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：狗龙羊<span style=\'background-color: #FFFF00\'>兔</span>猴虎<br>");
document.writeln("主攻特肖：狗龙羊<span style=\'background-color: #FFFF00\'>兔</span><br>");
document.writeln("主攻特码：06.30.12.36.21.33.<span style=\'background-color: #FFFF00\'>01</span>.49.20.44.02.38</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999zx.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");