document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("         <!--https://tk2.zaojiao365.net:4949/col/340/ampm.jpg-->");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'55\'><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 49px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 16pt\'><font color=\'#FFFF00\'>夜上小晨</font><font color=\'#FFFFFF\'>『独解跑马测字玄机』</font></font></b></table>");
document.writeln("");
document.writeln("");


document.writeln("");
document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>178期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>？00</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【触】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：触，接触，解龙鸡鼠马蛇。<br>⑵解：触，五行金，解金肖猴鸡</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：龙鸡鼠马蛇猴<br>");
document.writeln("主攻特肖：龙鸡鼠马<br>");
document.writeln("主攻特码：01.37.08.20.17.41.23.47.12.36.21.45</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999xz.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");
document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>177期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>马11</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【轻】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：轻，重量小，解马龙蛇羊兔。<br>⑵解：轻，五行木，解木肖虎兔</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：<span style=\'background-color: #FFFF00\'>马</span>龙蛇羊兔虎<br>");
document.writeln("主攻特肖：<span style=\'background-color: #FFFF00\'>马</span>龙蛇羊<br>");
document.writeln("主攻特码：<span style=\'background-color: #FFFF00\'>11</span>.47.13.49.12.36.22.34.02.14.15.39</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999xz.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");
document.writeln("");
document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>176期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>虎03</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【伸】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：伸，舒展开，解羊鸡蛇鼠虎。<br>⑵解：伸，五行金，解金肖猴鸡</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：羊鸡蛇鼠<span style=\'background-color: #FFFF00\'>虎</span>猴<br>");
document.writeln("主攻特肖：羊鸡蛇鼠<br>");
document.writeln("主攻特码：10.22.08.20.12.36.17.41.<span style=\'background-color: #FFFF00\'>03</span>.15.21.33</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999xz.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");

document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>174期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>蛇48</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【鸨】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：鸨，鸟类。比雁略大，解狗蛇羊兔马。<br>⑵解：鸨，五行水，解水肖鼠猪</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：狗<span style=\'background-color: #FFFF00\'>蛇</span>羊兔马鼠<br>");
document.writeln("主攻特肖：狗<span style=\'background-color: #FFFF00\'>蛇</span>羊兔<br>");
document.writeln("主攻特码：31.43.12.36.10.22.02.14.11.23.17.41</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999xz.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");

document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>170期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>羊10</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【帕】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：帕，用来擦手擦脸的纺织品，多为方形，解虎羊猪鸡狗。<br>⑵解：帕，五行土，解土肖牛羊龙狗</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：虎<span style=\'background-color: #FFFF00\'>羊</span>猪鸡狗龙<br>");
document.writeln("主攻特肖：虎<span style=\'background-color: #FFFF00\'>羊</span>猪鸡<br>");
document.writeln("主攻特码：15.39.22.34.06.30.08.20.31.43.13.49</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999xz.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");

document.writeln("");
document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>168期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>兔14</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【炊】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：炊， 烧火做饭，解兔猪鸡鼠蛇。<br>⑵解：炊，五行火，解火肖蛇马</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：<span style=\'background-color: #FFFF00\'>兔</span>猪鸡鼠蛇马<br>");
document.writeln("主攻特肖：<span style=\'background-color: #FFFF00\'>兔</span>猪鸡鼠<br>");
document.writeln("主攻特码：02.<span style=\'background-color: #FFFF00\'>14</span>.30.42.20.32.17.41.12.36.23.47</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999xz.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");


document.writeln("");
document.writeln("         <!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<b><font size=\'3\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #000000\'>164期跑马玄机测字开</span></font><span style=\'background-color: #008000\'><font color=\'#FFFF00\' size=\'3\'>鸡44</font></span><span style=\'background-color: #000000\'><font color=\'#FFFFFF\' size=\'3\'>准</font></span></b></b><br>");
document.writeln("<b>");
document.writeln("<font color=\'#FF0000\' size=\'5\'>【锡】</font></b><br>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; font-size: 16px\'>");
document.writeln("<font color=\'#0000FF\'>");
document.writeln("⑴：解：锡，金属元素，解猪鸡兔羊鼠。<br>⑵解：锡，五行金，解金肖猴鸡</font></span><br>");
document.writeln("<b><font face=\'微软雅黑\' size=\'3\' color=\'#FF0000\'>");
document.writeln("本期围特：猪<span style=\'background-color: #FFFF00\'>鸡</span>兔羊鼠猴<br>");
document.writeln("主攻特肖：猪<span style=\'background-color: #FFFF00\'>鸡</span>兔羊<br>");
document.writeln("主攻特码：06.30.08.20.02.14.22.34.05.17.21.45</font><br><font color=\'#FFFF00\'>");
document.writeln("<span style=\'background-color: #000066\'>【佛山夜上小晨】独家出版，欢迎各路同行转载</span></font></b></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39 bgcolor=\'#FFFF00\'><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' style=\'text-decoration: none\' href=\'https://j.1999xz.com:1999/\'><img src=https://www.62753b.com/images/33567.gif width=20 height=19><span style=font-family:楷体;color:#00f><font size=\'4\'>点击投注六合彩</font></span><span style=font-family:楷体;><font size=\'5\'><font color=\'#FF0000\'>1999.cc</font></font></a></strong></tr></table>");
document.writeln("");
document.writeln("</tr></table></td>  ");
document.writeln("         <!--开始-->");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");