document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'4\'>【平特小卖部-零售平连肖码】</font></b></p></table></td>");
document.writeln("           ");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("  ");
document.writeln("  ");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-weight:700\' face=\'微软雅黑\' size=\'2\'>");
document.writeln("		赔率介绍：平特肖2.1倍，二连肖4.2倍，三连肖11.12倍，四连肖32倍，五不中2.1倍，二中二70倍，三全中650倍，三中二23倍中三100倍</font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始--- ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>202期：开00.00.00.00.00.00T00</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：【】 ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									（）（）（）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("                                      （）（） （）  ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（11.12倍）");
document.writeln("											</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>    <br>");
document.writeln("                                      （）（）（）    ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（32倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>   <br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>00.00.00.00.00.00.00.00.00<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2中2/70倍）（3中3/650倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位四推荐平尾：【？尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8尾）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位五推荐连尾：<br>");
document.writeln("											【】【】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											【】【】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>	");
document.writeln("											【】【】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（15.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											00.00.00.00.00</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											00.00.00.00.00</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>224期：开00.00.00.00.00.00T00</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：【狗】 ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									（狗猴）（虎蛇）（牛羊）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("                                  （狗猴羊）（虎牛蛇）（牛狗羊）										</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（11.12倍）");
document.writeln("											</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>    <br>");
document.writeln("                                   （狗猴羊虎）（虎狗牛蛇）（猴牛狗羊）										</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（32倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>   <br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>06.30.20.02.14.23.47.15.21.45<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2中2/70倍）（3中3/650倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位四推荐平尾：【7尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8尾）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位五推荐连尾：<br>");
document.writeln("											【72】【04】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											【712】【045】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>	");
document.writeln("											【7124】【0745】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（15.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											47.31.48.40.11</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											09.22.10.03.14</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>222期：开14-04-34-09-15-38 T31</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【羊】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'> ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									（蛇羊）（猪龙）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（虎鼠）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("                                  （蛇羊龙）（鼠猪龙）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（羊虎鼠）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（11.12倍）");
document.writeln("											</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>    &nbsp;<br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("		</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">    40.11.47.21.30</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											34.42.28.09.21</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>222期：开43-26-01-33-27-06 T38</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【兔】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'> ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（兔鸡）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（龙牛）（鼠蛇）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位四推荐平尾：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【8尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8尾）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位五推荐连尾：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【83】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【62】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【836】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【625】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>	");
document.writeln("											【8365】【6025】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（15.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">19.05.40.45.12</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											27.38.05.34.10</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>220期：开18-17-22-46-32-26 T20</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【狗】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'> ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>19.04.40.21.33.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">22.18</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.42.</font><span style=\"background-color: #FFFF00\"><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">20</font></span><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.44<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2中2/70倍）（3中3/650倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">12.39.23.16.24</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											13.29.15.45.17</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("  ");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>219期：开41-45-31-17-22-30 T10</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【羊】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'> ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">20.46.26.06.32</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">47.12.39.48.27</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>218期：开41-10-21-37-11-31 T19</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【蛇】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'> ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br></font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">   11</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.23.14.38.40.17.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">41</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.20.15.39<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2中2/70倍）（3中3/650倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">40.05.02.29.16</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											31.26.33.29.13</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>217期：开41-37-06-01-02-46 T18</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									（鼠牛）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（虎马）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（狗蛇）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>04.40.15.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">02</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.38.22.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">06</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.30.23.47<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2中2/70倍）（3中3/650倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位四推荐平尾：【5尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8尾）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位五推荐连尾：<br>");
document.writeln("											【54】</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【67】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											【541】</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【678】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("  ");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>216期：开22-39-12-35-01-20 T39</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【龙】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'> ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（龙牛）（兔马）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（猪狗）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">12.<span style=\"background-color: #FFFF00\">36</span></font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.15.05.41.46.13.49.18.30<br>");
document.writeln("		推位四推荐平尾：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【9尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8尾）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>推位五推荐连尾：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【92】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【18】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">26.19.49.38.33</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											41.26.11.12.43</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("  <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>215期：开09-12-30-25-29-19 T49</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">28.36.39.14.13</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">20.21.10.42.17</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62103b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("  </tbody>");
document.writeln("</table></div>");