document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'4\'>【平特小卖部-零售平连肖码】</font></b></p></table></td>");
document.writeln("           ");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("  ");
document.writeln("    ");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-weight:700\' face=\'微软雅黑\' size=\'2\'>");
document.writeln("		赔率介绍：平特肖2.1倍，二连肖4.2倍，三连肖11.12倍，四连肖32倍，五不中2.1倍，二中二70倍，三全中650倍，三中二23倍中三100倍</font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("    ");
document.writeln("");
document.writeln("    <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		362期：开00-00-00-00-00-00 T00</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		                               摊位一平特：【猪】 ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									（羊猴）（蛇兔）（牛狗）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("                               （羊猴蛇）（羊蛇兔）（猴牛狗）	</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（11.12倍）");
document.writeln("											</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>    <br>");
document.writeln("                         （羊猴蛇狗）（羊牛蛇兔）（羊猴牛狗）											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（32倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>   <br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>");
document.writeln("		09.21.20.44.11.47.13.37.39.30<br>");
document.writeln("											</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		（2中2/70倍）（3中3/650倍）</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位四推荐平尾：【3尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位五推荐连尾：<br>");
document.writeln("											【32】【16】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											【432】【106】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>	");
document.writeln("											【4321】【1063】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（15.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											29.33.06.25.47</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("									    	29.10.44.18.40</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("    <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		361期：开21-10-08-42-18-05 T19</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		                               摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【猪】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		                               		</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									（鼠牛）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（马猴）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（羊兔）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>   <br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>");
document.writeln("		04.40.15.39.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">10</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.34.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">08</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.20.15.37<br>");
document.writeln("											</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		（2中2/70倍）（3中3/650倍）</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位四推荐平尾：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【9尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8倍）</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("    ");
document.writeln("");
document.writeln("    <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		360期：开30-41-25-33-17-38 T26</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		                               摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【猪】 ");
document.writeln("											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（猪狗）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（马蛇）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（羊虎）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("                               （猪狗马）（猪马蛇）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（狗羊虎）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>	</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（11.12倍）");
document.writeln("											</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>    <br>");
document.writeln("                         （猪狗马蛇）（猪虎马蛇）（狗马羊虎）											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（32倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>   <br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>");
document.writeln("		05.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">41.30</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.42.10.34.11.23.21.02<br>");
document.writeln("											</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		（2中2/70倍）（3中3/650倍）</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位四推荐平尾：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【7尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位五推荐连尾：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【71】【85】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											【712】</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【856】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>	");
document.writeln("											【7128】</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【8567】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（15.8倍）</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("    ");
document.writeln("    <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		359期：开48-21-15-44-03-42 T03</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		                               摊位一平特：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【牛】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		                               		</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位二推荐连肖：<br>");
document.writeln("									（蛇兔）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（猴羊）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（龙牛）</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（4.12倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("                               （蛇兔猴）</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">（猴龙羊）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（龙蛇牛）	</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（11.12倍）");
document.writeln("											</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>    <br>");
document.writeln("                         （蛇兔猴龙）（蛇猴龙羊）（羊龙蛇牛）											</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（32倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>   <br>");
document.writeln("");
document.writeln("											摊位三推荐平码：<br>");
document.writeln("		11.47.13.49.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">08</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.20.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">21</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.35.12.39<br>");
document.writeln("											</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		（2中2/70倍）（3中3/650倍）</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位四推荐平尾：【7尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位五推荐连尾：<br>");
document.writeln("											【79】</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【51】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											【793】</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【512】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>	");
document.writeln("											【7931】【5127】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（15.8倍）</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("    ");
document.writeln("");
document.writeln("    <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		357期：开22-26-47-08-25-38 T42</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平特小卖部】老板：冰山木,男，未婚。有车有房。</font>");
document.writeln("		<font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位四推荐平尾：</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【7尾】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("		推位五推荐连尾：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【78】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【51】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【782】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【514】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（7.08倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>	");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">【7825】</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>【5147】</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（15.8倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("											摊位六5不中：<br>");
document.writeln("											</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">32.43.10.11.20</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("									    	</font>");
document.writeln("		<font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">43.41.12.17.40</font><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("											</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62815b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.manolotron.com:49\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("  </tbody>");
document.writeln("</table></div>");