document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'4\'>【平特小卖部-零售平连肖码】</font></b></p></table></td>");
document.writeln("           ");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("  ");
document.writeln("    ");
document.writeln("  <!--开始-->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-weight:700\' face=\'微软雅黑\' size=\'2\'>");
document.writeln("		赔率介绍：平特肖2.1倍，二连肖4.2倍，三连肖11.12倍，四连肖32倍，五不中2.1倍，二中二70倍，三全中650倍，三中二23倍中三100倍</font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62109b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("    <!--开始---> ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		071期：开 48-06-23-29-02-04 T03</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平特小卖部】老板：冰山木,男，未婚。有车有房。</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln(" 摊位一平特</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln(" 		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><br>");
document.writeln(" 		");
document.writeln(" 		");
document.writeln("");

document.writeln(" 073期【马】√<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</font><br>											");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln(" 				摊位二推荐连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</font>");
document.writeln("		<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("（4.12倍）（11.12倍）（32倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("");
document.writeln("");
document.writeln("067期（虎蛇<span style=\'background-color: #FFFF00\'>鸡猪</span>兔<span style=\'background-color: #FFFF00\'>狗</span>）√ <br>");
document.writeln("068期（<span style=\'background-color: #FFFF00\'>猴虎马</span>牛<span style=\'background-color: #FFFF00\'>兔</span>羊）√ <br>");
document.writeln("069期（羊猴<span style=\'background-color: #FFFF00\'>鸡</span>蛇）√ <br>");
document.writeln("070期（<span style=\'background-color: #FFFF00\'>虎猪猴</span>龙<span style=\'background-color: #FFFF00\'>蛇</span>鼠）√ <br>");
document.writeln("071期（狗龙<span style=\'background-color: #FFFF00\'>牛虎猪蛇</span>）√ <br>");
document.writeln("072期（猪牛兔<span style=\'background-color: #FFFF00\'>猴</span>鼠<span style=\'background-color: #FFFF00\'>龙</span>）√ <br>");
document.writeln("073期（兔马狗鼠牛猴）√ <br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br></font><font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>摊位三推荐平码</font><BR><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2中2/70倍）（3中3/650倍）</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br><br>");
document.writeln("");
document.writeln("");
document.writeln("067期15.39.24.36.08.20.18.<span style=\'background-color: #FFFF00\'>30</span>.14.43<br>");
document.writeln("068期<span style=\'background-color: #FFFF00\'>21</span>.33.15.<span style=\'background-color: #FFFF00\'>39.23</span>.47.04.16.<span style=\'background-color: #FFFF00\'>38</span>.22<br>");
document.writeln("069期09.21.10.22.14.<span style=\'background-color: #FFFF00\'>38.</span></font><span style=\'background-color: #FFFF00\'><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\">08</font></span><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.20.29.36<br>");
document.writeln("070期15.39.18.42.<span style=\'background-color: #FFFF00\'>09</span>.45.37.49.24.41<br>");
document.writeln("071期19.43.25.49.16.40.</font><font color=\'#FF0000\' face=\'微软雅黑\' size=\"5\"><span style=\'background-color: #FFFF00\'>03</span></font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'>.15.30.36<br>");
document.writeln("072期30.42.04.40.26.38.21.<span style=\'background-color: #FFFF00\'>45</span>.41.<span style=\'background-color: #FFFF00\'>49</span><br>");
document.writeln("073期02.14.23.35.19.43.29.41.04.45<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</font><br>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>推位四推荐平尾</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（1.8倍）</font><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("073期【8尾】√<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br></font>");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>推位五推荐连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br>");
document.writeln("");
document.writeln("<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（3.18倍）（7.08倍）（15.8倍）</font><br>");
document.writeln("");
document.writeln("");
document.writeln("067期【<span style=\'background-color: #FFFF00\'>21</span>5】【<span style=\'background-color: #FFFF00\'>3</span>9<span style=\'background-color: #FFFF00\'>0</span>】<br>");
document.writeln("068期【<span style=\'background-color: #FFFF00\'>0</span>5<span style=\'background-color: #FFFF00\'>9</span>】<span style=\'background-color: #FFFF00\'>【843】</span><br>");
document.writeln("069期【24<span style=\'background-color: #FFFF00\'>0</span>】【<span style=\'background-color: #FFFF00\'>9</span>56】<br>");
document.writeln("070期【5<span style=\'background-color: #FFFF00\'>4</span>0】【<span style=\'background-color: #FFFF00\'>6</span>8<span style=\'background-color: #FFFF00\'>3</span>】<br>");
document.writeln("071期【<span style=\'background-color: #FFFF00\'>6</span>1<span style=\'background-color: #FFFF00\'>4</span>】【<span style=\'background-color: #FFFF00\'>2</span>7<span style=\'background-color: #FFFF00\'>8</span>】<br>");
document.writeln("072期【<span style=\'background-color: #FFFF00\'>5</span>82】【1<span style=\'background-color: #FFFF00\'>04</span>】<br>");
document.writeln("073期【738】【291】<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("									");
document.writeln("											");
document.writeln("<br>摊位六5不中<font color=\'#008000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>（2.1倍）</font><br>");
document.writeln("");
document.writeln("072期（26.01.02.30.16）√<br>");
document.writeln("073期（10.24.22.25.03）√<br>");



document.writeln("</b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FFFF00\' style=\'font-size: 12pt; background-color:#000000\' face=\'微软雅黑\'>");
document.writeln("		平特小卖部：平特免费大甩卖，粗中挑精，精中挑准！</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注资料网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>62109b.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束--> ");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.manolotron.com:49\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("  </tbody>");
document.writeln("</table></div>");