document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>六肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'67\'><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=61><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>眼镜波波</font><font color=\'#FFFFFF\'>『解四不像玄机』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("							<!--开始-->");
document.writeln("		<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=left>");
document.writeln("	<b><a href=\'https://hgjgfgg.www552257b.com:8443/#49029\'>");
document.writeln("	<span style=\'text-decoration: none\'><font face=\'楷体\' color=\'#FF0000\'>");
document.writeln("	<span style=\"font-size: 13pt\">063期今期鸡猴牛出特，刀切豆腐两面光<span style=\'background-color: #FFFF00\'>开？00</span></span></font><span style=\"font-size: 13pt\"><br>		</span>		");
document.writeln("	<font face=\'楷体\'><span style=\"font-size: 14pt\">①杀龙猪狗</span><font color=\'#008000\'><BR>");
document.writeln("<span style=\'font-size: 14pt\'>②图解特肖鸡猴牛兔马</span></font><span style=\'font-size: 14pt\'><font color=\'#008000\'><br>");
document.writeln("	③绿波+蓝波<img src=/images/zu.gif></font><font color=\'#FFFF00\'><span style=\'background-color: #000000\'>查看香港解特</span></font><font color=\'#008000\'><br>");
document.writeln("	</font>");
document.writeln("	</span>本人取特都是有思路可寻,对错看天意,喷狗绕道</font></span></a></b><span style=\'text-decoration: none\'><font face=\'楷体\'></font></font></table>");
document.writeln("			<table style=border-collapse:collapse border=0 width=100% height=\'31\'><tbody><tr>");
document.writeln("				<td height=31><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("		<!--结束-->");
document.writeln("							<!--开始-->");
document.writeln("		<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=left>");
document.writeln("	<b><a href=\'https://hgjgfgg.www552257b.com:8443/#49029\'>");
document.writeln("	<span style=\'text-decoration: none\'><font face=\'楷体\' color=\'#FF0000\'>");
document.writeln("	<span style=\"font-size: 13pt\">062期今期龙狗兔出特，出头根儿先朽烟<span style=\'background-color: #FFFF00\'>开龙49</span></span></font><span style=\"font-size: 13pt\"><br>		</span>		");
document.writeln("	<font face=\'楷体\'><span style=\"font-size: 14pt; background-color:#FFFF00\">①杀猪蛇猴</span><font color=\'#008000\'><BR>");
document.writeln("<span style=\'font-size: 14pt\'>②图解特肖</span></font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><span style=\'font-size: 14pt\'><font color=\'#008000\'>狗兔牛鼠</font></span><span style=\'font-size: 14pt\'><font color=\'#008000\'><br>");
document.writeln("	③</font></span><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">绿波</span></font><span style=\'font-size: 14pt\'><font color=\'#008000\'>+蓝波<img src=/images/zu.gif></font><font color=\'#FFFF00\'><span style=\'background-color: #000000\'>查看香港解特</span></font><font color=\'#008000\'><br>");
document.writeln("	</font>");
document.writeln("	</span>本人取特都是有思路可寻,对错看天意,喷狗绕道</font></span></a></b><span style=\'text-decoration: none\'><font face=\'楷体\'></font></font></table>");
document.writeln("			<table style=border-collapse:collapse border=0 width=100% height=\'31\'><tbody><tr>");
document.writeln("				<td height=31><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("		<!--结束-->");
document.writeln("							<!--开始-->");
document.writeln("		<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=left>");
document.writeln("	<b><a href=\'https://hgjgfgg.www552257b.com:8443/#49029\'>");
document.writeln("	<span style=\'text-decoration: none\'><font face=\'楷体\' color=\'#FF0000\'>");
document.writeln("	<span style=\"font-size: 13pt\">061期今期猴羊鸡出特，小身隐在三当家<span style=\'background-color: #FFFF00\'>开猴33</span></span></font><span style=\"font-size: 13pt\"><br>		</span>		");
document.writeln("	<font face=\'楷体\'><span style=\"font-size: 14pt; background-color:#FFFF00\">①杀狗虎牛</span><font color=\'#008000\'><BR>");
document.writeln("<span style=\'font-size: 14pt\'>②图解特肖</span></font><font color=\'#FF0000\' size=\"5\"><span style=\"background-color: #FFFF00\">猴</span></font><span style=\'font-size: 14pt\'><font color=\'#008000\'>羊鸡龙马</font></span><span style=\'font-size: 14pt\'><font color=\'#008000\'><br>");
document.writeln("	③蓝波+红波<img src=/images/zu.gif></font><font color=\'#FFFF00\'><span style=\'background-color: #000000\'>查看香港解特</span></font><font color=\'#008000\'><br>");
document.writeln("	</font>");
document.writeln("	</span>本人取特都是有思路可寻,对错看天意,喷狗绕道</font></span></a></b><span style=\'text-decoration: none\'><font face=\'楷体\'></font></font></table>");
document.writeln("			<table style=border-collapse:collapse border=0 width=100% height=\'31\'><tbody><tr>");
document.writeln("				<td height=31><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1700tz.com:1700/\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:17pt;color:#00f>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1700.CC</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("		<!--结束-->");
document.writeln("		");
document.writeln("");
document.writeln("</body>");
document.writeln("     ");