document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("} ");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62827.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『今期输尽光』</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://xn--secaq5b.xn--0dcaaz1ff5bzcvdxdtb1af.xn--gecrj9c:8443/#62827\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57386</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>245期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开？00中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买马输尽光，大单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买蓝双数，特码就开0123头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>244期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开虎03中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>猪</span>输尽光，<span style=\'background-color: #FFFF00\'>大双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开431<span style=\'background-color: #FFFF00\'>0</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>243期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开龙01中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>马</span>输尽光，小单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝双</span>数，特码就开<span style=\'background-color: #FFFF00\'>0</span>134头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>242期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猪30中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>蛇</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿单</span>数，特码就开402<span style=\'background-color: #FFFF00\'>3</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>241期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开牛04中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>猴</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿双</span>数，特码就开314<span style=\'background-color: #FFFF00\'>0</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>240期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开蛇24中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>马</span>输尽光，小双今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开13<span style=\'background-color: #FFFF00\'>2</span>0头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>239期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开狗31中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>兔</span>输尽光，大单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红双</span>数，特码就开01<span style=\'background-color: #FFFF00\'>3</span>4头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>238期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猪18中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>蛇</span>输尽光，小双今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开0<span style=\'background-color: #FFFF00\'>1</span>43头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>237期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猪06中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>鸡</span>输尽光，<span style=\'background-color: #FFFF00\'>大双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开1423头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>236期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开虎03中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>狗</span>输尽光，小单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红双</span>数，特码就开412<span style=\'background-color: #FFFF00\'>0</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>235期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开蛇24中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>兔</span>输尽光，<span style=\'background-color: #FFFF00\'>大双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿单</span>数，特码就开3401头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>234期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开狗07中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>鸡</span>输尽光，小单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝双</span>数，特码就开<span style=\'background-color: #FFFF00\'>0</span>432头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>233期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开马23中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>虎</span>输尽光，<span style=\'background-color: #FFFF00\'>大双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝单</span>数，特码就开103<span style=\'background-color: #FFFF00\'>2</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>232期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开兔02中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>狗</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿双</span>数，特码就开412<span style=\'background-color: #FFFF00\'>0</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>230期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开龙49中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>鸡</span>输尽光，大单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿双</span>数，特码就开0213头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>228期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开龙37中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>马</span>输尽光，大单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿双</span>数，特码就开<span style=\'background-color: #FFFF00\'>3</span>021头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>227期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开鸡20中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\"background-color: #FFFF00\">鼠</span>输尽光，小双今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\"background-color: #FFFF00\">红单</span>数，特码就开<span style=\"background-color: #FFFF00\">2</span>143头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>226期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开羊34中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>兔</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝双</span>数，特码就开10<span style=\'background-color: #FFFF00\'>3</span>2头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>225期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开鼠05中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\"background-color: #FFFF00\">猴</span>输尽光，<span style=\"background-color: #FFFF00\">小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\"background-color: #FFFF00\">蓝单</span>数，特码就开41<span style=\"background-color: #FFFF00\">0</span>3头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>224期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开羊22中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>蛇</span>输尽光，<span style=\'background-color: #FFFF00\'>小单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开<span style=\'background-color: #FFFF00\'>2</span>341头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>223期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猪30中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>兔</span>输尽光，大双今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买红双数，特码就开401<span style=\'background-color: #FFFF00\'>3</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>222期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开狗19中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>羊</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿单</span>数，特码就开324<span style=\'background-color: #FFFF00\'>1</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>221期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开龙01中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>狗</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿双</span>数，特码就开<span style=\'background-color: #FFFF00\'>0</span>423头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>220期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猴21中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>鼠</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开134<span style=\'background-color: #FFFF00\'>2</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>219期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开兔14中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>猴</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红双</span>数，特码就开3402头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>218期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开龙37中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>蛇</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开402<span style=\'background-color: #FFFF00\'>3</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>217期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开虎15中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>猪</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝双</span>数，特码就开432<span style=\'background-color: #FFFF00\'>1</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>216期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开虎15中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>狗</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开4023头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>215期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开鸡20中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>兔</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红双</span>数，特码就开43<span style=\'background-color: #FFFF00\'>2</span>0头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>214期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猪06中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>牛</span>输尽光，小双今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿单</span>数，特码就开413<span style=\'background-color: #FFFF00\'>0</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>213期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开兔38中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>羊</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红双</span>数，特码就开012<span style=\'background-color: #FFFF00\'>3</span>头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>212期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开龙49中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>兔</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝单</span>数，特码就开0312头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>211期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开鸡20中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>蛇</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红双</span>数，特码就开3<span style=\'background-color: #FFFF00\'>2</span>41头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>210期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开狗19中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>猴</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝单</span>数，特码就开<span style=\'background-color: #FFFF00\'>1</span>432头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln(" </tbody>");
document.writeln("</table> ");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");