document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("} ");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62827.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『今期输尽光』</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://xn--secaq5b.xn--0dcaaz1ff5bzcvdxdtb1af.xn--gecrj9c:8443/#62827\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57386</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");



document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>053期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开？00中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买羊输尽光，小双今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买红单数，特码就开4120头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>051期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开蛇49中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>兔</span>输尽光，大单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红双</span>数，特码就开23<span style=\'background-color: #FFFF00\'>4</span>1头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>050期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开牛05中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>马</span>输尽光，<span style=\'background-color: #FFFF00\'>小双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开14<span style=\'background-color: #FFFF00\'>0</span>2头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>049期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猪43中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>鼠</span>输尽光，<span style=\'background-color: #FFFF00\'>大双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝单</span>数，特码就开<span style=\'background-color: #FFFF00\'>4</span>320头</font>  ")
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>048期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开鼠18中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>马</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿双</span>数，特码就开<span style=\'background-color: #FFFF00\'>1</span>032头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>047期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开马12中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>羊</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买红双数，特码就开<span style=\'background-color: #FFFF00\'>1</span>432头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>046期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开马12中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>猴</span>输尽光，<span style=\'background-color: #FFFF00\'>大单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿双</span>数，特码就开32<span style=\'background-color: #FFFF00\'>1</span>4头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("<!--开始--> ");









document.writeln("");
document.writeln(" ");
document.writeln(" </tbody>");
document.writeln("</table> ");
