document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("} ");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62519.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『今期输尽光』</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://mnbvctrs.www58317a.com:888/#62102\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57185</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>342期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开？00中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买蛇输尽光，小单今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买蓝双数，特码就开2013头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>341期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开马34中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>猴</span>输尽光，大双今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>绿单</span>数，特码就开0241头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>340期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开马46中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>蛇</span>输尽光，<span style=\'background-color: #FFFF00\'>小单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝双</span>数，特码就开0<span style=\'background-color: #FFFF00\'>4</span>23头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");

document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>338期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猪41中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>鸡</span>输尽光，<span style=\'background-color: #FFFF00\'>小单</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝双</span>数，特码就开2301头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("<!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=40 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<b><font face=\'微软雅黑\' size=\'4\'>337期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'6\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开鼠16中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=41 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\"><b>");
document.writeln("");
document.writeln("		<font color=\'#000000\'>今期买<span style=\'background-color: #FFFF00\'>蛇</span>输尽光，<span style=\'background-color: #FFFF00\'>大双</span>今期无人买</font>  ");
document.writeln("		</b> </font> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=37 bgcolor=\'#FFFFFF\' align=\'center\' ><b>");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 13pt\">");
document.writeln("");
document.writeln("		<font color=\'#000000\'>有钱不买<span style=\'background-color: #FFFF00\'>红单</span>数，特码就开0<span style=\'background-color: #FFFF00\'>1</span>43头</font>  ");
document.writeln("");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");

document.writeln("");
document.writeln(" ");
document.writeln(" ");
document.writeln(" </tbody>");
document.writeln("</table> ");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://tz.2388ttz.com:2388/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");