document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln(" ");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>毛毛小解</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『东南漫画』</font></b></table>");
document.writeln("");
document.writeln("               <!--图片--> ");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("       <img src=\'https://tk2.zaojiao365.net:4949/col/55/dnmh.jpg\' style=\'width: 100%;\' /> </td>");
document.writeln("    </tr>      ");
document.writeln("  ");
document.writeln("    <!--图片--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第055期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（六字开出一二伴）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：六字开出一二伴，解马羊牛猴虎狗。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：马羊牛猴虎狗</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第054期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（处世清闲不带忧）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：处世清闲不带忧，解马狗猴猪鼠羊。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：马狗<span style=\'background-color: #FFFF00\'>猴</span>猪鼠羊</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第052期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（日日夕阳听猿怨）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：日日夕阳听猿怨，解鸡蛇虎猴鼠兔。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：鸡蛇虎<span style=\'background-color: #FFFF00\'>猴</span>鼠兔</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第051期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（二七邂逅六团圆）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：二七邂逅六团圆，解牛兔羊龙蛇虎。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：牛兔羊龙<span style=\'background-color: #FFFF00\'>蛇</span>虎</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");

document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第048期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（屋内两生酒味香）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：屋内两生酒味香，解鸡猪兔虎牛狗。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：鸡<span style=\'background-color: #FFFF00\'>猪</span>兔虎牛狗</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第047期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（两仪八卦平天下）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：两仪八卦平天下，解蛇马羊猴兔龙。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：蛇马羊<span style=\'background-color: #FFFF00\'>猴</span>兔龙</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第046期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（四六转动五坠落）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：四六转动五坠落，解蛇鸡兔虎牛龙。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：蛇鸡<span style=\'background-color: #FFFF00\'>兔</span>虎牛龙</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第045期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（二三沧海三桑田）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：二三沧海三桑田，解龙牛马鼠兔羊。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：龙<span style=\'background-color: #FFFF00\'>牛</span>马鼠兔羊</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");


document.writeln("");
document.writeln("           ");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td colspan=\'3\'><a target=\'_blank\' href=\'https://dddeep.www37289c.com:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://493388.com/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>37289b.com</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>  ");