document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln(" ");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>毛毛小解</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『东南漫画』</font></b></table>");
document.writeln("");
document.writeln("               <!--图片--> ");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("       <img src=\'https://tk2.zaojiao365.net:4949/col/8/dnmh.jpg\' style=\'width: 100%;\' /> </td>");
document.writeln("    </tr>      ");
document.writeln("  ");
document.writeln("    <!--图片--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第008期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（二九两数取一个）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：二九两数取一个，解：羊龙猪虎牛鸡。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：羊龙猪虎牛鸡</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第006期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（一九同来八知音）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：一九同来八知音，解：鼠猪羊兔龙蛇。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：鼠猪羊兔龙<span style=\'background-color: #FFFF00\'>蛇</span></font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第005期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（四五转出两路忙）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：四五转出两路忙，解：鸡猴蛇兔牛猪。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：<span style=\'background-color: #FFFF00\'>鸡</span>猴蛇兔牛猪</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第004期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（忠心无二有主张）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：忠心无二有主张，解：兔马狗鼠蛇龙。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：兔马狗<span style=\'background-color: #FFFF00\'>鼠</span>蛇龙</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");

document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第002期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（云四合一现跟七）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：云四合一现跟七，解：猴狗鼠鸡马虎。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：猴狗鼠鸡马<span style=\'background-color: #FFFF00\'>虎</span></font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");



document.writeln("");
document.writeln("           ");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td colspan=\'3\'><a target=\'_blank\' href=\'https://dddeep.www37289c.com:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://493388.com/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>37289b.com</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>  ");