document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln(" ");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>毛毛小解</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『东南漫画』</font></b></table>");
document.writeln("");
document.writeln("               <!--图片--> ");
document.writeln("");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("       <img src=\'https://tk2.zaojiao365.net:4949/col/152/dnmh.jpg\' style=\'width: 100%;\' /> </td>");
document.writeln("    </tr>      ");
document.writeln("  ");
document.writeln("    <!--图片--> ");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第152期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（一名功成千古垂）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：一名功成千古垂，解羊兔牛蛇猪鸡。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：羊兔牛蛇猪鸡</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第150期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（未妨惆怅四九思）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：未妨惆怅四九思，解蛇龙猴兔鸡虎。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：蛇龙<span style=\'background-color: #FFFF00\'>猴</span>兔鸡虎</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第149期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（四字接着喜气求）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：四字接着喜气求，解羊虎鸡牛蛇猴。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：虎<span style=\'background-color: #FFFF00\'>羊</span>龙马牛狗</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第148期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（运交茂寅颇遂心）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：运交茂寅颇遂心，解虎羊龙马牛狗。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：<span style=\'background-color: #FFFF00\'>虎</span>羊龙马牛狗</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第147期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（青草绿叶来作食）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：青草绿叶来作食，解蛇兔鸡猪猴虎。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：蛇<span style=\'background-color: #FFFF00\'>兔</span>鸡猪猴虎</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第145期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（日色高升月低微）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：日色高升月低微，解鼠马蛇虎猪兔。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：鼠马蛇虎猪<span style=\'background-color: #FFFF00\'>兔</span></font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第144期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（三通鼓角四角鸡）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：三通鼓角四角鸡，解蛇狗<span style=\'background-color: #FFFF00\'>牛</span>兔猪马。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：蛇狗<span style=\'background-color: #FFFF00\'>牛</span>兔猪马</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");
document.writeln("              <!--开始--> ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 bgcolor=\'#FFFFFF\' align=\'left\' ><b>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' face=\'微软雅黑\' style=\'font-size: 16pt\'>第142期：【东南漫画解特】</font><font color=\'#FF0000\' face=\'微软雅黑\' style=\'font-size: 16pt\'><Br>");
document.writeln("		（灵童心水清自明）<br></font>  ");
document.writeln("		<font face=\'微软雅黑\' color=\'#000000\'>");
document.writeln("		解：灵童心水清自明，解鼠蛇虎兔狗猴。</font><br>");
document.writeln("		 ");
document.writeln("		<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>");
document.writeln("		综合特码：鼠蛇<span style=\'background-color: #FFFF00\'>虎</span>兔狗猴</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("               <!--开始--> ");
document.writeln("");



document.writeln("");
document.writeln("           ");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td colspan=\'3\'><a target=\'_blank\' href=\'https://dddeep.www37289c.com:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://493388.com/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>跑狗论坛<font color=\'#FF0000\'>37289b.com</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>  ");