document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>小朵</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『财神奇遇』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388tz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("     <!--开始--");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（155期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font color=\'#FF0000\'>【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("	<span style=\'font-size: 11pt; font-weight: 700\'>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------</font><br>");
document.writeln("		");
document.writeln("奇遇①：来料中。（关注我，不迷路）<br>");
document.writeln("奇遇②：来料中。（期期参考中特码）<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("	特肖【记住62103b.com 最早查看】	<br>");
document.writeln("		四肖：【最早更新在62103b.com】<br>");
document.writeln("		挑特18码：关注查看<br>");
document.writeln("		主博九码：财富只在机会中！</td>");
document.writeln("    </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("     <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（259期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font color=\'#FF0000\'>【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("	<span style=\'font-size: 11pt; font-weight: 700\'>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------</font><br>");
document.writeln("		");
document.writeln("奇遇①：同门地虎。（明肖虎，地肖蛇羊虎狗鸡鼠）<br>");
document.writeln("奇遇②：黑马。（明肖马，黑解黑肖兔龙蛇马羊猴）<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("	特肖【虎马蛇猴狗鸡鼠兔龙】	<br>");
document.writeln("		四肖：【虎马蛇猴】<br>");
document.writeln("		挑特18码：02.38.10.34.11.23.08.20.18.30.31.43.04.40.13.37.12.36<br>");
document.writeln("		主博九码：02.34.11.20.18.31.04.13.36</td>");
document.writeln("    </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("     <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（258期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font color=\'#FF0000\'>【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("	<span style=\'font-size: 11pt; font-weight: 700\'>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------</font><br>");
document.writeln("		");
document.writeln("奇遇①：双尾虎。（明肖虎，双尾解双肖龙虎猴狗马鼠）<br>");
document.writeln("奇遇②：牛羊四周是绿草。（明肖牛羊，绿草解牛羊龙狗兔马）<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("	特肖【虎牛</span><span style=\"font-weight: 700; background-color: #FFFF00\"><font color=\"#FF0000\" size=\"5\">羊</font></span><span style=\'font-size: 11pt; font-weight: 700\'>马龙狗鼠兔猴】	<br>");
document.writeln("		四肖：【虎牛</span><span style=\'font-weight: 700\'><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font></span><span style=\'font-size: 11pt; font-weight: 700\'>马】</td>");
document.writeln("    </tr>");
document.writeln("   <!--开始-->");
document.writeln("     <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（257期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font color=\'#FF0000\'>【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("	<span style=\'font-size: 11pt; font-weight: 700\'>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------</font><br>");
document.writeln("		");
document.writeln("奇遇①：两条吉龙。（明肖龙，吉解吉肖蛇羊鸡龙马兔）<br>");
document.writeln("奇遇②：蛇狗之战。（明肖蛇狗，战解战肖牛马虎狗）<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("	特肖【</span><span style=\'font-weight: 700\'><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font></span><span style=\'font-size: 11pt; font-weight: 700\'>蛇狗羊鸡兔虎牛马】	<br>");
document.writeln("		四肖：【</span><span style=\'font-weight: 700\'><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font></span><span style=\'font-size: 11pt; font-weight: 700\'>蛇狗羊】<br>");
document.writeln("		挑特18码：12.</span><span style=\'font-weight: 700\'><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">36.</span></font></span><span style=\'font-size: 11pt; font-weight: 700\'>11.47.30.42.21.33.19.31.25.49.02.38.15.39.22.46</td>");
document.writeln("    </tr>");
document.writeln("   <!--开始-->");
document.writeln("     <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（256期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font color=\'#FF0000\'>【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("	<span style=\'font-size: 11pt; font-weight: 700\'>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------</font><br>");
document.writeln("		");
document.writeln("奇遇①：天降一条龙。（明肖龙，天降解天肖牛猪猴龙马兔）<br>");
document.writeln("奇遇②：母猪。（明肖猪，母解女肖蛇羊鸡猪兔）<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("	特肖【龙猪兔牛猴</span><span style=\'font-weight: 700\'><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">马</span></font></span><span style=\'font-size: 11pt; font-weight: 700\'>羊蛇鸡】	<br>");
document.writeln("		四肖：【龙猪兔牛】<br>");
document.writeln("		挑特18码：24.36.05.17.13.25.15.39.08.20.22.</span><span style=\"font-weight: 700; background-color: #FFFF00\"><font color=\"#FF0000\" size=\"5\">34</font></span><span style=\'font-size: 11pt; font-weight: 700\'>.21.33.23.47.07.19</td>");
document.writeln("    </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("     <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（255期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font color=\'#FF0000\'>【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("	<span style=\'font-size: 11pt; font-weight: 700\'>");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------</font><br>");
document.writeln("		");
document.writeln("奇遇①：两条野狗。（明肖狗，野解野兽龙蛇猴兔鼠虎）<br>");
document.writeln("奇遇②：路遇小蛇。（明肖蛇，小解小肖鼠蛇兔鸡龙猴）<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("	特肖【狗蛇鼠</span><span style=\'font-weight: 700\'><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">兔</span></font></span><span style=\'font-size: 11pt; font-weight: 700\'>鸡龙猴虎马】	<br>");
document.writeln("		四肖：【狗蛇鼠</span><span style=\'font-weight: 700\'><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">兔</span></font></span><span style=\'font-size: 11pt; font-weight: 700\'>】</td>");
document.writeln("    </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://asdqweq.www82693b.com:888/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://www.496688a.com/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>广东八二站<font color=\'#FF0000\'>82693.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");