document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>小朵</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『财神奇遇』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（260期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：凶狗。（明肖狗，凶肖牛猪猴虎鼠狗）<br>");
document.writeln("奇遇②：家猪。（明肖猪，家禽牛马羊鸡猪狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【狗猪牛猴虎鼠马羊鸡】	<br>");
document.writeln("		四肖：【狗猪牛猴】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：07.31.18.30.04.16.09.21.15.27.05.17.23.35.10.22.20.44<br>");
document.writeln("		主博九码：07.30.16.21.15.17.35.10.20</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（258期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：红色金鸡。（明肖鸡，金肖猴鸡，红肖鼠马兔鸡）<br>");
document.writeln("奇遇②：丑猪。（明肖猪，丑肖牛猪猴虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【鸡猪猴鼠马兔虎狗</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font><font style=\"font-size: 12pt\">】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（256期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：土狗。（明肖狗，土肖牛羊龙狗）<br>");
document.writeln("奇遇②：一只凶鼠。（明肖鼠，凶肖牛猪猴虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【狗鼠牛羊龙</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">虎</span></font><font style=\"font-size: 12pt\">猪猴马】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（255期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：条蛇飞上天。（明肖蛇，天肖牛猪猴龙马兔）<br>");
document.writeln("奇遇②：前方有龙。（明肖龙，前肖鼠牛虎兔龙蛇）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【蛇龙牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>猴马兔鼠虎】	<br>");
document.writeln("		四肖：【蛇龙牛<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：12.36.01.37.04.16.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">30</span></font>.42.09.21.11.23.02.14.05.17.27.39<br>");
document.writeln("		主博九码：12.01.04.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">30</span></font>.21.23.14.17.39</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（254期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：丑蛇。（明肖蛇，丑肖牛猪猴虎鼠狗）<br>");
document.writeln("奇遇②：家有头猪。（明肖猪，家禽牛马羊鸡猪狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【蛇猪牛猴</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">虎</span></font><font style=\"font-size: 12pt\">鼠狗马羊】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（253期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：单身狗。（明肖狗，单肖马龙猴虎鼠狗）<br>");
document.writeln("奇遇②：南洋兔子。（明肖兔，南肖蛇马羊）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">马</span></font>兔龙猴虎鼠狗蛇羊】	<br>");
document.writeln("		四肖：【<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">马</span></font>兔龙猴】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（252期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：两条地龙。（明肖龙，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：丑虎。（明肖虎，凶肖牛猪猴虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙虎<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>羊鸡狗鼠牛猪】	<br>");
document.writeln("		四肖：【龙虎<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>羊】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：13.37.03.15.12.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">36</span></font>.22.34.20.44.31.43.05.17.16.40.30.42<br>");
document.writeln("		主博九码：13.03.12.22.20.31.17.16.30</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（251期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：前方遇狗。（明肖狗，前肖鼠牛虎兔龙蛇）<br>");
document.writeln("奇遇②：土生土长真龙王。（明肖龙，土肖牛羊龙狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙鼠牛虎<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">兔</span></font>蛇羊狗猪】	<br>");
document.writeln("		四肖：【龙鼠牛虎】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：01.13.05.17.16.40.03.15.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">14</span></font>.26.24.36.34.46.07.31.06.30<br>");
document.writeln("		主博九码：01.05.16.15.26.24.34.07.06</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（250期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：爬地虎。（明肖虎，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：真龙对战。（明肖龙，战肖牛马虎狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【虎龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>羊鸡鼠狗马牛】	<br>");
document.writeln("		四肖：【虎龙<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">蛇</span></font>羊】<br>");
document.writeln("		</font>");
document.writeln("");
document.writeln("	/td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（249期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：家养土鸡。（明肖鸡，家禽牛马羊鸡猪狗）<br>");
document.writeln("奇遇②：吉祥龙。（明肖龙，吉肖蛇羊鸡龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font>龙羊狗牛马猪蛇兔】	<br>");
document.writeln("		四肖：【<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font>龙羊狗】<br>");
document.writeln("		</font>");
document.writeln("");
document.writeln("	</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（248期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：老龙呼风唤雨。（明肖龙，风肖兔虎龙，雨肖鼠猪牛）<br>");
document.writeln("奇遇②：兔子爱吃南方草。（明肖兔，南肖蛇羊马，草肖羊马牛兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙虎兔鼠猪牛蛇</font><span style=\"background-color: #FFFF00\"><font color=\"#FF0000\" size=\"5\">马</font></span><font style=\"font-size: 12pt\">羊】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（247期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：野狗。（明肖狗，野兽龙蛇猴虎鼠兔）<br>");
document.writeln("奇遇②：老马耕地。（明肖马，地肖蛇羊鸡虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font>马龙蛇猴虎鼠兔羊】	<br>");
document.writeln("		四肖：【<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font>马龙蛇猴】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：07.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">31</span></font>.23.35.13.49.12.36.21.33.03.15.17.29.02.14.22.34");
document.writeln("		</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（246期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：白龙马前行。（明肖马龙，前肖鼠牛虎兔龙蛇）<br>");
document.writeln("奇遇②：牧羊凶犬。（明肖狗，凶肖牛猪猴虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【马龙狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>蛇鼠猴牛兔】	<br>");
document.writeln("		四肖：【马龙狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">虎</span></font>】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：23.47.13.25.07.31.03.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">15</span></font>.12.36.05.41.21.45.04.16.02.14<br>");
document.writeln("		主博九码：23.25.31.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">15</span></font>.36.41.21.16.02</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（245期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：家中羊群。（明肖羊，家禽牛马羊鸡猪狗）<br>");
document.writeln("奇遇②：一条地蛇。（明肖蛇，地肖蛇羊鸡虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【羊蛇牛马鸡猪狗虎</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">鼠</span></font><font style=\"font-size: 12pt\">】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（244期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：野牛。（明肖牛，野兽龙蛇猴虎鼠兔）<br>");
document.writeln("奇遇②：玉兔天仙。（明肖兔，天肖牛猪猴龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【牛兔龙蛇猴</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">虎</span></font><font style=\"font-size: 12pt\">鼠兔马】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：28.40.02.14.13.37.12.36.21.45.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">03</span></font><font size=\"2\">.15.05.29.14.26.23.47</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（242期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：龙宫满天星。（明肖龙，天肖牛猪猴龙马兔）<br>");
document.writeln("奇遇②：凶狗。（明肖狗，凶肖牛猪猴虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙狗鼠<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>牛猴虎马兔】	<br>");
document.writeln("		四肖：【龙狗鼠<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：13.49.07.31.05.17.18.<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">30</span></font>.28.40.09.21.15.39.11.23.02.14<br>");
document.writeln("		主博九码：13.31.05.18.40.09.15.23.02</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（241期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：一只吉祥兔。（明肖兔，吉肖蛇羊鸡龙马兔）<br>");
document.writeln("奇遇②：一战成虎。（明肖虎，战肖牛马虎狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【兔虎蛇羊鸡龙马</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font><font style=\"font-size: 12pt\">狗】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：02.14.15.27.12.36.22.34.08.20.13.49.11.23.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">04</span></font><font size=\"2\">.16.31.43</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（240期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：两条地龙。（明肖龙，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：野虎相斗。（明肖虎，野兽龙蛇猴虎鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙虎</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">羊鸡鼠狗猴兔】	<br>");
document.writeln("		四肖：【龙虎</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">羊】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（239期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：兔子爱吃南方草 。（明肖兔，南肖蛇羊马，草肖羊马牛兔）<br>");
document.writeln("奇遇②：猛虎行凶。（明肖虎，凶肖牛猪猴虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【兔虎牛猪鼠猴蛇</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font style=\"font-size: 12pt\">马】	<br>");
document.writeln("		四肖：【兔虎牛猪】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：02.14.15.39.16.40.06.30.17.29.21.45.12.36.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">31</span></font><font size=\"2\">.43.11.23<br>");
document.writeln("		主博九码：02.15.16.30.17.21.36.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">31</span></font><font size=\"2\">.11</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（238期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：凶狗 。（明肖狗，凶肖牛猪猴虎鼠狗）<br>");
document.writeln("奇遇②：家有头猪。（明肖猪，家禽牛马羊鸡猪狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>牛鼠虎猴马羊鸡】	<br>");
document.writeln("		四肖：【狗<font color=\'#FF0000\' size=\'5\'><span style=\"background-color: #FFFF00\">猪</span></font>牛鼠】<br>");
document.writeln("");
document.writeln("");
document.writeln("	</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（237期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：九阴鸡爪 。（明肖鸡，阴肖鼠龙蛇马狗猪）<br>");
document.writeln("奇遇②：真龙飞天。（明肖龙，天肖牛猪猴龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【鸡龙鼠蛇马狗</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">猪</span></font><font style=\"font-size: 12pt\">牛兔】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（236期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：兔子爱吃南方草 。（明肖兔，南肖蛇羊马，草肖牛羊马兔）<br>");
document.writeln("奇遇②：野外捕蛇。（明肖蛇，野兽龙蛇猴虎鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【兔蛇羊马牛龙</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">虎</span></font><font style=\"font-size: 12pt\">猴鼠】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（235期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：老鼠打地洞 。（明肖鼠，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：母兔骑牛。（明肖兔牛，母解女肖蛇羊鸡猪兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【鼠牛兔</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">羊鸡虎狗猪】	<br>");
document.writeln("		四肖：【鼠牛兔</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：03.15.16.40.02.14.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">24</span></font><font size=\"2\">.36.22.34.08.20.15.39.31.43.06.30<br>");
document.writeln("		主博九码：03.16.02.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">24</span></font><font size=\"2\">.34.20.15.31.06</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（234期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：七虎冲在前。（明肖虎，前肖鼠牛虎兔龙蛇）<br>");
document.writeln("奇遇②：风雨中龙虎对战。（明肖龙虎，风肖兔虎龙，雨肖鼠猪牛，战肖牛马虎狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【虎龙鼠牛兔蛇猪马</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font style=\"font-size: 12pt\">】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：15.27.13.49.05.17.16.40.02.14.12.36.06.30.11.23</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.07</span></font><font size=\"2\">.31</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（233期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：打野鼠。（明鼠，野兽龙蛇猴鼠虎兔）<br>");
document.writeln("奇遇②：天上真龙。（明肖龙，天肖牛猪猴龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【鼠龙蛇猴虎兔牛猪</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">马</span></font><font style=\"font-size: 12pt\">】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：05.17.13.49.12.36.09.21.03.15.14.38.16.40.30.42.11.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">23</span></font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://xn--iecpa7b6b.xn--hdcakck9fcb2gqp1d.xn--gecrj9c:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://hjyjthjy.www661161c.com:8443/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>广东八二站<font color=\'#FF0000\'>82157.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");