document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body class=\'bjbj\'>");
document.writeln("");
document.writeln("");
document.writeln("	<div class=\'a1\'>");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 18pt\'>小朵</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>『财神奇遇』</font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（133期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：野外蟒蛇。（明肖蛇，野兽龙蛇猴虎鼠兔）<br>");
document.writeln("奇遇②：与虎前行。（明肖虎，前肖鼠牛虎兔龙蛇）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【蛇虎龙鼠兔猴牛鸡狗】	<br>");
document.writeln("		四肖：【蛇虎龙鼠】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：12.24.03.15.13.49.05.41.02.14.21.33.28.40.20.32.07.43<br>");
document.writeln("		主博九码：12.15.49.05.14.33.28.32.43</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（131期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：七虎冲在前。（明肖虎，前肖鼠牛虎兔龙蛇）<br>");
document.writeln("奇遇②：双尾蛇。（明肖蛇，双肖蛇羊鸡牛猪兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【虎蛇</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font><font style=\"font-size: 12pt\">猪龙鸡鼠兔羊】	<br>");
document.writeln("		四肖：【虎蛇</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font><font style=\"font-size: 12pt\">猪】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（130期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：野狗。（明肖狗，野兽龙蛇猴虎鼠兔）<br>");
document.writeln("奇遇②：鸡毛一地。（明肖鸡，地肖蛇羊鸡虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【狗鸡龙蛇猴虎</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">鼠</span></font><font style=\"font-size: 12pt\">兔羊】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：07.31.20.32.25.37.12.48.09.21.15.39.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">17</span></font><font size=\"2\">.41.02.14.22.34<br>");
document.writeln("		主博九码：07.20.25.48.09.39.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">17</span></font><font size=\"2\">.14.22</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（129期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：老鼠打土洞。（明肖鼠，土肖牛羊龙狗，洞肖蛇狗鼠）<br>");
document.writeln("奇遇②：家养一只鸡。（明肖鸡，家禽牛马羊鸡猪狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><font style=\"font-size: 12pt\">蛇羊鸡牛猪兔猴鼠】	<br>");
document.writeln("		四肖：【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><font style=\"font-size: 12pt\">蛇羊鸡】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（128期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：双龙会。（明肖龙，双肖蛇羊鸡牛猪兔）<br>");
document.writeln("奇遇②：小蛇下蛋。（明肖蛇，小肖蛇鸡龙猴鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙蛇羊鸡牛猪</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">兔</span></font><font style=\"font-size: 12pt\">猴鼠】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：13.25.12.36.22.34.08.20.16.40.06.30.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">02</span></font><font size=\"2\">.14.21.33.17.41<br>");
document.writeln("		主博九码：13.12.22.08.16.06.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">02</span></font><font size=\"2\">.21.17</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（127期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：单枪匹马。（明肖马，单肖龙马猴虎鼠狗）<br>");
document.writeln("奇遇②：野猴。（明肖猴，野兽解龙蛇猴鼠虎兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【马猴龙虎鼠狗</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">兔鸡】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（126期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：家中狗。（明肖狗，家禽牛马羊鸡猪狗）<br>");
document.writeln("奇遇②：地头蛇。（明肖蛇，地肖蛇羊鸡虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font style=\"font-size: 12pt\">蛇牛马羊鸡猪虎鼠】	<br>");
document.writeln("		四肖：【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font style=\"font-size: 12pt\">蛇牛马】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（125期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：吉祥龙。（明肖龙，吉肖蛇羊鸡龙马兔）<br>");
document.writeln("奇遇②：天猴。（明肖猴，天肖牛猪猴龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙猴</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">羊鸡马兔牛猪】	<br>");
document.writeln("		四肖：【龙猴</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">羊】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：01.37.09.21</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.12.</span></font><font size=\"2\">36.34.46.08.20.11.23.02.38.16.40.30.42<br>");
document.writeln("		主博九码：01.21</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.12</span></font><font size=\"2\">.34.20.11.38.16.42</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（124期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：蛇女。（明肖蛇，女肖蛇羊鸡猪兔）<br>");
document.writeln("奇遇②：土拨鼠。（明肖鼠，土肖牛羊龙狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【蛇鼠</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font style=\"font-size: 12pt\">鸡猪兔牛龙狗】	<br>");
document.writeln("		四肖：【蛇鼠</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font style=\"font-size: 12pt\">鸡】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：12.36.05.41.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">22</span></font><font size=\"2\">.34.08.20.18.30.02.14.16.40.13.49.31.43<br>");
document.writeln("		主博九码：12.36.05.41</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.22.</span></font><font size=\"2\">34.08.20.18</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（123期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：小兔。（明肖兔，小肖龙蛇猴鸡鼠兔）<br>");
document.writeln("奇遇②：秋风阵阵。（秋肖猴鸡狗，风肖兔虎龙）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【兔龙蛇</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">猴</span></font><font style=\"font-size: 12pt\">鸡鼠虎狗牛】	<br>");
document.writeln("		四肖：【兔龙蛇</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">猴</span></font><font style=\"font-size: 12pt\">】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：02.14.13.49.24.36</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.21</span></font><font size=\"2\">.33.08.20.17.41.15.39.31.43.16.40<br>");
document.writeln("		主博九码：02.49.24</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.21.</span></font><font size=\"2\">08.17.15.31.16</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（121期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：母蛇。（明肖蛇，母解女肖蛇羊鸡猪兔）<br>");
document.writeln("奇遇②：一地鸡毛。（明肖鸡，地肖蛇羊鸡虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【蛇鸡羊猪</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">兔</span></font><font style=\"font-size: 12pt\">虎鼠狗龙】	<br>");
document.writeln("		四肖：【蛇鸡羊猪】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：12.36.08.20.10.22.06.30</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.02</span></font><font size=\"2\">.14.15.39.04.17.07.19.37.49<br>");
document.writeln("		主博九码：12.08.10.06.14.15.17.07.37</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（120期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：土拨鼠。（明肖鼠，土肖牛羊龙狗）<br>");
document.writeln("奇遇②：单枪匹马。（明肖马，单解单肖猴龙马虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【</font><span style=\"background-color: #FFFF00\"><font color=\"#FF0000\" size=\"5\">鼠</font></span><font style=\"font-size: 12pt\">马牛羊龙狗虎鸡猴】	<br>");
document.writeln("		四肖：【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">鼠</span></font><font style=\"font-size: 12pt\">马牛羊】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（119期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：虎王地盘。（明肖虎，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：肥猪之家。（明肖猪，家禽牛马羊鸡猪狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【虎猪蛇羊</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">鸡</span></font><font style=\"font-size: 12pt\">鼠狗牛马】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（118期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：两条地蛇。（明肖蛇，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：一头野虎。（明肖虎，野兽龙蛇猴虎鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【蛇虎羊鸡鼠狗龙</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">猴</span></font><font style=\"font-size: 12pt\">兔】	<br>");
document.writeln("		四肖：【蛇虎羊鸡】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：12.36.03.15.22.34.08.20.17.41.31.43.13.49.09.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">21.</span></font><font size=\"2\">02.14<br>");
document.writeln("		主博九码：12.03.22.08.17.31.13</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.21</span></font><font size=\"2\">.02</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（117期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：小龙。（明肖龙，小肖鼠龙蛇猴兔鸡）<br>");
document.writeln("奇遇②：猛虎耕地。（明肖虎，地肖蛇羊鸡虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><font style=\"font-size: 12pt\">虎鼠蛇猴兔鸡羊狗】	<br>");
document.writeln("		四肖：【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><font style=\"font-size: 12pt\">虎鼠蛇】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（116期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：鸡飞狗战。（明肖鸡狗，战肖牛马虎狗）<br>");
document.writeln("奇遇②：农家有头牛。（明肖牛，家禽牛马羊鸡猪狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【鸡狗牛虎马猪</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font style=\"font-size: 12pt\">蛇龙】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：08.20.31.43.16.40.03.15.23.47.30.42.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">10</span></font><font size=\"2\">.22.12.36.13.49</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（115期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：地鼠。（明肖鼠，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：秋风落叶。（秋肖猴鸡狗，风肖兔虎龙）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">鼠</span></font><font style=\"font-size: 12pt\">猴鸡狗蛇羊虎兔龙】	<br>");
document.writeln("		四肖：【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">鼠</span></font><font style=\"font-size: 12pt\">猴鸡狗】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（114期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：孙猴之家。（明肖猴，家禽牛马羊鸡猪狗）<br>");
document.writeln("奇遇②：天龙之子。（明肖龙，天肖牛猪猴龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【猴龙牛马羊鸡</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">猪</span></font><font style=\"font-size: 12pt\">狗兔】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：09.21.13.49.16.40.11.23.10.22.08.20.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">18</span></font><font size=\"2\">.30.31.43.02.14</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://j.1777tz.com:1777\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>查看最全图纸进入<font color=\'#FF0000\'>49图库</font></font></b></p></a></td></tr>");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（113期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：一只爱吃草的兔子（明肖兔，吃草肖牛羊马兔）<br>");
document.writeln("奇遇②：野猴。（明肖猴，野兽龙蛇猴虎鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【兔猴牛羊马龙</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">虎鼠】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（112期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：八戒刨地（地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：野鼠。（明肖鼠，野兽龙蛇猴虎鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【鼠蛇羊鸡虎</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font style=\"font-size: 12pt\">兔猴龙】	");
document.writeln("		</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（111期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：草原牛马羊（明肖牛马羊，草肖牛马羊兔）<br>");
document.writeln("奇遇②：一地鸡毛。（明肖鸡，地肖蛇羊鸡虎鼠狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【牛马羊鸡兔虎鼠</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font style=\"font-size: 12pt\">蛇】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：04.16.23.35.10.22.08.20.14.38.15.39.17.41.31.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">43</span></font><font size=\"2\">.12.36</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（110期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：地龙（明肖龙，地肖蛇羊鸡虎鼠狗）<br>");
document.writeln("奇遇②：吉祥羊娃娃。（明肖羊，吉肖蛇羊鸡龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙羊</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">鸡虎鼠狗马兔】	<br>");
document.writeln("		四肖：【龙羊</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">蛇</span></font><font style=\"font-size: 12pt\">鸡】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（109期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：两头母牛（明肖牛，母解女肖蛇羊鸡猪兔）<br>");
document.writeln("奇遇②：马家女将。（明肖马，家禽牛马羊鸡猪狗）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【牛羊马蛇鸡猪兔</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">狗</span></font><font style=\"font-size: 12pt\">龙】	<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：04.40.10.22.11.23.12.36.08.20.30.42.02.14.31.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">43</span></font><font size=\"2\">.01.13</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（108期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：真龙吉祥（明肖龙，吉祥解吉肖蛇羊鸡龙马兔）<br>");
document.writeln("奇遇②：野外捕鼠。（明肖鼠，野兽龙蛇猴虎鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙鼠蛇</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font style=\"font-size: 12pt\">鸡马兔猴虎】	<br>");
document.writeln("		四肖：【龙鼠蛇</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font style=\"font-size: 12pt\">】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（107期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：一棵绿色火龙果（明肖龙，绿肖牛羊龙狗）<br>");
document.writeln("奇遇②：满地金鸡花。（明肖鸡，地肖蛇羊鸡虎鼠狗，金肖猴鸡）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【龙鸡牛</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font style=\"font-size: 12pt\">狗蛇虎鼠猴】	<br>");
document.writeln("		四肖：【龙鸡牛</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">羊</span></font><font style=\"font-size: 12pt\">】</font></td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（106期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：赤兔战马（明肖兔马，战肖牛马虎狗）<br>");
document.writeln("奇遇②：野猴。（明肖猴，野兽龙蛇猴虎鼠兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【兔马猴</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font><font style=\"font-size: 12pt\">虎狗龙蛇鼠】	<br>");
document.writeln("		四肖：【兔马猴</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">牛</span></font><font style=\"font-size: 12pt\">】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：14.38.11.23.09.21</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">.16</span></font><font size=\"2\">.28.15.39.31.43.13.49.12.36.17.41<br>");
document.writeln("		主博九码：14.23.09.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">16</span></font><font size=\"2\">.15.31.13.12.41</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" <!--开始-->");
document.writeln("    ");
document.writeln("	<tr> <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("		<b>");
document.writeln("		");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		<font style=\'font-size: 14pt\'><font color=\'#0000FF\'>小朵【财神奇遇解析】（105期）<br></font>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<font style=\"font-size: 12pt\" color=\"#FF0000\">【奇遇小朵】个人心水，仅供参考！</font><font style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("		</font>	</font>");
document.writeln("		");
document.writeln("		</b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("		<font size=\"4\" color=\"#FF0000\">-------------------</font><font style=\"font-size: 12pt\"><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b><font style=\"font-size: 12pt\">");
document.writeln("		");
document.writeln("奇遇①：真龙天子（明肖龙，天肖牛猪猴龙马兔）<br>");
document.writeln("奇遇②：美丽一条蛇。（明肖蛇，美肖蛇羊鸡龙马兔）</font></b><font style=\"font-size: 12pt\"><br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		<font color=\'#FF0000\'>-------------------<br>");
document.writeln("	（主要心水）</font><br>");
document.writeln("		");
document.writeln("		</font>");
document.writeln("		");
document.writeln("	<span style=\'font-weight: 700\'>");
document.writeln("");
document.writeln("		<font style=\"font-size: 12pt\">");
document.writeln("		特肖【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><font style=\"font-size: 12pt\">蛇牛猪猴马兔羊鸡】	<br>");
document.writeln("		四肖：【</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">龙</span></font><font style=\"font-size: 12pt\">蛇牛猪】<br>");
document.writeln("		</font><font size=\"2\">");
document.writeln("		挑特18码：13.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">49</span></font><font size=\"2\">.12.36.04.40.18.30.09.21.11.23.02.14.22.34.20.32<br>");
document.writeln("		主博九码：13.</font><font color=\"#FF0000\" size=\"5\"><span style=\"background-color: #FFFF00\">49</span></font><font size=\"2\">.12.36.04.40.18.30.09</td>   </tr>");
document.writeln("   <!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://ttrrrccc.www82187c.com:8443/#49029\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=https://hjyjthjy.www661161c.com:8443/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' size=\'5\'>广东八二站<font color=\'#FF0000\'>82187.com</font></font></b></p></a></td></tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("  </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");