document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;} ");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>62109b.com</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『四字玄机』</font></b></p></td></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("<!--结束-->");

document.writeln("<!--结束-->");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#0000FF\' size=\'3\'>047期【四字玄机】</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' size=\'5\'>『</font><font color=\'#008000\' size=\'5\'>二九左右</font><font color=\'#000000\' size=\'5\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\' size=\"4\">");
document.writeln("&#10146;&#10146;推荐特肖:羊兔虎猪马牛<br>");
document.writeln("	</font><font color=\'#FF0000\' size=\"4\">");
document.writeln("10.34.02.38.15.39.17.41.11.23.16.28</font></b></font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#0000FF\' size=\'3\'>046期【四字玄机】</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' size=\'5\'>『</font><font color=\'#008000\' size=\'5\'>四六左右</font><font color=\'#000000\' size=\'5\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\' size=\"4\">");
document.writeln("&#10146;&#10146;推荐特肖:<span style=\'background-color: #FFFF00\'>兔</span>牛蛇狗鼠虎<br>");
document.writeln("	</font><font color=\'#FF0000\' size=\"4\">");
document.writeln("14.38.16.28.24.36.19.31.17.41.27.39</font></b></font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#0000FF\' size=\'3\'>045期【四字玄机】</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' size=\'5\'>『</font><font color=\'#008000\' size=\'5\'>二九前后</font><font color=\'#000000\' size=\'5\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\' size=\"4\">");
document.writeln("&#10146;&#10146;推荐特肖:<span style=\'background-color: #FFFF00\'>牛</span>龙鼠猴牛马<br>");
document.writeln("	</font><font color=\'#FF0000\' size=\"4\">");
document.writeln("<span style=\'background-color: #FFFF00\'>12</span>.36.01.13.05.41.21.33.16.28.23.47</font></b></font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#0000FF\' size=\'3\'>044期【四字玄机】</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' size=\'5\'>『</font><font color=\'#008000\' size=\'5\'>四八左右</font><font color=\'#000000\' size=\'5\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\' size=\"4\">");
document.writeln("&#10146;&#10146;推荐特肖:鼠龙羊猴<span style=\'background-color: #FFFF00\'>兔</span>鸡<br>");
document.writeln("	</font><font color=\'#FF0000\' size=\"4\">");
document.writeln("29.41.13.37.10.22.33.45.<span style=\'background-color: #FFFF00\'>02</span>.14.20.32</font></b></font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");

document.writeln("<!--结束-->");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'center\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font face=\'微软雅黑\' color=\'#0000FF\' size=\'3\'>043期【四字玄机】</font></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b>");
document.writeln("	<font color=\'#000000\' size=\'5\'>『</font><font color=\'#008000\' size=\'5\'>一九前后</font><font color=\'#000000\' size=\'5\'>』</font></b></font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font face=\'微软雅黑\'><b><font color=\'#000000\' size=\"4\">");
document.writeln("&#10146;&#10146;推荐特肖:猴牛狗马<span style=\'background-color: #FFFF00\'>猪</span>羊<br>");
document.writeln("	</font><font color=\'#FF0000\' size=\"4\">");
document.writeln("09.21.04.16.31.43.11.23.06.18.10.22</font></b></font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("<!--结束-->");







document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("<tr><td><a target=\'_blank\' href=\'https://tz.2388ttz.com:2388\' style=\'text-decoration: none\'>");
document.writeln("<p align=\'center\'>");
document.writeln("	<img src=/images/yh.gif style=\'width:20px\' height=\'19\'><b><font face=\'楷体\' color=\'#0000FF\' style=\"font-size: 16pt\">点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>2388.CC</font></span></b></p></a></td></tr>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</div> ");