document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--https://tk2.ku33a.net:4949/col/344/tmxj.jpg-->");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>六合彩</font><font color=\'#FFFFFF\'>『特码玄机』</font></font></table>");
document.writeln("");

document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>185期特码玄机开？00</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:千古风流有诗在，身穿棉衣戴红帽</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：蛇马牛狗兔羊<br>玄机解肖：蛇马牛狗</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中185期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>184期特码玄机开猪42</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:龙头一点出现金，一大一小争不休</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：鸡鼠羊蛇狗<span style=\'background-color: #FFFF00\'>猪</span><br>玄机解肖：鸡鼠羊蛇</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中184期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>183期特码玄机开龙25</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:花园深处有六合，有求结伴武则天</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：兔猪羊猴牛<span style=\'background-color: #FFFF00\'>龙</span><br>玄机解肖：兔猪羊猴</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中183期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>180期特码玄机开兔02</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:身披重甲力无双，潇洒风流善使枪</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：马龙<span style=\'background-color: #FFFF00\'>兔</span>虎羊鼠<br>玄机解肖：马龙<span style=\'background-color: #FFFF00\'>兔</span>虎</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中180期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>178期特码玄机开鸡20</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:事不凑巧也随变，一四胜望八志高</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：<span style=\'background-color: #FFFF00\'>鸡</span>蛇虎鼠猪牛<br>玄机解肖：<span style=\'background-color: #FFFF00\'>鸡</span>蛇虎鼠</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中178期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>176期特码玄机开虎03</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:龙虎相斗势对立，一二相合三五直</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：狗<span style=\'background-color: #FFFF00\'>虎</span>鼠猴龙兔<br>玄机解肖：狗<span style=\'background-color: #FFFF00\'>虎</span>鼠猴</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中176期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>172期特码玄机开鸡32</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:两岸青山秀色新，人協回春添色彩</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：猴狗<span style=\'background-color: #FFFF00\'>鸡</span>马猪虎<br>玄机解肖：猴狗<span style=\'background-color: #FFFF00\'>鸡</span>马</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中172期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>171期特码玄机开牛16</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:人欢聚散一杯酒，南北东西万里程</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：鼠<span style=\'background-color: #FFFF00\'>牛</span>龙猴虎蛇<br>玄机解肖：鼠<span style=\'background-color: #FFFF00\'>牛</span>龙猴</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中171期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>168期特码玄机开兔14</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:龙翔凤舞熊婆娑，头戴凤冠唱高歌</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：牛蛇猪<span style=\'background-color: #FFFF00\'>兔</span>龙鸡<br>玄机解肖：牛蛇猪<span style=\'background-color: #FFFF00\'>兔</span></font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中168期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>164期特码玄机开鸡44</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:四字过后五字赢，如今之计买十一</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：马<span style=\'background-color: #FFFF00\'>鸡</span>羊狗鼠虎<br>玄机解肖：马<span style=\'background-color: #FFFF00\'>鸡</span>羊狗</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中164期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>161期特码玄机开马35</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:三餐依然多享泰，船到江心补漏迟</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：猪羊<span style=\'background-color: #FFFF00\'>马</span>鼠龙鸡<br>玄机解肖：猪羊<span style=\'background-color: #FFFF00\'>马</span>鼠</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中161期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>160期特码玄机开虎27</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:一字当头十相投，时来运转否泰交</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：龙兔马牛<span style=\'background-color: #FFFF00\'>虎</span>鼠<br>玄机解肖：龙兔马牛</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://disanduisan.www29769c.com:8443#62827c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中160期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>  ");