document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>无标题文档</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");


document.writeln("<!--https://tk2.zaojiao365.net:4949/col/344/tmxj.jpg-->");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>六合彩</font><font color=\'#FFFFFF\'>『特码玄机』</font></font></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>364期特码玄机开？00</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:十拿九稳是金火，一击即中接财来</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：鼠虎羊猪马狗<br>玄机解肖：鼠虎羊猪</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中134期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>363期特码玄机开龙12</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:一世勤劳传佳风，万里云空龙飞翔</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：<span style=\'background-color: #FFFF00\'>龙</span>猴狗兔牛虎<br>玄机解肖：<span style=\'background-color: #FFFF00\'>龙</span>猴狗兔</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中134期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>362期特码玄机开龙36</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:二前惆怅十牡丹，三六晚来二九残</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：鸡狗兔<span style=\'background-color: #FFFF00\'>龙</span>猴猪<br>玄机解肖：鸡狗兔<span style=\'background-color: #FFFF00\'>龙</span></font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中134期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>361期特码玄机开鸡19</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:四字过后五字赢，如今之计买十一</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：马<span style=\'background-color: #FFFF00\'>鸡</span>羊狗鼠虎<br>玄机解肖：马<span style=\'background-color: #FFFF00\'>鸡</span>羊狗</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中134期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>360期特码玄机开虎26</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:码海扬帆二二开，十一十三合一数</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：猴狗龙<span style=\'background-color: #FFFF00\'>虎</span>鼠猪<br>玄机解肖：猴狗龙<span style=\'background-color: #FFFF00\'>虎</span></font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中134期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");


document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font color=\'#FF00FF\'>359期特码玄机开猴08</font><br> ");
document.writeln("<span style=\'color: #000\'>特码玄机:头码来得三六七，五出八现同看聚</span><font color=\'#008000\' size=\'3\'><br>");
document.writeln("</font><font color=\'#800000\' size=\'4\'> ");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("");
document.writeln("");
document.writeln("玄机解肖：蛇<span style=\'background-color: #FFFF00\'>猴</span>鼠虎马鸡<br>玄机解肖：蛇<span style=\'background-color: #FFFF00\'>猴</span>鼠虎</font></span></p>");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'38\'><tbody><tr>");
document.writeln("			<td height=38><p style=text-align:center><strong><a target=\'_blank\' href=\'https://ggdnd.www29215c.com:8443#62102c\' style=\'text-decoration: none\'><img src=/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>雷锋规律九肖");
document.writeln("			【连中134期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");




document.writeln("");
document.writeln("</body>");
document.writeln("</html>  ");