document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                   <b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<img width=\"100%\" src=\"/images/cs12.jpg\">");
document.writeln("");
document.writeln("					<font size=\"4\"><span style=\"background-color: #FF0000\">特肖高手榜<br>	");
document.writeln("");
document.writeln("					</span>	");
document.writeln("");
document.writeln("			</font>	");
document.writeln("");
document.writeln("					<font size=\"4\">参加规则：<br>	");
document.writeln("");
document.writeln("			</font>	");
document.writeln("");
document.writeln("					<font size=\"3\">1、为了维护彩民利益，不得出现包中，100%，砸等字眼，引诱别人加注，一切以参考为主！<span style=\"background-color: #FF0000\"><br>");
document.writeln("");
document.writeln("					</span>	");
document.writeln("");
document.writeln("					2、所有特肖贴，控制在16码以内，超数作废。<br>");
document.writeln("					3、五期内未中一期将撤消参加资格。</font><br>");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("			</span>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    ");
document.writeln("     </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("      <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("      ");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("");
document.writeln("   		");
document.writeln("		");
document.writeln("		");
document.writeln("		<span style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("      <!--天肖牛猪猴龙马兔  地肖蛇羊鸡虎鼠狗--> ");
document.writeln("				<b> ");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【半面妆容】(3肖)</font></b></span><b><font color=\"#0000FF\"></b></font></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");


document.writeln("		081期【鸡猪<span style=\'background-color: #FFFF00\'>龙</span>】<br>		");

document.writeln("		082期【虎猪鼠】<br>		");
document.writeln("		");
document.writeln("		</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("	      <!--左肖鼠牛龙蛇猴鸡  右肖虎兔马羊狗猪--> 			");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【小妖女】(2+1肖)</font></span></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");

document.writeln("			079期【兔猴+<span style=\'background-color: #FFFF00\'>鸡</span>】<br><br>");
document.writeln("			080期【牛狗+<span style=\'background-color: #FFFF00\'>兔</span>】<br><br>");
document.writeln("			082期【兔鼠+猴】<br><br>");
document.writeln("				");
document.writeln("				");
document.writeln("				</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("		      <!--前肖鼠牛虎兔龙蛇  后肖马羊猴鸡狗猪--> 	");
document.writeln("		");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【神经】(3肖4码)</font></b><font style=\'font-size: 14pt\'><b><br>");


document.writeln("								");
document.writeln("				082期牛鸡猪<br>");
document.writeln("				09.21.33.45<br><br>");
document.writeln("								");
document.writeln("								");
document.writeln("				</span></b></font></p>");
document.writeln("				<p><b><br>");
document.writeln("		");
document.writeln("");
document.writeln("				      <!--吃菜猪猴鸡鼠 吃肉狗龙虎蛇 吃草牛羊马兔--> 	");
document.writeln("	");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【小情怀】(12码)</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");


document.writeln("082期<br>");
document.writeln("11.22.26.29.32.40<br>");
document.writeln("20.08.37.48.39.34<br>	");



document.writeln("				</span><br>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("		</td> </div>");
document.writeln("    ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("  ");
document.writeln("		        <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("             <b>");
document.writeln("             <br>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		<span style=\'font-size: 14pt\'><font color=\"#0000FF\"><br>		");
document.writeln("  <!--绿肖牛羊龙狗  红肖鼠马兔鸡  蓝肖猪猴蛇虎--> 	");
document.writeln("");
document.writeln("				</font> 	");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【三流汉子】(4肖)</font></span></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");

document.writeln("082期【羊马蛇猪】<br><br>");


document.writeln("				");
document.writeln("				");
document.writeln("				");
document.writeln("				</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("	  <!--大肖牛羊马猪虎狗  小肖鼠龙蛇猴兔鸡--> 				");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【归彩】(8码)</font></span></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");




document.writeln("				077期？<br>");
document.writeln("				【16.20.47.48】<br>");
document.writeln("				【35.<span style=\'background-color: #FFFF00\'>32</span>.42.17】<br>	<br>				");
document.writeln("				");


document.writeln("				078期？<br>");
document.writeln("				【44.<span style=\'background-color: #FFFF00\'>05</span>.20.49】<br>");
document.writeln("				【45.23.21.37】<br>	<br>				");
document.writeln("				");


document.writeln("				082期？<br>");
document.writeln("				【04.10.14.47】<br>");
document.writeln("				【02.05.46.17】<br>	<br>				");
document.writeln("				");

document.writeln("				</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("	");
document.writeln("		  <!--双肖虎猴龙狗马鼠  单肖牛羊蛇兔鸡猪--> 	");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【自称马神】(10码)</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");
document.writeln("		    ");

document.writeln("				078期<br>");
document.writeln("			（41.46.24.17.29）<br>");
document.writeln("			（<span style=\'background-color: #FFFF00\'>05</span>.40.28.06.13）<br>	");
document.writeln("				");
document.writeln("				079期<br>");
document.writeln("			（13.28.07.06.29）<br>");
document.writeln("			（30.26.37.36.<span style=\'background-color: #FFFF00\'>44</span>）<br>	");
document.writeln("				");
document.writeln("				");
document.writeln("				082期<br>");
document.writeln("			（37.34.47.13.09）<br>");
document.writeln("			（22.11.31.41.26）<br>	");
document.writeln("				");
document.writeln("				");
document.writeln("				</span></b></font><b><br>");
document.writeln("		");
document.writeln("");
document.writeln("			  <!--春肖兔虎龙 夏肖蛇马羊 秋肖猴鸡狗  冬肖鼠猪牛--> 		");
document.writeln("	");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【高冷王子】(3+1肖)</font><font style=\'font-size: 14pt\'><br>");
document.writeln("				079期马蛇狗+<span style=\'background-color: #FFFF00\'>鸡</span><br><br>");
document.writeln("				080期狗鸡鼠+<span style=\'background-color: #FFFF00\'>兔</span><br><br>");
document.writeln("				082期鼠猴马+鸡<br><br>");
document.writeln("				");
document.writeln("				</span><br>");
document.writeln("		");
document.writeln("");
document.writeln("		    ");
document.writeln("	   </span> </font></b><br>	");
document.writeln("		");
document.writeln("		");
document.writeln("			");
document.writeln("				</p>	");
document.writeln("		");
document.writeln("		");
document.writeln("			");
document.writeln("			</td></div>		");
document.writeln("    </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("<!-- 结束 -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!-- 网址推广 -->");
document.writeln(" <tr>");
document.writeln(" <td style=\'text-align:center\' height=\'60\'>");
document.writeln("<!--  网址推广 -->");
document.writeln(" ");
document.writeln("  </div>");