document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<style>");
document.writeln("bjbj {");
document.writeln("background-color:#ffffff;");
document.writeln("}");
document.writeln(".a1 td {");
document.writeln("	border-bottom: solid 1px #c0c0c0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始-->");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td height=42 bgcolor=\'#FFFFFF\' >");
document.writeln("		<p align=\'left\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                   <b>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					<font face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<img width=\"100%\" src=\"/images/cs12.jpg\">");
document.writeln("");
document.writeln("					<font size=\"4\"><span style=\"background-color: #FF0000\">特肖高手榜<br>	");
document.writeln("");
document.writeln("					</span>	");
document.writeln("");
document.writeln("			</font>	");
document.writeln("");
document.writeln("					<font size=\"4\">参加规则：<br>	");
document.writeln("");
document.writeln("			</font>	");
document.writeln("");
document.writeln("					<font size=\"3\">1、为了维护彩民利益，不得出现包中，100%，砸等字眼，引诱别人加注，一切以参考为主！<span style=\"background-color: #FF0000\"><br>");
document.writeln("");
document.writeln("					</span>	");
document.writeln("");
document.writeln("					2、所有特肖贴，控制在16码以内，超数作废。<br>");
document.writeln("					3、五期内未中一期将撤消参加资格。</font><br>");
document.writeln("");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("			</span>");
document.writeln("		</font>");
document.writeln("		");
document.writeln("		<b>　</b></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    ");
document.writeln("     </tbody>");
document.writeln("</table>");
document.writeln(" </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("      <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("      ");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' style=\'border-collapse: collapse\' border=\'1\' bordercolor=\'#FF3300\'>");
document.writeln("  <tbody>");
document.writeln("    <tr>");
document.writeln("      <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("");
document.writeln("   		");
document.writeln("		");
document.writeln("		");
document.writeln("		<span style=\'font-size: 14pt\'><br>		");
document.writeln("		");
document.writeln("      <!--天肖牛猪猴龙马兔  地肖蛇羊鸡虎鼠狗--> ");
document.writeln("				<b> ");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【半面妆容】(3肖)</font></b></span><b><font color=\"#0000FF\"></b></font></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");




document.writeln("		327期【龙鼠<span style=\'background-color: #FFFF00\'>羊</span>】<br>		");
document.writeln("		328期【兔狗蛇】<br>		");
document.writeln("		");
document.writeln("		</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("	      <!--左肖鼠牛龙蛇猴鸡  右肖虎兔马羊狗猪--> 			");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【小妖女】(2+1肖)</font></span></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");


document.writeln("			320期【龙羊+<span style=\'background-color: #FFFF00\'>蛇</span>】<br>				");
document.writeln("			321期【<span style=\'background-color: #FFFF00\'>鸡</span>猴+猪】<br>				");
document.writeln("			324期【<span style=\'background-color: #FFFF00\'>虎</span>龙+马】<br>				");
document.writeln("			325期【<span style=\'background-color: #FFFF00\'>鸡</span>羊+虎】<br>				");
document.writeln("			328期【鼠猪+鸡】<br>				");
document.writeln("				");
document.writeln("				");
document.writeln("				</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("		      <!--前肖鼠牛虎兔龙蛇  后肖马羊猴鸡狗猪--> 	");
document.writeln("		");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【神经】(3肖4码)</font></b><font style=\'font-size: 14pt\'><b><br>");


document.writeln("				326期龙<span style=\'background-color: #FFFF00\'>蛇</span>猴<br>");
document.writeln("				04.16.28.40<br>");
document.writeln("				328期龙蛇鸡<br>");
document.writeln("				03.15.16.40<br>");
document.writeln("								");
document.writeln("								");
document.writeln("				</span></b></font></p>");
document.writeln("				<p><b><br>");
document.writeln("		");
document.writeln("");
document.writeln("				      <!--吃菜猪猴鸡鼠 吃肉狗龙虎蛇 吃草牛羊马兔--> 	");
document.writeln("	");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【小情怀】(12码)</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");


document.writeln("				328期<br>");
document.writeln("				13.45.31.26.30.05<br>");
document.writeln("				49.10.37.08.04.14<br>	");



document.writeln("						");
document.writeln("				</span><br>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("		</td> </div>");
document.writeln("    ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("        ");
document.writeln("  ");
document.writeln("		        <td style=\'text-align:center;background:#FFF\' width=\'45%\' rowspan=\'2\'><div style=\'height: normal;\'>");
document.writeln("             <b>");
document.writeln("             <br>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		<span style=\'font-size: 14pt\'><font color=\"#0000FF\"><br>		");
document.writeln("  <!--绿肖牛羊龙狗  红肖鼠马兔鸡  蓝肖猪猴蛇虎--> 	");
document.writeln("");
document.writeln("				</font> 	");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【三流汉子】(4肖)</font></span></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");

document.writeln("			328期【狗马羊虎】<br>				");
document.writeln("				");
document.writeln("				");
document.writeln("				");
document.writeln("				</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("	  <!--大肖牛羊马猪虎狗  小肖鼠龙蛇猴兔鸡--> 				");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【归彩】(8码)</font></span></b><span style=\'font-size: 14pt\'><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");



document.writeln("				328期？<br>");
document.writeln("				【08.13.21.42】<br>");
document.writeln("				【27.14.44.22】<br>				");

document.writeln("				");
document.writeln("				</b></font></span><p>");
document.writeln("				<b><br>");
document.writeln("		");
document.writeln("");
document.writeln("		");
document.writeln("	");
document.writeln("		  <!--双肖虎猴龙狗马鼠  单肖牛羊蛇兔鸡猪--> 	");
document.writeln("");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【自称马神】(10码)</font></b><font style=\'font-size: 14pt\'><b><br>");
document.writeln("		    ");
document.writeln("		    ");

document.writeln("				323期<br>");
document.writeln("			（45.<span style=\'background-color: #FFFF00\'>02</span>.25.13.07）<br>");
document.writeln("			（06.47.42.17.01）<br>	");
document.writeln("				325期<br>");
document.writeln("			（19.24.29.25.41）<br>");
document.writeln("			（15.09.17.14.<span style=\'background-color: #FFFF00\'>07</span>）<br>	");
document.writeln("				328期<br>");
document.writeln("			（39.13.29.46.17）<br>");
document.writeln("			（18.22.03.14.45）<br>	");

document.writeln("				");
document.writeln("				");
document.writeln("				");
document.writeln("				</span></b></font><b><br>");
document.writeln("		");
document.writeln("");
document.writeln("			  <!--春肖兔虎龙 夏肖蛇马羊 秋肖猴鸡狗  冬肖鼠猪牛--> 		");
document.writeln("	");
document.writeln("				<font color=\'#0000FF\' style=\'font-size: 14pt\'>【高冷王子】(3+1肖)</font><font style=\'font-size: 14pt\'><br>");
document.writeln("		    ");



document.writeln("				328期牛鼠鸡+狗<br>				");

document.writeln("				");
document.writeln("				</span><br>");
document.writeln("		");
document.writeln("");
document.writeln("		    ");
document.writeln("	   </span> </font></b><br>	");
document.writeln("		");
document.writeln("		");
document.writeln("			");
document.writeln("				</p>	");
document.writeln("		");
document.writeln("		");
document.writeln("			");
document.writeln("			</td></div>		");
document.writeln("    </tr> ");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("<!-- 结束 -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!-- 网址推广 -->");
document.writeln(" <tr>");
document.writeln(" <td style=\'text-align:center\' height=\'60\'>");
document.writeln("<!--  网址推广 -->");
document.writeln(" ");
document.writeln("  </div>");