document.writeln("<!--图库 start-->");
document.writeln("    <div id=\"tk\"></div>");
document.writeln("<style>");
document.writeln("#tan22222-black { display:table; background: rgba(0,0,0,.2); width:100%; height:100%; overflow:hidden; _position:relative; position: fixed; z-index:10000;left: 0px;top: 0px;}");
document.writeln("@media screen and (min-width: 320px) {#tan22222-out {font-size: 14px; line-height: 20px;}}");
document.writeln("@media screen and (min-width: 360px) {#tan22222-out {font-size: 14px; line-height: 20px;}}");
document.writeln("@media screen and (min-width: 400px) {#tan22222-out {font-size: 16px; line-height: 24px;}}");
document.writeln("@media screen and (min-width: 440px) {#tan22222-out {font-size: 16px; line-height: 24px;}}");
document.writeln("@media screen and (min-width: 480px) {#tan22222-out {font-size: 16px; line-height: 24px;}}");
document.writeln("@media screen and (min-width: 640px) {#tan22222-out {font-size: 16px; line-height: 24px;}}");
document.writeln("#tan22222-out { vertical-align:middle; display:table-cell; text-align:center; _position: fixed; _top:50%; _left:50%;}");
document.writeln("#tan22222-out p { margin: 0 auto;} ");
document.writeln("#tan22222-out img { border: 0;}");
document.writeln("#tan22222-con { color: #444; background: #fff; border-radius: 5px; overflow: hidden; box-shadow: 0 5px 20px rgba(0,0,0,.2); display:inline-block; _position:relative; _top:-50%; _left:-50%;} ");
document.writeln(".tan22222-tit { line-height: 1.5em; padding: 0.5em 0.7em; font-size: 16px; font-weight: bold; text-align: left; background: #f5f5f5;}");
document.writeln(".tan22222-tit img { width: 26px; height: 26px; vertical-align: text-bottom; margin-right: 10px;}");
document.writeln(".tan22222-close { float: right; font-size: 14px; font-weight: normal; display: inline-block; cursor: pointer;}");
document.writeln(".tan22222-close:hover { background-position: 0 -34px;}");
document.writeln(".tan22222-box { text-align: left; padding: 10px;}");
document.writeln(".tan22222-box img { max-width: 100%; height: auto;}</style>");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln(".tan02133-box { text-align: left; padding: 10px;}");
document.writeln(".tan02133-box img { max-width: 100%; max-height: 720px;height: auto; }</style>");
document.writeln("<style>");
document.writeln("#tanxpg-black { display:none; background: rgba(0,0,0,.2); width:100%; height:100%; overflow:hidden; _position:relative; position: fixed; z-index:10000;left: 0px;top: 0px;}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div id=\"tanxpg-black\"><div id=\"tan22222-out\"><div id=\"tan22222-con\"> ");
document.writeln("");
document.writeln("<div class=\"tan22222-tit\"><span class=\"tan22222-close\" onclick=\"hidetanxpg();\">");
document.writeln("	关闭</span>澳彩资料网62103b.com,友情提供！</div>");
document.writeln("<div class=\"tan02133-box\">");
document.writeln("<p align=\"center\"><a target=\"_blank\" onclick=\"hidetanxpg();\"></a><a href=\"javascript:;\"><img id=\"tctp3\" src=\"\"></a></p>");
document.writeln("</div></div></div></div> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<script>");
document.writeln("function hidetanxpg(){");
document.writeln("	document.getElementById(\"tanxpg-black\").style.display=\"none\";");
document.writeln("}");
document.writeln("</script>");
document.writeln("");
document.writeln("<style>");
document.writeln("/*主页图库*/");
document.writeln(".tuku ul {");
document.writeln("	display: flex;");
document.writeln("	flex-wrap: wrap;");
document.writeln("	justify-content: space-around;");
document.writeln("}");
document.writeln("");
document.writeln(".tuku ul li {");
document.writeln("	width: 26%;");
document.writeln("	margin: .22rem;");
document.writeln("	text-align: center;");
document.writeln("}");
document.writeln("");
document.writeln(".tuku ul li img {");
document.writeln("	width: 100%;");
document.writeln("        height: 85px;");
document.writeln("        border: 0;");
document.writeln("	margin: 8px 0;");
document.writeln("}");
document.writeln("");
document.writeln("}");
document.writeln(".klj {border:solid 1px grey collapse;font-weight:700; font-size:18pt; font-family:微软雅黑; background:#000; color:#fff; width:100%; text-align:center;}");
document.writeln(".coll {color:#ffff00;}");
document.writeln("</style>");
document.writeln("");

document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f\' bgcolor=#0000FF height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳彩资料网</font><font color=\'#FFFFFF\'>『网络热图』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"tuku  section\" id=\"channel04\">");
document.writeln("                    <ul class=\"mj_body mj_body_select\" id=\"mj01\" style=\"display: block;\">");
document.writeln("<ul>");
document.writeln("");
document.writeln("");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/ujcc314.jpg\"></a>");
document.writeln("		<p>发财单双</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://www.225593a.com/tk/002314.jpg\"></a>");
document.writeln("		<p>精选三肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://czxcdzfd.www23153b.com:888/images/ptyx314.jpg\"></a>");
document.writeln("		<p>网红平特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://czxcdzfd.www23153b.com:888/images/sanx314.jpg\"></a>");
document.writeln("		<p>极限三肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://czxcdzfd.www23153b.com:888/images/pptt314.jpg\"></a>");
document.writeln("		<p>神机平特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/cafu314.jpg\"></a>");
document.writeln("		<p>综合杀图</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://www.225593a.com/tk/004314.jpg\"></a>");
document.writeln("		<p>单双中特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/dgbt314.jpg\"></a>");
document.writeln("		<p>家园三尾</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/qtjh314.jpg\"></a>");
document.writeln("		<p>狮王平特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/lhwt314.jpg\"></a>");
document.writeln("		<p>四肖八码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/ugd314.jpg\"></a>");
document.writeln("		<p>双波六肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://www.962626c.com/img/cbtpt314.jpg\"></a>");
document.writeln("		<p>藏宝平特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/ug6i314.jpg\"></a>");
document.writeln("		<p>六肖中特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://www.61269c.com/images/zbsdt314.jpg\"></a>");
document.writeln("		<p>蛇蛋四肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/pti314.jpg\"></a>");
document.writeln("		<p>包租平特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/21ma314.jpg\"></a>");
document.writeln("		<p>霞姐21码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/3u6n314.jpg\"></a>");
document.writeln("		<p>三肖六码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://www.689292b.com/public/3n6m314.jpg\"></a>");
document.writeln("		<p>三尾六码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://aaallleee.www29769a.com:888/img/djpt314.jpg\"></a>");
document.writeln("		<p>独家平特</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://aaallleee.www29769a.com:888/img/lvwa5x10m314.jpg\"></a>");
document.writeln("		<p>五肖10码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/ugyf314.jpg\"></a>");
document.writeln("		<p>四肖八码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/pejf314.jpg\"></a>");
document.writeln("		<p>家野三肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("	<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/fgnt314.jpg\"></a>");
document.writeln("		<p>二尾四码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/uynt314.jpg\"></a>");
document.writeln("		<p>钟馗六尾</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/gugi314.jpg\"></a>");
document.writeln("		<p>一头一波</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/6i12m314.jpg\"></a>");
document.writeln("		<p>六肖12码</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/lhnt314.jpg\"></a>");
document.writeln("		<p>内幕四尾</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://dasfdcxfsdfs.www353578b.com:888/tutu/7ie314.jpg\"></a>");
document.writeln("		<p>老曾七肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://aaallleee.www29769a.com:888/img/lzwj7x314.jpg\"></a>");
document.writeln("		<p>无错七肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");
document.writeln("<li>");
document.writeln("		<div>");
document.writeln("		<a href=\"javascript:;\"><img src=\"https://czxcdzfd.www23153b.com:888/images/nbu6x314.jpg\"></a>");
document.writeln("		<p>泄密六肖</p>");
document.writeln("		</div>");
document.writeln("	</li>");

document.writeln("			</ul>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("     //弹出一个iframe层 ");
document.writeln("    $(\'#mj01 a\').on(\'click\', function(e){");
document.writeln("    var val=$(this).children(\'img\').attr(\'src\');");
document.writeln("    var path=val;");
document.writeln("    $(\'#tctp3\').attr(\'src\',path); ");
document.writeln("    document.getElementById(\'tanxpg-black\').style.display=\'table\';");
document.writeln("    });");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<!--图库 end-->");