document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 18pt\'>");
document.writeln("『独家来料一句中特』</font></b></table>");
document.writeln("   ");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<table border=\'0\' width=\'100%\' cellspacing=\'0\' cellpadding=\'0\' bgcolor=\'#FFFFFF\' style=\'border-left-width: 0px; border-right-width: 0px; border-top-width: 0px\'><tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("				<th width=\'14%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("		171期</font></th>");
document.writeln("				<th style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("				<span style=\'text-decoration: none\'>");
document.writeln("				<font color=\'#FF0000\'><span style=\'font-size: 11pt\'>");
document.writeln("			蛇马羊虎牛猪兔，合双小数中本期</font></th>");
document.writeln("				<th width=\'16%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'><font color=\'#000000\'>");
document.writeln("				开？00</font></th>");
document.writeln("			</tr>");
document.writeln("");

document.writeln("");
document.writeln("<tr>");
document.writeln("				<th width=\'14%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("		168期</font></th>");
document.writeln("				<th style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("				<span style=\'text-decoration: none\'>");
document.writeln("				<font color=\'#FF0000\'><span style=\'font-size: 11pt\'>");
document.writeln("			鸡牛<span style=\'background-color: #FFFF00\'>兔</span>马猴鼠龙，合双大数中本期</font></th>");
document.writeln("				<th width=\'16%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'><font color=\'#000000\'>");
document.writeln("				开兔14</font></th>");
document.writeln("			</tr>");
document.writeln("");

document.writeln("");
document.writeln("<tr>");
document.writeln("				<th width=\'14%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("		167期</font></th>");
document.writeln("				<th style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("				<span style=\'text-decoration: none\'>");
document.writeln("				<font color=\'#FF0000\'><span style=\'font-size: 11pt\'>");
document.writeln("			蛇龙马<span style=\'background-color: #FFFF00\'>兔</span>鼠狗牛，合双小数中本期</font></th>");
document.writeln("				<th width=\'16%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'><font color=\'#000000\'>");
document.writeln("				开兔14</font></th>");
document.writeln("			</tr>");
document.writeln("");

document.writeln("");
document.writeln("<tr>");
document.writeln("				<th width=\'14%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("		166期</font></th>");
document.writeln("				<th style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("				<span style=\'text-decoration: none\'>");
document.writeln("				<font color=\'#FF0000\'><span style=\'font-size: 11pt\'>");
document.writeln("			羊虎牛龙鼠猪<span style=\'background-color: #FFFF00\'>鸡</span>，合双<span style=\'background-color: #FFFF00\'>大数</span>中本期</font></th>");
document.writeln("				<th width=\'16%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'><font color=\'#000000\'>");
document.writeln("				开鸡32</font></th>");
document.writeln("			</tr>");
document.writeln("");

document.writeln("<tr>");
document.writeln("				<th width=\'14%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("		165期</font></th>");
document.writeln("				<th style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'>");
document.writeln("				<span style=\'text-decoration: none\'>");
document.writeln("				<font color=\'#FF0000\'><span style=\'font-size: 11pt\'>");
document.writeln("			鸡马龙狗蛇<span style=\'background-color: #FFFF00\'>虎</span>猴，<span style=\'background-color: #FFFF00\'>合单</span>大数中本期</font></th>");
document.writeln("				<th width=\'16%\' style=\'border-style: solid; border-width: 1px\' bordercolor=\'#000000\' height=\'47\'><font color=\'#000000\'>");
document.writeln("				开虎03</font></th>");
document.writeln("			</tr>");
document.writeln("");



document.writeln("");
document.writeln("		");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1777tz.com:1777/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1777.CC</font></span></a></strong></tr></table>");
document.writeln("<!--推广结束-->");
document.writeln("");
document.writeln("</body>");