document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--https://tk2.cgpoweredu.net:4949/col/340/yjzy.jpg-->");
document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>无名码友</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『一句真言』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1999.cc</font></span></a></strong></tr></table>");
document.writeln("");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>189期特码玄机开？00</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：牛马春耕农家地<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+蛇羊	<br>");
document.writeln("玄机双波：主红 防绿</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("01.32.24.31.44.11.21.04.43.17<br>");
document.writeln("35.13.33.36.16.42.07.49.12.34<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://zz336.www76891b.com:8443#62827c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></tdd>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>186期特码玄机开鼠29</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：金石不渝值千金<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+猪蛇	<br>");
document.writeln("玄机双波：主绿 防红</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("04.46.31.10.37.16.14.49.34.42<br>");
document.writeln("38.13.30.<span style=\'background-color: #FFFF00\'>29</span>.44.22.25.11.43.06<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://zz336.www76891b.com:8443#62827c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></tdd>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>185期特码玄机开猪42</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：面朝黄土背朝天<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+鸡牛	<br>");
document.writeln("玄机双波：主蓝 防红</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("30.31.28.19.40.43.14.01.02.11<br>");
document.writeln("<span style=\'background-color: #FFFF00\'>42</span>.26.37.23.08.27.13.05.04.35<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://zz336.www76891b.com:8443#62827c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></tdd>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>184期特码玄机开猪42</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：掩耳盗铃自欺人<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：双数+狗龙	<br>");
document.writeln("玄机双波：主绿 防红</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("08.29.40.31.01.44.30.15.38.22<br>");
document.writeln("19.34.<span style=\'background-color: #FFFF00\'>42</span>.21.28.47.32.43.06.26<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://zz336.www76891b.com:8443#62827c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></tdd>");
document.writeln("<!--开始-->");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>183期特码玄机开龙25</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：菜园蔬菜绿油油<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+牛猪	<br>");
document.writeln("玄机双波：主绿 防红</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("21.30.42.02.32.34.29.39.14.07<br>");
document.writeln("25.12.03.45.46.28.11.01.13.22<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://zz336.www76891b.com:8443#62827c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></tdd>");
document.writeln("<!--开始-->");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>181期特码玄机开虎27</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：鼠牛必定来开<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+牛鸡	<br>");
document.writeln("玄机双波：主红 防蓝</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("29.49.41.37.20.36.11.03.<span style=\'background-color: #FFFF00\'>27</span>.22<br>");
document.writeln("13.17.08.15.09.26.47.44.32.28<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://zz336.www76891b.com:8443#62827c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></tdd>");
document.writeln("<!--开始-->");

document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>180期特码玄机开兔02</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：欢喜冤家前后同<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+猪羊	<br>");
document.writeln("玄机双波：主蓝 防绿</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("40.41.48.12.46.17.23.37.15.<span style=\'background-color: #FFFF00\'>02</span><br>");
document.writeln("01.25.09.03.26.18.36.04.31.24<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://zz336.www76891b.com:8443#62827c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></tdd>");
document.writeln("<!--开始-->");



document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1999.cc</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("  ");
document.writeln("</body>");
document.writeln("</html>  ");