document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("<!--https://tk2.zaojiao365.net:4949/col/340/yjzy.jpg-->");
document.writeln("");
document.writeln("");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>无名码友</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『一句真言』</font></b></table>");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1999.cc</font></span></a></strong></tr></table>");
document.writeln("");

document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>344期特码玄机开？00</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：过目不往其英资<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+猴龙	<br>");
document.writeln("玄机双波：主红 防蓝</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("14.13.42.06.08.31.05.23.21.20<br>");
document.writeln("28.12.03.40.26.01.07.18.04.27<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://www.61269a.com#62102c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("  <table style=\'b order-collapse:collapse;color:#000;font-weight:700;border:1px solid #000\' border=1 width=100%>");
document.writeln("");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; ; word-break: break-all; text-align: center; line-height: 26px;\'>");
document.writeln("");
document.writeln("<p style=\'font-size: 11pt; margin-bottom: 8px; text-align: left;\'>");
document.writeln("<font size=\'4\' color=\'#0000FF\'>342期特码玄机开猪05</font><font size=\'4\'><br> ");
document.writeln("</font> ");
document.writeln("<span style=\'color: #008000; font-weight:700\'><font size=\'4\'>一句真言：绿荷生出白莲花<br>");
document.writeln("</font>");
document.writeln("</span>");
document.writeln("<span style=\'font-family: 微软雅黑; text-indent: 2em; \'>");
document.writeln("<font size=\'4\'>");
document.writeln("<span style=\'color: #008000\'>玄机给肖：单数+虎狗	<br>");
document.writeln("玄机双波：主绿 防蓝</span><span style=\'color: #008000; font-weight: 700\'><br>  ");
document.writeln("</span>");
document.writeln("</font>  ");
document.writeln("</span>");
document.writeln("<font color=\'#FF0000\' size=\'4\'>本期主特(20码)<br>");
document.writeln("47.17.35.46.20.19.45.36.34.31<br>");
document.writeln("22.08.41.38.15.33.<span style=\'background-color: #FFFF00\'>05</span>.30.12.18<table style=border-collapse:collapse border=0 width=100% height=\'46\'><tbody><tr>");
document.writeln("			<td height=46 bgcolor=\'#FFFF00\'><p style=text-align:center><strong><a target=\'_blank\' href=\'https://www.61269a.com#62102c\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif width=20 height=19><span style=font-family:楷体;font-size:12pt;color:#00f>相识一场【吉凶六肖连中14期】点击查看</a></strong></tr></table>");
document.writeln("</a></tr></table></td>");
document.writeln("<!--开始-->");
document.writeln("");




document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'><img src=https://qahghh.www62361b.com:888/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>点击投注六合彩</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>1999.cc</font></span></a></strong></tr></table>");
document.writeln("");
document.writeln("  ");
document.writeln("</body>");
document.writeln("</html>  ");