document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'57\'><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 51px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'4\'>62109a.com『原创幽默猜测解特』</font></b></table>");
document.writeln("<div class=\'jyyzt\'><table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\'>");
document.writeln("");
document.writeln("");
document.writeln("       <!--开始-->");
document.writeln(" <tr>");
document.writeln("    <td align=\'left\' height=\"116\">");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#0000FF\'>（2）</font><font color=\'#000000\'> ");
document.writeln("	2024年第121期幽默猜测</font><font color=\'#FF0000\'>（减肥）</font><font color=\'#000000\'>：上班时收到老婆短信：吃什么食物能减肥？我上网查了一下回她：1．玉米；2．山楂；3．苹果；4．地瓜。下班回家看到她躺沙发上喘气，问她怎么了？她说：“一根玉米两颗山楂不在话下，三个苹果也还行，四个地瓜撑死我了</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#FF9933\'>综合解特：减肥解鸡羊狗马猴龙</font></b></div>");
document.writeln("   <br>");
document.writeln("   ");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#009900\'>");
document.writeln("	综合特肖：鸡羊狗马猴龙</font></b></div>");
document.writeln(" </td></tr>");
document.writeln(" <!--结束-->");
document.writeln("");
document.writeln("       <!--开始-->");
document.writeln(" <tr>");
document.writeln("    <td align=\'left\' height=\"116\">");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#0000FF\'>（2）</font><font color=\'#000000\'> ");
document.writeln("	2024年第120期幽默猜测</font><font color=\'#FF0000\'>（新成员）</font><font color=\'#000000\'>：新成员家里来了个新成员兔子，它的到来天家都很欢迎，争先都排队跟她合照，可是一照个个就停不了，一个接着一个，都不让兔子休息一下。本期图片会给我们带来什么样的玄机呢</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#FF9933\'>综合解特：新成员解马猴龙鸡狗鼠</font></b></div>");
document.writeln("   <br>");
document.writeln("   ");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#009900\'>");
document.writeln("	综合特肖：马猴龙鸡狗</font><font size=\'5\'><span style=\"background-color: #FFFF00\">鼠</span></font></b></div>");
document.writeln(" </td></tr>");
document.writeln(" <!--结束-->");
document.writeln("");
document.writeln("       <!--开始-->");
document.writeln(" <tr>");
document.writeln("    <td align=\'left\' height=\"116\">");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#0000FF\'>（2）</font><font color=\'#000000\'> ");
document.writeln("	2024年第119期幽默猜测</font><font color=\'#FF0000\'>（分享）</font><font color=\'#000000\'>：分享看着刚叼着满嘴小鱼回来的同类，小鸟多希望自己的同类可以分享一些小鱼给它，到底小鸟最后有没有得到同类分享的猎物呢？....本期图片会给我们带来什么样的玄机呢</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#FF9933\'>综合解特：分享解马鸡牛蛇兔猴</font></b></div>");
document.writeln("   <br>");
document.writeln("   ");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#009900\'>");
document.writeln("	综合特肖：马</font><font size=\'5\'><span style=\"background-color: #FFFF00\">鸡</span></font><font size=\'4\' color=\'#009900\'>牛蛇兔猴</font></b></div>");
document.writeln(" </td></tr>");
document.writeln(" <!--结束-->");
document.writeln("");
document.writeln("       <!--开始-->");
document.writeln(" <tr>");
document.writeln("    <td align=\'left\' height=\"116\">");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#0000FF\'>（2）</font><font color=\'#000000\'> ");
document.writeln("	2024年第117期幽默猜测</font><font color=\'#FF0000\'>（女孩）</font><font color=\'#000000\'>2024年第117期幽默猜测：女孩我曾经给六个女孩一起追过。。。后来实在跑不动了，给揍了一顿。本期图片会给我们带来什么样的玄机呢</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#FF9933\'>综合解特：女孩解龙狗鸡兔蛇牛</font></b></div>");
document.writeln("   <br>");
document.writeln("   ");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#009900\'>");
document.writeln("	综合特肖：</font><font size=\'5\'><span style=\"background-color: #FFFF00\">龙</span></font><font size=\'4\' color=\'#009900\'>狗鸡兔蛇牛</font></b></div>");
document.writeln(" </td></tr>");
document.writeln(" <!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("     ");
document.writeln("     ");
document.writeln("            ");
document.writeln(" ");
document.writeln(" ");
document.writeln("</table>");
document.writeln("</div>  ");
document.writeln("     ");
document.writeln("    ");
document.writeln("");
document.writeln("    ");