document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'57\'><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 51px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'4\'>62827a.com『原创幽默猜测解特』</font></b></table>");
document.writeln("<div class=\'jyyzt\'><table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("       <!--开始-->");
document.writeln(" <tr>");
document.writeln("    <td align=\'left\' height=\"115\">");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#0000FF\'>（2）</font><font color=\'#000000\'> ");
document.writeln("	2024年第201期幽默猜测</font><font color=\'#FF0000\'>（女孩)</font><font color=\'#000000\'>:女孩我曾经给六个女孩一起追过。。。后来实在跑不动了，给揍了一顿。..本期图片会给我们带来什么样的玄机呢</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#FF9933\'>综合解特：女孩解马鸡龙羊牛兔<br>");
document.writeln("   ");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#009900\'>");
document.writeln("	综合特肖：马鸡龙羊牛兔</font></b></div>");
document.writeln(" </td></tr>");
document.writeln(" <!--结束-->");
document.writeln("     ");
document.writeln("       <!--开始-->");
document.writeln(" <tr>");
document.writeln("    <td align=\'left\' height=\"115\">");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#0000FF\'>（2）</font><font color=\'#000000\'> ");
document.writeln("	2024年第200期幽默猜测</font><font color=\'#FF0000\'>（分享)</font><font color=\'#000000\'>:分享看着刚叼着满嘴小鱼回来的同类，小鸟多希望自己的同类可以分享一些小鱼给它，到底小鸟最后有没有得到同类分享的猎物呢？.本期图片会给我们带来什么样的玄机呢</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#FF9933\'>综合解特：分享解狗猴马猪龙鼠<br>");
document.writeln("   ");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#009900\'>");
document.writeln("	综合特肖：</font><font size=\'5\'><span style=\"background-color: #FFFF00\">狗</span></font><font size=\'4\' color=\'#009900\'>猴马猪龙鼠</font></b></div>");
document.writeln(" </td></tr>");
document.writeln(" <!--结束-->");
document.writeln("     ");
document.writeln("");
document.writeln("");
document.writeln("            ");
document.writeln(" ");
document.writeln(" ");
document.writeln("</table>");
document.writeln("</div>  ");
document.writeln("     ");
document.writeln("    ");