document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'57\'><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 51px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' size=\'4\'>62109a.com『原创幽默猜测解特』</font></b></table>");
document.writeln("<div class=\'jyyzt\'><table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("       <!--开始-->");
document.writeln(" <tr>");
document.writeln("    <td align=\'left\' height=\"116\">");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#0000FF\'>（2）</font><font color=\'#000000\'> ");
document.writeln("	2024年第129期幽默猜测</font><font color=\'#FF0000\'>（旅游团）</font><font color=\'#000000\'>：旅游团春节期间，小朋友和动物们组团出游它们坐着77号旅游大巴一路赏春，大家一路欢声笑语，猫头鹰白天开车会不会睡着呢？....本期图片会给我们带来什么样的玄机呢</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#FF9933\'>综合解特：旅游团解羊狗马虎鼠鸡</font></b></div>");
document.writeln("   <br>");
document.writeln("   ");
document.writeln("<div class=\'jyyzt-txt3\'><b><font size=\'4\' color=\'#009900\'>");
document.writeln("	综合特肖：羊狗马虎鼠鸡</font></b></div>");
document.writeln(" </td></tr>");
document.writeln(" <!--结束-->");
document.writeln("");
document.writeln("     ");
document.writeln("     ");
document.writeln("            ");
document.writeln(" ");
document.writeln(" ");
document.writeln("</table>");
document.writeln("</div>  ");
document.writeln("     ");
document.writeln("    ");
document.writeln("");