document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>跑马图</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『一语中特』</font></b></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("   <!--gavc--");
document.writeln("   <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'>220期一语中特【正在来料】</div>");
document.writeln("<div class=\'jyyzt-txt2\'>解释：最早来料，关注跑马论坛616129.com</div>");
document.writeln("<div class=\'jyyzt-txt3\'>综合：解特：最早来料，关注跑马论坛616129.com 开0000准</div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("   <!--gavc-->");
document.writeln("");
document.writeln("");

document.writeln("");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\'>218期一语中特【三山五狱】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\'>解释：五岳:泰山、华山、衡山、嵩山、恒山。泛指名山或各地。解蛇马龙狗兔猴</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'>综合：蛇马龙狗兔猴开0000准</div>");
document.writeln("    </td>");
document.writeln("  </tr>");

document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\'>216期一语中特【左右逢源】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\'>解释：处遇到充足的水源。指做事得心应手，怎样进行都很顺利。解猪龙虎狗羊牛</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'>综合：猪<span style=\'background-color: #FFFF00\'>龙</span>虎狗羊牛开龙36准</div>");
document.writeln("    </td>");
document.writeln("  </tr>");

document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\'>214期一语中特【春蛙秋蝉】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\'>解释：春天蛙叫，秋天蝉鸣。比喻喧闹夸张、空洞无物的言谈。解鸡羊猪蛇虎马</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'>综合：鸡羊猪蛇<span style=\'background-color: #FFFF00\'>虎</span>马开虎14准</div>");
document.writeln("    </td>");
document.writeln("  </tr>");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>跑狗图</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『一语中特』</font></b></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");


document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\'>218期一语中特【万箭穿心】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\'>解释：犹万箭攒心。形容万分伤痛。解龙马羊鸡牛蛇</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'>综合：龙马羊鸡牛蛇开0000准</div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("");
document.writeln("  <tr>");
document.writeln("    <td align=\'left\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\'>217期一语中特【异姓骨肉】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\'>解释：虽然不同姓但像骨肉兄弟一样亲近。解羊牛马鼠鸡狗</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'>综合：羊牛马鼠鸡<span style=\'background-color: #FFFF00\'>狗</span>开狗18</div>");
document.writeln("    </td>");
document.writeln("  </tr>");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("</table>");
document.writeln("<p>　</p>");