document.writeln("<style>");
document.writeln(".jyyzt {}");
document.writeln(".jyyzt table { font-weight: bold; font-size: 18px; border: 0;}");
document.writeln(".jyyzt table thead th { padding: 5px; color: #fff; font-size: 24px; background: linear-gradient(to top, #07306c, #2356a1);}");
document.writeln(".jyyzt table td { padding: 5px 10px;}");
document.writeln(".jyyzt-txt1 { color: #090;}");
document.writeln(".jyyzt-txt2 { font-weight: normal; color: #00f;}");
document.writeln(".jyyzt-txt3 { font-weight: normal; color: #f00;}");
document.writeln(".jyyzt-txt3 span { background: #ff0;}");
document.writeln("@media screen and (max-width:750px){");
document.writeln(".jyyzt table { font-size: 16px;}");
document.writeln(".jyyzt table thead th { font-size: 18px;}");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>跑马图</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『一语中特』</font></b></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\' size=\"4\">170期一语中特【英姿飒爽】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\' size=\"4\">解释：英姿：英勇威武的姿态；飒爽：豪迈矫健。形容英俊威武、精神焕发的样子。。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><font size=\"4\">综合：鸡马鼠兔狗牛开0000准</font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");

document.writeln("");
document.writeln("<tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\' size=\"4\">169期一语中特【掩卷沉思】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\' size=\"4\">解释：仔细地思考。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><font size=\"4\">综合：羊马<span style=\'background-color: #FFFF00\'>猴</span>兔鼠虎开猴45准</font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");

document.writeln("");
document.writeln("<tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\' size=\"4\">167期一语中特【秀美标致】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\' size=\"4\">解释：筋骨象钢铁打铸的一般。形容身体健壮有力或意志坚强不屈。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><font size=\"4\">综合：<span style=\'background-color: #FFFF00\'>兔</span>牛猴鼠马鸡开兔14准</font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("");

document.writeln("");
document.writeln("<tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\' size=\"4\">166期一语中特【钢筋铁骨】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\' size=\"4\">解释：筋骨象钢铁打铸的一般。形容身体健壮有力或意志坚强不屈。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><font size=\"4\">综合：兔牛猴鼠马<span style=\'background-color: #FFFF00\'>鸡</span>开鸡32准</font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("");

document.writeln("");
document.writeln("<tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\' size=\"4\">165期一语中特【芟夷大难】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\' size=\"4\">解释：削平大乱。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><font size=\"4\">综合：蛇狗牛<span style=\'background-color: #FFFF00\'>虎</span>兔鼠开虎03准</font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("5");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("");
document.writeln("</table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\' height=\'150\'>");
document.writeln("  <tbody>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFF00\' face=\'楷体\' style=\'font-size: 20pt\'>跑狗图</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『一语中特』</font></b></table>");
document.writeln("<div class=\'jyyzt\'>");
document.writeln("<table width=\'100%\' border=\'1\'>");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\' size=\"4\">170期一语中特【青毡旧物】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\' size=\"4\">解释：青毡子是家传的故物。比喻珍贵之物。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><font size=\"4\">综合：马蛇狗兔猪虎开0000准</font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td align=\'left\' height=\'73\'>");
document.writeln("<div class=\'jyyzt-txt1\'><font color=\'#006600\' size=\"4\">169期一语中特【尽锐出战】</font></div>");
document.writeln("<div class=\'jyyzt-txt2\'><font color=\'#000000\' size=\"4\">解释：把所有的精锐部队派出作战。比喻派出了主力，用上了杀手锏。</font></div>");
document.writeln("<div class=\'jyyzt-txt3\'><font size=\"4\">综合：蛇牛龙<span style=\'background-color: #FFFF00\'>猴</span>鼠马开猴45准</font></div>");
document.writeln("    </td>");
document.writeln("  </tr>");
document.writeln("");






document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("</table>");
document.writeln("<p>　</p>");