document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>目中无人</font><font color=\'#FFFFFF\'>『牛逼一波』</font></font></b></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'3\' cellpadding=\'0\'>");
document.writeln("");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		201期主【绿波】防【红波】开？00准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		200期主【红波】防<span style=\'background-color: #FFFF00\'>【蓝波】</span>开羊47准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		198期主<span style=\'background-color: #FFFF00\'>【绿波】</span>防【蓝波】开猪43准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");


document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		196期主<span style=\'background-color: #FFFF00\'>【蓝波】</span>防【红波】开龙14准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		195期主【红波】防<span style=\'background-color: #FFFF00\'>【蓝波】</span>开蛇25准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");


document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		193期主【绿波】防<span style=\'background-color: #FFFF00\'>【红波】</span>开马24准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		192期主<span style=\'background-color: #FFFF00\'>【红波】</span>防【蓝波】开鸡45准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		191期主【蓝波】防<span style=\'background-color: #FFFF00\'>【红波】</span>开牛29准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		190期主【绿波】防<span style=\'background-color: #FFFF00\'>【红波】</span>开鼠18准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		189期主【蓝波】防<span style=\'background-color: #FFFF00\'>【绿波】</span>开牛17准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		188期主【红波】防<span style=\'background-color: #FFFF00\'>【蓝波】</span>开兔15准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		187期主【蓝波】防<span style=\'background-color: #FFFF00\'>【红波】</span>开鸡45准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		186期主【绿波】防<span style=\'background-color: #FFFF00\'>【红波】</span>开狗08准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		185期主【红波】防<span style=\'background-color: #FFFF00\'>【绿波】</span>开牛05准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		184期主【红波】防<span style=\'background-color: #FFFF00\'>【绿波】</span>开虎28准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		183期主【红波】防<span style=\'background-color: #FFFF00\'>【绿波】</span>开鸡33准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");
document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		182期主【红波】防<span style=\'background-color: #FFFF00\'>【蓝波】</span>开鼠42准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");



document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		180期主【蓝波】防<span style=\'background-color: #FFFF00\'>【红波】</span>开牛29准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");


document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		179期主【蓝波】防<span style=\'background-color: #FFFF00\'>【红波】</span>开马24准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");

document.writeln("    <!--开始-->   ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 >");
document.writeln("		<p align=\"center\"><b>");
document.writeln("");
document.writeln(" ");
document.writeln("		<font face=\'微软雅黑\' style=\"font-size: 14pt\">");
document.writeln("		178期主【蓝波】防<span style=\'background-color: #FFFF00\'>【绿波】</span>开兔27准</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("");
document.writeln("    <!--开始-->   ");








document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");