document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>实战来料【稳定九肖】</font></b></table>");
document.writeln("           ");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln("");
document.writeln(".ys114 {text-align: center;}");
document.writeln(".ys112 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'ys114\'>");
document.writeln("	");
document.writeln("<strong>");
document.writeln(" ");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	<br>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("	</strong>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<b>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("<!--四季-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【春夏秋冬】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 15pt\'>");
document.writeln("");
document.writeln("	");


document.writeln("197期四季中特【春<span style=\'background-color: #FFFF00\'>夏</span>秋】<font color=\"#FF0000\">√</font><br>	");
document.writeln("198期四季中特【夏秋<span style=\'background-color: #FFFF00\'>冬</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("199期四季中特【<span style=\'background-color: #FFFF00\'>春</span>夏冬】<font color=\"#FF0000\">√</font><br>	");
document.writeln("200期四季中特【<span style=\'background-color: #FFFF00\'>秋</span>冬春】<font color=\"#FF0000\">√</font><br>	");
document.writeln("201期四季中特【<span style=\'background-color: #FFFF00\'>春</span>夏秋】<font color=\"#FF0000\">√</font><br>	");
document.writeln("202期四季中特【夏秋冬】<font color=\"#FF0000\">√</font><br>	");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--");
document.writeln("春：兔虎龙 夏：蛇马羊");
document.writeln("秋：猴鸡狗 冬：鼠猪牛");
document.writeln("-->");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--才艺-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【琴棋书画】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 15pt\'>");


document.writeln("184期才艺中特【棋书<span style=\'background-color: #FFFF00\'>画</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("185期才艺中特【琴棋<span style=\'background-color: #FFFF00\'>画</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("186期才艺中特【<span style=\'background-color: #FFFF00\'>棋</span>书画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("187期才艺中特【棋<span style=\'background-color: #FFFF00\'>书</span>画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("188期才艺中特【琴书<span style=\'background-color: #FFFF00\'>画</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("189期才艺中特【<span style=\'background-color: #FFFF00\'>棋</span>书画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("190期才艺中特【<span style=\'background-color: #FFFF00\'>棋</span>琴画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("191期才艺中特【棋<span style=\'background-color: #FFFF00\'>书</span>画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("192期才艺中特【琴<span style=\'background-color: #FFFF00\'>棋</span>画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("193期才艺中特【<span style=\'background-color: #FFFF00\'>棋</span>书琴】<font color=\"#FF0000\">√</font><br>	");
document.writeln("194期才艺中特【<span style=\'background-color: #FFFF00\'>棋</span>书画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("195期才艺中特【琴棋<span style=\'background-color: #FFFF00\'>画</span>】<font color=\"#FF0000\">√</font><br>	");
document.writeln("196期才艺中特【棋<span style=\'background-color: #FFFF00\'>书</span>画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("197期才艺中特【琴书棋】<font color=\"#FF0000\">×</font><br>	");
document.writeln("198期才艺中特【<span style=\'background-color: #FFFF00\'>棋</span>书画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("199期才艺中特【棋琴画】<font color=\"#FF0000\">×</font><br>	");
document.writeln("200期才艺中特【<span style=\'background-color: #FFFF00\'>棋</span>书画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("201期才艺中特【琴<span style=\'background-color: #FFFF00\'>书</span>画】<font color=\"#FF0000\">√</font><br>	");
document.writeln("202期才艺中特【棋书画】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--");
document.writeln("琴：鸡兔蛇 棋：鼠牛狗");
document.writeln("书：马龙虎 画：羊猪猴");
document.writeln("-->");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("<!--九肖-->");
document.writeln("");
document.writeln("<font color=\'#FF0000\' style=\"font-size: 16pt\">【九肖中特】</font><br>");
document.writeln("");
document.writeln("	<span style=\'font-size: 13pt\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("199期⑨肖【马龙羊兔蛇猴狗<span style=\'background-color: #FFFF00\'>虎</span>牛】<font color=\"#FF0000\">√</font><br>	");
document.writeln("200期⑨肖【<span style=\'background-color: #FFFF00\'>狗</span>马牛猴兔羊蛇猪鼠】<font color=\"#FF0000\">√</font><br>	");
document.writeln("201期⑨肖【羊虎兔鸡猴马狗<span style=\'background-color: #FFFF00\'>龙</span>鼠】<font color=\"#FF0000\">√</font><br>	");
document.writeln("202期⑨肖【兔猪狗牛马羊猴蛇虎】<font color=\"#FF0000\">√</font><br>	");

document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	");
document.writeln("	<br>");
document.writeln("</span>");
document.writeln("");
document.writeln("<!--结束-->");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</div>");
document.writeln("	");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><font style=\'font-size: 16pt\'>");
document.writeln("				<strong>");
document.writeln("				<a target=\"_blank\" style=\"text-decoration: none\" href=\"https://xn--mdcx6gra7cc.xn--hdcl2bk2m1bc.xn--gecrj9c:8443/#62827\"><span style=font-family:楷体;color:#00f>更多好料请关注</span><font color=\'#FF0000\'><span style=font-family:楷体;font-size:17pt;>62827b.com</span></font></a></strong></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("	");