document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'gb2132\'>");
document.writeln("<title>六肖</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #00f; height: 50px;\' bgcolor=#0000FF><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>62102b.com</font><font color=\'#FFFFFF\'>『正+另版输尽光』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("		<table style=border-collapse:collapse border=0 width=100%>");
document.writeln("		<tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://mnbvctrs.www58317a.com:888/#62102\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><font style=\'font-size: 14pt\'><span style=font-family:楷体;color:#00f>进入澳门马会传真</span></font><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>57185</font><font color=\'#FF0000\' style=\'font-size: 16pt\'>.com</font></span></a></strong></td></tr></table>");
document.writeln("");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>197期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(羊+猴)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>？</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>196期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(牛+鸡)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>蛇</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>195期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(猴+羊)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>猪</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>194期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(狗+兔)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>鸡</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>193期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(猪+马)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>猴</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");

document.writeln("");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>192期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(鸡+马)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>猴</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");

document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>191期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(鼠+猪)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>龙</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");

document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>189期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(虎+龙)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>马</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>188期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(虎+猪)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>马</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>187期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(猪+蛇)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>鸡</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>186期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(猴+猪)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>鸡</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                                                 <!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font face=\'楷体\'>185期</font><font face=\'微软雅黑\'>正另版买</font><font color=\'#FF0000\' size=\'4\' face=\'楷体\'>(鸡+狗)</font><font size=\'4\' face=\'楷体\'>输尽光</font><font face=\'楷体\'>开<font color=\'#0000FF\'>猴</font>准</font></b></table>");
document.writeln("        <!--结束-->      ");
document.writeln("");
document.writeln("");



document.writeln("");
document.writeln("");
document.writeln("<!--推广开始-->");
document.writeln("			<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://lt2023.lanbods.com:4949/\' style=\'text-decoration: none\'><img src=/images/33567.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 16pt\'>49图库<font color=\"#FF0000\">49.com</font>图纸最全-最快</a></strong></tr></table>");
document.writeln("<!--推广结束-->");

document.writeln("");
document.writeln("       ");
document.writeln("</body>");
document.writeln("</html>");